# AIM Suite III v3.1 Makefile for SGI Indigo
# by Ricky Cheng
#
MACH=`/bin/uname -m`
SYS=-DSYS5
CC=cc
TIMETYPE=-DT_TIMES
MIPS2=
CCCOPT=$(MIPS2) -cckr -O4 -bestGnum -float -jmpopt -Wb,-peep -Dshort=int -no_mpc
CORD=#-cord -feedback multiuser.fb -v
LDOPT=
DHZ=-DHZ=100

CFLAGS= $(CCOPT) -w $(TIMETYPE) $(LDOPT) $(DHZ) $(SYS)
CCFLAGS= $(CCCOPT) $(CORD) -w $(TIMETYPE) $(LDOPT) $(DHZ) $(SYS)

MSRCTASKS = add.c disk1.c div.c fun.c funcal.c mul.c \
	pipe_cpy.c ram.c creat-clo.c disk_src.c

TASKS = add.o disk1.o div.o fun.o funcal.o mul.o \
	pipe_cpy.o ram.o creat-clo.o disk_src.o

MSRC = multiuser.c vmctl.c tp_ctl.c ttyctl.c ttyinit.c ttyconf.c rand.c rtmsec.c $(MSRCTASKS)

OBJS = multiuser.o vmctl.o tp_ctl.o ttyctl.o ttyinit.o ttyconf.o rand.o rtmsec.o $(TASKS)

# ugly but portable, even on (very) dumb makes..

install: multiuser .firsttime
	./blend

multiuser: suite3.h vmdrvr tp_drvr ttydrvr $(MSRC)
	$(CC) $(CCFLAGS) -o multiuser $(MSRC)

.firsttime: report lptest blend
	/bin/chmod a+x REPT
	/bin/tar -xvof fakeh.tar
	@touch .firsttime

mix:
	./blend

tsks:   $(TASKS) suite3.h

report:	plot filter

.c.o:	suite3.h
	$(CC) $(CFLAGS) -c $*.c

#multiuser: suite3.h vmdrvr tp_drvr ttydrvr $(OBJS)
#	$(CC) $(CFLAGS) -o multiuser $(OBJS)

blend: blend.c
	$(CC) $(CCFLAGS) -o blend blend.c

calc_hz: calc_hz.c
	$(CC) $(CCFLAGS) -o calc_hz calc_hz.c

plot: plot.c 
	$(CC) $(CCFLAGS) -o plot plot.c
 
filter: filter.c
	$(CC) $(CCFLAGS) filter.c -o filter

#vmctl.o vmdrvr.o: vmtest.h vmem.h testerr.h

vmdrvr: vmdrvr.c vmem.c
	$(CC) $(CCFLAGS) vmdrvr.c vmem.c -o vmdrvr

tp_drvr: tp_drvr.c tp_test.h testerr.h
	$(CC) $(CCFLAGS) -D_BSD_SIGNALS tp_drvr.c -o tp_drvr

lptest: lptest.c
	$(CC) $(CCFLAGS) lptest.c -o lptest

#tp_ctl.o: tp_test.h testerr.h

OBJS1 = ttyctl.o ttydrvr.o ttyinit.o ttyconf.o

#$(OBJS1): ttytest.h testerr.h

ttydrvr: ttydrvr.c ttyinit.c ttyconf.c
	$(CC) $(CCFLAGS) ttydrvr.c ttyinit.c ttyconf.c -o ttydrvr

newrun:
	@echo "Resetting AIM Suite III for another run."
	@rm -f tmp* core *.o *.u

reset:
	@echo "Resetting AIM Suite III to new install condition."
	@cp Makefile.s Makefile
	@rm -rf .firsttime workfile suite3.ss toutput results
	@rm -rf plot filter blend calc_hz input multiuser nohup.out
	@rm -rf RUN SAVE runit
	@rm -rf ttydrvr vmdrvr tp_drvr lptest
	@rm -rf core fakeh 
	@rm -f $(OBJS) tmp* *.u

clean:
	@rm -f *.o *.u tmp* core multiuser

