#ifndef __IDE_ioc3_H__
#define	__IDE_ioc3_H__

/*
 * d_ioc3.h
 *
 * IDE ioc3 tests header 
 *
 * Copyright 1995, Silicon Graphics, Inc.
 * ALL RIGHTS RESERVED
 *
 * UNPUBLISHED -- Rights reserved under the copyright laws of the United
 * States.   Use of a copyright notice is precautionary only and does not
 * imply publication or disclosure.
 *
 * U.S. GOVERNMENT RESTRICTED RIGHTS LEGEND:
 * Use, duplication or disclosure by the Government is subject to restrictions
 * as set forth in FAR 52.227.19(c)(2) or subparagraph (c)(1)(ii) of the Rights
 * in Technical Data and Computer Software clause at DFARS 252.227-7013 and/or
 * in similar or successor clauses in the FAR, or the DOD or NASA FAR
 * Supplement.  Contractor/manufacturer is Silicon Graphics, Inc.,
 * 2011 N. Shoreline Blvd. Mountain View, CA 94039-7311.
 *
 * THE CONTENT OF THIS WORK CONTAINS CONFIDENTIAL AND PROPRIETARY
 * INFORMATION OF SILICON GRAPHICS, INC. ANY DUPLICATION, MODIFICATION,
 * DISTRIBUTION, OR DISCLOSURE IN ANY FORM, IN WHOLE, OR IN PART, IS STRICTLY
 * PROHIBITED WITHOUT THE PRIOR EXPRESS WRITTEN PERMISSION OF SILICON
 * GRAPHICS, INC.
 */

#ident	"ide/godzilla/include/d_ioc3.h:  $Revision: 1.7 $"

#include "d_ioregs.h"

typedef __uint32_t              ioc3registers_t;

/*ioc3 PCI configuration space*/
#define	IOC3REGS_ID			IOC3REG_PCI_ID 
#define	IOC3REGS_ID_MASK		0xFFFFFFFF 
#define	IOC3REGS_ID_DEFAULT		0x310a9

#define	IOC3REGS_SCR			IOC3REG_PCI_SCR 
#define	IOC3REGS_SCR_MASK		0xFFFFFFFF 
#define	IOC3REGS_SCR_DEFAULT		0x0

#define	IOC3REGS_REV 			IOC3REG_PCI_REV 
#define	IOC3REGS_REV_MASK		0xFFFFFFF0
#define	IOC3REGS_REV_DEFAULT		0xFF000000

#define	IOC3REGS_LAT			IOC3REG_PCI_LAT 
#define	IOC3REGS_LAT_MASK		0xFFFFFFFF 
#define	IOC3REGS_LAT_DEFAULT		0x0

#define	IOC3REGS_ADDR			IOC3REG_PCI_ADDR 
#define	IOC3REGS_ADDR_MASK		0xFFFFFFFF  
#define	IOC3REGS_ADDR_DEFAULT		0x0

#define	IOC3REGS_ADDR_L			IOC3REG_PCI_ERR_ADDR_L 
#define	IOC3REGS_ADDR_L_MASK		0xFFFFFFFF 
#define	IOC3REGS_ADDR_L_DEFAULT		0x0

#define	IOC3REGS_ADDR_H			IOC3REG_PCI_ERR_ADDR_H 
#define	IOC3REGS_ADDR_H_MASK		0xFFFFFFFF 
#define	IOC3REGS_ADDR_H_DEFAULT		0x0

/*pci mem space regs*/
#define	IOC3REGS_IR			IOC3REG_SIO_IR 
#define	IOC3REGS_IR_MASK		0xFFFFFFFF 
#define	IOC3REGS_IR_DEFAULT		0x0

#define	IOC3REGS_IES			IOC3REG_SIO_IES 
#define	IOC3REGS_IES_MASK		0xFFFFFFFF 
#define	IOC3REGS_IES_DEFAULT		0x0

#define	IOC3REGS_IEC			IOC3REG_SIO_IEC 
#define	IOC3REGS_IEC_MASK		0xFFFFFFFF 
#define	IOC3REGS_IEC_DEFAULT		0x0

#define	IOC3REGS_CR			IOC3REG_SIO_CR 
#define	IOC3REGS_CR_MASK		0xFFFFFFFF 
#define	IOC3REGS_CR_DEFAULT		0x0

#define	IOC3REGS_OUT			IOC3REG_INT_OUT 
#define	IOC3REGS_OUT_MASK		0xFFFFFFFF 
#define	IOC3REGS_OUT_DEFAULT		0x0

#define	IOC3REGS_MCR			IOC3REG_MCR 
#define	IOC3REGS_MCR_MASK		0xFFFFFFFF 
#define	IOC3REGS_MCR_DEFAULT		0x0

#define	IOC3REGS_S			IOC3REG_GPCR_S 
#define	IOC3REGS_S_MASK			0xFFFFFFFF 
#define	IOC3REGS_S_DEFAULT		0x0

#define	IOC3REGS_C			IOC3REG_GPCR_C 
#define	IOC3REGS_C_MASK			0xFFFFFFFF 
#define	IOC3REGS_C_DEFAULT		0x0

#define	IOC3REGS_GPDR			IOC3REG_GPDR 
#define	IOC3REGS_GPDR_MASK		0x000001FF 
#define	IOC3REGS_GPDR_DEFAULT		0x0

#define	IOC3REGS_0			IOC3REG_GPPR_0 
#define	IOC3REGS_0_MASK			0xFFFFFFFF 
#define	IOC3REGS_0_DEFAULT		0x0

/*ioc3 Parallal port mem space*/
#define	IOC3REGS_PPBR_H_A		IOC3REG_PPBR_H_A  
#define	IOC3REGS_PPBR_H_A_MASK		0xFFFFFFFF 
#define	IOC3REGS_PPBR_H_A_DEFAULT	0x0

#define	IOC3REGS_PPBR_L_A		IOC3REG_PPBR_L_A 
#define	IOC3REGS_PPBR_L_A_MASK		0xFFFFFFFF 
#define	IOC3REGS_PPBR_L_A_DEFAULT	0x0

#define	IOC3REGS_PPCR_A			IOC3REG_PPCR_A	  
#define	IOC3REGS_PPCR_A_MASK		0x0000FFFF 
#define	IOC3REGS_PPCR_A_DEFAULT		0x0

#define	IOC3REGS_PPCR			IOC3REG_PPCR 
#define	IOC3REGS_PPCR_MASK		0xFFFFFFFF 
#define	IOC3REGS_PPCR_DEFAULT		0x0  

#define	IOC3REGS_PPBR_H_B		IOC3REG_PPBR_H_B 
#define	IOC3REGS_PPBR_H_B_MASK		0xFFFFFFFF 
#define	IOC3REGS_PPBR_H_B_DEFAULT	0x0

#define	IOC3REGS_PPBR_L_B		IOC3REG_PPBR_L_B 
#define	IOC3REGS_PPBR_L_B_MASK		0xFFFFFFFF 
#define	IOC3REGS_PPBR_L_B_DEFAULT	0x0

#define	IOC3REGS_PPCR_B			IOC3REG_PPCR_B 
#define	IOC3REGS_PPCR_B_MASK		0x0000FFFF 
#define	IOC3REGS_PPCR_B_DEFAULT		0x0

/*keyboard and mouse*/
#define	IOC3REGS_KM_CSR			IOC3REG_KM_CSR 
#define	IOC3REGS_KM_CSR_MASK		0xFFFFFFFF 
#define	IOC3REGS_KM_CSR_DEFAULT		0x0

#define	IOC3REGS_K_RD			IOC3REG_K_RD 
#define	IOC3REGS_K_RD_MASK		0xFFFFFFFF 
#define	IOC3REGS_K_RD_DEFAULT		0x0

#define	IOC3REGS_M_RD			IOC3REG_M_RD 
#define	IOC3REGS_M_RD_MASK		0xFFFFFFFF 
#define	IOC3REGS_M_RD_DEFAULT		0x0

#define	IOC3REGS_K_WD			IOC3REG_K_WD 
#define	IOC3REGS_K_WD_MASK		0xFFFFFFFF 
#define	IOC3REGS_K_WD_DEFAULT		0x0

#define	IOC3REGS_M_WD			IOC3REG_M_WD 
#define	IOC3REGS_M_WD_MASK		0xFFFFFFFF 
#define	IOC3REGS_M_WD_DEFAULT		0x0

/* Serial Port Registers */
#define	IOC3REGS_SBBR_H			IOC3REG_SBBR_H 
#define	IOC3REGS_SBBR_H_MASK		0xFFFFF000 
#define	IOC3REGS_SBBR_H_DEFAULT		0x0

#define	IOC3REGS_SBBR_L			IOC3REG_SBBR_L 
#define	IOC3REGS_SBBR_L_MASK		0xFFFFF000 
#define	IOC3REGS_SBBR_L_DEFAULT		0x0

#define	IOC3REGS_SSCR_A			IOC3REG_SSCR_A 
#define	IOC3REGS_SSCR_A_MASK		0xFFFFFFFF 
#define	IOC3REGS_SSCR_A_DEFAULT		0x0

/*Mask changed as upper 2 bits ignored by ioc3 ioc3 doc v4.5.1 pg 96 first para*/
#define	IOC3REGS_STPIR_A		IOC3REG_STPIR_A 
#define	IOC3REGS_STPIR_A_MASK		0x000003F8 
#define	IOC3REGS_STPIR_A_DEFAULT	0x0

#define	IOC3REGS_STCIR_A		IOC3REG_STCIR_A 
#define	IOC3REGS_STCIR_A_MASK		0x000003F8 
#define	IOC3REGS_STCIR_A_DEFAULT	0x0

#define	IOC3REGS_SRPIR_A		IOC3REG_SRPIR_A 
#define	IOC3REGS_SRPIR_A_MASK		0x000003F8 
#define	IOC3REGS_SRPIR_A_DEFAULT	0x0

#define	IOC3REGS_SRCIR_A		IOC3REG_SRCIR_A 
#define	IOC3REGS_SRCIR_A_MASK		0x000003F8 
#define	IOC3REGS_SRCIR_A_DEFAULT	0x0

#define	IOC3REGS_SRTR_A			IOC3REG_SRTR_A 
#define	IOC3REGS_SRTR_A_MASK		0x00000FFF 
#define	IOC3REGS_SRTR_A_DEFAULT		0x0

#define	IOC3REGS_SHADOW_A		IOC3REG_SHADOW_A 
#define	IOC3REGS_SHADOW_A_MASK		0xFFFFFFFF 
#define	IOC3REGS_SHADOW_A_DEFAULT	0x0

#define	IOC3REGS_SSCR_B			IOC3REG_SSCR_B 
#define	IOC3REGS_SSCR_B_MASK		0x000003F8 
#define	IOC3REGS_SSCR_B_DEFAULT		0x0

#define	IOC3REGS_STPIR_B		IOC3REG_STPIR_B 
#define	IOC3REGS_STPIR_B_MASK		0x000003F8 
#define	IOC3REGS_STPIR_B_DEFAULT	0x0

#define	IOC3REGS_STCIR_B		IOC3REG_STCIR_B 
#define	IOC3REGS_STCIR_B_MASK		0x000003F8 
#define	IOC3REGS_STCIR_B_DEFAULT	0x0

#define	IOC3REGS_SRPIR_B		IOC3REG_SRPIR_B 
#define	IOC3REGS_SRPIR_B_MASK		0x000003F8 
#define	IOC3REGS_SRPIR_B_DEFAULT	0x0

#define	IOC3REGS_SRCIR_B		IOC3REG_SRCIR_B 
#define	IOC3REGS_SRCIR_B_MASK		0x000003F8 
#define	IOC3REGS_SRCIR_B_DEFAULT	0x0

#define	IOC3REGS_SRTR_B			IOC3REG_SRTR_B 
#define	IOC3REGS_SRTR_B_MASK		0x00000FFF 
#define	IOC3REGS_SRTR_B_DEFAULT		0x0

#define	IOC3REGS_SHADOW_B		IOC3REG_SHADOW_B 
#define	IOC3REGS_SHADOW_B_MASK		0xFFFFFFFF 
#define	IOC3REGS_SHADOW_B_DEFAULT	0x0

/*Ethernet*/
#define	IOC3REGS_REG_OFF		IOC3REG_REG_OFF 
#define	IOC3REGS_REG_OFF_MASK		0xFFFFFFFF 
#define	IOC3REGS_REG_OFF_DEFAULT	0x0

#define	IOC3REGS_RAM_OFF		IOC3REG_RAM_OFF 
#define	IOC3REGS_RAM_OFF_MASK		0xFFFFFFFF 
#define	IOC3REGS_RAM_OFF_DEFAULT	0x0

#define	IOC3REGS_EMCR			IOC3REG_EMCR 
#define	IOC3REGS_EMCR_MASK		0x800300FF 
#define	IOC3REGS_EMCR_DEFAULT		0x0

#define	IOC3REGS_EISR			IOC3REG_EISR 
#define	IOC3REGS_EISR_MASK		0xFFFFFFFF 
#define	IOC3REGS_EISR_DEFAULT		0x0

#define	IOC3REGS_EIER			IOC3REG_EIER 
#define	IOC3REGS_EIER_MASK		0xFFFFFFFF 
#define	IOC3REGS_EIER_DEFAULT		0x0

#define	IOC3REGS_ERCSR			IOC3REG_ERCSR 
#define	IOC3REGS_ERCSR_MASK		0xFFFFFFFF 
#define	IOC3REGS_ERCSR_DEFAULT		0x0

#define	IOC3REGS_ERBR_H			IOC3REG_ERBR_H 
#define	IOC3REGS_ERBR_H_MASK		0xFFFFFFFF 
#define	IOC3REGS_ERBR_H_DEFAULT		0x0

#define	IOC3REGS_ERBR_L			IOC3REG_ERBR_L 
#define	IOC3REGS_ERBR_L_MASK		0xFFFFF000 
#define	IOC3REGS_ERBR_L_DEFAULT		0x0

#define	IOC3REGS_ERBAR			IOC3REG_ERBAR 
#define	IOC3REGS_ERBAR_MASK		0xFFFF0000 
#define	IOC3REGS_ERBAR_DEFAULT		0x0

/*Mask changed as upper 2 bits ignored by ioc3 ioc3 doc v4.5.1 pg 96 first para*/
#define	IOC3REGS_ERCIR			IOC3REG_ERCIR 
#define	IOC3REGS_ERCIR_MASK		0x000003F8 
#define	IOC3REGS_ERCIR_DEFAULT		0x0

#define	IOC3REGS_ERPIR			IOC3REG_ERPIR 
#define	IOC3REGS_ERPIR_MASK		0x000003F8 
#define	IOC3REGS_ERPIR_DEFAULT		0x0

#define	IOC3REGS_ERTR			IOC3REG_ERTR 
#define	IOC3REGS_ERTR_MASK		0x000007FF 
#define	IOC3REGS_ERTR_DEFAULT		0x0

#define	IOC3REGS_SCR			IOC3REG_PCI_SCR 
#define	IOC3REGS_SCR_MASK		0xFFFFFFFF 
#define	IOC3REGS_SCR_DEFAULT		0x0

#define	IOC3REGS_ETCSR			IOC3REG_ETCSR 
#define	IOC3REGS_ETCSR_MASK		0xFFFFFFFF 
#define	IOC3REGS_ETCSR_DEFAULT		0x0

#define	IOC3REGS_ERSR			IOC3REG_ERSR 
#define	IOC3REGS_ERSR_MASK		0xFFFFFFFF 
#define	IOC3REGS_ERSR_DEFAULT		0x0

#define	IOC3REGS_ETCDC			IOC3REG_ETCDC 
#define	IOC3REGS_ETCDC_MASK		0xFFFFFFFF 
#define	IOC3REGS_ETCDC_DEFAULT		0x0

#define	IOC3REGS_ETBR_H			IOC3REG_ETBR_H 
#define	IOC3REGS_ETBR_H_MASK		0xFFFFFFFF
#define	IOC3REGS_ETBR_H_DEFAULT		0x0

#define IOC3REGS_ETBR_L			IOC3REG_ETBR_L
#define IOC3REGS_ETBR_L_MASK		0xFFFFC001
#define IOC3REGS_ETBR_L_DEFAULT		0x0

#define IOC3REGS_ETCIR			IOC3REG_ETCIR
#define IOC3REGS_ETCIR_MASK		0x00003F80
#define IOC3REGS_ETCIR_DEFAULT		0x0

#define IOC3REGS_ETPIR			IOC3REG_ETPIR
#define IOC3REGS_ETPIR_MASK		0x00003F80
#define IOC3REGS_ETPIR_DEFAULT		0x0

#define IOC3REGS_EBIR			IOC3REG_EBIR
#define IOC3REGS_EBIR_MASK		0xFFFFDF1F
#define IOC3REGS_EBIR_DEFAULT		0x0

#define IOC3REGS_EMAR_H			IOC3REG_EMAR_H
#define IOC3REGS_EMAR_H_MASK		0x0000FFFF
#define IOC3REGS_EMAR_H_DEFAULT		0x0

#define IOC3REGS_EMAR_L			IOC3REG_EMAR_L
#define IOC3REGS_EMAR_L_MASK   		0xFFFFFFFE
#define IOC3REGS_EMAR_L_DEFAULT		0x0

#define IOC3REGS_EHAR_H			IOC3REG_EHAR_H
#define IOC3REGS_EHAR_H_MASK		0xFFFFFFFF
#define IOC3REGS_EHAR_H_DEFAULT		0x0

#define IOC3REGS_EHAR_L			IOC3REG_EHAR_L
#define IOC3REGS_EHAR_L_MASK		0xFFFFFFFF
#define IOC3REGS_EHAR_L_DEFAULT		0x0

#define IOC3REGS_MICR			IOC3REG_MICR
#define IOC3REGS_MICR_MASK		0xFFFFFFFF
#define IOC3REGS_MICR_DEFAULT		0x0

#define IOC3REGS_MIDR			IOC3REG_MIDR
#define IOC3REGS_MIDR_MASK		0xFFFFFFFF
#define IOC3REGS_MIDR_DEFAULT		0x0

#define IOC3REGS_INT_OUT_P		IOC3REG_INT_OUT_P
#define IOC3REGS_INT_OUT_P_MASK		0xFFFFFFFF
#define IOC3REGS_INT_OUT_P_DEFAULT	0x0

#define IOC3REGS_SSCR_A_P		IOC3REG_SSCR_A_P
#define IOC3REGS_SSCR_A_P_MASK		0xFFFFFFFF
#define IOC3REGS_SSCR_A_P_DEFAULT	0x0

#define IOC3REGS_STPIR_A_P		IOC3REG_STPIR_A_P
#define IOC3REGS_STPIR_A_P_MASK		0xFFFFFFFF
#define IOC3REGS_STPIR_A_P_DEFAULT	0x0

#define IOC3REGS_STCIR_A_P		IOC3REG_STCIR_A_P
#define IOC3REGS_STCIR_A_P_MASK		0xFFFFFFFF
#define IOC3REGS_STCIR_A_P_DEFAULT	0x0

#define IOC3REGS_SRPIR_A_P		IOC3REG_SRPIR_A_P
#define IOC3REGS_SRPIR_A_P_MASK		0xFFFFFFFF
#define IOC3REGS_SRPIR_A_P_DEFAULT	0x0

#define IOC3REGS_SRCIR_A_P		IOC3REG_SRCIR_A_P
#define IOC3REGS_SRCIR_A_P_MASK		0xFFFFFFFF
#define IOC3REGS_SRCIR_A_P_DEFAULT	0x0

#define IOC3REGS_SRTR_A_P		IOC3REG_SRTR_A_P
#define IOC3REGS_SRTR_A_P_MASK		0xFFFFFFFF
#define IOC3REGS_SRTR_A_P_DEFAULT	0x0

#define IOC3REGS_SHADOW_A_P		IOC3REG_SHADOW_A_P
#define IOC3REGS_SHADOW_A_P_MASK	0xFFFFFFFF
#define IOC3REGS_SHADOW_A_P_DEFAULT	0x0

#define IOC3REGS_SSCR_B_P		IOC3REG_SSCR_B_P
#define IOC3REGS_SSCR_B_P_MASK		0xFFFFFFFF
#define IOC3REGS_SSCR_B_P_DEFAULT	0x0

#define IOC3REGS_STPIR_B_P		IOC3REG_STPIR_B_P
#define IOC3REGS_STPIR_B_P_MASK		0xFFFFFFFF
#define IOC3REGS_STPIR_B_P_DEFAULT	0x0

#define IOC3REGS_STCIR_B_P		IOC3REG_STCIR_B_P
#define IOC3REGS_STCIR_B_P_MASK		0xFFFFFFFF
#define IOC3REGS_STCIR_B_P_DEFAULT	0x0

#define IOC3REGS_SRPIR_B_P		IOC3REG_SRPIR_B_P
#define IOC3REGS_SRPIR_B_P_MASK		0xFFFFFFFF
#define IOC3REGS_SRPIR_B_P_DEFAULT	0x0

#define IOC3REGS_SRCIR_B_P		IOC3REG_SRCIR_B_P
#define IOC3REGS_SRCIR_B_P_MASK		0xFFFFFFFF
#define IOC3REGS_SRCIR_B_P_DEFAULT	0x0

#define IOC3REGS_SRTR_B_P		IOC3REG_SRTR_B_P
#define IOC3REGS_SRTR_B_P_MASK		0xFFFFFFFF
#define IOC3REGS_SRTR_B_P_DEFAULT	0x0

#define IOC3REGS_SHADOW_B_P		IOC3REG_SHADOW_B_P
#define IOC3REGS_SHADOW_B_P_MASK	0xFFFFFFFF
#define IOC3REGS_SHADOW_B_P_DEFAULT	0x0


/* 
 * macro definitions: yes, the BR_xxxx_32 Reads and Writes are really 32 bits...
 * 	register access macros depend bridge_wid_no to be set to
 *	the correct xbow port id. Default is XBOW_PORT_F
 *	PIO_REG_WR_32(address, mask, value);
 *	PIO_REG_RD_32(address, mask, value);
 */	
                                         
/*
 * constants used in ioc3_regs.c
 */
#define	IOC3REGS_REGS_PATTERN_MAX	6

typedef struct	_ioc3_Registers {
	char		*name;  	/* name of the register */
	__uint32_t	address;	/* address */
	__uint32_t	mode;	    	/* read / write only or read & write */
	__uint32_t	mask;	    	/* read-write mask */
	__uint32_t	def;    	/* default value */
} ioc3_Registers;

typedef struct pcicfg32_s {
        __uint32_t      pci_id ;
        __uint32_t      pci_scr ;
        __uint32_t      pci_rev ;
        __uint32_t      pci_lat ;
        __uint32_t      pci_addr ;
        __uint32_t      pad_0[11] ;
        __uint32_t      pci_erraddrl ;
        __uint32_t      pci_erraddrh ;
} pcicfg32_t ;

#endif	/* __IDE_ioc3_H__ */
