
#ifndef __IDE_scsi_
#define	__IDE_scsi_

/*
 * Copyright 1995, Silicon Graphics, Inc.
 * ALL RIGHTS RESERVED
 *
 * UNPUBLISHED -- Rights reserved under the copyright laws of the United
 * States.   Use of a copyright notice is precautionary only and does not
 * imply publication or disclosure.
 *
 * U.S. GOVERNMENT RESTRICTED RIGHTS LEGEND:
 * Use, duplication or disclosure by the Government is subject to restrictions
 * as set forth in FAR 52.227.19(c)(2) or subparagraph (c)(1)(ii) of the Rights
 * in Technical Data and Computer Software clause at DFARS 252.227-7013 and/or
 * in similar or successor clauses in the FAR, or the DOD or NASA FAR
 * Supplement.  Contractor/manufacturer is Silicon Graphics, Inc.,
 * 2011 N. Shoreline Blvd. Mountain View, CA 94039-7311.
 *
 * THE CONTENT OF THIS WORK CONTAINS CONFIDENTIAL AND PROPRIETARY
 * INFORMATION OF SILICON GRAPHICS, INC. ANY DUPLICATION, MODIFICATION,
 * DISTRIBUTION, OR DISCLOSURE IN ANY FORM, IN WHOLE, OR IN PART, IS STRICTLY
 * PROHIBITED WITHOUT THE PRIOR EXPRESS WRITTEN PERMISSION OF SILICON
 * GRAPHICS, INC.
 */

#ident	"ide/godzilla/include/d_scsiregs.h:  $Revision: 1.4 $"

typedef __uint32_t              scsiregisters_t;

/*scsi PCI configuration space*/

#define SCSI_VENDOR_ID			SCSI0_PCI_CFG_BASE+0x0
#define SCSI_DEVICE_ID			SCSI0_PCI_CFG_BASE+0x2
#define SCSI_COMMAND			SCSI0_PCI_CFG_BASE+0x4
#define SCSI_STATUS			SCSI0_PCI_CFG_BASE+0x6
#define SCSI_REVISION_ID		SCSI0_PCI_CFG_BASE+0x8
#define SCSI_CLASS_CODE			SCSI0_PCI_CFG_BASE+0x9
#define SCSI_CACHE_LINE_SIZE		SCSI0_PCI_CFG_BASE+0xC
#define SCSI_LATENCY_TIMER		SCSI0_PCI_CFG_BASE+0xD
#define SCSI_HEADER_TYPE		SCSI0_PCI_CFG_BASE+0xE
#define SCSI_IO_BASE_ADDRESS		SCSI0_PCI_CFG_BASE+0x10
#define SCSI_MEMORY_BASE_ADDRESS	SCSI0_PCI_CFG_BASE+0x14
#define SCSI_ROM_BASE_ADDRESS		SCSI0_PCI_CFG_BASE+0x30
#define SCSI_INTR_LINE			SCSI0_PCI_CFG_BASE+0x3C
#define SCSI_INTR_PIN			SCSI0_PCI_CFG_BASE+0x3D
#define SCSI_MIN_GRANT			SCSI0_PCI_CFG_BASE+0x3E
#define SCSI_MAX_LATENCY		SCSI0_PCI_CFG_BASE+0x3F
/*memory space pci bus interface*/
#define SCSI_ID_LOW			SCSI0_PCI_DEVIO_BASE+0x0
#define SCSI_ID_HIGH			SCSI0_PCI_DEVIO_BASE+0x2
#define SCSI_CONF_0			SCSI0_PCI_DEVIO_BASE+0x4
#define SCSI_CONF_1			SCSI0_PCI_DEVIO_BASE+0x6
#define SCSI_INTF_CONTROL		SCSI0_PCI_DEVIO_BASE+0x8
#define SCSI_INTF_STATUS		SCSI0_PCI_DEVIO_BASE+0xA
#define SCSI_SEMAPHORE			SCSI0_PCI_DEVIO_BASE+0xC
#define SCSI_NVRAM_INTF			SCSI0_PCI_DEVIO_BASE+0xE
/*dma*/		
#define SCSI_DMA_CONF			SCSI0_PCI_DEVIO_BASE+0x20		
#define SCSI_DMA_CONTROL		SCSI0_PCI_DEVIO_BASE+0x22
#define SCSI_DMA_STATUS			SCSI0_PCI_DEVIO_BASE+0x24
#define SCSI_DMA_FIFO_STATUS		SCSI0_PCI_DEVIO_BASE+0x26
#define SCSI_DMA_TFR_COUNTER_LOW	SCSI0_PCI_DEVIO_BASE+0x28
#define SCSI_DMA_ADDR_WORD_CNT_0	SCSI0_PCI_DEVIO_BASE+0x2C
#define SCSI_DMA_ADDR_WORD_CNT_1	SCSI0_PCI_DEVIO_BASE+0x2E
#define SCSI_DMA_ADDR_WORD_CNT_2	SCSI0_PCI_DEVIO_BASE+0x30
#define SCSI_DMA_ADDR_WORD_CNT_3	SCSI0_PCI_DEVIO_BASE+0x32
#define SCSI_DMA2_CONF			SCSI0_PCI_DEVIO_BASE+0x40
#define SCSI_DMA2_CONTROL		SCSI0_PCI_DEVIO_BASE+0x42
#define SCSI_DMA2_STATUS		SCSI0_PCI_DEVIO_BASE+0x44
#define SCSI_DMA2_FIFO_STATUS		SCSI0_PCI_DEVIO_BASE+0x46
#define SCSI_DMA2_TFR_COUNTER_LOW	SCSI0_PCI_DEVIO_BASE+0x48
#define SCSI_DMA2_TFR_COUNTER_HIGH	SCSI0_PCI_DEVIO_BASE+0x4A
#define SCSI_DMA2_ADDR_WORD_CNT_0	SCSI0_PCI_DEVIO_BASE+0x4C
#define SCSI_DMA2_ADDR_WORD_CNT_1	SCSI0_PCI_DEVIO_BASE+0x4E
#define SCSI_DMA2_ADDR_WORD_CNT_2	SCSI0_PCI_DEVIO_BASE+0x50
#define SCSI_DMA2_ADDR_WORD_CNT_3	SCSI0_PCI_DEVIO_BASE+0x52
#define SCSI_DMA_COMM_FIFO_ADDR_PORT	SCSI0_PCI_DEVIO_BASE+0x60
#define SCSI_DMA_DATA_FIFO_ADDR_PORT	SCSI0_PCI_DEVIO_BASE+0x62
/*RISC registers*/	
#define SCSI_ACC				nSCSI0_PCI_DEVIO_BASE+0x80
#define SCSI_R1				SCSI0_PCI_DEVIO_BASE+0x82
#define SCSI_R2				SCSI0_PCI_DEVIO_BASE+0x84
#define SCSI_R3				SCSI0_PCI_DEVIO_BASE+0x86
#define SCSI_R4				SCSI0_PCI_DEVIO_BASE+0x88
#define SCSI_R5				SCSI0_PCI_DEVIO_BASE+0x8A
#define SCSI_R6				SCSI0_PCI_DEVIO_BASE+0x8C
#define SCSI_R7				SCSI0_PCI_DEVIO_BASE+0x8E
#define SCSI_R8				SCSI0_PCI_DEVIO_BASE+0x90
#define SCSI_R9				SCSI0_PCI_DEVIO_BASE+0x92
#define SCSI_R10			SCSI0_PCI_DEVIO_BASE+0x94
#define SCSI_R11			SCSI0_PCI_DEVIO_BASE+0x96
#define SCSI_R12			SCSI0_PCI_DEVIO_BASE+0x98
#define SCSI_R13			SCSI0_PCI_DEVIO_BASE+0x9A
#define SCSI_R14			SCSI0_PCI_DEVIO_BASE+0x9C
#define SCSI_R15			SCSI0_PCI_DEVIO_BASE+0x9E
#define SCSI_PROCESSOR_STATUS		SCSI0_PCI_DEVIO_BASE+0xA0
#define SCSI_INTR_VECTOR		SCSI0_PCI_DEVIO_BASE+0xA2
#define SCSI_PROCESSOR_CNTL		SCSI0_PCI_DEVIO_BASE+0xA4
#define SCSI_RAM_ADDR_0			SCSI0_PCI_DEVIO_BASE+0xA6
#define SCSI_RAM_ADDR_1			SCSI0_PCI_DEVIO_BASE+0xA8
#define SCSI_LOOP_CNT			SCSI0_PCI_DEVIO_BASE+0xAA
#define SCSI_PROGRAM_COUNTER		SCSI0_PCI_DEVIO_BASE+0xAC
#define SCSI_MEMORY_TIMING		SCSI0_PCI_DEVIO_BASE+0xAE
#define SCSI_EXT_MEM_BOUNDARY		SCSI0_PCI_DEVIO_BASE+0xB0
#define SCSI_STACK_POINTER		SCSI0_PCI_DEVIO_BASE+0xB2
#define SCSI_GPIO_DATA			SCSI0_PCI_DEVIO_BASE+0xB4
#define SCSI_GPIO_ENABLE		SCSI0_PCI_DEVIO_BASE+0xB6
#define SCSI_HW_REVISION_LEVEL		SCSI0_PCI_DEVIO_BASE+0xBE
#define SCSI_HOST_COMM_CNTL		SCSI0_PCI_DEVIO_BASE+0xC0
#define SCSI_PROCESSOR_BREAKPOINT_0	SCSI0_PCI_DEVIO_BASE+0xC2
#define SCSI_PROCESSOR_BREAKPOINT_1	SCSI0_PCI_DEVIO_BASE+0xC4
#define SCSI_TEST_CNTL			SCSI0_PCI_DEVIO_BASE+0xC6
#define SCSI_TEST_MODE			SCSI0_PCI_DEVIO_BASE+0xC8
/*spx*/	
#define SCSI_SXP_PART_ID		SCSI0_PCI_DEVIO_BASE+0x80
#define SCSI_SXP_CONF_1			SCSI0_PCI_DEVIO_BASE+0x82
#define SCSI_SXP_CONF_2			SCSI0_PCI_DEVIO_BASE+0x84
#define SCSI_SXP_CONF_3			SCSI0_PCI_DEVIO_BASE+0x86
#define SCSI_SXP_INSTR_POINTER		SCSI0_PCI_DEVIO_BASE+0x8C
#define SCSI_SXP_RETURN_ADDR		SCSI0_PCI_DEVIO_BASE+0x90
#define SCSI_SXP_COMMAND		SCSI0_PCI_DEVIO_BASE+0x94
#define SCSI_SXP_INTR			SCSI0_PCI_DEVIO_BASE+0x98
#define SCSI_SXP_SEQUENCE		SCSI0_PCI_DEVIO_BASE+0x9C
#define SCSI_SXP_GROSS_ERR		SCSI0_PCI_DEVIO_BASE+0x9E
#define SCSI_SXP_EXCEPTION		SCSI0_PCI_DEVIO_BASE+0xA0
#define SCSI_SXP_OVERRIDE		SCSI0_PCI_DEVIO_BASE+0xA4
#define SCSI_SXP_LITTERAL_BASE		SCSI0_PCI_DEVIO_BASE+0xA8
#define SCSI_SXP_USER_FLAGS		SCSI0_PCI_DEVIO_BASE+0xAC
#define SCSI_SXP_USER_EXCEPTION		SCSI0_PCI_DEVIO_BASE+0xB0
#define SCSI_SXP_BREAKPOINT		SCSI0_PCI_DEVIO_BASE+0xB4
#define SCSI_SXP_SCSI_BUS_ID		SCSI0_PCI_DEVIO_BASE+0xC0
#define SCSI_SXP_DEV_CONF_1		SCSI0_PCI_DEVIO_BASE+0xC2
#define SCSI_SXP_DEV_CONF_2		SCSI0_PCI_DEVIO_BASE+0xC4
#define SCSI_SXP_PHASE_POINTER		SCSI0_PCI_DEVIO_BASE+0xC8
#define SCSI_SXP_BUFFER_POINTER		SCSI0_PCI_DEVIO_BASE+0xCC
#define SCSI_SXP_BUFFER_COUNTER		SCSI0_PCI_DEVIO_BASE+0xD0
#define SCSI_SXP_BUFFER			SCSI0_PCI_DEVIO_BASE+0xD2
#define SCSI_SXP_BUFFER_BYTE		SCSI0_PCI_DEVIO_BASE+0xD4
#define SCSI_SXP_BUFFER_WORD		SCSI0_PCI_DEVIO_BASE+0xD6
#define SCSI_SXP_BUFFER_WORD_TRANS	SCSI0_PCI_DEVIO_BASE+0xD8
#define SCSI_SXP_FIFO			SCSI0_PCI_DEVIO_BASE+0xDA
#define SCSI_SXP_FIFI_STATUS		SCSI0_PCI_DEVIO_BASE+0xDC
#define SCSI_SXP_FIFO_TOP_RESIDUE	SCSI0_PCI_DEVIO_BASE+0xDE
#define SCSI_SXP_FIFO_BOTTOM_RESIDUE	SCSI0_PCI_DEVIO_BASE+0xE0
#define SCSI_SXP_TFR_REGISTER		SCSI0_PCI_DEVIO_BASE+0xE4
#define SCSI_SXP_TFR_COUNT_LOW		SCSI0_PCI_DEVIO_BASE+0xE8
#define SCSI_SXP_TFR_COUNT_HIGH		SCSI0_PCI_DEVIO_BASE+0xEA
#define SCSI_SXP_TFR_COUNTER_LOW	SCSI0_PCI_DEVIO_BASE+0xEC
#define SCSI_SXP_TFR_COUNTER_HIGH	SCSI0_PCI_DEVIO_BASE+0xEE
#define SCSI_SXP_ARBITRATION_DATA	SCSI0_PCI_DEVIO_BASE+0xF0
#define SCSI_SXP_CONTROL_PINS		SCSI0_PCI_DEVIO_BASE+0xF2
#define SCSI_SXP_DATA_PINS		SCSI0_PCI_DEVIO_BASE+0xF4
#define SCSI_SXP_DIFF_CNTL_PINS		SCSI0_PCI_DEVIO_BASE+0xF6
/*mail box*/		
#define SCSI_MAILBOX0			SCSI0_PCI_DEVIO_BASE+0x70
#define SCSI_MAILBOX1			SCSI0_PCI_DEVIO_BASE+0x72
#define SCSI_MAILBOX2			SCSI0_PCI_DEVIO_BASE+0x74	
#define SCSI_MAILBOX3			SCSI0_PCI_DEVIO_BASE+0x76
#define SCSI_MAILBOX4			SCSI0_PCI_DEVIO_BASE+0x78
#define SCSI_MAILBOX5			SCSI0_PCI_DEVIO_BASE+0x7A
#define SCSI_MAILBOX6			SCSI0_PCI_DEVIO_BASE+0x7C
#define SCSI_MAILBOX7			SCSI0_PCI_DEVIO_BASE+0x7E

/*register test constants*/


#define SCSI_VENDOR_ID_MASK			0xFFFFFFFF
#define SCSI_VENDOR_ID_DEFAULT			0x01020

#define SCSI_DEVICE_ID_MASK			0xFFFFFFFF
#define SCSI_DEVICE_ID_DEFAULT			0x01077

#define SCSI_COMMAND_MASK			0xFFFFFFFF
#define SCSI_COMMAND_DEFAULT			0x0

#define SCSI_STATUS_MASK			0xFFFFFFFF
#define SCSI_STATUS_DEFAULT			0x0

#define SCSI_REVISION_ID_MASK			0xFFFFFFFF
#define SCSI_REVISION_ID_DEFAULT		0x01

#define SCSI_CLASS_CODE_MASK			0xFFFFFFFF
#define SCSI_CLASS_CODE_DEFAULT			0x0

#define SCSI_CACHE_LINE_SIZE_MASK		0xFFFFFFFF
#define SCSI_CACHE_LINE_SIZE_DEFAULT		0x0

#define SCSI_LATENCY_TIMER_MASK			0xF8
#define SCSI_LATENCY_TIMER_DEFAULT		0x0

#define SCSI_HEADER_TYPE_MASK			0xFFFFFFFF
#define SCSI_HEADER_TYPE_DEFAULT		0x0

#define SCSI_IO_BASE_ADDRESS_MASK		0xFFFFFF00
#define SCSI_IO_BASE_ADDRESS_DEFAULT		0x0

#define SCSI_MEMORY_BASE_ADDRESS_MASK		0xFFFFF000
#define SCSI_MEMORY_BASE_ADDRESS_DEFAULT	0x0

#define SCSI_ROM_BASE_ADDRESS_MASK		0xFFFF0000
#define SCSI_ROM_BASE_ADDRESS_DEFAULT		0x0

#define SCSI_INTR_LINE_MASK			0xFFFFFFFF
#define SCSI_INTR_LINE_DEFAULT			0x0

#define SCSI_INTR_PIN_MASK			0xFFFFFFFF
#define SCSI_INTR_PIN_DEFAULT			0x0

#define SCSI_MIN_GRANT_MASK			0xFFFFFFFF
#define SCSI_MIN_GRANT_DEFAULT			0x0

#define SCSI_MAX_LATENCY_MASK			0xFFFFFFFF
#define SCSI_MAX_LATENCY_DEFAULT		0x0

#define SCSI_ID_LOW_MASK			0xFFFFFFFF
#define SCSI_ID_LOW_DEFAULT			0x0

#define SCSI_ID_HIGH_MASK			0xFFFFFFFF
#define SCSI_ID_HIGH_DEFAULT			0x0

#define SCSI_CONF_0_MASK			0xFFFFFFFF
#define SCSI_CONF_0_DEFAULT			0x0

#define SCSI_CONF_1_MASK			0xFFFFFFFF
#define SCSI_CONF_1_DEFAULT			0x0

#define SCSI_INTF_CONTROL_MASK			0xFFFFFFFF
#define SCSI_INTF_CONTROL_DEFAULT		0x0

#define SCSI_INTF_STATUS_MASK			0xFFFFFFFF
#define SCSI_INTF_STATUS_DEFAULT		0x0

#define SCSI_SEMAPHORE_MASK			0x3
#define SCSI_SEMAPHORE_DEFAULT			0x0

#define SCSI_NVRAM_INTF_MASK			0xF
#define SCSI_NVRAM_INTF_DEFAULT			0x0

#define SCSI_DMA_CONF_MASK			0xFFFFFFFF
#define SCSI_DMA_CONF_DEFAULT			0x0

#define SCSI_DMA_CONTROL_MASK			0xFFFFFFFF
#define SCSI_DMA_CONTROL_DEFAULT		0x0

#define SCSI_DMA_STATUS_MASK			0xFFFFFFFF
#define SCSI_DMA_STATUS_DEFAULT			0x0

#define SCSI_DMA_FIFO_STATUS_MASK		0xFFFFFFFF
#define SCSI_DMA_FIFO_STATUS_DEFAULT		0x0

#define SCSI_DMA_TFR_COUNTER_LOW_MASK		0xFFFFFFFF
#define SCSI_DMA_TFR_COUNTER_LOW_DEFAULT	0x0

#define SCSI_DMA_ADDR_WORD_CNT_0_MASK		0xFFFFFFFF
#define SCSI_DMA_ADDR_WORD_CNT_0_DEFAULT	0x0

#define SCSI_DMA_ADDR_WORD_CNT_1_MASK		0xFFFFFFFF
#define SCSI_DMA_ADDR_WORD_CNT_1_DEFAULT	0x0

#define SCSI_DMA_ADDR_WORD_CNT_2_MASK		0xFFFFFFFF
#define SCSI_DMA_ADDR_WORD_CNT_2_DEFAULT	0x0

#define SCSI_DMA_ADDR_WORD_CNT_3_MASK		0xFFFFFFFF
#define SCSI_DMA_ADDR_WORD_CNT_3_DEFAULT	0x0

#define SCSI_DMA2_CONF_MASK			0xFFFFFFFF
#define SCSI_DMA2_CONF_DEFAULT			0x0

#define SCSI_DMA2_CONTROL_MASK			0xFFFFFFFF
#define SCSI_DMA2_CONTROL_DEFAULT		0x0

#define SCSI_DMA2_STATUS_MASK			0xFFFFFFFF
#define SCSI_DMA2_STATUS_DEFAULT		0x0

#define SCSI_DMA2_FIFO_STATUS_MASK		0xFFFFFFFF
#define SCSI_DMA2_FIFO_STATUS_DEFAULT		0x0

#define SCSI_DMA2_TFR_COUNTER_LOW_MASK		0xFFFFFFFF
#define SCSI_DMA2_TFR_COUNTER_LOW_DEFAULT	0x0

#define SCSI_DMA2_TFR_COUNTER_HIGH_MASK		0xFFFFFFFF
#define SCSI_DMA2_TFR_COUNTER_HIGH_DEFAULT	0x0

#define SCSI_DMA2_ADDR_WORD_CNT_0_MASK		0xFFFFFFFF
#define SCSI_DMA2_ADDR_WORD_CNT_0_DEFAULT	0x0

#define SCSI_DMA2_ADDR_WORD_CNT_1_MASK		0xFFFFFFFF
#define SCSI_DMA2_ADDR_WORD_CNT_1_DEFAULT	0x0

#define SCSI_DMA2_ADDR_WORD_CNT_2_MASK		0xFFFFFFFF
#define SCSI_DMA2_ADDR_WORD_CNT_2_DEFAULT	0x0

#define SCSI_DMA2_ADDR_WORD_CNT_3_MASK		0xFFFFFFFF
#define SCSI_DMA2_ADDR_WORD_CNT_3_DEFAULT	0x0

#define SCSI_DMA_COMM_FIFO_ADDR_PORT_MASK	0xFFFFFFFF
#define SCSI_DMA_COMM_FIFO_ADDR_PORT_DEFAULT	0x0

#define SCSI_DMA_DATA_FIFO_ADDR_PORT_MASK	0xFFFFFFFF
#define SCSI_DMA_DATA_FIFO_ADDR_PORT_DEFAULT	0x0

#define SCSI_ACC_MASK			0xFFFFFFFF
#define SCSI_ACC_DEFAULT		0x0

#define SCSI_R1_MASK			0xFFFFFFFF
#define SCSI_R1_DEFAULT			0x0

#define SCSI_R2_MASK			0xFFFFFFFF
#define SCSI_R2_DEFAULT			0x0

#define SCSI_R3_MASK			0xFFFFFFFF
#define SCSI_R3_DEFAULT			0x0

#define SCSI_R4_MASK			0xFFFFFFFF
#define SCSI_R4_DEFAULT			0x0

#define SCSI_R5_MASK			0xFFFFFFFF
#define SCSI_R5_DEFAULT			0x0

#define SCSI_R6_MASK			0xFFFFFFFF
#define SCSI_R6_DEFAULT			0x0

#define SCSI_R7_MASK			0xFFFFFFFF
#define SCSI_R7_DEFAULT			0x0

#define SCSI_R8_MASK			0xFFFFFFFF
#define SCSI_R8_DEFAULT			0x0

#define SCSI_R9_MASK			0xFFFFFFFF
#define SCSI_R9_DEFAULT			0x0

#define SCSI_R10_MASK			0xFFFFFFFF
#define SCSI_R10_DEFAULT		0x0

#define SCSI_R11_MASK			0xFFFFFFFF
#define SCSI_R11_DEFAULT		0x0

#define SCSI_R12_MASK			0xFFFFFFFF
#define SCSI_R12_DEFAULT		0x0

#define SCSI_R13_MASK			0xFFFFFFFF
#define SCSI_R13_DEFAULT		0x0

#define SCSI_R14_MASK			0xFFFFFFFF
#define SCSI_R14_DEFAULT		0x0

#define SCSI_R15_MASK			0xFFFFFFFF
#define SCSI_R15_DEFAULT		0x0

#define SCSI_PROCESSOR_STATUS_MASK	0xFFFFFFFF
#define SCSI_PROCESSOR_STATUS_DEFAULT	0x0

#define SCSI_INTR_VECTOR_MASK		0xFFFFFFFF
#define SCSI_INTR_VECTOR_DEFAULT	0x0

#define SCSI_PROCESSOR_CNTL_MASK	0xFFFFFFFF
#define SCSI_PROCESSOR_CNTL_DEFAULT	0x0

#define SCSI_RAM_ADDR_0_MASK		0xFFFFFFFF
#define SCSI_RAM_ADDR_0_DEFAULT		0x0

#define SCSI_RAM_ADDR_1_MASK		0xFFFFFFFF
#define SCSI_RAM_ADDR_1_DEFAULT		0x0

#define SCSI_LOOP_CNT_MASK		0xFFFFFFFF
#define SCSI_LOOP_CNT_DEFAULT		0x0

#define SCSI_PROGRAM_COUNTER_MASK	0xFFFFFFFF
#define SCSI_PROGRAM_COUNTER_DEFAULT	0x0

#define SCSI_MEMORY_TIMING_MASK		0xFFFFFFFF
#define SCSI_MEMORY_TIMING_DEFAULT	0x0

#define SCSI_EXT_MEM_BOUNDARY_MASK	0xFFFFFFFF
#define SCSI_EXT_MEM_BOUNDARY_DEFAULT	0x0

#define SCSI_STACK_POINTER_MASK		0xFFFFFFFF
#define SCSI_STACK_POINTER_DEFAULT	0x0

#define SCSI_GPIO_DATA_MASK		0xFFFFFFFF
#define SCSI_GPIO_DATA_DEFAULT		0x0

#define SCSI_GPIO_ENABLE_MASK		0xFFFFFFFF
#define SCSI_GPIO_ENABLE_DEFAULT	0x0

#define SCSI_HW_REVISION_LEVEL_MASK	0xFFFFFFFF
#define SCSI_HW_REVISION_LEVEL_DEFAULT	0x0

#define SCSI_HOST_COMM_CNTL_MASK	0xFFFFFFFF
#define SCSI_HOST_COMM_CNTL_DEFAULT	0x0

#define SCSI_PROCESSOR_BREAKPOINT_0_MASK	0xFFFFFFFF
#define SCSI_PROCESSOR_BREAKPOINT_0_DEFAULT	0x0

#define SCSI_PROCESSOR_BREAKPOINT_1_MASK	0xFFFFFFFF
#define SCSI_PROCESSOR_BREAKPOINT_1_DEFAULT	0x0

#define SCSI_TEST_CNTL_MASK			0xFFFFFFFF
#define SCSI_TEST_CNTL_DEFAULT			0x0

#define SCSI_TEST_MODE_MASK			0xFFFFFFFF
#define SCSI_TEST_MODE_DEFAULT			0x0

#define SCSI_SXP_PART_ID_MASK			0xFFFFFFFF
#define SCSI_SXP_PART_ID_DEFAULT		0x0

#define SCSI_SXP_CONF_1_MASK			0xFEEF
#define SCSI_SXP_CONF_1_DEFAULT			0x0

#define SCSI_SXP_CONF_2_MASK			0x007F
#define SCSI_SXP_CONF_2_DEFAULT			0x0

#define SCSI_SXP_CONF_3_MASK			0xFE0F
#define SCSI_SXP_CONF_3_DEFAULT			0x0

#define SCSI_SXP_INSTR_POINTER_MASK		0xFFFF
#define SCSI_SXP_INSTR_POINTER_DEFAULT		0x0

#define SCSI_SXP_RETURN_ADDR_MASK		0x01FF
#define SCSI_SXP_RETURN_ADDR_DEFAULT		0x0

#define SCSI_SXP_COMMAND_MASK			0xFFFF
#define SCSI_SXP_COMMAND_DEFAULT		0x0

#define SCSI_SXP_INTR_MASK			0xFFFFFFFF
#define SCSI_SXP_INTR_DEFAULT			0x0

#define SCSI_SXP_SEQUENCE_MASK			0xFFFFFFFF
#define SCSI_SXP_SEQUENCE_DEFAULT		0x0

#define SCSI_SXP_GROSS_ERR_MASK			0xFFFFFFFF
#define SCSI_SXP_GROSS_ERR_DEFAULT		0x0

#define SCSI_SXP_EXCEPTION_MASK			0xD7F8
#define SCSI_SXP_EXCEPTION_DEFAULT		0x0

#define SCSI_SXP_OVERRIDE_MASK			0xFFFFFFFF
#define SCSI_SXP_OVERRIDE_DEFAULT		0x0

#define SCSI_SXP_LITTERAL_BASE_MASK		0xFFFFFFFF
#define SCSI_SXP_LITTERAL_BASE_DEFAULT		0x0

#define SCSI_SXP_USER_FLAGS_MASK		0xFFFFFFFF
#define SCSI_SXP_USER_FLAGS_DEFAULT		0x0

#define SCSI_SXP_USER_EXCEPTION_MASK		0xFFFFFFFF
#define SCSI_SXP_USER_EXCEPTION_DEFAULT		0x0

#define SCSI_SXP_BREAKPOINT_MASK		0xFFFFFFFF
#define SCSI_SXP_BREAKPOINT_DEFAULT		0x0

#define SCSI_SXP_SCSI_BUS_ID_MASK		0xFFFFFFFF
#define SCSI_SXP_SCSI_BUS_ID_DEFAULT		0x0

#define SCSI_SXP_DEV_CONF_1_MASK		0xFFFFFFFF
#define SCSI_SXP_DEV_CONF_1_DEFAULT		0x0

#define SCSI_SXP_DEV_CONF_2_MASK		0xFFFFFFFF
#define SCSI_SXP_DEV_CONF_2_DEFAULT		0x0

#define SCSI_SXP_PHASE_POINTER_MASK		0xFFFFFFFF
#define SCSI_SXP_PHASE_POINTER_DEFAULT		0x0

#define SCSI_SXP_BUFFER_POINTER_MASK		0xFFFFFFFF
#define SCSI_SXP_BUFFER_POINTER_DEFAULT		0x0

#define SCSI_SXP_BUFFER_COUNTER_MASK		0xFFFFFFFF
#define SCSI_SXP_BUFFER_COUNTER_DEFAULT		0x0

#define SCSI_SXP_BUFFER_MASK			0xFFFFFFFF
#define SCSI_SXP_BUFFER_DEFAULT			0x0

#define SCSI_SXP_BUFFER_BYTE_MASK		0xFFFFFFFF
#define SCSI_SXP_BUFFER_BYTE_DEFAULT		0x0

#define SCSI_SXP_BUFFER_WORD_MASK		0xFFFFFFFF
#define SCSI_SXP_BUFFER_WORD_DEFAULT		0x0

#define SCSI_SXP_BUFFER_WORD_TRANS_MASK		0xFFFFFFFF
#define SCSI_SXP_BUFFER_WORD_TRANS_DEFAULT	0x0

#define SCSI_SXP_FIFO_MASK			0xFFFFFFFF
#define SCSI_SXP_FIFO_DEFAULT			0x0

#define SCSI_SXP_FIFI_STATUS_MASK		0xFFFFFFFF
#define SCSI_SXP_FIFI_STATUS_DEFAULT		0x0

#define SCSI_SXP_FIFO_TOP_RESIDUE_MASK		0xFFFFFFFF
#define SCSI_SXP_FIFO_TOP_RESIDUE_DEFAULT	0x0

#define SCSI_SXP_FIFO_BOTTOM_RESIDUE_MASK	0xFFFFFFFF
#define SCSI_SXP_FIFO_BOTTOM_RESIDUE_DEFAULT	0x0

#define SCSI_SXP_TFR_REGISTER_MASK		0xFFFFFFFF
#define SCSI_SXP_TFR_REGISTER_DEFAULT		0x0

#define SCSI_SXP_TFR_COUNT_LOW_MASK		0xFFFFFFFF
#define SCSI_SXP_TFR_COUNT_LOW_DEFAULT		0x0

#define SCSI_SXP_TFR_COUNT_HIGH_MASK		0xFFFFFFFF
#define SCSI_SXP_TFR_COUNT_HIGH_DEFAULT		0x0

#define SCSI_SXP_TFR_COUNTER_LOW_MASK		0xFFFFFFFF
#define SCSI_SXP_TFR_COUNTER_LOW_DEFAULT	0x0

#define SCSI_SXP_TFR_COUNTER_HIGH_MASK		0xFFFFFFFF
#define SCSI_SXP_TFR_COUNTER_HIGH_DEFAULT	0x0

#define SCSI_SXP_ARBITRATION_DATA_MASK		0xFFFFFFFF
#define SCSI_SXP_ARBITRATION_DATA_DEFAULT	0x0

#define SCSI_SXP_CONTROL_PINS_MASK		0xFFFFFFFF
#define SCSI_SXP_CONTROL_PINS_DEFAULT		0x0

#define SCSI_SXP_DATA_PINS_MASK			0xFFFFFFFF
#define SCSI_SXP_DATA_PINS_DEFAULT		0x0

#define SCSI_SXP_DIFF_CNTL_PINS_MASK		0xFFFFFFFF
#define SCSI_SXP_DIFF_CNTL_PINS_DEFAULT		0x0

#define SCSI_MAILBOX0_MASK			0xFFFFFFFF
#define SCSI_MAILBOX0_DEFAULT			0x0

#define SCSI_MAILBOX1_MASK			0xFFFFFFFF
#define SCSI_MAILBOX1_DEFAULT			0x0

#define SCSI_MAILBOX2_MASK			0xFFFFFFFF
#define SCSI_MAILBOX2_DEFAULT			0x0

#define SCSI_MAILBOX3_MASK			0xFFFFFFFF
#define SCSI_MAILBOX3_DEFAULT			0x0

#define SCSI_MAILBOX4_MASK			0xFFFFFFFF
#define SCSI_MAILBOX4_DEFAULT			0x0

#define SCSI_MAILBOX5_MASK			0xFFFFFFFF
#define SCSI_MAILBOX5_DEFAULT			0x0

#define SCSI_MAILBOX6_MASK			0xFFFFFFFF
#define SCSI_MAILBOX6_DEFAULT			0x0

#define SCSI_MAILBOX7_MASK			0xFFFFFFFF
#define SCSI_MAILBOX7_DEFAULT			0x0

/*SCSI 1 memory space*/
#define SCSI1_SEMAPHORE                         SCSI1_PCI_DEVIO_BASE+0xC
#define SCSI1_SEMAPHORE_MASK                    0x3
#define SCSI1_SEMAPHORE_DEFAULT	                0x0
/*
 * constants used in scsi_regs.c
 */
#define	SCSIREGS_REGS_PATTERN_MAX	6
#define MEMORY_SPACE_ENABLE 0x2
#define BUS_MASTER_ENABLE   0x4
#define ICR_SOFT_RESET          0x0001
#define ICR_ENABLE_ALL_INTS     0x0002
#define ICR_ENABLE_RISC_INT     0x0004
#define ICR_ENABLE_SXP_INT      0x0004
#define HCCR_CMD_RESET              0x1000  /* reset RISC */
#define HCCR_CMD_PAUSE              0x2000  /* pause RISC */
#define HCCR_CMD_RELEASE            0x3000  /* release paused RISC */
#define HCCR_CMD_SET_HOST_INT       0x5000  /* set host interrupt */
#define HCCR_CMD_CLEAR_RISC_INT     0x7000  /* clear RISC interrupt */
#define HCCR_WRITE_BIOS_ENABLE      0x9000  /* write BIOS enable */
#define HCCR_SRAM_PARITY_ENABLE     0xA000  /* enable sram parity */
#define HCCR_FORCE_PARITY_ERROR     0xE000  /* enable sram parity */
#define CONF_1_BURST_ENABLE     0x4

typedef struct	_scsi_Registers {
	char		*name;  	/* name of the register */
	__uint32_t	address;	/* address */
	__uint32_t	mode;	    	/* read / write only or read & write */
	__uint32_t	mask;	    	/* read-write mask */
	__uint32_t	def;    	/* default value */
	__uint32_t	size;    	/* rtegister size */
} scsi_Registers;

#endif	/* __IDE_scsi_ */
