/*	Copyright (c) 1990, 1991 UNIX System Laboratories, Inc.	*/
/*	Copyright (c) 1988 AT&T	*/
/*	  All Rights Reserved  	*/

/*	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF     	*/
/*	UNIX System Laboratories, Inc.                     	*/
/*	The copyright notice above does not evidence any   	*/
/*	actual or intended publication of such source code.	*/

#ident	"@(#)libc:inc/synonyms.h	1.40.2.1"

#define __pread32	___pread32
#define __pwrite32	___pwrite32
#define endpwent	_endpwent
#define endspent	_endspent
#define fgetpwent	_fgetpwent
#define fgetpwent_r	_fgetpwent_r
#define fgetspent	_fgetspent
#define fgetspent_r	_fgetspent_r
#define getpwent	_getpwent
#define getpwent_r	_getpwent_r
#define getpwnam	_getpwnam
#define getpwnam_r	_getpwnam_r
#define getpwuid	_getpwuid
#define getpwuid_r	_getpwuid_r
#define getspent	_getspent
#define getspent_r	_getspent_r
#define getspnam	_getspnam
#define getspnam_r	_getspnam_r
#define putpwent	_putpwent
#define putspent	_putspent
#define setpwent	_setpwent
#define setspent	_setspent

/* external data */
#define _ctype_		__ctype_
#define altzone		_altzone
#define capabilities	_capabilities
#define daylight	_daylight
#define getdate_err	_getdate_err
#define	h_errno		_h_errno
#define lone		_lone
#define lten		_lten
#define lzero		_lzero
#define	opterr		_opterr
#define	optind		_optind
#define	optopt		_optopt
#define	optarg		_optarg
#define sys_errlist	_sys_errlist
#define sys_nerr	_sys_nerr
#define timezone	_timezone
#define tzname		_tzname
#define rpc_createerr	_rpc_createerr
#define svc_fdset	_svc_fdset
#define ypbind_resp_arms	_ypbind_resp_arms

/*
 * The memory allocation routines (malloc, free, realloc, calloc, memalign)
 * are weak symbols so that users can create their own allocation routines
 * or put wrappers around the libc version. HOWEVER unlike other weak symbols,
 * these routines must not be defined here in this libc header. Modules
 * internal to libc include this header so that they directly (and correctly)
 * call the strong symbols (the underbar version, _function). But in the case
 * of the allocation routines, libc modules should be calling the user defined
 * routines, if they exist, or else the weak symbols.
 *
 * #define calloc	_calloc
 * #define free		_free
 * #define malloc	_malloc
 * #define memalign	_memalign
 * #define realloc	_realloc
 */

/* functions */
#define	ABIinfo		_ABIinfo
#define	BSD_getime	_BSD_getime
#define	Msgdb		_Msgdb
#define a64l		_a64l
#define acalloc		_acalloc
#define accept		_accept
#define access		_access
#define acct		_acct
#define acquire_lock	_acquire_lock
#define acreate		_acreate
#define addexportent	_addexportent
#define addmntent	_addmntent
#define addsev		_addsev
#define addseverity	_addseverity
#define adelete		_adelete
#define adjtime		_adjtime
#define afree		_afree
#define aio_cancel	_aio_cancel
#define aio_cancel64	_aio_cancel64
#define aio_error	_aio_error
#define aio_error64	_aio_error64
#define aio_fsync	_aio_fsync
#define aio_fsync64	_aio_fsync64
#define aio_hold        _aio_hold
#define aio_hold64	_aio_hold64
#define aio_read	_aio_read
#define aio_read64	_aio_read64
#define aio_return	_aio_return
#define aio_return64	_aio_return64
#define aio_sgi_init    _aio_sgi_init
#define aio_sgi_init64	_aio_sgi_init64
#define aio_suspend	_aio_suspend
#define aio_suspend64	_aio_suspend64
#define aio_write	_aio_write
#define aio_write64	_aio_write64
#define aio_init	_aio_init
#define alarm		_alarm
#define alphasort	_alphasort
#define alphasort64	_alphasort64
#define amallinfo	_amallinfo
#define amalloc		_amalloc
#define amallocblksize	_amallocblksize
#define amallopt	_amallopt
#define amemalign	_amemalign
#define arealloc	_arealloc
#define arecalloc	_arecalloc
#define argvtostr	_argvtostr
#define arsctl		_arsctl
#define arsop		_arsop
#define ascftime	_ascftime
#define asctime_r	_asctime_r
#define async_daemon	_async_daemon
#define atcheckpoint	_atcheckpoint
#define atrestart	_atrestart
#define atfork_child	_atfork_child
#define atfork_child_prepend	_atfork_child_prepend
#define atfork_parent	_atfork_parent
#define atfork_pre	_atfork_pre
#define atsproc_child	_atsproc_child
#define atsproc_parent	_atsproc_parent
#define atsproc_pre	_atsproc_pre
#define atold		_atold
#define atoll		_atoll
#define atomic_op	_atomic_op
#define atomic_op32	_atomic_op32
#define attr_get	_attr_get
#define attr_getf	_attr_getf
#define attr_list	_attr_list
#define attr_listf	_attr_listf
#define attr_multi	_attr_multi
#define attr_multif	_attr_multif
#define attr_remove	_attr_remove
#define attr_removef	_attr_removef
#define attr_set	_attr_set
#define attr_setf	_attr_setf
#define auditbuf	_auditbuf
#define auditctl	_auditctl
#define auditdmp	_auditdmp
#define auditevt	_auditevt
#define auditlog	_auditlog
#define barrier		_barrier
#define bclr		_bclr
#define bcmp		_bcmp
#define bcopy		_bcopy
#define bfclr		_bfclr
#define bfset		_bfset
#define bftstclr	_bftstclr
#define bftstset	_bftstset
#define bind		_bind
#define bindresvport	_bindresvport
#define blkclr		_blkclr
#define blockproc	_blockproc
#define blockprocall	_blockprocall
#define brk		_brk
#define brkbase		_brkbase
#define bset		_bset
#define bt_arg		_bt_arg
#define bt_argend	_bt_argend
#define bt_argstart	_bt_argstart
#define bt_end		_bt_end
#define bt_next		_bt_next
#define bt_start	_bt_start
#define bt_symloc	_bt_symloc
#define btowc		_btowc
#define btst		_btst
#define bzero		_bzero
#define cachectl	_cachectl
#define cacheflush	_cacheflush
#define cache_synch_handler	_cache_synch_handler
#define catclose	_catclose
#define catgetmsg	_catgetmsg
#define __catgetmsg_error_code ___catgetmsg_error_code
#define catgets		_catgets
#define __catgets_error_code ___catgets_error_code
#define catopen		_catopen
#define __catopen_error_code ___catopen_error_code
#define catmsgfmt	_catmsgfmt
#define _cat_name	__cat_name
#define __cat_path_name ___cat_path_name
#define _cat_init       __cat_init
#define cfgetispeed	_cfgetispeed
#define __new_cfgetispeed ___new_cfgetispeed
#define cfgetospeed	_cfgetospeed
#define __new_cfgetospeed ___new_cfgetospeed
#define cfree		_cfree
#define cfsetispeed	_cfsetispeed
#define __new_cfsetispeed ___new_cfsetispeed
#define cfsetospeed	_cfsetospeed
#define __new_cfsetospeed ___new_cfsetospeed
#define cftime		_cftime
#define chdir		_chdir
#define chmod		_chmod
#define chown		_chown
#define chproj		_chproj
#define chroot		_chroot
#define clock_getres	_clock_getres
#define clock_gettime	_clock_gettime
#define clock_settime	_clock_settime
#define close		_close
#define closedir	_closedir
#define closelog	_closelog
#define closeproj	_closeproj
#define confstr		_confstr
#define connect		_connect
#define creat		_creat
#define creat64		_creat64
#define crypt		_crypt
#define ctermid		_ctermid
#define ctermid_r	_ctermid_r
#define ctime_r		_ctime_r
#define cuserid		_cuserid
#define	delmntent	_delmntent
#define dev_to_devname	_dev_to_devname
#define fdes_to_devname	_fdes_to_devname
#define filename_to_devname _filename_to_devname
#define dev_to_drivername _dev_to_drivername
#define fdes_to_drivername _fdes_to_drivername
#define filename_to_drivername _filename_to_drivername
#define devstat		_devstat
#define dial		_dial
#define dlopen		_dlopen
#define dlclose		_dlclose
#define dlsym		_dlsym
#define dlerror		_dlerror
#define	dmi		_dmi
#define drand48		_drand48
#define dup		_dup
#define dup2		_dup2
#define ecvt		_ecvt
#define ecvt_r		_ecvt_r
#define edata		_edata
#define eicbusywait	_eicbusywait
#define eicbusywait_f	_eicbusywait_f
#define eicclear	_eicclear
#define eicclear_f	_eicclear_f
#define eicinit		_eicinit
#define eicinit_f	_eicinit_f
#define encrypt		_encrypt
#ifndef _LANGUAGE_ASSEMBLY
#define end		_end
#endif
#define endexportent	_endexportent
#define endgrent	_endgrent
#define endinvent	_endinvent
#define endinvent_r	_endinvent_r
#define endmntent	_endmntent
#define endnetgrent	_endnetgrent
#define endprident	_endprident
#define endprojent	_endprojent
#define endrpcent	_endrpcent
#define endutent	_endutent
#define endutxent	_endutxent
#define environ		_environ
#define erand48		_erand48
#define etext		_etext
#define ether_aton	_ether_aton
#define ether_aton_r	_ether_aton_r
#define ether_hostton	_ether_hostton
#define ether_line	_ether_line
#define ether_ntoa	_ether_ntoa
#define ether_ntoa_r	_ether_ntoa_r
#define ether_ntohost	_ether_ntohost
#define execl		_execl
#define execle		_execle
#define execlp		_execlp
#define execv		_execv
#define execve		_execve
#define execvp		_execvp
#define exportfs	_exportfs
#define fattach		_fattach
#define fchdir		_fchdir
#define fchmod		_fchmod
#define fchown		_fchown
#define fchproj		_fchproj
#define fcntl		_fcntl
#define fcvt		_fcvt
#define fcvt_r		_fcvt_r
#define fdatasync	_fdatasync
#define fdetach		_fdetach
#define fdevstat	_fdevstat
#define fdopen		_fdopen
#define ffs		_ffs
#define fgetdfltprojuser _fgetdfltprojuser
#define fgetgrent	_fgetgrent
#define fgetgrent_r	_fgetgrent_r
#define fgethostent	_fgethostent
#define fgethostent_r	_fgethostent_r
#define fgetnetent	_fgetnetent
#define fgetnetent_r	_fgetnetent_r
#define fgetprotoent	_fgetprotoent
#define fgetprotoent_r	_fgetprotoent_r
#define fgetrpcent	_fgetrpcent
#define fgetrpcent_r	_fgetrpcent_r
#define fgetservent	_fgetservent
#define fgetservent_r	_fgetservent_r
#define fgetpos64	_fgetpos64
#define fgetprojall	_fgetprojall
#define fgetprojuser	_fgetprojuser
#define fgetwc		_fgetwc
#define fgetws		_fgetws
#define filepriv	_filepriv
#define finite		_finite
#define finitel		_finitel
#define flockfile	_flockfile
#define flvlfile	_flvlfile
#define fmtmsg		_fmtmsg
#define fnmatch		_fnmatch
#define fopen		_fopen
#define fopen64		_fopen64
#define fork		_fork
#define fp_class_d	_fp_class_d
#define fp_class_f	_fp_class_f
#define fp_class_q	_fp_class_q
#define fpathconf	_fpathconf
#define fpclass		_fpclass
#define fpclassl	_fpclassl
#define fpgetmask	_fpgetmask
#define fpgetround	_fpgetround
#define fpgetsticky	_fpgetsticky
#define fprojid		_fprojid
#define	fprojname	_fprojname
#define fpsetmask	_fpsetmask
#define fpsetround	_fpsetround
#define fpsetsticky	_fpsetsticky
#define fputwc		_fputwc
#define fputws		_fputws
#define freelvent	_freelvent
#define free_barrier	_free_barrier
#define freopen64	_freopen64
#define frexpl		_frexpl
#define fseek64		_fseek64
#define fseeko		_fseeko
#define fseeko64	_fseeko64
#define fsetpos64	_fsetpos64
#define fstat		_fstat
#define fstat64		_fstat64
#define fstatfs		_fstatfs
#define fstatvfs	_fstatvfs
#define fstatvfs64	_fstatvfs64
#define fsync		_fsync
#define ftello		_ftello
#define ftello64	_ftello64
#define ftell64		_ftell64
#define ftime		_ftime
#define ftok		_ftok
#define ftruncate	_ftruncate
#define ftruncate64	_ftruncate64
#define ftrylockfile	_ftrylockfile
#define ftw		_ftw
#define ftw64		_ftw64
#define funlockfile	_funlockfile
#define	fvalidateproj	_fvalidateproj
#define fxstat		_fxstat
#define gcvt		_gcvt
#define get_num_modules _get_num_modules
#define get_module_info _get_module_info
#define get_fpc_csr	_get_fpc_csr
#define get_fpc_eir	_get_fpc_eir
#define get_fpc_irr	_get_fpc_irr
#define getash		_getash
#define getcontext	_getcontext
#define getcwd		_getcwd
#define getdate		_getdate
#define getdents	_getdents
#define getdents64	_getdents64
#define getdfltprojuser _getdfltprojuser
#define getdomainname	_getdomainname
#define getdtablesize	_getdtablesize
#define getdtablehi	_getdtablehi
#define getegid		_getegid
#define geteuid		_geteuid
#define getexportent	_getexportent
#define getexportopt	_getexportopt
#define getgid		_getgid
#define getgrent	_getgrent
#define getgrent_r	_getgrent_r
#define getgrgid	_getgrgid
#define getgrgid_r	_getgrgid_r
#define getgrmember	_getgrmember
#define getgrnam	_getgrnam
#define getgrnam_r	_getgrnam_r
#define getgroups	_getgroups
#define gethostid	_gethostid
#define gethostent	_gethostent
#define gethostent_r	_gethostent_r
#define gethostname	_gethostname
#define gethz		_gethz
#define getabi		_getabi
#define getinvent	_getinvent
#define getinvent_r	_getinvent_r
#define getitimer	_getitimer
#define getlogin	_getlogin
#define getlogin_r	_getlogin_r
#define getlvent	_getlvent
#define getmntany	_getmntany
#define getmntent	_getmntent
#define getmountid	_getmountid
#define getmsg		_getmsg
#define getnetgrent	_getnetgrent
#define getopt		_getopt
#define getoptreset	_getoptreset
#define getpagesize	_getpagesize
#define getpass		_getpass
#define getpeername	_getpeername
#define getpgid		_getpgid
#define getpgrp		_getpgrp
#define getpid		_getpid
#define getpmsg		_getpmsg
#define getppid		_getppid
#define getprid		_getprid
#define getpriority	_getpriority
#define getprojall	_getprojall
#define getprojuser	_getprojuser
#define getpw		_getpw
#define getpwnam_r	_getpwnam_r
#define getpwuid_r	_getpwuid_r
#define getrlimit	_getrlimit
#define getrlimit64	_getrlimit64
#define getrpcbyname	_getrpcbyname
#define getrpcbyname_r	_getrpcbyname_r
#define getrpcbynumber	_getrpcbynumber
#define getrpcbynumber_r	_getrpcbynumber_r
#define getrpcent	_getrpcent
#define getrpcent_r	_getrpcent_r
#define getrusage	_getrusage
#define getsid		_getsid
#define getsockname	_getsockname
#define getsockopt	_getsockopt
#define getspinfo	_getspinfo
#define getsubopt	_getsubopt
#define gettimeofday	_gettimeofday
#define gettxt		_gettxt
#define getucontext	_getucontext
#define getuid		_getuid
#define getutent	_getutent
#define getutid		_getutid
#define getutline	_getutline
#define getutmp		_getutmp
#define getutmpx	_getutmpx
#define getutxent	_getutxent
#define getutxid	_getutxid
#define getutxline	_getutxline
#define getvfsany	_getvfsany
#define getvfsent	_getvfsent
#define getvfsfile	_getvfsfile
#define getvfsspec	_getvfsspec
#define getw		_getw
#define getwd		_getwd
#define getwidth	_getwidth
#define getws		_getws
#define glob		_glob
#define globfree	_globfree
#define gmtime_r	_gmtime_r
#define goserror	_goserror
#define grantpt		_grantpt
#define gsignal		_gsignal
#define gtty		_gtty
#define hasmntopt	_hasmntopt
#define hcreate		_hcreate
#define hdestroy	_hdestroy
#define hsearch		_hsearch
#define ia_closeinfo    _ia_closeinfo
#define ia_get_dir	_ia_get_dir
#define ia_get_gid	_ia_get_gid
#define ia_get_logchg   _ia_get_logchg
#define ia_get_logexpire _ia_get_logexpire
#define ia_get_logflag  _ia_get_logflag
#define ia_get_loginact _ia_get_loginact
#define ia_get_logmax   _ia_get_logmax
#define ia_get_logmin   _ia_get_logmin
#define ia_get_logpwd   _ia_get_logpwd
#define ia_get_logwarn  _ia_get_logwarn
#define ia_get_lvl	_ia_get_lvl
#define ia_get_mask     _ia_get_mask
#define ia_get_sgid     _ia_get_sgid
#define ia_get_sh	_ia_get_sh
#define ia_get_uid	_ia_get_uid
#define ia_openinfo     _ia_openinfo
#define iconv     	_iconv
#define iconv_open     	_iconv_open
#define iconv_close    	_iconv_close
#define __iconv_gettable ___iconv_gettable
#define iconv_test	_iconv_test
#define id2str		_id2str
#define ilogb		_ilogb
#define index		_index
#define initauxgroup    _initauxgroup
#define init_barrier	_init_barrier
#define initgroups	_initgroups
#define init_lock	_init_lock
#define innetgr		_innetgr
#define insque		_insque
#define ioctl		_ioctl
#define isastream	_isastream
#define isatty		_isatty
#define is_mips2	_is_mips2
#define isenglish	_isenglish
#define isideogram	_isideogram
#define isnan		_isnan
#define isnand		_isnand
#define isnanf		_isnanf
#define isnumber	_isnumber
#define isphonogram	_isphonogram
#define isspecial	_isspecial
#define issubdir	_issubdir
#define iswalnum	_iswalnum
#define iswalpha	_iswalpha
#define iswascii	_iswascii
#define iswcntrl	_iswcntrl
#define iswctype	_iswctype
#define iswdigit	_iswdigit
#define iswgraph	_iswgraph
#define iswupper	_iswupper
#define iswlower	_iswlower
#define iswpunct	_iswpunct
#define iswprint	_iswprint
#define iswspace	_iswspace
#define iswxdigit	_iswxdigit
#define jrand48		_jrand48
#define kill		_kill
#define ksigaction	_ksigaction
#define ksigqueue	_ksigqueue
#define l3tol		_l3tol
#define l64a		_l64a
#define ladd		_ladd
#define lchown		_lchown
#define lchproj		_lchproj
#define lckpwdf		_lckpwdf
#define lcong48		_lcong48
#define ldexpl		_ldexpl
#define ldivide		_ldivide
#define lexp10		_lexp10
#define lfind		_lfind
#define lfmt		_lfmt
#define link		_link
#define linkfollow	_linkfollow
#define libc_threadinit	_libc_threadinit
#define lio_listio	_lio_listio
#define lio_listio64	_lio_listio64
#define listen		_listen
#define llabs		_llabs
#define lldiv		_lldiv
#define llog10		_llog10
#define lmul		_lmul
#define lockf		_lockf
#define lockf64		_lockf64
#define logb		_logb
#define logbl		_logbl
#define localtime_r	_localtime_r
#define longjmp		_longjmp
#define lrand48		_lrand48
#define lsearch		_lsearch
#define lseek		_lseek
#define lseek64		_lseek64
#define lshiftl		_lshiftl
#define lsign		_lsign
#define lstat		_lstat
#define lstat64		_lstat64
#define lsub		_lsub
#define ltol3		_ltol3
#define lvldom		_lvldom
#define lvlequal	_lvlequal
#define lvlfile		_lvlfile
#define lvlin		_lvlin
#define lvlintersect	_lvlintersect
#define lvlipc		_lvlipc
#define lvlout		_lvlout
#define lvlproc		_lvlproc
#define lvlunion	_lvlunion
#define lvlvalid	_lvlvalid
#define lvlvfs		_lvlvfs
#define lxstat		_lxstat
#define m_fork		_m_fork
#define m_get_myid	_m_get_myid
#define m_get_numprocs	_m_get_numprocs
#define m_kill_procs	_m_kill_procs
#define m_lock		_m_lock
#define m_next		_m_next
#define m_park_procs	_m_park_procs
#define m_rele_procs	_m_rele_procs
#define m_set_procs	_m_set_procs
#define m_sync		_m_sync
#define m_unlock	_m_unlock
#define madvise		_madvise
#define makecontext	_makecontext
#define makeut		_makeut
#define makeutx		_makeutx
#define mdbm_close	_mdbm_close
#define mdbm_close_fd	_mdbm_close_fd
#define mdbm_delete	_mdbm_delete
#define mdbm_fetch	_mdbm_fetch
#define mdbm_first	_mdbm_first
#define mdbm_firstkey	_mdbm_firstkey
#define mdbm_invalidate _mdbm_invalidate
#define mdbm_next	_mdbm_next
#define mdbm_nextkey	_mdbm_nextkey
#define mdbm_open	_mdbm_open
#define mdbm_sethash	_mdbm_sethash
#define mdbm_store	_mdbm_store
#define mdbm_sync	_mdbm_sync
#define memccpy		_memccpy
#define memcntl		_memcntl
#define mincore		_mincore
#define mkdir		_mkdir
#define mkfifo		_mkfifo
#define mkmld		_mkmld
#define mknod		_mknod
#define mkstemp		_mkstemp
#define mktemp		_mktemp
#define mldmode		_mldmode
#define mld_create	_mld_create
#define mld_create_special	_mld_create_special
#define mld_destroy	_mld_destroy
#define mldset_create	_mldset_create
#define mldset_create_special	_mldset_create_special
#define mldset_place	_mldset_place
#define mldset_destroy	_mldset_destroy
#define pm_create	_pm_create
#define pm_create_special	_pm_create_special
#define pm_create_simple	_pm_create_simple
#define pm_filldefault	_pm_filldefault
#define pm_destroy	_pm_destroy
#define pm_attach	_pm_attach
#define pm_getdefault	_pm_getdefault
#define pm_setdefault	_pm_setdefault
#define pm_getall	_pm_getall
#define pm_getstat	_pm_getstat
#define pm_setpagesize	_pm_setpagesize
#define process_mldlink	_process_mldlink
#define process_cpulink _process_cpulink
#define migr_range_migrate	_migr_range_migrate
#define migr_policy_args_init	_migr_policy_args_init
#define numa_acreate	_numa_acreate
#define mlock		_mlock
#define mlockall	_mlockall
#define mmap		_mmap
#define mmap64		_mmap64
#define modf		_modf
#define modff		_modff
#define modut		_modut
#define modutx		_modutx
#define monitor		_monitor
#define mount		_mount
#define mpconf		_mpconf
#define mpin		_mpin
#define mprotect	_mprotect
#define mrand48		_mrand48
#define msgctl		_msgctl
#define msgget		_msgget
#define msgrcv		_msgrcv
#define msgsnd		_msgsnd
#define msync		_msync
#define munlock		_munlock
#define munlockall	_munlockall
#define munmap		_munmap
#define munpin		_munpin
#define mq_open		_mq_open
#define mq_close	_mq_close
#define mq_unlink	_mq_unlink
#define mq_send		_mq_send
#define mq_receive	_mq_receive
#define mq_notify	_mq_notify
#define mq_setattr	_mq_setattr
#define mq_getattr	_mq_getattr
#define nanosleep	_nanosleep
#define new_barrier	_new_barrier
#define newarraysess	_newarraysess
#define nextafter	_nextafter
#define nextafterl	_nextafterl
#define nfs_getfh	_nfs_getfh
#define nfssvc		_nfssvc
#define nftw		_nftw
#define nftw64		_nftw64
#define ngetdents	_ngetdents
#define ngetdents64	_ngetdents64
#define nice		_nice
#define nl_langinfo	_nl_langinfo
#define nrand48		_nrand48
#define ns_list		_ns_list
#define ns_lookup	_ns_lookup
#define nuname		_nuname
#define old_aio_cancel  _old_aio_cancel
#define old_aio_error   _old_aio_error
#define old_aio_fsync   _old_aio_fsync
#define old_aio_read    _old_aio_read
#define old_aio_return  _old_aio_return
#define old_aio_suspend _old_aio_suspend
#define old_aio_write   _old_aio_write
#define old_lio_listio  _old_lio_listio
#define open		_open
#define open64		_open64
#define opendir		_opendir
#define openlog		_openlog
#define openproj	_openproj
#define oserror		_oserror
#define pagelock	_pagelock
#define pathconf	_pathconf
#define pause		_pause
#define pclose		_pclose
#define pcreatel	_pcreatel
#define pcreatelp	_pcreatelp
#define pcreatev	_pcreatev
#define pcreateve	_pcreateve
#define pcreatevp	_pcreatevp
#define pfmt		_pfmt
#define pipe		_pipe
#define plock		_plock
#define poll		_poll
#define popen		_popen
#define prctl		_prctl
#define pread		_pread
#define pread64		_pread
#define procblk		_procblk
#define procpriv	_procpriv
#define procprivl	_procprivl
#define profil		_profil
#define projid		_projid
#define projname	_projname
#define psiginfo	_psiginfo
#define psignal		_psignal
#define ptrace		_ptrace
#define ptsname		_ptsname
#define putenv		_putenv
#define putmsg		_putmsg
#define putpmsg		_putpmsg
#define pututline	_pututline
#define pututxline	_pututxline
#define putw		_putw
#define putws		_putws
#define pwrite		_pwrite
#define pwrite64	_pwrite
#define qecvt		_qecvt
#define qecvt_r		_qecvt_r
#define qfcvt		_qfcvt
#define qfcvt_r		_qfcvt_r
#define qgcvt		_qgcvt
#define quotactl	_quotactl
#define raise		_raise
#define read		_read
#define readdir		_readdir
#define readdir64	_readdir64
#define readdir_r	_readdir_r
#define readdir64_r	_readdir64_r
#define readlink	_readlink
#define readv		_readv
#define realpath	_realpath
#define recv		_recv
#define recvfrom	_recvfrom
#define recvmsg		_recvmsg
#define regcomp		_regcomp
#define regerror	_regerror
#define regexec		_regexec
#define regfree		_regfree
#define registerhost	_registerhost
#define registerinethost _registerinethost
#define release_lock	_release_lock
#define remexportent	_remexportent
#define remque		_remque
#define rename		_rename
#define renamehost	_renamehost
#define rexecl		_rexecl
#define rexecle		_rexecle
#define rexeclp		_rexeclp
#define rexecv		_rexecv
#define rexecve		_rexecve
#define rexecvp		_rexecvp
#define rfsys		_rfsys
#define rindex		_rindex
#define rmdir		_rmdir
#define sbrk		_sbrk
#define scalb		_scalb
#define scalbl		_scalbl
#define scandir		_scandir
#define scandir64	_scandir64
#define scaninvent	_scaninvent
#define	sched_get_priority_max	_sched_get_priority_max
#define	sched_get_priority_min	_sched_get_priority_min
#define	sched_getparam	_sched_getparam
#define	sched_getscheduler	_sched_getscheduler
#define	sched_rr_get_interval	_sched_rr_get_interval
#define	sched_setparam	_sched_setparam
#define	sched_setscheduler	_sched_setscheduler
#define	sched_yield	_sched_yield
#define schedctl	_schedctl
#define secsys		_secsys
#define seed48		_seed48
#define seekdir		_seekdir
#define seekdir64	_seekdir64
#define select		_select
#define sem_close	_sem_close
#define sem_destroy	_sem_destroy
#define sem_getvalue	_sem_getvalue
#define sem_init	_sem_init
#define sem_mode	_sem_mode
#define sem_open	_sem_open
#define sem_post	_sem_post
#define sem_print	_sem_print
#define sem_unlink	_sem_unlink
#define sem_wait	_sem_wait
#define sem_trywait	_sem_trywait
#define semctl		_semctl
#define semget		_semget
#define semop		_semop
#define send		_send
#define sendmsg		_sendmsg
#define sendto		_sendto
#define set_fpc_csr	_set_fpc_csr
#define set_fpc_led	_set_fpc_led
#define setash		_setash
#define setblockproccnt		_setblockproccnt
#define setblockproccntall	_setblockproccntall
#define setcat		_setcat
#define setchrclass	_setchrclass
#define setcontext	_setcontext
#define setdomainname	_setdomainname
#define setegid		_setegid
#define seteuid		_seteuid
#define setexportent	_setexportent
#define setgid		_setgid
#define setgrent	_setgrent
#define setgroups	_setgroups
#define sethostid	_sethostid
#define sethostfile	_sethostfile
#define sethostname	_sethostname
#define setinvent	_setinvent
#define setinvent_r	_setinvent_r
#define setitimer	_setitimer
#define setjmp		_setjmp
#define setkey		_setkey
#define setlabel	_setlabel
#define setlogmask	_setlogmask
#define setmntent	_setmntent
#define setnetgrent	_setnetgrent
#define setoserror	_setoserror
#define setpgid		_setpgid
#define setpgrp		_setpgrp
#define setprid		_setprid
#define setprident	_setprident
#define setpriority	_setpriority
#define setprojent	_setprojent
#define setreuid	_setreuid
#define setregid	_setregid
#define setrgid		_setrgid
#define setrlimit	_setrlimit
#define setrlimit64	_setrlimit64
#define setrpcent	_setrpcent
#define setruid		_setruid
#define setsid		_setsid
#define setsockopt	_setsockopt
#define setspinfo	_setspinfo
#define settimeofday	_settimeofday
#define setucontext	_setucontext
#define setuid		_setuid
#define setutent	_setutent
#define setutxent	_setutxent
#define sgigsc		_sgigsc
#define shmat		_shmat
#define shmctl		_shmctl
#define shmdt		_shmdt
#define shmget		_shmget
#define shm_open	_shm_open
#define shm_unlink	_shm_unlink
#define shutdownx	_shutdown
#define sgi_altersigs	_sgi_altersigs
#define sgi_sigffset	_sgi_sigffset
#define sgi_dumpset	_sgi_dumpset
#define sgidladd	_sgidladd
#define sgidlopen_version	_sgidlopen_version
#define sgigetdsoversion	_sgigetdsoversion
#define sgikopt		_sgikopt
#define sginap		_sginap
#define sig2str		_sig2str
#define sigaction	_sigaction
#define sigaddset	_sigaddset
#define sigaltstack	_sigaltstack
#define sigdelset	_sigdelset
#define sigemptyset	_sigemptyset
#define sigfillset	_sigfillset
#define sigflag		_sigflag
#define sighold		_sighold
#define sigignore	_sigignore
#define siginterrupt	_siginterrupt
#define sigismember	_sigismember
#define siglongjmp	_siglongjmp
#define sigpause	_sigpause
#define sigpending	_sigpending
#define sigpoll		_sigpoll
#define sigprocmask	_sigprocmask
#define sigqueue	_sigqueue
#define sigrelse	_sigrelse
#define sigsend		_sigsend
#define sigsendset	_sigsendset
#define sigset		_sigset
#define sigsetjmp	_sigsetjmp
#define sigstatus	_sigstatus
#define sigsuspend	_sigsuspend
#define sigtimedwait	_sigtimedwait
#define sigwait		_sigwait
#define sigwaitinfo	_sigwaitinfo
#define sigwaitrt	_sigwaitrt
#define sleep		_sleep
#define snprintf	_snprintf
#define socket		_socket
#define socketpair	_socketpair
#define posix_spin_lock _posix_spin_lock
#define spin_lock	_spin_lock
#define spin_lockc	_spin_lockc
#define spin_lockw	_spin_lockw
#define spin_init	_spin_init
#define spin_destroy	_spin_destroy
#define spin_test	_spin_test
#define spin_trylock	_spin_trylock
#define spin_unlock	_spin_unlock
#define spin_print	_spin_print
#define spin_mode	_spin_mode
#define sprofil		_sprofil
#define srand48		_srand48
#define ssdi_get_config_and_load 	_ssdi_get_config_and_load
#define ssignal		_ssignal
#define stat		_stat
#define stat64		_stat64
#define stat_lock	_stat_lock
#define statfs		_statfs
#define statvfs		_statvfs
#define statvfs64	_statvfs64
#define stime		_stime
#define str2id		_str2id
#define str2sig		_str2sig
#define strcasecmp	_strcasecmp
#define strdup		_strdup
#define strfmon		_strfmon
#define strncasecmp	_strncasecmp
#define strptime	_strptime
#define strtoargv	_strtoargv
#define strtok_r	_strtok_r
#define strtold		_strtold
#define strtoll		_strtoll
#define strtoull	_strtoull
#define stty		_stty
#define swab		_swab
#define swapcontext	_swapcontext
#define swapctl		_swapctl
#define symlink		_symlink
#define sync		_sync
#define synchutmp	_synchutmp
#define system		_system
#define sys3b		_sys3b
#ifndef _LANGUAGE_ASSEMBLY
#define syscall		_syscall
#endif
#define sysconf		_sysconf
#define sysfs		_sysfs
#define sysget		_sysget
#define sysmips		_sysmips
#define syssgi		_syssgi
#define sysi86		_sysi86
#define sysid   	_sysid
#define sysinfo		_sysinfo
#define syslog		_syslog
#define sysmp		_sysmp
#define syssgi		_syssgi
#define taskblock	_taskblock
#define taskcreate	_taskcreate
#define taskctl		_taskctl
#define taskdestroy	_taskdestroy
#define tasksetblockcnt	_tasksetblockcnt
#define taskunblock	_taskunblock
#define tcdrain		_tcdrain
#define tcflow		_tcflow
#define tcflush		_tcflush
#define tcgetattr	_tcgetattr
#define __new_tcgetattr	___new_tcgetattr
#define tcgetpgrp	_tcgetpgrp
#define tcgetsid	_tcgetsid
#define tcsendbreak	_tcsendbreak
#define tcsetattr	_tcsetattr
#define __new_tcsetattr	___new_tcsetattr
#define tcsetpgrp	_tcsetpgrp
#define tdelete		_tdelete
#define tell		_tell
#define tell64		_tell64
#define telldir		_telldir
#define telldir64	_telldir64
#define tempnam		_tempnam
#define tfind		_tfind
#define times		_times
#define timer_create	_timer_create
#define timer_delete	_timer_delete
#define timer_getoverrun _timer_getoverrun
#define timer_gettime	_timer_gettime
#define timer_settime	_timer_settime
#define tmpfile64	_tmpfile64
#define towupper	_towupper
#define towlower	_towlower
#define truncate	_truncate
#define truncate64	_truncate64
#define tsearch		_tsearch
#define ttyname		_ttyname
#define ttyname_r	_ttyname_r
#define ttyslot		_ttyslot
#define twalk		_twalk
#define tzname		_tzname
#define tzset		_tzset
#define uadmin		_uadmin
#define ulckpwdf	_ulckpwdf
#define ulimit		_ulimit
#define umask		_umask
#define umount		_umount
#define uname		_uname
#define unblockproc	_unblockproc
#define unblockprocall	_unblockprocall
#define undial		_undial
#define ungetwc		_ungetwc
#define unlink		_unlink
#define unlockpt	_unlockpt
#define unordered	_unordered
#define unregisterhost	_unregisterhost
#define updutfile	_updutfile
#define updutmp		_updutmp
#define updutmpx	_updutmpx
#define updutxfile	_updutxfile
#define updwtmp		_updwtmp
#define updwtmpx	_updwtmpx
#define usadd		_usadd
#define uscalloc	_uscalloc
#define uscasinfo	_uscasinfo
#define usclosepollsema	_usclosepollsema
#define usconfig	_usconfig
#define uscpsema	_uscpsema
#define usctlsema	_usctlsema
#define usdetach	__usdetach
#define usdumphist	_usdumphist
#define usdumpsema	_usdumpsema
#define usfree		_usfree
#define usfreepollsema	_usfreepollsema
#define usfreesema	_usfreesema
#define usgetinfo	_usgetinfo
#define usinit		_usinit
#define usinitsema	_usinitsema
#define usmallinfo	_usmallinfo
#define usmalloc	_usmalloc
#define usmallocblksize	_usmallocblksize
#define usmallopt	_usmallopt
#define usmemalign	_usmemalign
#define usnewpollsema	_usnewpollsema
#define usnewsema	_usnewsema
#define usopenpollsema	_usopenpollsema
#define uspsema		_uspsema
#define usputinfo	_usputinfo
#define usrealloc	_usrealloc
#define usrecalloc	_usrecalloc
#define ustat		_ustat
#define ustestsema	_ustestsema
#define usvsema		_usvsema
#define utime		_utime
#define utimes		_utimes
#define utmpname	_utmpname
#define utmpxname	_utmpxname
#define utssys		_utssys
#define uuid_create	_uuid_create
#define uuid_create_nil	_uuid_create_nil
#define uuid_is_nil	_uuid_is_nil
#define uuid_equal	_uuid_equal
#define uuid_compare	_uuid_compare
#define uuid_to_string	_uuid_to_string
#define uuid_from_string	_uuid_from_string
#define uuid_hash	_uuid_hash
#define uuid_hash64	_uuid_hash64
#define validateproj	_validateproj
#define valloc		_valloc
#define vfork		_vfork
#define vfprintf	_vfprintf
#define vlfmt		_vlfmt
#define vpfmt		_vpfmt
#define vprintf		_vprintf
#define vsnprintf	_vsnprintf
#define vsprintf	_vsprintf
#define vsyslog		_vsyslog
#define wait		_wait
#define wait3		_wait3
#define waitid		_waitid
#define waitpid		_waitpid
#define waitsys		_waitsys
#define wcscoll		_wcscoll
#define wcsftime	_wcsftime
#define wcsstr		_wcsstr
#define wcstod		_wcstod
#define wcstof		_wcstof
#define wcstok		_wcstok
#define wcstok_r	_wcstok_r
#define wcstol		_wcstol
#define wcstold		_wcstold
#define wcstoll		_wcstoll
#define wcstombs	_wcstombs
#define wcstoul		_wcstoul
#define wcstoull	_wcstoull
#define wcswidth	_wcswidth
#define wcsxfrm		_wcsxfrm
#define wctob		_wctob
#define wctype		_wctype
#define wcwidth		_wcwidth
#define wordexp		_wordexp
#define wordfree	_wordfree
#define write		_write
#define writev		_writev
#define wscat		_wscat
#define wschr		_wschr
#define wscmp		_wscmp
#define wscpy		_wscpy
#define wscspn		_wscspn
#define wslen		_wslen
#define wsncat		_wsncat
#define wsncmp		_wsncmp
#define wsncpy		_wsncpy
#define wspbrk		_wspbrk
#define wsrchr		_wsrchr
#define wsspn		_wsspn
#define wstostr		_wstostr
#define xstat		_xstat
#define _daemonize	__daemonize
#define _yp_getpwent	__yp_getpwent
#define _yp_setpwent	__yp_setpwent

/* BSD compatibility: _BSD_COMPAT */
#define BSDalphasort	_BSDalphasort
#define BSDchown	_BSDchown
#define BSDclosedir	_BSDclosedir
#define BSDdup2		_BSDdup2
#define BSDfchown	_BSDfchown
#define BSDfopen  	_BSDfopen
#define BSDfprintf	_BSDfprintf
#define BSDfreopen	_BSDfreopen
#define BSDgetgroups	_BSDgetgroups
#define BSDgetpgrp	_BSDgetpgrp
#define BSDgettimeofday	_BSDgettimeofday
#define BSDinitgroups	_BSDinitgroups
#define BSDlongjmp	_BSDlongjmp
#define BSDopendir	_BSDopendir
#define BSDprintf	_BSDprintf
#define BSDreaddir	_BSDreaddir
#define BSDscandir	_BSDscandir
#define BSDseekdir	_BSDseekdir
#define BSDsetgroups	_BSDsetgroups
#define BSDsetjmp	_BSDsetjmp
#define BSDsetpgrp	_BSDsetpgrp
#define BSDsettimeofday	_BSDsettimeofday
#define BSDsignal	_BSDsignal
#define bsd_signal	_bsd_signal
#define BSDsigpause	_BSDsigpause
#define BSDsprintf	_BSDsprintf
#define BSDtelldir	_BSDtelldir
#define BSDvfprintf	_BSDvfprintf
#define BSDvprintf	_BSDvprintf
#define BSDvsprintf	_BSDvsprintf
#define dbm_close   	_dbm_close
#define dbm_close64   	_dbm_close64
#define dbm_delete_compat _dbm_delete_compat
#define dbm_fetch_compat _dbm_fetch_compat
#define dbm_firstkey_compat _dbm_firstkey_compat
#define dbm_forder_compat _dbm_forder_compat
#define dbm_nextkey_compat _dbm_nextkey_compat
#define dbm_open    	_dbm_open
#define dbm_open64    	_dbm_open64
#define dbm_store_compat _dbm_store_compat
#define dbmclose	_dbmclose
#define dbmclose64	_dbmclose64
#define dbminit 	_dbminit
#define dbminit64 	_dbminit64
#define delete_compat  	_delete_compat
#define dn_comp  	_dn_comp
#define dn_expand	_dn_expand
#define dn_skipname	__dn_skipname
#define endhostent	_endhostent
#define endnetent	_endnetent
#define endprotoent	_endprotoent
#define endservent	_endservent
#define fetch_compat   	_fetch_compat
#define firstkey_compat	_firstkey_compat
#define flock		_flock
#define forder_compat	_forder_compat
#define fp_query	__fp_query
#define gethostbyaddr	_gethostbyaddr
#define gethostbyaddr_r	_gethostbyaddr_r
#define gethostbyname	_gethostbyname
#define gethostbyname_r	_gethostbyname_r
#define gethostresorder	_gethostresorder
#define getnetbyaddr	_getnetbyaddr
#define getnetbyaddr_r	_getnetbyaddr_r
#define getnetbyname	_getnetbyname
#define getnetbyname_r	_getnetbyname_r
#define getnetent	_getnetent
#define getnetent_r	_getnetent_r
#define getprotobyname	_getprotobyname
#define getprotobyname_r	_getprotobyname_r
#define getprotobynumber	_getprotobynumber
#define getprotobynumber_r	_getprotobynumber_r
#define getprotoent	_getprotoent
#define getprotoent_r	_getprotoent_r
#define getservbyname	_getservbyname
#define getservbyname_r	_getservbyname_r
#define getservbyport	_getservbyport
#define getservbyport_r	_getservbyport_r
#define getservent	_getservent
#define getservent_r	_getservent_r
#define h_errlist   	_h_errlist
#define h_nerr   	_h_nerr
#define herror   	_herror
#define hostalias   	__hostalias
#define hstrerror	_hstrerror
#define inet_addr	_inet_addr
#define inet_aton	_inet_aton
#define inet_isaddr	_inet_isaddr
#define inet_lnaof	_inet_lnaof
#define inet_makeaddr	_inet_makeaddr
#define inet_netof	_inet_netof
#define inet_network	_inet_network
#define inet_ntoa	_inet_ntoa
#define inet_ntop	_inet_ntop
#define inet_pton	_inet_pton
#define inet_nsap_addr	_inet_nsap_addr
#define inet_nsap_ntoa	_inet_nsap_ntoa
#define initstate	_initstate
#define insque		_insque
#define killpg		_killpg
#define link_addr	_link_addr
#define link_ntoa	_link_ntoa
#define nextkey_compat 	_nextkey_compat
#define	p_cdname	__p_cdname
#define	p_class 	__p_class
#define	p_query 	__p_query
#define	p_rr    	__p_rr
#define	p_time  	__p_time
#define	p_type  	__p_type
#define	putlong  	__putlong
#define	putshort  	__putshort
#define rand_r   	_rand_r
#define random   	_random
#define rcmd     	_rcmd
#define re_comp		_re_comp
#define re_exec		_re_exec
#define reboot		_reboot
#define remque		_remque
#define res_init	_res_init
#define res_isourserver	__res_isourserver
#define res_mkquery	_res_mkquery
#define res_nameinquery __res_nameinquery
#define res_query 	_res_query
#define res_querydomain	_res_querydomain
#define res_queriesmatch	__res_queriesmatch
#define res_randomid	__res_randomid
#define res_search	_res_search
#define res_send	_res_send
#define res_send_setqhook	__res_send_setqhook
#define res_send_setrhook	__res_send_setrhook
#define res_hnok	__res_hnok
#define res_ownok	__res_ownok
#define res_mailok	__res_mailok
#define res_dnok	__res_dnok
#define loc_ntoa	__loc_ntoa
#define loc_aton	__loc_aton
#define rexec		_rexec
#define rresvport	_rresvport
#define ruserok  	_ruserok
#define ruserpass	_ruserpass
#define setbuffer 	_setbuffer
#define sethostent	_sethostent
#define sethostresorder	_sethostresorder
#define setlinebuf	_setlinebuf
#define setnetent	_setnetent
#define setprotoent	_setprotoent
#define setservent	_setservent
#define setstate 	_setstate
#define sigblock	_sigblock
#define sigsetmask	_sigsetmask
#define sigstack	_sigstack
#define sigvec		_sigvec
#define srandom  	_srandom
#define store_compat   	_store_compat
#define sysctl   	_sysctl
#define ualarm		_ualarm
#define usleep		_usleep
#define vhangup		_vhangup

/* rpc related functions */
#define authnone_create		_authnone_create
#define authnone_lock		_authnone_lock
#define authunix_create		_authunix_create
#define authunix_create_default	_authunix_create_default
#define callrpc			_callrpc
#define callrpc_lock		_callrpc_lock
#define clear_pollfd		_clear_pollfd
#define clnt_broadcast		_clnt_broadcast
#define clnt_broadcast_exp	_clnt_broadcast_exp
#define clnt_create		_clnt_create
#define clnt_create_vers	_clnt_create_vers
#define clnt_fd_lock		_clnt_fd_lock
#define clnt_multicast		_clnt_multicast
#define clnt_multicast_exp	_clnt_multicast_exp
#define	clnt_broadmulti		_clnt_broadmulti
#define	clnt_broadmulti_exp	_clnt_broadmulti_exp
#define clnt_pcreateerror	_clnt_pcreateerror
#define clnt_perrno		_clnt_perrno
#define clnt_perror		_clnt_perror
#define clnt_setbroadcastbackoff	_clnt_setbroadcastbackoff
#define clnt_spcreateerror	_clnt_spcreateerror
#define clnt_sperrno		_clnt_sperrno
#define clnt_sperror		_clnt_sperror
#define clnt_syslog		_clnt_syslog
#define dupreq_lock		_dupreq_lock
#define clntraw_create		_clntraw_create
#define clnttcp_create		_clnttcp_create
#define clnttcp_getreply	_clnttcp_getreply
#define clntudp_bufcreate	_clntudp_bufcreate
#define clntudp_create		_clntudp_create
#define get_myaddress		_get_myaddress
#define getnetname  		_getnetname
#define host2netname		_host2netname
#define lock_value		_lock_value
#define mt_debug		_mt_debug
#define netname2host		_netname2host
#define netname2user		_netname2user
#define pmap_getmaps		_pmap_getmaps
#define pmap_getport		_pmap_getport
#define pmap_rmtcall		_pmap_rmtcall
#define pmap_set		_pmap_set
#define pmap_setrmtcalltimeout	_pmap_setrmtcalltimeout
#define pmap_settimeouts	_pmap_settimeouts
#define pmap_unset		_pmap_unset
#define portnum_lock		_portnum_lock
#define registerrpc		_registerrpc
#define rpc_control		_rpc_control
#define sproc			_sproc
#define sprocsp			_sprocsp
#define nsproc			_nsproc
#define set_pollfd		_set_pollfd
#define svc_args_done		_svc_args_done
#define svc_copy		_svc_copy
#define svc_exit_mutex		_svc_exit_mutex
#define svc_fd_lock		_svc_fd_lock
#define svc_getreq		_svc_getreq
#define svc_getreqset		_svc_getreqset
#define svc_lock		_svc_lock
#define svc_max_fd		_svc_max_fd
#define svc_mt_mode		_svc_mt_mode
#define svc_mutex		_svc_mutex
#define svc_nfds		_svc_nfds
#define svc_nfds_set 		_svc_nfds_set
#define svc_pipe		_svc_pipe
#define svc_polling		_svc_polling
#define svc_register		_svc_register
#define svc_run			_svc_run
#define svc_sendreply		_svc_sendreply
#define svc_thr_fdwait		_svc_thr_fdwait
#define svc_thr_mutex		_svc_thr_mutex
#define svc_unregister		_svc_unregister
#define svc_versquiet		_svc_versquiet
#define svc_versquiet		_svc_versquiet
#define svc_xprt_alloc		_svc_xprt_alloc
#define svc_xprt_destroy	_svc_xprt_destroy
#define svc_xprt_free		_svc_xprt_free
#define svcerr_auth		_svcerr_auth
#define svcerr_decode		_svcerr_decode
#define svcerr_noproc		_svcerr_noproc
#define svcerr_noprog		_svcerr_noprog
#define svcerr_progvers		_svcerr_progvers
#define svcerr_systemerr	_svcerr_systemerr
#define svcerr_weakauth		_svcerr_weakauth
#define svcfd_create		_svcfd_create
#define svcraw_create		_svcraw_create
#define svctcp_create		_svctcp_create
#define svcudp_bufcreate	_svcudp_bufcreate
#define svcudp_create		_svcudp_create
#define svcudp_enablecache	_svcudp_enablecache
#define svcudp_xprtcopy		_svcudp_xprtcopy
#define user2netname		_user2netname
#define xdr_accepted_reply	_xdr_accepted_reply
#define xdr_array		_xdr_array
#define xdr_authunix_parms	_xdr_authunix_parms
#define xdr_bool      		_xdr_bool
#define xdr_bytes     		_xdr_bytes
#define xdr_callhdr		_xdr_callhdr
#define xdr_callmsg		_xdr_callmsg
#define xdr_char      		_xdr_char
#define xdr_des_block		_xdr_des_block
#define xdr_double		_xdr_double
#define xdr_enum      		_xdr_enum
#define xdr_float		_xdr_float
#define xdr_free      		_xdr_free
#define xdr_hyper		_xdr_longlong_t
#define xdr_int       		_xdr_int
#define xdr_int32	    	_xdr_int32
#define xdr_int64	    	_xdr_longlong_t
#define xdr_long      		_xdr_long
#define xdr_longlong		_xdr_longlong_t
#define xdr_longlong_t		_xdr_longlong_t
#define xdr_netobj    		_xdr_netobj
#define xdr_opaque    		_xdr_opaque
#define xdr_opaque_auth		_xdr_opaque_auth
#define xports			_xports
#if 0
#define xdr_quadruple		_xdr_quadruple
#endif
#define xdr_pmap		_xdr_pmap
#define xdr_pmaplist		_xdr_pmaplist
#define xdr_pointer		_xdr_pointer
#define xdr_reference		_xdr_reference
#define xdr_rejected_reply	_xdr_rejected_reply
#define xdr_replymsg		_xdr_replymsg
#define xdr_rmtcall_args	_xdr_rmtcall_args
#define xdr_rmtcallres		_xdr_rmtcallres
#define xdr_short     		_xdr_short
#define xdr_string    		_xdr_string
#define xdr_time_t    		_xdr_time_t
#define xdr_u_char    		_xdr_u_char
#define xdr_u_hyper		_xdr_u_longlong_t
#define xdr_u_int     		_xdr_u_int
#define xdr_u_long    		_xdr_u_long
#define xdr_u_longlong		_xdr_u_longlong_t
#define xdr_u_longlong_t	_xdr_u_longlong_t
#define xdr_u_short   		_xdr_u_short
#define xdr_uint32	    	_xdr_uint32
#define xdr_uint64	    	_xdr_ulonglong_t
#define xdr_union     		_xdr_union
#define xdr_vector		_xdr_vector
#define xdr_void      		_xdr_void
#define xdr_wrapstring		_xdr_wrapstring
#define xdrmem_create		_xdrmem_create
#define xdrrec_create		_xdrrec_create
#define xdrrec_endofrecord	_xdrrec_endofrecord
#define xdrrec_eof		_xdrrec_eof
#define xdrrec_readbytes	_xdrrec_readbytes
#define xdrrec_skiprecord	_xdrrec_skiprecord
#define xdrstdio_create		_xdrstdio_create
#define xprt_register		_xprt_register
#define xprt_unregister		_xprt_unregister

/* yp related functions */
#define xdr_datum			_xdr_datum
#define xdr_yp_binding			_xdr_yp_binding
#define xdr_yp_buf			_xdr_yp_buf
#define xdr_yp_inaddr			_xdr_yp_inaddr
#define xdr_ypall			_xdr_ypall
#define xdr_ypbind_resp			_xdr_ypbind_resp
#define xdr_ypbind_setdom		_xdr_ypbind_setdom
#define xdr_ypdelete_args		_xdr_ypdelete_args
#define xdr_ypdomain_wrap_string	_xdr_ypdomain_wrap_string
#define xdr_ypmap_parms			_xdr_ypmap_parms
#define xdr_ypmap_wrap_string		_xdr_ypmap_wrap_string
#define xdr_ypmaplist			_xdr_ypmaplist
#define xdr_ypmaplist_wrap_string	_xdr_ypmaplist_wrap_string
#define xdr_ypowner_wrap_string		_xdr_ypowner_wrap_string
#define xdr_yppushresp_xfr		_xdr_yppushresp_xfr
#define xdr_ypreq_key			_xdr_ypreq_key
#define xdr_ypreq_nokey			_xdr_ypreq_nokey
#define xdr_ypreq_xfr			_xdr_ypreq_xfr
#define xdr_ypresp_key_val		_xdr_ypresp_key_val
#define xdr_ypresp_maplist		_xdr_ypresp_maplist
#define xdr_ypresp_master		_xdr_ypresp_master
#define xdr_ypresp_order		_xdr_ypresp_order
#define xdr_ypresp_val			_xdr_ypresp_val
#define xdr_ypupdate_args		_xdr_ypupdate_args
#define yp_all				_yp_all
#define yp_bind				_yp_bind
#define yp_first			_yp_first
#define yp_get_default_domain		_yp_get_default_domain
#define yp_master			_yp_master
#define yp_match			_yp_match
#define yp_next				_yp_next
#define yp_order			_yp_order
#define yp_unbind			_yp_unbind
#define yp_update			_yp_update
#define yperr_string			_yperr_string
#define ypprot_err			_ypprot_err

/* Trusted IRIX functions in gen of libc */
#define sgi_revoke                      _sgi_revoke
#define satread				_satread
#define satwrite			_satwrite
#define satvwrite			_satvwrite
#define saton				_saton
#define satoff				_satoff
#define satstate			_satstate
#define satsetid			_satsetid
#define satgetid			_satgetid
#define ia_audit			_ia_audit

/* Trusted IRIX functions in mls of libc */
#define acl_from_text			_acl_from_text
#define acl_to_short_text		_acl_to_short_text
#define acl_to_text			_acl_to_text
#define acl_size			_acl_size
#define acl_copy_ext			_acl_copy_ext
#define acl_copy_int			_acl_copy_int
#define acl_free			_acl_free
#define acl_valid			_acl_valid
#define acl_delete_def_file		_acl_delete_def_file
#define acl_get_fd			_acl_get_fd
#define acl_get_file			_acl_get_file
#define acl_set_fd			_acl_set_fd
#define acl_set_file			_acl_set_file
#define acl_dup				_acl_dup
#define cap_clear			_cap_clear
#define cap_init			_cap_init
#define cap_from_text			_cap_from_text
#define cap_to_text			_cap_to_text
#define cap_value_to_text		_cap_value_to_text
#define cap_size			_cap_size
#define cap_copy_ext			_cap_copy_ext
#define cap_copy_int			_cap_copy_int
#define cap_envl			_cap_envl
#define cap_envp			_cap_envp
#define cap_free			_cap_free
#define cap_get_fd			_cap_get_fd
#define cap_get_file			_cap_get_file
#define cap_get_proc			_cap_get_proc
#define cap_set_fd			_cap_set_fd
#define cap_set_file			_cap_set_file
#define cap_set_proc			_cap_set_proc
#define cap_set_proc_flags		_cap_set_proc_flags
#define cap_get_flag			_cap_get_flag
#define cap_set_flag			_cap_set_flag
#define cap_dup				_cap_dup
#define cap_acquire			_cap_acquire
#define cap_surrender			_cap_surrender
#define	sgi_getcapabilitybyname		_sgi_getcapabilitybyname
#define mac_from_msen_mint		_mac_from_msen_mint
#define mac_from_msen			_mac_from_msen
#define mac_from_mint			_mac_from_mint
#define msen_from_text			_msen_from_text
#define msen_to_text			_msen_to_text
#define msen_from_mac			_msen_from_mac
#define msen_free			_msen_free
#define msen_valid			_msen_valid
#define msen_equal			_msen_equal
#define msen_dom			_msen_dom
#define msen_size			_msen_size
#define mint_from_text			_mint_from_text
#define mint_to_text			_mint_to_text
#define mint_from_mac			_mint_from_mac
#define mint_free			_mint_free
#define mint_valid			_mint_valid
#define mint_equal			_mint_equal
#define mint_dom			_mint_dom
#define mint_size			_mint_size
#define mac_from_text			_mac_from_text
#define mac_to_text			_mac_to_text
#define mac_to_text_long		_mac_to_text_long
#define mac_free			_mac_free
#define mac_get_fd			_mac_get_fd
#define mac_get_file			_mac_get_file
#define mac_get_proc			_mac_get_proc
#define mac_set_fd			_mac_set_fd
#define mac_set_file			_mac_set_file
#define mac_set_proc			_mac_set_proc
#define mac_valid			_mac_valid
#define mac_dominate			_mac_dominate
#define mac_equal			_mac_equal
#define	mac_cleared			_mac_cleared
#define	mac_clearedlbl			_mac_clearedlbl
#define mac_cleared_ps			_mac_cleared_ps
#define mac_cleared_pl			_mac_cleared_pl
#define mac_cleared_fs			_mac_cleared_fs
#define mac_cleared_fl			_mac_cleared_fl
#define	mac_clearance_error		_mac_clearance_error
#define	sgi_getclearancebyname		_sgi_getclearancebyname
#define	mac_dup				_mac_dup
#define	mac_size			_mac_size
#define	mac_demld			_mac_demld
#define mac_is_moldy			_mac_is_moldy
#define	mac_set_moldy			_mac_set_moldy
#define	mac_label_devs			_mac_label_devs
#define	sys_call			_sys_call
#define	sat_eventtostr			_sat_eventtostr
#define	sat_strtoevent			_sat_strtoevent
#define	sat_write_filehdr		_sat_write_filehdr
#define	sat_close_filehdr		_sat_close_filehdr
#define	sat_read_file_info		_sat_read_file_info
#define	sat_free_file_info		_sat_free_file_info
#define	sat_write_file_info		_sat_write_file_info
#define	sat_read_header_info		_sat_read_header_info
#define	sat_free_header_info		_sat_free_header_info
#define	sat_intrp_pathname		_sat_intrp_pathname
#define	sgi_eag_mount			_sgi_eag_mount

/* Trusted IRIX functions in sesmgr of libc */
#define t6alloc_blk			_t6alloc_blk
#define t6attr_alloc			_t6attr_alloc
#define t6create_attr			_t6create_attr
#define t6free_blk			_t6free_blk
#define t6free_attr			_t6free_attr
#define t6cmp_blk			_t6cmp_blk
#define t6cmp_attrs			_t6cmp_attrs
#define t6copy_blk			_t6copy_blk
#define t6copy_attr			_t6copy_attr
#define t6dup_blk			_t6dup_blk
#define t6dup_attr			_t6dup_attr
#define t6clear_blk			_t6clear_blk
#define t6get_attr			_t6get_attr
#define t6set_attr			_t6set_attr
#define t6size_attr			_t6size_attr
#define t6ext_attr			_t6ext_attr
#define t6new_attr			_t6new_attr
#define t6mls_socket			_t6mls_socket
#define t6get_endpt_mask		_t6get_endpt_mask
#define t6set_endpt_mask		_t6set_endpt_mask
#define t6get_endpt_default		_t6get_endpt_default
#define t6set_endpt_default		_t6set_endpt_default
#define t6last_attr			_t6last_attr
#define t6peek_attr			_t6peek_attr
#define t6recvfrom			_t6recvfrom
#define t6sendto			_t6sendto
#define t6rhdb_put_host			_t6rhdb_put_host
#define t6rhdb_get_host			_t6rhdb_get_host
#define t6rhdb_flush			_t6rhdb_flush
#define t6rhdb_stat			_t6rhdb_stat

/* sesmgr utility functions */
#define tsix_get_mac			_tsix_get_mac
#define tsix_get_solabel		_tsix_get_solabel
#define tsix_get_uid			_tsix_get_uid
#define tsix_off			_tsix_off
#define tsix_on				_tsix_on
#define tsix_recvfrom_mac		_tsix_recvfrom_mac
#define tsix_sendto_mac			_tsix_sendto_mac
#define tsix_set_mac			_tsix_set_mac
#define tsix_set_mac_byrhost		_tsix_set_mac_byrhost
#define tsix_set_solabel		_tsix_set_solabel
#define tsix_set_uid			_tsix_set_uid

/* names that need to be hidden in the min-ABI library */
#ifdef ABI

#define abs		_abi_abs
#define atoi		_abi_atoi
#define atol		_abi_atol
#define difftime	_abi_difftime
#undef endgrent
#define endgrent	_abi_endgrent
#undef endpwent
#define endpwent	_abi_endpwent
#undef fgetgrent
#define fgetgrent	_abi_fgetgrent
#undef fgetpwent
#define fgetpwent	_abi_fgetpwent
#undef ftruncate
#define ftruncate	_abi_ftruncate
#undef getdents
#define getdents	_abi_getdents
#undef getgrent
#define getgrent	_abi_getgrent
#undef getpwent
#define getpwent	_abi_getpwent
#define getenv		_abi_getenv
#define gmtime		_abi_gmtime
#undef isatty
#define isatty		_abi_isatty
#define labs		_abi_labs
#define localtime	_abi_localtime
#define memchr		_abi_memchr
#define memcmp		_abi_memcmp
#define memcpy		_abi_memcpy
#define memmove		_abi_memmove
#define memset		_abi_memset
#define mktime		_abi_mktime
#undef setgrent
#define setgrent	_abi_setgrent
#undef setpwent
#define setpwent	_abi_setpwent
#undef sleep
#define sleep		_abi_sleep
#define strcat		_abi_strcat
#define strchr		_abi_strchr
#define strcmp		_abi_strcmp
#define strcpy		_abi_strcpy
#define strcspn		_abi_strcspn
#define strlen		_abi_strlen
#define strncmp		_abi_strncmp
#define strncpy		_abi_strncpy
#define strtol		_abi_strtol
#undef syscall
#define syscall		_abi_syscall
#undef sysi86
#define sysi86		_abi_sysi86
#undef truncate
#define truncate	_abi_truncate
#undef ttyslot
#define ttyslot		_abi_ttyslot
#undef tzset
#define tzset		_abi_tzset

#endif /* ABI */

#ifndef _LANGUAGE_ASSEMBLY
typedef void VOID;
#endif
#define _assert		__assert
#define _ctype		__ctype
#define _filbuf		__filbuf
#define _flsbuf		__flsbuf
#define _iob		__iob

/* DSO vs NONSHARED defines */
#ifdef _LIBC_NONSHARED
#define	_INITBSS
#define _INITBSSS
#else
#define	_INITBSS	=0
#define _INITBSSS	={0}
#endif
