#include <ksys/cell/subsysid.h>

subsystem "cms" CMS_SVC_SUBSYSID MEMBERSHIP

import "cell/cms/cms_base.h"
import "cell/cms/cms_message.h"

asynchronous
send_message(
	in	pointerto cms_message_t message)

asynchronous
mesg_connect(
	in	valueof	cell_t	source_cell)

asynchronous
mesg_disconnect(
	in	valueof	cell_t	source_cell)

asynchronous
recovery_complete(
	in	valueof	cell_t	source_cell)
