#include <ksys/cell/subsysid.h>

subsystem "creds" CRED_SVC_SUBSYSID

import <sys/cred.h>

synchronous
int
get_cred(
	in	valueof		credid_t credid,
	out	pointerto	cred_t   cred,
	out	bufferof	gid_t	 groups,
	out	pointerto	int	 error)
