#include <ksys/cell/subsysid.h>

subsystem "ucopy" UCOPY_SUBSYSID


callback
int
copyin(
	in	valueof		caddr_t	src,
	out	bufferof	char	dst)

callback
int
copyout(
	in	bufferof	char	src,
	in	valueof		caddr_t	dst)

callback
int
zero(
	in	valueof		caddr_t	dst,
	in	valueof		size_t	len)

callback
int
get_flid(
	out	pointerto	flid_t	flidp)
