/**************************************************************************
 *                                                                        *
 *               Copyright (C) 1996 Silicon Graphics, Inc.                *
 *                                                                        *
 *  These coded instructions, statements, and computer programs  contain  *
 *  unpublished  proprietary  information of Silicon Graphics, Inc., and  *
 *  are protected by Federal copyright law.  They  may  not be disclosed  *
 *  to  third  parties  or copied or duplicated in any form, in whole or  *
 *  in part, without the prior written consent of Silicon Graphics, Inc.  *
 *                                                                        *
 **************************************************************************/
#ident  "$Revision: 1.5 $"

/*
 * Remote function interfaces supported by the VFS ds behavior
 */
#include "ksys/cell/subsysid.h"

subsystem	"dcvfs"		DCVFS_SUBSYSID

import <ksys/cell/tkm.h>
import <ksys/cell/service.h>
import <ksys/cell.h>

import <fs/cfs/cfs.h>

synchronous void
vfsrecall(
	in	pointerto	<cfs_handle_t>		vfs_hdlp,
	in	valueof		tk_set_t		recset,
	in	valueof		tk_disp_t		why,
        in      valueof         cell_t                  unmounter, 
	out	pointerto	int			errorp)

synchronous void
abort_unmount(
	in	pointerto	<cfs_handle_t>		rvp_hdlp,
	in	pointerto	<cfs_handle_t>		vfs_hdlp,
        in      valueof         cell_t                  unmounter)


