/**************************************************************************
 *									  *
 *		 Copyright (C) 1995-1996 Silicon Graphics, Inc.		  *
 *									  *
 *  These coded instructions, statements, and computer programs  contain  *
 *  unpublished  proprietary  information of Silicon Graphics, Inc., and  *
 *  are protected by Federal copyright law.  They  may  not be disclosed  *
 *  to  third  parties  or copied or duplicated in any form, in whole or  *
 *  in part, without the prior written consent of Silicon Graphics, Inc.  *
 *									  *
 **************************************************************************/
#ident	"$Id: dcvn.idl,v 1.7 1997/09/04 00:11:27 rcc Exp $"

/*
 * Message interfaces exported by the client-side 'dcvn' structure.
 */
#include "ksys/cell/subsysid.h"

subsystem	"dcvn"	DCVN_SUBSYSID

import <ksys/cell/tkm.h>
import <ksys/cell/service.h>
import <ksys/cell.h>

import <fs/cfs/cfs.h>

synchronous void
vnode_change(
	in	pointerto	cfs_handle_t	handlep,
	in	valueof		vchange_t	cmd,
        in	valueof		__psint_t	val,
	out	pointerto	int		error)

synchronous void
page_cache_operation(
	in	pointerto	cfs_handle_t	handlep,
	in	valueof		int		op,
	in	valueof		off_t		first,
	in	valueof		off_t		last,
        in	valueof		uint64_t	flags,
        in	valueof		int		fiopt,
	out	pointerto	int		error)

/* one-way message */
asynchronous
recall(
	in	pointerto	cfs_handle_t	handlep,
	in	valueof		tk_set_t	recset,
	in	valueof		tk_disp_t	why)



