/* Layout file created by tedit */

#ifndef TUDONTAUTOINCLUDE
#include "tuLabelMenuItem.h"
#include "tuSeparator.h"
#include "tuMenu.h"
#include "tuMenuBar.h"
#include "tuFrame.h"
#include "tuLabel.h"
#include "tuTextField.h"
#include "tuRowColumn.h"
#include "tuGap.h"
#include "tuLabelButton.h"
#endif /* TUDONTAUTOINCLUDE */

#ifdef TUREGISTERGADGETS
#undef TUREGISTERGADGETS
#endif /* TUREGISTERGADGETS */
#define TUREGISTERGADGETS { \
    tuLabelMenuItem::registerForPickling(); \
    tuSeparator::registerForPickling(); \
    tuMenu::registerForPickling(); \
    tuMenuBar::registerForPickling(); \
    tuFrame::registerForPickling(); \
    tuLabel::registerForPickling(); \
    tuTextField::registerForPickling(); \
    tuRowColumn::registerForPickling(); \
    tuGap::registerForPickling(); \
    tuLabelButton::registerForPickling(); \
}

static char* layoutstr =
"(RowColumn "
 "(rows 5) "
 "(cols 1) "
 "(growdir vertical) "
 "(defaultAlignment 0) "
 "(resources "
  "((fixedHeight True))) "
 "(child "
  "(Frame "
   "(resources "
    "((frame outie))) "
   "(child "
    "(MenuBar "
     "(rows 1) "
     "(cols 4) "
     "(defaultAlignment 0) "
     "(resources "
      "((horizontalOffset 5) "
       "(fixedHeight True))) "
     "(child "
      "(LabelMenuItem "
       "(subMenu "
        "(Menu "
         "(rows 6) "
         "(cols 1) "
         "(defaultAlignment 3) "
         "(ownParent True) "
         "(title File) "
         "(resources "
          "((topInset 4) "
           "(bottomInset 4) "
           "(leftInset 4) "
           "(rightInset 4) "
           "(horizontalOffset 2))) "
         "(child "
          "(LabelMenuItem  "
           "(resources "
            "((callback __Browser_save) "
             "(accelerator Alt\\ s) "
             "(labelString Save\\ MIB\\ Values))))) "
         "(constraint R0C0A3) "
         "(child "
          "(LabelMenuItem  "
           "(resources "
            "((callback __Browser_saveAs) "
             "(accelerator \\\"Alt-S\\\"\\ Shift\\ Alt\\ s) "
             "(labelString Save\\ MIB\\ Values\\ As...))))) "
         "(constraint R1C0A3) "
         "(child "
          "(Separator "
           "(orientation horizontal))) "
         "(constraint R2C0A3) "
         "(child "
          "(LabelMenuItem "
           "(instanceName closeKids)  "
           "(resources "
            "((callback __Browser_closeKids) "
             "(accelerator Alt\\ l) "
             "(labelString Close\\ Lower\\ Level\\ Windows))))) "
         "(constraint R3C0A3) "
         "(child "
          "(Separator "
           "(orientation horizontal))) "
         "(constraint R4C0A3) "
         "(child "
          "(LabelMenuItem  "
           "(resources "
            "((callback __Browser_quit) "
             "(accelerator Alt\\ q) "
             "(labelString Quit))))) "
         "(constraint R5C0A3))) "
       "(resources "
        "((labelString File))))) "
     "(constraint R0C0A0) "
     "(child "
      "(LabelMenuItem "
       "(instanceName navigateLabel) "
       "(subMenu "
        "(Menu "
         "(instanceName navMenu) "
         "(rows 3) "
         "(cols 1) "
         "(defaultAlignment 3) "
         "(ownParent True) "
         "(title Navigate) "
         "(resources "
          "((topInset 4) "
           "(bottomInset 4) "
           "(leftInset 4) "
           "(rightInset 4) "
           "(horizontalOffset 2))) "
         "(child "
          "(LabelMenuItem "
           "(instanceName mib-2)  "
           "(resources "
            "((callback __Browser_mibSelected) "
             "(labelString mib-2))))) "
         "(constraint R0C0A3) "
         "(child "
          "(LabelMenuItem "
           "(instanceName enterprises)  "
           "(resources "
            "((callback __Browser_mibSelected) "
             "(labelString enterprises))))) "
         "(constraint R1C0A3) "
         "(child "
          "(LabelMenuItem "
           "(instanceName experimental)  "
           "(resources "
            "((callback __Browser_mibSelected) "
             "(labelString experimental))))) "
         "(constraint R2C0A3))) "
       "(resources "
        "((labelString Navigate))))) "
     "(constraint R0C1A0) "
     "(child "
      "(LabelMenuItem "
       "(subMenu "
        "(Menu "
         "(rows 1) "
         "(cols 1) "
         "(defaultAlignment 3) "
         "(ownParent True) "
         "(title Help) "
         "(resources "
          "((topInset 4) "
           "(bottomInset 4) "
           "(leftInset 4) "
           "(rightInset 4) "
           "(horizontalOffset 2))) "
         "(child "
          "(LabelMenuItem  "
           "(resources "
            "((callback __bTop_help) "
             "(accelerator Alt\\ h) "
             "(labelString Help))))) "
         "(constraint R0C0A3))) "
       "(resources "
        "((labelString Help))))) "
     "(constraint R0C3A0))))) "
 "(constraint R0C0A0) "
 "(child "
  "(RowColumn "
   "(rows 4) "
   "(cols 2) "
   "(defaultAlignment 0) "
   "(resources "
    "((topInset 10) "
     "(leftInset 10) "
     "(rightInset 10) "
     "(horizontalOffset 10) "
     "(verticalOffset 10) "
     "(fixedHeight True))) "
   "(child "
    "(Label "
     "(resources "
      "((labelString Node:) "
       "(font -*-helvetica-bold-r-normal--14-*-*-*-p-*-iso8859-1))))) "
   "(constraint R0C0A6) "
   "(child "
    "(Frame "
     "(resources "
      "((frame innie))) "
     "(child "
      "(TextField "
       "(instanceName nodeField) "
       "(text ) "
       "(resources "
        "((terminatorCallBack __Browser_nextField) "
         "(keepAllTextVisible False))))))) "
   "(constraint R0C1A4) "
   "(child "
    "(Label "
     "(resources "
      "((labelString Community:) "
       "(font -*-helvetica-bold-r-normal--14-*-*-*-p-*-iso8859-1))))) "
   "(constraint R1C0A6) "
   "(child "
    "(Frame "
     "(resources "
      "((frame innie))) "
     "(child "
      "(TextField "
       "(instanceName communityField) "
       "(text ) "
       "(resources "
        "((terminatorCallBack __Browser_nextField) "
         "(keepAllTextVisible False))))))) "
   "(constraint R1C1A4) "
   "(child "
    "(Label "
     "(resources "
      "((labelString Timeout\\ interval:) "
       "(font -*-helvetica-bold-r-normal--14-*-*-*-p-*-iso8859-1))))) "
   "(constraint R2C0A6) "
   "(child "
    "(Frame "
     "(resources "
      "((frame innie))) "
     "(child "
      "(TextField "
       "(instanceName timeoutField) "
       "(text ) "
       "(resources "
        "((terminatorCallBack __Browser_nextField) "
         "(keepAllTextVisible False))))))) "
   "(constraint R2C1A4) "
   "(child "
    "(Label "
     "(resources "
      "((labelString Number\\ of\\ retries:) "
       "(font -*-helvetica-bold-r-normal--14-*-*-*-p-*-iso8859-1))))) "
   "(constraint R3C0A6) "
   "(child "
    "(Frame "
     "(resources "
      "((frame innie))) "
     "(child "
      "(TextField "
       "(instanceName retriesField) "
       "(text ) "
       "(resources "
        "((terminatorCallBack __Browser_nextField) "
         "(keepAllTextVisible False))))))) "
   "(constraint R3C1A4))) "
 "(constraint R1C0A0) "
 "(child "
  "(Gap "
   "(orientation horizontal) "
   "(resources "
    "((minWidth 500))))) "
 "(constraint R2C0A0) "
 "(child "
  "(Separator "
   "(orientation horizontal))) "
 "(constraint R3C0A0) "
 "(child "
  "(RowColumn "
   "(instanceName buttonsRC) "
   "(rows 1) "
   "(cols 4) "
   "(defaultAlignment 0) "
   "(resources "
    "((topInset 10) "
     "(bottomInset 10) "
     "(leftInset 10) "
     "(rightInset 10) "
     "(horizontalOffset 10) "
     "(fixedWidth True))) "
   "(child "
    "(LabelButton "
     "(instanceName mib-2) "
     "(resources "
      "((callback __Browser_mibSelected) "
       "(labelString mib-2))))) "
   "(constraint R0C0A0) "
   "(child "
    "(LabelButton "
     "(instanceName enterprises) "
     "(resources "
      "((callback __Browser_mibSelected) "
       "(labelString enterprises))))) "
   "(constraint R0C1A0) "
   "(child "
    "(LabelButton "
     "(instanceName experimental) "
     "(resources "
      "((callback __Browser_mibSelected) "
       "(labelString experimental))))) "
   "(constraint R0C2A0) "
   "(child "
    "(LabelButton "
     "(instanceName individual) "
     "(resources "
      "((callback __Browser_mibSelected) "
       "(labelString Variable...))))) "
   "(constraint R0C3A0))) "
 "(constraint R4C0A5))";
