/* Layout file created by tedit */

#ifndef TUDONTAUTOINCLUDE
#include "tuLabelMenuItem.h"
#include "tuSeparator.h"
#include "tuMenu.h"
#include "tuMenuBar.h"
#include "tuFrame.h"
#include "tuLabel.h"
#include "tuTextField.h"
#include "tuRowColumn.h"
#include "tuGap.h"
#include "tuScrollView.h"
#endif /* TUDONTAUTOINCLUDE */

#ifdef TUREGISTERGADGETS
#undef TUREGISTERGADGETS
#endif /* TUREGISTERGADGETS */
#define TUREGISTERGADGETS { \
    tuLabelMenuItem::registerForPickling(); \
    tuSeparator::registerForPickling(); \
    tuMenu::registerForPickling(); \
    tuMenuBar::registerForPickling(); \
    tuFrame::registerForPickling(); \
    tuLabel::registerForPickling(); \
    tuTextField::registerForPickling(); \
    tuRowColumn::registerForPickling(); \
    tuGap::registerForPickling(); \
    tuScrollView::registerForPickling(); \
}

static char* layoutstr =
"(RowColumn "
 "(rows 2) "
 "(cols 1) "
 "(growdir vertical) "
 "(defaultAlignment 0) "
 "(child "
  "(Frame "
   "(resources "
    "((frame outie))) "
   "(child "
    "(MenuBar "
     "(rows 1) "
     "(cols 3) "
     "(defaultAlignment 0) "
     "(resources "
      "((horizontalOffset 5) "
       "(fixedHeight True))) "
     "(child "
      "(LabelMenuItem "
       "(subMenu "
        "(Menu "
         "(rows 5) "
         "(cols 1) "
         "(defaultAlignment 3) "
         "(ownParent True) "
         "(title File) "
         "(resources "
          "((topInset 4) "
           "(bottomInset 4) "
           "(leftInset 4) "
           "(rightInset 4) "
           "(horizontalOffset 2))) "
         "(child "
          "(LabelMenuItem "
           "(instanceName save)  "
           "(resources "
            "((accelerator Alt\\ s) "
             "(labelString Save\\ Description))))) "
         "(constraint R0C0A3) "
         "(child "
          "(LabelMenuItem "
           "(instanceName saveAs)  "
           "(resources "
            "((accelerator \\\"Alt-S\\\"\\ Shift\\ Alt\\ s) "
             "(labelString Save\\ Description\\ As...))))) "
         "(constraint R1C0A3) "
         "(child "
          "(Separator "
           "(orientation horizontal))) "
         "(constraint R2C0A3) "
         "(child "
          "(LabelMenuItem "
           "(instanceName openParent)  "
           "(resources "
            "((callback __bTop_openMain) "
             "(accelerator Alt\\ m) "
             "(labelString Pop\\ Main\\ Window))))) "
         "(constraint R3C0A3) "
         "(child "
          "(LabelMenuItem "
           "(instanceName close)  "
           "(resources "
            "((callback __bTop_close) "
             "(accelerator Alt\\ c) "
             "(labelString Close))))) "
         "(constraint R4C0A3))) "
       "(resources "
        "((labelString File))))) "
     "(constraint R0C0A0) "
     "(child "
      "(LabelMenuItem "
       "(subMenu "
        "(Menu "
         "(rows 1) "
         "(cols 1) "
         "(defaultAlignment 3) "
         "(ownParent True) "
         "(title Help) "
         "(resources "
          "((topInset 4) "
           "(bottomInset 4) "
           "(leftInset 4) "
           "(rightInset 4) "
           "(horizontalOffset 2))) "
         "(child "
          "(LabelMenuItem  "
           "(resources "
            "((callback __bTop_help) "
             "(accelerator Alt\\ h) "
             "(labelString Help))))) "
         "(constraint R0C0A3))) "
       "(resources "
        "((labelString Help))))) "
     "(constraint R0C2A0))))) "
 "(constraint R0C0A0) "
 "(child "
  "(RowColumn "
   "(rows 4) "
   "(cols 1) "
   "(growdir vertical) "
   "(defaultAlignment 0) "
   "(resources "
    "((topInset 10) "
     "(bottomInset 10) "
     "(leftInset 10) "
     "(rightInset 10) "
     "(horizontalOffset 10) "
     "(verticalOffset 10) "
     "(fixedWidth True))) "
   "(child "
    "(RowColumn "
     "(rows 2) "
     "(cols 2) "
     "(growdir vertical) "
     "(defaultAlignment 0) "
     "(resources "
      "((leftInset 10) "
       "(horizontalOffset 10) "
       "(verticalOffset 5) "
       "(fixedHeight True))) "
     "(child "
      "(Label "
       "(resources "
        "((labelString Object\\ ID:) "
         "(font -*-helvetica-bold-r-normal--14-*-*-*-p-*-iso8859-1))))) "
     "(constraint R0C0A2) "
     "(child "
      "(Frame "
       "(resources "
        "((frame Innie))) "
       "(child "
        "(TextField "
         "(instanceName idField) "
         "(text ) "
         "(resources "
          "((background ReadOnlyBackground) "
           "(readOnly True) "
           "(keepAllTextVisible False))))))) "
     "(constraint R0C1A0) "
     "(child "
      "(Label "
       "(resources "
        "((labelString Name:) "
         "(font -*-helvetica-bold-r-normal--14-*-*-*-p-*-iso8859-1))))) "
     "(constraint R1C0A2) "
     "(child "
      "(Frame "
       "(resources "
        "((frame Innie))) "
       "(child "
        "(TextField "
         "(instanceName nameField) "
         "(text ) "
         "(resources "
          "((background ReadOnlyBackground) "
           "(readOnly True) "
           "(keepAllTextVisible False))))))) "
     "(constraint R1C1A0))) "
   "(constraint R0C0A0) "
   "(child "
    "(Gap "
     "(orientation horizontal) "
     "(resources "
      "((minWidth 300))))) "
   "(constraint R1C0A0) "
   "(child "
    "(RowColumn "
     "(rows 1) "
     "(cols 2) "
     "(defaultAlignment 0) "
     "(resources "
      "((leftInset 8) "
       "(horizontalOffset 5) "
       "(fixedHeight True))) "
     "(child "
      "(Label "
       "(resources "
        "((labelString Object:))))) "
     "(constraint R0C0A0) "
     "(child "
      "(Label "
       "(resources "
        "((labelString \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ Description:))))) "
     "(constraint R0C1A0))) "
   "(constraint R2C0A0) "
   "(child "
    "(Frame "
     "(resources "
      "((frame ditch))) "
     "(child "
      "(ScrollView "
       "(horizBar True) "
       "(vertBar True) "
       "(child "
        "(RowColumn "
         "(instanceName centralRC) "
         "(rows 1) "
         "(cols 1) "
         "(defaultAlignment 4) "
         "(resources "
          "((topInset 5) "
           "(bottomInset 5) "
           "(leftInset 5) "
           "(rightInset 5) "
           "(horizontalOffset 10) "
           "(verticalOffset 5))))))))) "
   "(constraint R3C0A0))) "
 "(constraint R1C0A3))";
