/* Layout file created by tedit */

#ifndef TUDONTAUTOINCLUDE
#include "tuLabelMenuItem.h"
#include "tuSeparator.h"
#include "tuMenu.h"
#include "tuMenuBar.h"
#include "tuFrame.h"
#include "tuLabel.h"
#include "tuTextField.h"
#include "tuRowColumn.h"
#include "tuGap.h"
#include "tuLabelButton.h"
#endif /* TUDONTAUTOINCLUDE */

#ifdef TUREGISTERGADGETS
#undef TUREGISTERGADGETS
#endif /* TUREGISTERGADGETS */
#define TUREGISTERGADGETS { \
    tuLabelMenuItem::registerForPickling(); \
    tuSeparator::registerForPickling(); \
    tuMenu::registerForPickling(); \
    tuMenuBar::registerForPickling(); \
    tuFrame::registerForPickling(); \
    tuLabel::registerForPickling(); \
    tuTextField::registerForPickling(); \
    tuRowColumn::registerForPickling(); \
    tuGap::registerForPickling(); \
    tuLabelButton::registerForPickling(); \
}

static char* layoutstr =
"(RowColumn "
 "(rows 5) "
 "(cols 1) "
 "(defaultAlignment 0) "
 "(resources "
  "((fixedHeight True))) "
 "(child "
  "(Frame "
   "(resources "
    "((frame outie))) "
   "(child "
    "(MenuBar "
     "(rows 1) "
     "(cols 4) "
     "(defaultAlignment 0) "
     "(resources "
      "((horizontalOffset 5) "
       "(fixedHeight True))) "
     "(child "
      "(LabelMenuItem "
       "(subMenu "
        "(Menu "
         "(rows 5) "
         "(cols 1) "
         "(defaultAlignment 3) "
         "(ownParent True) "
         "(title File) "
         "(resources "
          "((topInset 4) "
           "(bottomInset 4) "
           "(leftInset 4) "
           "(rightInset 4) "
           "(horizontalOffset 2))) "
         "(child "
          "(LabelMenuItem "
           "(instanceName save)  "
           "(resources "
            "((accelerator Alt\\ s) "
             "(labelString Save\\ MIB\\ Values))))) "
         "(constraint R0C0A3) "
         "(child "
          "(LabelMenuItem "
           "(instanceName saveAs)  "
           "(resources "
            "((accelerator \\\"Alt-S\\\"\\ Shift\\ Alt\\ s) "
             "(labelString Save\\ MIB\\ Values\\ As...))))) "
         "(constraint R1C0A3) "
         "(child "
          "(Separator "
           "(orientation horizontal))) "
         "(constraint R2C0A3) "
         "(child "
          "(LabelMenuItem "
           "(instanceName openParent)  "
           "(resources "
            "((callback __bTop_openMain) "
             "(accelerator Alt\\ m) "
             "(labelString Pop\\ Main\\ Window))))) "
         "(constraint R3C0A3) "
         "(child "
          "(LabelMenuItem  "
           "(resources "
            "((callback __Indiv_close) "
             "(accelerator Alt\\ c) "
             "(labelString Close))))) "
         "(constraint R4C0A3))) "
       "(resources "
        "((labelString File))))) "
     "(constraint R0C0A0) "
     "(child "
      "(LabelMenuItem "
       "(subMenu "
        "(Menu "
         "(rows 3) "
         "(cols 1) "
         "(defaultAlignment 3) "
         "(ownParent True) "
         "(title Edit) "
         "(resources "
          "((topInset 4) "
           "(bottomInset 4) "
           "(leftInset 4) "
           "(rightInset 4) "
           "(horizontalOffset 2))) "
         "(child "
          "(LabelMenuItem "
           "(instanceName get)  "
           "(resources "
            "((callback __Indiv_get) "
             "(accelerator Alt\\ g) "
             "(labelString Get))))) "
         "(constraint R0C0A3) "
         "(child "
          "(LabelMenuItem "
           "(instanceName get)  "
           "(resources "
            "((callback __Indiv_getNext) "
             "(accelerator Alt\\ n) "
             "(labelString Get\\ Next))))) "
         "(constraint R1C0A3) "
         "(child "
          "(LabelMenuItem "
           "(instanceName set)  "
           "(resources "
            "((callback __Indiv_set) "
             "(labelString Set))))) "
         "(constraint R2C0A3))) "
       "(resources "
        "((labelString Edit))))) "
     "(constraint R0C1A0) "
     "(child "
      "(LabelMenuItem "
       "(subMenu "
        "(Menu "
         "(rows 2) "
         "(cols 1) "
         "(defaultAlignment 3) "
         "(ownParent True) "
         "(title Help) "
         "(resources "
          "((topInset 4) "
           "(bottomInset 4) "
           "(leftInset 4) "
           "(rightInset 4) "
           "(horizontalOffset 2))) "
         "(child "
          "(LabelMenuItem "
           "(instanceName describe)  "
           "(resources "
            "((callback __Indiv_describe) "
             "(accelerator Alt\\ d) "
             "(labelString Description))))) "
         "(constraint R0C0A3) "
         "(child "
          "(LabelMenuItem  "
           "(resources "
            "((callback __bTop_help) "
             "(accelerator Alt\\ h) "
             "(labelString Help))))) "
         "(constraint R1C0A3))) "
       "(resources "
        "((labelString Help))))) "
     "(constraint R0C3A0))))) "
 "(constraint R0C0A0) "
 "(child "
  "(RowColumn "
   "(rows 4) "
   "(cols 2) "
   "(defaultAlignment 0) "
   "(resources "
    "((topInset 10) "
     "(leftInset 10) "
     "(rightInset 10) "
     "(horizontalOffset 10) "
     "(verticalOffset 10) "
     "(fixedHeight True))) "
   "(child "
    "(Label "
     "(resources "
      "((labelString Node:) "
       "(font -*-helvetica-bold-r-normal--14-*-*-*-p-*-iso8859-1))))) "
   "(constraint R0C0A6) "
   "(child "
    "(Frame "
     "(resources "
      "((frame innie))) "
     "(child "
      "(TextField "
       "(instanceName nodeField) "
       "(text ) "
       "(resources "
        "((background ReadOnlyBackground) "
         "(readOnly True) "
         "(terminatorCallBack __Indiv_nextField) "
         "(keepAllTextVisible False))))))) "
   "(constraint R0C1A4) "
   "(child "
    "(Label "
     "(resources "
      "((labelString Object\\ ID:) "
       "(font -*-helvetica-bold-r-normal--14-*-*-*-p-*-iso8859-1))))) "
   "(constraint R1C0A6) "
   "(child "
    "(Frame "
     "(resources "
      "((frame innie))) "
     "(child "
      "(TextField "
       "(instanceName oidField) "
       "(text ) "
       "(resources "
        "((terminatorCallBack __Indiv_nextField) "
         "(keepAllTextVisible False))))))) "
   "(constraint R1C1A4) "
   "(child "
    "(Label "
     "(resources "
      "((labelString Name:) "
       "(font -*-helvetica-bold-r-normal--14-*-*-*-p-*-iso8859-1))))) "
   "(constraint R2C0A6) "
   "(child "
    "(Frame "
     "(resources "
      "((frame innie))) "
     "(child "
      "(TextField "
       "(instanceName nameField) "
       "(text ) "
       "(resources "
        "((terminatorCallBack __Indiv_nextField) "
         "(keepAllTextVisible False))))))) "
   "(constraint R2C1A4) "
   "(child "
    "(Label "
     "(resources "
      "((labelString Value:) "
       "(font -*-helvetica-bold-r-normal--14-*-*-*-p-*-iso8859-1))))) "
   "(constraint R3C0A6) "
   "(child "
    "(Frame "
     "(resources "
      "((frame innie))) "
     "(child "
      "(TextField "
       "(instanceName valueField) "
       "(text ) "
       "(resources "
        "((terminatorCallBack __Indiv_nextField) "
         "(keepAllTextVisible False))))))) "
   "(constraint R3C1A4))) "
 "(constraint R1C0A0) "
 "(child "
  "(Gap "
   "(orientation horizontal) "
   "(resources "
    "((minWidth 450))))) "
 "(constraint R2C0A0) "
 "(child "
  "(Separator "
   "(orientation horizontal))) "
 "(constraint R3C0A0) "
 "(child "
  "(RowColumn "
   "(rows 1) "
   "(cols 3) "
   "(defaultAlignment 0) "
   "(resources "
    "((topInset 10) "
     "(bottomInset 10) "
     "(leftInset 10) "
     "(rightInset 10) "
     "(horizontalOffset 10) "
     "(fixedWidth True))) "
   "(child "
    "(LabelButton "
     "(instanceName getBtn) "
     "(resources "
      "((callback __Indiv_get) "
       "(labelString Get))))) "
   "(constraint R0C0A0) "
   "(child "
    "(LabelButton "
     "(instanceName getNextBtn) "
     "(resources "
      "((callback __Indiv_getNext) "
       "(labelString Get\\ next))))) "
   "(constraint R0C1A0) "
   "(child "
    "(LabelButton "
     "(instanceName setBtn) "
     "(resources "
      "((callback __Indiv_set) "
       "(labelString Set))))) "
   "(constraint R0C2A0))) "
 "(constraint R4C0A5))";
