.TH getash 2
.SH NAME
getash \- get array session handle
.SH SYNOPSIS
.nf
\f3#include <sys/types.h>\f1
\f3#include <unistd.h>\f1
.sp .8v
\f3ash_t getash(void);\f1
.fi
.SH DESCRIPTION
The \f2getash\fP function returns the array session handle (ASH) for
the array session that contains the calling process.
.PP
The handle for an array session is normally assigned by the system
when the array session is first created.
This can be overridden using the privileged \f2setash\fP(2) function.
For details, see the man pages for \f2setash\fP(2).
.SH SEE ALSO
newarraysess(2),
setash(2),
array_sessions(5).
.SH "DIAGNOSTICS"
\f2getash\fP always returns the array session handle.
There are no error conditions.
