'\"macro stdmacro
.if n .pH g2.getuid @(#)getuid	40.15 of 4/5/91
.\" Copyright 1991 UNIX System Laboratories, Inc.
.\" Copyright 1989, 1990 AT&T
.nr X
.if \nX=0 .ds x} getuid 2 "" "\&"
.if \nX=1 .ds x} getuid 2 ""
.if \nX=2 .ds x} getuid 2 "" "\&"
.if \nX=3 .ds x} getuid "" "" "\&"
.TH \*(x}
.SH NAME
\f4getuid\f1, \f4geteuid\f1, \f4getgid\f1, \f4getegid\f1 \- get real user, effective user, real group, and effective group \s-1ID\s+1s
.Op c p a
.SH C SYNOPSIS
\f4#include <sys/types.h>\f1
.br
\f4#include <unistd.h>\f1
.PP
.B "uid_t getuid (void);"
.br
.B "uid_t geteuid (void);"
.sp 2
.br
.B "gid_t getgid (void);"
.br
.B "gid_t getegid (void);"
.Op
.Op f
.SH FORTRAN SYNOPSIS
.B "integer function getuid()"
.br
.B "integer*2 function geteuid()"
.br
.B "integer function getgid()"
.br
.B "integer*2 function getegid()"
.Op
.SH DESCRIPTION
\f4getuid\fP
returns the real user
ID
of the calling process.
.PP
\f4geteuid\fP
returns the effective user
ID
of the calling process.
.PP
\f4getgid\fP
returns the real group
ID
of the calling process.
.PP
\f4getegid\fP
returns the effective group
ID
of the calling process.
.SH "SEE ALSO"
\f4intro\fP(2), \f4setuid\fP(2)
.\"	@(#)getuid.2	6.2 of 9/6/83
.Ee
