'\"macro stdmacro
.TH MADVISE 2
.SH NAME
madvise \- give advice about handling memory
.SH SYNOPSIS
.B #include <sys/mman.h>
.sp
.B "int madvise (void \(**addr, size_t len, int behavior);"
.SH DESCRIPTION
\f2madvise\fP provides the system advice about the process' expected
use of its address space from \f2addr\fP to \f2addr + len\fP.
.LP
The following types of \f2behavior\fP are currently recognized by the system:
.PP
.ig
.TP 17
.SM MADV_NORMAL
informs the system that no further special treatment of the stated address
range is needed.
.TP 17
.SM MADV_RANDOM
.TP 17
.SM MADV_SEQUENTIAL
.TP 17
.SM MADV_WILLNEED
..
.TP 17
.SM
.B MADV_DONTNEED
informs the system that the address range from \f2addr\fP to \f2addr + len\fP
will likely not be referenced in the near future.
The memory to which the indicated addresses are mapped will be the first
to be reclaimed when memory is needed by the system.
.PP
\f2madvise\fP will fail if:
.TP 15
.SM
\%[ENOMEM]
Addresses in the range (\f2addr, addr + len\fP\^) 
are outside the valid range for the address space of the process.
.TP
.SM
\%[EINVAL]
\f2behavior\fP is not recognized by the system.
.SH SEE ALSO
mmap(2), msync(2).
.SH DIAGNOSTICS
A 0 value is returned on success; a -1 value indicates an error.
.SH BUGS
MADV_DONTNEED advice is currently only heeded for memory
mapped via explicit \f2mmap(2)\fP system calls.
