'\"macro stdmacro
'\"
'\" (C) COPYRIGHT SILICON GRAPHICS, INC.
'\" UNPUBLISHED PROPRIETARY INFORMATION.
'\" ALL RIGHTS RESERVED.
'\"
.nr X
.if \nX=0 .ds x} rexec 2 "" "\&"
.if \nX=1 .ds x} rexec 2 ""
.if \nX=2 .ds x} rexec 2 "" "\&"
.if \nX=3 .ds x} rexec "" "" "\&"
.TH \*(x}
.SH NAME
\f4rexec\f2: \f4rexecl\f1, \f4rexecv\f1, \f4rexecle\f1, \f4rexecve\f1, \f4rexeclp\f1, \f4rexecvp\f1 \- execute a file on a remote cell
.SH SYNOPSIS
.na
\f4#include <unistd.h>\fP
.HP
\f4int rexecl (cell_t cell, const char \(**path, const char \(**arg0, ..., const char \(**argn, (char *)0);\f1
.HP
\f4int rexecv (cell_t cell, const char \(**path, char \(**const \(**argv);\f1
.HP
\f4int rexecle (cell_t cell, const char \(**path, const char \(**arg0, ..., const char \(**argn, (char *0), const char \(**envp[]);\f1
.HP
\f4int rexecve (cell_t cell, const char \(**path, char \(**const \(**argv, char \(**const \(**envp);\f1
.HP
\f4int rexeclp (cell_t cell, const char \(**file, const char \(**arg0, ..., const char \(**argn, (char *)0);\f1
.HP
\f4int rexecvp (cell_t cell, const char \(**file, char \(**const \(**argv);\f1
.ad
.SH DESCRIPTION
\f4rexec\fP
in all its forms overlays a new process image on an old process and commences
execution on a new cell. This system call is reserved to be supported in
Cellular IRIX. In IRIX release 6.5, the only valid value for \f2cell\f1
is 0 and then each form of \f4rexec\fP is equivalent to the corresponding
form of \f4exec\fP.
.P
.SH ERRORS
In addition to the error codes returned by \f4exec\fP,
the following error code may be returned by any of the forms of \f4rexec\fP:
.TP 12
\&[EINVAL\&]
An invalid value for \f2cell\f1 was specified.
.SH "SEE ALSO"
\f4exec\fP(2),
.SH DIAGNOSTICS
If
\f4rexec\fP
returns to the calling process, an error has occurred; the return value
is \-1 and
\f4errno\fP
is set to indicate the error.
