'\"macro stdmacro
.Op c p a
.TH satmp_done 2
.SH NAME
satmp_done \- de\-register token\-mapping daemon with kernel
.SH C SYNOPSIS
.B #include <sys/t6satmp.h>
.PP
.nf
.B int satmp_done (void);
.fi
.SH DESCRIPTION
.I satmp_done
de\-registers the token\-mapping daemon.
The calling process must have appropriate privilege.
If
.B _POSIX_CAP
is in effect, appropriate privilege includes
.B CAP_NETWORK_MGT
capability.
.SH ERRORS
.I satmp_done
will fail if one or more of the following are true:
.TP 15
[ENOPKG]
Trusted Networking is not configured on this system.
.TP 15
[EPERM]
The caller doesn't have
.B CAP_NETWORK_MGT
capability.
.SH "RETURN VALUE"
.I satmp_done
returns 0 if successful. A return value of \-1 indicates an error and
.I errno
is set to indicate the error.
.SH "SEE ALSO"
satmp_get_attr_reply(2),
satmp_get_lrtok_reply(2),
satmp_init(2),
satmp_init_reply(2),
satmp(7).
.SH "ORIGIN"
Silicon Graphics, Inc.
