'\"macro stdmacro
.Op c p a
.TH satmp_init_reply 2
.SH NAME
satmp_init_reply \- send SATMP_INIT_REPLY message to the kernel
.SH C SYNOPSIS
.B #include <sys/t6satmp.h>
.PP
.nf
.B "int satmp_init_reply (int fd, u_int addr, int flag, u_int generation);"
.fi
.SH DESCRIPTION
.I satmp_init_reply
sends a
.B SATMP_INIT_REPLY
message to the kernel.
.B fd
is a file descriptor that references the token\-mapping daemon\'s socket.
.B addr 
is the address of the hostid sending the message.
.B flag
indicates success or failure. It\'s valid values are
.B IRQ_FLAG_OK
and
.B IRQ_FLAG_FAILED .
.B generation
is the generation of the remote token\-mapping database.
.SH ERRORS
.I satmp_init_reply
will fail if one or more of the following are true:
.TP 15
[ENOPKG]
Trusted Networking is not configured on this system.
.TP 15
[EPERM]
.B fd
doesn't refer to the token\-mapping socket.
.TP 15
[EINVAL]
The value of
.B flags
is not
.B IRQ_FLAG_OK
or
.B IRQ_FLAG_FAILED .
.SH "RETURN VALUE"
.I satmp_init_reply
returns 0 if successful. A return value of \-1 indicates an error and
.I errno
is set to indicate the error.
.SH "SEE ALSO"
satmp_done(2),
satmp_get_attr_reply(2),
satmp_get_lrtok_reply(2),
satmp_init(2),
satmp(7).
.SH "ORIGIN"
Silicon Graphics, Inc.
