'\"macro stdmacro
.Op c p a
.TH satmp_get_lrtok_reply 2
.SH NAME
satmp_get_lrtok_reply \- send SATMP_GET_LTROK_REPLY message to the kernel
.SH C SYNOPSIS
.B #include <sys/t6satmp.h>
.PP
.nf
.B "int satmp_get_lrtok_reply (int fd, const void *buf, size_t size);"
.fi
.SH DESCRIPTION
.I satmp_get_lrtok_reply
sends a
.B SATMP_GET_LRTOK_REPLY
message to the kernel.
.B fd
is a file descriptor that references the token\-mapping daemon\'s socket.
.B buf
is the address of a buffer containing the message.
.B size
is the size of the message in bytes.
.SH ERRORS
.I satmp_get_lrtok_reply
will fail if one or more of the following are true:
.TP 15
[ENOPKG]
Trusted Networking is not configured on this system.
.TP 15
[EPERM]
.B fd
doesn't refer to the token\-mapping socket.
.TP 15
[EFAULT]
.B buf
doesn't refer to memory in the calling processes address space.
.TP 15
[ENOMEM]
The kernel cannot allocate sufficient memory to hold the message.
.SH "RETURN VALUE"
.I satmp_get_lrtok_reply
returns 0 if successful. A return value of \-1 indicates an error and
.I errno
is set to indicate the error.
.SH "SEE ALSO"
satmp_done(2),
satmp_get_attr_reply(2),
satmp_init(2),
satmp_init_reply(2),
satmp(7).
.SH "ORIGIN"
Silicon Graphics, Inc.
