'\"macro stdmacro
.Op c p a
.TH sched_yield 2
.SH NAME
\f4sched_yield\fP \- yield the processor
.SH C SYNOPSIS
.nf
\f3#include <sched.h>\f1
.sp .6v
\f4int sched_yield (void);\f1
.fi
.SH DESCRIPTION
The \f4sched_yield\fP system call causes the calling process to relinquish
the processor to a runnable process of higher or equal priority.
In the event a higher or equal priority  process is not available,
the calling process reacquires control of the processor.
.SH SEE ALSO
alarm(2),
pause(2),
sched_getscheduler(2),
sched_getparam(2),
sched_setparam(2),
sched_setscheduler(2),
setitimer(2),
sginap(2),
sleep(3)
.SH DIAGNOSTICS
Upon successful completion, a value of 0 is returned to the calling process. 

