'\"! tbl | mmdoc
'\"macro stdmacro
.de Ex
.lg 0
.ls 1
.sp
.nf
.if !\n(.A .ft C
.ta 4m,+4m,+4m,+4m,+4m,+4m,+4m,+4m,+4m,+4m,+4m,+4m,+4m,+4m
.\" .ta 96p,+48p,+48p,+48p,+48p,+48p,+48p,+48p,+48p,+48p,+48p,+48p,+48p,+48p
..
.\" end display of program excerpts and commands
.de Ee
.if !\n(.A .ft 1
.\" if arg given then don't space. Kludge in case at very bottom of page at
.\" end of chapter.
.if '\\$1'' .sp
.fi
.ls
.lg 1
..
.TH SGIGSC 2
.SH NAME
sgigsc \- SGI graphics system call
.SH SYNOPSIS
.B #include <sys/sgigsc.h>
.PP
.nf
.B "int sgigsc(int op, ...);"
.fi
.SH DESCRIPTION
This system call is used for underlying operating system support of graphics
and window management functions.
It is not intended for direct use by user programs.
'\".so /pubs/tools/origin.sgi
