DIAGDEPTH= ../..
include ${DIAGDEPTH}/Makedefs

HFILES= tlb.h
CFILES= global.c mem.c mod.c nocache.c pid.c probe.c purge.c translate.c \
	valid.c utlb_miss.c tlbtest.c

include ${DIAGDEPTH}/Makerules
