#define kaio_init        _kaio_init
#define kaio_read	_kaio_read
#define kaio_write	_kaio_write
#define kaio_submit	_kaio_submit
#define kaio_suspend	_kaio_suspend
#define kaio_error	_kaio_error
#define kaio_return	_kaio_return
#define kaio_lio	_kaio_lio
#define kaio_cancel	_kaio_cancel
#define kaio_fsync	_kaio_fsync
#define kaio_hold	_kaio_hold
#define _kaio_closechk    __kaio_closechk
#define _kaio_reset	__kaio_reset
#define _kaio_realloc_fds __kaio_realloc_fds
#define _kaio_lio_free    __kaio_lio_free
#define _kaio_eligible    __kaio_eligible
#define _kaio_user_active    __kaio_user_active

#define aio_cancel      _aio_cancel
#define aio_cancel64    _aio_cancel64
#define aio_error       _aio_error
#define aio_error64     _aio_error64
#define aio_fsync       _aio_fsync
#define aio_fsync64     _aio_fsync64
#define aio_hold        _aio_hold
#define aio_hold64      _aio_hold64
#define aio_read        _aio_read
#define aio_read64      _aio_read64
#define aio_return      _aio_return
#define aio_return64    _aio_return64
#define aio_sgi_init    _aio_sgi_init
#define aio_sgi_init64  _aio_sgi_init64
#define aio_suspend     _aio_suspend
#define aio_suspend64   _aio_suspend64
#define aio_write       _aio_write
#define aio_write64     _aio_write64
#define aio_init        _aio_init

#define syssgi        _syssgi
