#include <limits.h>

#include <ABIinfo.h>
#include <abi_mutex.h>
#include <aio.h>
#include <archives.h>
#include <assert.h>
#include <backtrace.h>
#include <bstring.h>
#include <capability.h>
#include <clearance.h>
#include <comp.h>
#include <core.out.h>
#include <cpio.h>
#include <cr1.h>
#include <crypt.h>
#include <cs.h>
#include <ctype.h>
#include <deflt.h>
#include <devconvert.h>
#include <devmgmt.h>
#include <di_aux.h>
#include <di_group.h>
#include <di_passwd.h>
#include <dial.h>
#include <dirent.h>
#include <diskinfo.h>
/* uses stat64 so kind of needs _LARGEFILE64_SOURCE or SGI_SOURCE */
#if defined(_LARGEFILE64_SOURCE) || _SGIAPI
#include <mountinfo.h>
#include <diskinvent.h>
#endif

#include <dlfcn.h>
#include <dpipe.h>
#include <errno.h>
#include <exportent.h>
/*#include <fam.h> XX needs PATH_MAX */
#include <fcntl.h>
#include <fmtmsg.h>
#include <fnmatch.h>
#include <fp_class.h>
#include <fsd.h>
#include <ftw.h>
#include <getabi.h>
#include <getopt.h>
#include <glob.h>
#include <grp.h>
#include <hostreg.h>
#include <ia.h>
#include <iconv.h>
#include <iconv_cnv.h>
#include <iconv_int.h>
#include <invent.h>
#include <langinfo.h>
#include <lastlog.h>
#include <listen.h>
#include <locale.h>
#include <malloc.h>
#include <math.h>
#include <mediaclient.h>
#include <memory.h>
#include <mls.h>
#include <mntent.h>
#include <mon.h>
#include <monetary.h>
#include <mqueue.h>
#include <mutex.h>
#include <ndbm.h>
#include <netconfig.h>
#include <netdb.h>
#include <netdir.h>
#include <nl_types.h>
#include <paths.h>
#include <pkgdev.h>
#include <pkginfo.h>
#include <pkglocs.h>
#include <pkgstrct.h>
#include <pkgtrans.h>
#include <poll.h>
#include <proj.h>
#include <pthread.h>
#include <pwd.h>
#include <re_comp.h>
#include <regex.h>
#include <rtlock.h>
#include <sac.h>
#include <sat.h>
#include <sched.h>
#include <search.h>
#include <semaphore.h>
#include <setjmp.h>
#include <sgi_nl.h>
#include <sgtty.h>
#include <shadow.h>
#include <siginfo.h>
#include <signal.h>
#include <ssdi.h>
#include <standards.h>
#include <std.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <stropts.h>
#include <sum.h>
#include <sysexits.h>
#include <syslog.h>
#include <tar.h>
#include <task.h>
#include <tcl.h>
#include <termio.h>
#include <termios.h>
#include <time.h>
#include <timers.h>
#include <tiuser.h>
#include <tzfile.h>
#include <ucontext.h>
#include <ulimit.h>
#include <ulocks.h>
#include <uncomp.h>
#include <unistd.h>
#include <ustat.h>
#include <utime.h>
#include <utmp.h>
#include <utmpx.h>
#include <valtools.h>
#include <wait.h>
#include <wchar.h>
#include <wordexp.h>
#include <wsregexp.h>
#include <xti.h>

/* XPG4 set of sys headers */
#include <sys/ipc.h>
#include <sys/sem.h>
#include <sys/msg.h>
#include <sys/shm.h>
#include <sys/mman.h>
#include <sys/resource.h>
#include <sys/statvfs.h>
#include <sys/timeb.h>
#include <sys/times.h>
#include <sys/uio.h>
#include <sys/utsname.h>

/* some others */
#include <sys/procfs.h>
#include <sys/cachectl.h>
#include <sys/dirent.h>
#include <sys/param.h>
#include <sys/procset.h>
#include <sys/prctl.h>
#include <sys/poll.h>
/*#include <sys/pmo.h> uses 64 bit bit field */
#include <sys/utssys.h>
#include <sys/syssgi.h>
#include <sys/sysmp.h>
#include <sys/sysget.h>
#include <sys/systeminfo.h>
#include <sys/systeminfo.h>
#include <sys/sysinfo.h>
#include <sys/syslog.h>
#include <sys/sysmips.h>
