.TH Add_disk 1
.SH NAME
Add_disk \- add an optional disk to the system
.SH SYNOPSIS
.nf
\f3Add_disk\f1 [ \f2controller_number\f1 ] [ \f2disk_number\f1 ] [ \c
\f2lun_number\f1 ]
.fi
.SH DESCRIPTION
.I Add_disk
enables you to add an extra SCSI disk to a system if the disk is
on an integral SCSI controller
(i.e., it can not be used for
disks attached to VME SCSI controllers).
.P
The
.I disk_number
option must be specified if you are not adding the default ID of 2; similarly
the controller and lun must be specified if other than 0.
.PP
The
.I Add_disk
command creates the required directory, makes the appropriate
device file links, makes a new filesystem, does the required mount operation,
and adds the appropriate entry to
.IR /etc/fstab .
.PP
Appropriate checks are made for filesystems already existing on the
common partitions (0, 6, and 7).
If they are present, you
are asked if you want to proceed before a filesystem is made.
If
the answer is no,
.I Add_disk
exits.
.SH NOTE
Older versions of this command worked only with controller 0, and
used a default mount point of \f2/disk\f1#, where # was the SCSI ID.
This
version uses \f2/disk\f1##, where the first # is the controller and the
second is the SCSI ID.
.PP
.I Add_disk
is a shell script and can be used as a template to determine
what is necessary.
The volume header on the disk must already have been
initialized with the
.IR fx (1M)
program.
.SH SEE ALSO
fx(1M),
mkfs(1M),
fstab(4).
