.\" Copyright 1991 UNIX System Laboratories, Inc.
.\" Copyright 1989, 1990 AT&T
.nr X
.if \nX=0 .ds x} cal 1 "User Environment Utilities" "\&"
.TH \*(x}
.SH NAME
\f4cal\f1 \- print calendar
.SH SYNOPSIS
.nf
\f4cal\f1 [ [ \f2month\f1 ] \f2year\f1 ]
.fi
.SH DESCRIPTION
\f4cal\fP
prints a calendar for the specified year.
If a month is also specified, a calendar
just for that month is printed.
If neither is specified, a calendar for
the present month is printed.
The
\f2month\f1
is a number between 1 and 12.
The
\f2year\f1
can be between 1
and 9999.
The calendar
produced is that for England and the United States.
.SH NOTES
An unusual calendar is printed for September 1752.
That is the month 11 days were skipped to make up
for lack of leap year adjustments.
To see this calendar, type:
\f4cal 9 1752\f1
.P
The command \f4cal 83\fP refers to the year 83, not 1983.
.P
The year is always considered to start in January even though this
is historically naive.
.\"	@(#)cal.1	6.2 of 9/2/83
