.TH check 1
.SH NAME
check \- check RCS status of a file
.SH SYNOPSIS
.nf
\f3check\f1 \f3[ -d ]\f1 \f3[ -l ]\f1 \f3[ \f2rcsdir\fP ]\f1
.fi
.SH DESCRIPTION
.I check
displays RCS checkout information
for files in the current directory.
This includes the revision level,
checkout status of the file,
and who the file is checked out to.
\f2check\fP assumes \f2./RCS\fP
is the default RCS directory.
A different RCS directory
can be specified with the
.I rcsdir
argument.
.PP
The
.B -d
switch causes
.I check
to display the date when the file was checked out in addition to the
usual information.
The
.B -l
switch causes
.I check
to display only the names
of files currently checked out.
.PP
If
.I check
finds no files checked out, then it exits with status 0.
If some files are checked out, it exits with status 1.
If an error occurs, it exits with status 2.
.SH "SEE ALSO"
'\".SH AUTHOR
'\"Kipp Hickman
ci(1),
co(1),
ident(1),
merge(1),
rcs(1),
rcsdiff(1),
rcsmerge(1),
rlog(1),
rcsfile(4).
