'\"macro stdmacro
.TH check_abi_interface 1
.SH NAME
\f4check_abi_interface\f1 \- check abi compliance of a library interface
.SH SYNOPSIS
\f4/usr/bin/check_abi_interface [\-abidir \f2directory\f4]
.in +6
[\-missing] [\-extra] [\-libname \f2library\f4] \f2file\f1
.in -6
.SH DESCRIPTION
\f4check_abi_interface\fP
checks a library interface and displays abi
entries which are missing as well as public entries which
are not part of the abi.
.TP 5
\f4\-abidir \f2directory\f1
This specifies a directory which contains files which
specify abi routines.  The filenames are of the form
LIBRARY.names.
.TP
\f4\-libname \f2library_list\f1
This specifies the name of the library to use when
searching in abidir.  The default is the name of the
file.
.TP
\f4\-missing\f1
Display only abi routines which are missing from the library.
.TP
\f4\-extra\f1
Display only public routines which are not part of the abi.
.RE
.SH FILES
/usr/lib/abi/data	directory containing ABI entry points
.SH SEE ALSO
check_abi_compliance(1), check_for_syscalls(1), elfdump(1).
'\".so /pubs/tools/origin.sgi
