'\"macro stdmacro
.TH check_for_syscalls 1
.SH NAME
\f4check_for_syscalls\f1 \- check for embedded syscalls in an object file.
.SH SYNOPSIS
\f4/usr/bin/check_for_syscalls [\-syscalls \f2syscall_file\f4] \f2file\f1
.SH DESCRIPTION
\f4check_for_syscalls\fP
finds embedded system calls in an object file.
.TP 5
\f4\-syscalls \f2syscall_file\f1
This file is used to translate from system call numbers
to names. The default is \f4/usr/lib/abi/data/syscall.h\fP.
.RE
.SH FILES
/usr/lib/abi/data/syscall.h
'\".so /pubs/tools/origin.sgi
