.TH clear 1
.SH NAME
clear \- clear terminal screen
.SH SYNOPSIS
.nf
\f3clear\f1
.fi
.SH DESCRIPTION
.B clear
clears your screen if this is possible.
It looks in the environment for the terminal type and then
uses the
.IR terminfo (4)
database
to figure out how to clear the screen.
.PP
.B clear
opens a full screen window and clears all bitplanes (front, back
overlay, underlay, alphaoverlay and so forth).
It sends a redraw to all open windows.
.SH FILES
/usr/lib/terminfo/?/*	compiled terminal description database
.SH SEE ALSO
terminfo(4).
