.\" Copyright 1991 UNIX System Laboratories, Inc.
.\" Copyright 1989, 1990 AT&T
.nr X
.if \nX=0 .ds x} cmp 1 "Essential Utilities" "\&"
.TH \*(x}
.SH NAME
\f4cmp\f1 \- compare two files
.SH SYNOPSIS
.nf
\f4cmp\f1 [ \f4\-l\f1 ] [ \f4\-s\f1 ] \f2file1 file2\f1 \c
[ \f2skip1\f1 ] [ \f2skip2\f1 ]
.fi
.SH DESCRIPTION
The two files are
compared.
(If
.I file1
is
\f4\-\f1,
the standard input is used.)
Under default options,
\f4cmp\fP
makes no comment if the files are the same;
if they differ, it announces the byte and line number
at which the difference occurred.
If one file is an initial subsequence
of the other, that fact is noted.
\f2skip1\f1
and
\f2skip2\f1
are initial byte offsets into
\f2file1\f1 and \f2file2\f1
respectively, and may be either octal or decimal; a leading
\f40 \f1 denotes octal.
.P
Options:
.TP
\f4 \-l\f1
Print the byte number (decimal) and the
differing bytes (octal) for each difference.
.TP
\f4 \-s\f1
Print nothing for differing files;
return codes only.
.SH FILES
.TP
\f4/usr/lib/locale/\f2locale\f4/LC_MESSAGES/uxcore.abi\f1
language-specific message file (See \f4LANG\fP on \f4environ\f1(5).)
.SH "SEE ALSO"
comm(1),
diff(1).
.SH DIAGNOSTICS
Exit code \f40\f1 is returned for identical
files, \f41\f1 for different files, and \f42\f1 for an
inaccessible or missing argument.
.\"	@(#)cmp.1	6.2 of 9/2/83
