'\"macro stdmacro
.nr X
.if \nX=0 .ds x} DKPROBE 1 "Performance Co-Pilot" "\&"
.if \nX=1 .ds x} DKPROBE 1 "Performance Co-Pilot"
.if \nX=2 .ds x} DKPROBE 1 "" "\&"
.if \nX=3 .ds x} DKPROBE "" "" "\&"
.\" $Id: dkprobe.1,v 2.3 1997/09/24 01:08:17 markgw Exp $
.TH \*(x}
.SH NAME
\f3dkprobe\f1 \- probe all configured disks
.SH SYNOPSIS
\f3/usr/pcp/bin/dkprobe\f1
[\f3\-V\f1]
.SH DESCRIPTION
.B dkprobe
uses
.BR getinvent (3)
to establish the list of disk devices in the system, then
attempts to open the volume header of each.
.PP
On systems that do not use the Hardware Graph Filesystem (see
.BR hwgraph (4)),
i.e. versions of IRIX prior to IRIX6.4,
.B dkprobe
is called from
.B /etc/init.d/pcp
when
.BR pmcd (1)
is started
to ensure that
the IRIX disk statistics are initialized.
There should be no constructive reason for running
.B dkprobe
otherwise.
.PP
The
.B \-V
flag turns on verbose mode; the name of each disk volume
is printed as it is probed, and an error message is produced
if the probe fails for any reason.
.SH FILES
.nrPD 0
.TP 20
.B /dev/rdsk/*vh
the volume headers
.PD
.SH SEE ALSO
.BR pmcd (1),
.BR getinvent (3)
and
.BR vh (7M).
