.TH DLOOK 1
.SH NAME
\f3dlook\f1 \- a tool for showing memory and process placement
.SH SYNOPSIS
.nf
dlook [\f3-sample\f1 \f3n\f1] [\f3-mapped\f1] [\f3-text\f1] [\f3-out\f1 \f2file\f1] [\f3-v[erbose]\f1]
      [\f3-p[hysical]\f1] [\f3-c[olor]\f1] \f2command\f1 [args]
.fi

.SH DESCRIPTION
The given \f2command\f1 is executed and after each child process exits
\f2dlook\f1 shows where each process was running when it exited
and how its stack and heap data was placed with page size information.
If sampling is enabled, this data is also displayed at regular intervals.

.SH OPTIONS
.TP
\f3-sample\f1 \f3n\f1
Sample each process approximately every \f3n\f1 seconds. The default
is no sampling.
.TP
\f3-mapped\f1
Show where mapped memory regions with addresses below text are placed.
.TP
\f3-text\f1
Show how program text data is placed.
.TP
\f3-out\f1 \f2file\f
Output is sent to \f2file\f1 rather than standard error.
.TP
\f3-v[erbose]\f1
Show \f2dlook\f1 parameters and more detail.
.TP
\f3-p[hysical]\f1
Show virtual to physical address mappings.
.TP
\f3-c[olor]\f1
Show secondary cache page colors. Automatically enables the \f3-p[hysical]\f1 option.
.TP

.SH EXAMPLE

To show memory and thread placement for a  program called a.out
that would normally be run by
.nf.
   % a.out < in > out 
.fi
and place the resuls in a file called \f2output\f1 
one would simply
.nf
   % dlook -out output a.out < in > out .
.fi


