'\"macro stdmacro
.if n .pH man1.domainname @(#)domainname	30.3 of 2/1/86
.TH DOMAINNAME 1  
.SH NAME
domainname \- set or display name of current NIS domain
.SH SYNOPSIS
.B domainname
[ \f2name-of-domain\f1 ]
.SH DESCRIPTION
.IX "domainname command"  ""  "\fLdomainname\fP \(em set/display domain name"
.IX domain  "set or display current"
.IX "current domain"  "set or display"
.IX display  "current domain"
.IX set  "current domain"
Without an argument,
.I domainname
displays the name of the current network information service (NIS) domain,
which typically encompasses a group of hosts under the same administration.  As
such, the name of an NIS domain is typically a valid Internet
domain name in order to be consistent with the domain name used by
the BIND name server,
.IR named (1M).
.P
Only the super-user can set the domain name by giving an argument;
this is performed by the system startup procedure using the contents of
.IR /var/yp/ypdomain .
This setting is persists only until the machine is rebooted, when it will
once again be set using the contents of the above file.
To permanently change the value change this file, then run the domainname
command as a privileged user or run the command:
.IR "/var/yp/ypinit -c" .
.P
Currently, the network information service uses domains only to refer
collectively to a group of hosts.
.SH SEE ALSO
ypinit(1M)
.\".SH ORIGIN
.\"Sun Microsystems
