.TH eagch 1
.SH NAME
eagch \- change extended attribute (Plan G) information
.SH SYNOPSIS
.nf
\f3eagch\fP [\f3-\fPattr\f3=\fPvalue]... [path]...
.fi
.SH DESCRIPTION
.I eagch
modifies the extended attribute
.RI ( "Plan G" )
data associated with the named
.IR path s.
.PP
The possible values of \f3\-\f1\f2attr\f1 are:
.TP 7
.B \-acl
Give
.I path
the access control list (ACL) specified by
.IR value .
.TP
.B \-acl-default
Give the directory named by
.I path
the directory default
ACL
specified by
.IR value .
.TP
.B \-mac
Set the mandatory access control (MAC) label to the specified
.IR value .
.TP
.B \-cap-set-effective
If
.I value
is
.BR on ,
the set effective capabilities bit for the specified file is set,
otherwise it is cleared.
.TP
.B \-cap-allowed
Set the allowed capabilities of the file to those listed in
.IR value .
.TP
.B \-cap-forced
Set the forced capabilities of the file to those listed in
.IR value .
.SH "NOTES"
In most cases,
.I eagch
should be used in preference to
.IR eagch (1M).
.I eagch
requires that the running system kernel support extended attributes.
.SH "SEE ALSO"
eagedit(1M),
eagls(1),
mkeag(1M).
