'\"macro stdmacro
.TH EAGLS 1
.SH NAME
eagls \- show extended attributes of the contents of a directory
.SH SYNOPSIS
.B eagls
[
.B \-adlv
] [path ...]
.SH DESCRIPTION
.I eagls
displays the extended attribute information associated with file system
entries.
If no
.IR path s
are specified the contents of the current directory are displayed
except for those entries whose names begin with
.BR . .
If the
.B \-a
option is given the entries whose names begin with 
.B .
are included.
If the
.B \-d
option is given 
.I path
itself is shown, not its contents.

The normal output for
.I eagls
is:

.nr
	path acl acl-default capabilities 0 mac
.fi

An asterisk
.RB (*)
will be displayed for any field for which data is not available.
The
.B 0
in the fourth field is a place holder for an as yet unimplemented datum.

If the
.B \-l
option is given the
inode number,
link count,
owner,
owning group,
size,
and modification time
are printed
immediatly following the
.IR path .
If the
.B \-v
option is given the results are printed in a verbose format.
.SH SEE\ ALSO
\f4ls(1)\f1
\f4eagch(1)\f1
\f4eagedit(1m)\f1
'\".SH ORIGIN
'\"4th Berkeley Software Distribution
