'\"macro stdmacro
.TH ESPARCHIVE 1
.SH NAME
esparchive \- Archiving utility for Embedded Support Partner
.SH DESCRIPTION
.I esparchive\^
is a utility that is used for archiving the database in the Embedded Support Partner.
This is generally used to conserve space on the disk. The archiving utility has to be launched from
the command line. Archiving will run only if the size of the database is greater than 10MB.
The archiving process temporarily shuts down the Embedded Support Partner to conserve data integrity during
the archival process. Once archived the database is compressed and used only for generating reports. A new database
is created with no records in it. To delete archives use the Embedded Support Partner user interface.
.P
.SH SEE ALSO
esp(5)
.SH REFERENCES
SGI Embedded Support Partner User Guide

