'\"macro stdmacro
.if n .pH g2.getconf @(#)getconf	30.2 of 01/12/96
.TH GETCONF 1
.SH NAME
getconf \- get configuration variables (XPG4)
.SH SYNOPSIS
.PP
.B getconf
.I system_var
.sp
.B getconf
.I path_var
.I path_name
.SH DESCRIPTION
.B getconf\^
provides a method to determine the current
values of certain configurable system limits, options and parameters.
.PP
If the 
.I system_var
argument is given, \f4getconf\fP(1) will print the value of
each requested system parameter, one per line.
.PP
If the 
.I path_var
and
.I pathname
arguments are given, \f4getconf\fP(1) will print the value of
the requested variable specified by the
.I path_var
argument for the path specified by the
.I pathname
operand.
.SH STDOUT
If the specified variable is defined on the system and its value is 
described to be available, its value will be written in the following format:
.sp
.in+0.5i
"%s\\n", <value>
.in-0.5i
.sp
Otherwise, if the specified variable is defined on the system, its value will 
be written in the following format:
.sp
.in+0.5i
"%d\\n", <value>
.in-0.5i
.sp
If the specified variable is valid, but is undefined on the system,
\f4getconf\fP will write using the following format:
.sp
.in+0.5i
"undefined\\n"
.in-0.5i
.sp
If the variable name is invalid or an error occurs, nothing will be written
to standard output.
.SH OPERANDS
The following operands are supported:
.sp
.I path_var
.sp
.in+1.0i
A name of a configuration variable whose value is available from the
.I pathconf()
function.  All of the values in the following table are supported in addition
to others described in \f4pathconf\fP(1):
.in-1.0i
.sp
.if n .ta 2.0i 1.8i 4.2i
.if t .ta 1.0i 1.5i 3.2i
.nf
.na
.B
LINK_MAX	NAME_MAX	_POSIX_CHOWN_RESTRICTED
.B
MAX_CANON	PATH_MAX	_POSIX_NO_TRUNC
.B
MAX_INPUT	PIPE_BUF	_POSIX_VDISABLE
.fi
.sp
.I pathname
.sp
.in+1.0i
A pathname for which the variable specified by
.I path_var
is to be determined.
.in-1.0i
.sp
.I system_var
.sp
.in+1.0i
A name of a configuration variable whose value is available from the
.I sysconf()
function.  All of the values in the following table are supported:
.in-1.0i
.if n .ta 2.0i 1.8i 4.2i
.if t .ta 1.0i 1.5i 3.2i
.nf
.na
.sp
.B
ARG_MAX	NL_TEXTMAX	POSIX2_C_DEV
.B
BC_BASE_MAX	OPEN_MAX	POSIX2_C_VERSION
.B
BC_DIM_MAX	_POSIX_ARG_MAX	POSIX2_EXPR_NEST_MAX
.B
BC_SCALE_MAX	_POSIX_CHILD_MAX	POSIX2_FORT_DEV
.B
BC_STRING_MAX	_POSIX_JOB_CONTROL	POSIX2_FORT_RUN
.B
CHAR_BIT	_POSIX_LINK_MAX	POSIX2_LINE_MAX
.B
CHAR_MAX	_POSIX_MAX_CANON	POSIX2_LOCALEDEF
.B
CHAR_MIN	_POSIX_MAX_INPUT	POSIX2_RE_DUP_MAX
.B
CHILD_MAX	_POSIX_NAME_MAX	POSIX2_SW_DEV
.B
CLK_TCK	_POSIX_NGROUPS_MAX	POSIX2_UPE
.B
COLL_WEIGHTS_MAX	_POSIX_OPEN_MAX	POSIX2_VERSION
.B
CS_PATH	_POSIX_PATH_MAX	RE_DUP_MAX
.B
EXPR_NEST_MAX	_POSIX_PIPE_BUF	SCHAR_MAX
.B
INT_MAX	_POSIX_SAVED_IDS	SCHAR_MIN
.B
LINE_MAX	_POSIX_STREAM_MAX	SHRT_MIN
.B
LONG_MAX	_POSIX_TZNAME_MAX	SSIZE_MAX
.B
LONG_MIN	_POSIX_VERSION	STREAM_MAX
.B
MB_LEN_MAX	POSIX2_BC_BASE_MAX	TZNAME_MAX
.B
NGROUPS_MAX	POSIX2_BC_DIM_MAX	UCHAR_MAX
.B
NL_ARGMAX	POSIX2_BC_SCALE_MAX	UINT_MAX
.B
NL_LANGMAX	POSIX2_BC_STRING_MAX	ULONG_MAX
.B
NL_MAX	POSIX2_CHAR_TERM	USHRT_MAX
.B
NL_MSGMAX	POSIX2_COLL_WEIGHTS_MAX
.B
NL_SETMAX	POSIX2_C_BIND
.B
CHARCLASS_NAME_MAX	NL_TEXTMAX	_XOPEN_VERSION
.B
LONG_BIT	NZERO	_XOPEN_XCU_VERSION
.B
NL_ARGMAX	TMP_MAX	_XOPEN_XPG2
.B
NL_LANGMAX	WORD_BIT	_XOPEN_XPG3
.B
NL_MAX	_XOPEN_CRYPT	_XOPEN_XPG4
.B
NL_MSGMAX	_XOPEN_ENH_I18N	NL_SETMAX
.B
_XOPEN_SHM	ATEXIT_MAX	PAGESIZE
.B
_XOPEN_UNIX	IOV_MAX	PAGE_SIZE
.B
KERN_POINTERS	KERN_SIM
.fi
.SH EXIT STATUS
\f4getconf\fP exits with a status of greater than zero if any errors are 
encountered, otherwise it exits with status 0.
.SH "SEE ALSO"
\f4pathconf\fP(1), \f4sysconf\fP(3C), \f4pathconf\fP(2), \f4limits\fP(4)
