.TH GR_SN 1
.SH NAME
\f3gr_sn\f1 \- NUMA Memory Management Configuration Tool
.SH SYNOPSIS
.nf
gr_sn
.fi

.SH DESCRIPTION
Graphical version of \f3sn\f1(1);

Multiple nodes may be selected at once in order to set the same
system values in more than one node at a time.  Note that when
more than one node is selected, the values displayed are for the
first node selected.

.P
.SH RESTRICTIONS

Only the superuser or users with the MEMORY_MGT capability are
allowed to use this command to change numa parameters.
.SH SEE ALSO
\f3numa\f1(5),
\f3refcnt\f1(5),
\f3sn\f1(1),
\f3nstats\f1(1), 
\f3gr_nstats\f1(1).
