'\"macro stdmacro
.TH HEAD 1
.SH NAME
head \- give first few lines
.SH SYNOPSIS
.B head
[
.BR \- count
] [
file ...]
.br
.B head
[
.BR \-n
count ] [
file ...]
.SH DESCRIPTION
This filter gives the first
.I count\^
lines of each of the specified files, or of the standard input.
If
.I count\^
is omitted it defaults to
10.
.SH EXAMPLE
.IP
head -6 filea fileb filec
.PP
will print out the first six lines of the three specified files.
The filename will appear before each new set of head lines listed,
if more than one file has been specified.
.SH EXTENDED\ DESCRIPTION
X/Open CAE Specification(1994)--Commands and Utilities.
.SH SEE\ ALSO
tail(1).
'\".SH ORIGIN
'\"4th Berkeley Software Distribution
