'\"macro stdmacro
.if n .pH g1.line @(#)line	30.2 of 12/25/85
.nr X
.if \nX=0 .ds x} LINE 1 "User Environment Utilities" "\&"
.if \nX=1 .ds x} LINE 1 "User Environment Utilities"
.if \nX=2 .ds x} LINE 1 "" "\&"
.if \nX=3 .ds x} LINE "" "" "\&"
.TH \*(x}
.SH NAME
line \- read one line
.SH SYNOPSIS
.B line
.SH DESCRIPTION
.I line\^
copies one line (up to a new-line) from the standard
input and writes it on the standard output.
It
returns an exit code of 1 on
.SM
.B EOF
and always
prints at least a new-line.
It is often used within shell files to
read from the user's terminal.
.SH SEE ALSO
sh(1),
read(2)
.\"	@(#)line.1	6.2 of 9/2/83
.Ee
'\".so /pubs/tools/origin.att
