'\"macro stdmacro
.TH LIST_TAPE 1
.SH NAME
List_tape \- list the contents of a given backup tape
.SH SYNOPSIS
.B List_tape
[
.I \-v
] [
.I \-h hostname
] [
.I \-t tapedevice
]
.SH DESCRIPTION
The
.I List_tape\^
command lists the contents of a system backup tape made with
.IR Backup (1),
.IR cpio (1),
.IR tar (1),
or
.IR bru (1).
.PP
If a tape drive attached to a remote host is used,  the name of the
remote host needs to be specified with the
.B \-h hostname
option on the command line.  For remote listing to successfully work, the
user should have a TCP/IP network connection to the remote host and also
have "guest" rsh privileges on that host.
.PP
If the local or remote tape device is pointed to by a device file other
than
.B /dev/tape,
the device should be specified by the
.B \-t tapedevice
option.
The
.B \-v
option performs a verify pass, comparing the files in the backup with
the files in the filesystem.  This requires that either the files
have a full pathname in the archive (
.B Backup
uses relative pathnames), or that the label file be present, with the
directory in the last field on the 
.I label:
line, or that the
.B List_tape
command be used in the same directory where the backup was made.
.PP
The List_tape command only works with the formats mentioned above
and displays the extra info added by Backup(1) or the system backup
tool, if present.
.SH SEE ALSO
Backup(1), Restore(1), bru(1), cpio(1), tar(1).
