'\"macro stdmacro
.if n .pH g1.more @(#)more	40.17 of 5/29/91
.\" Copyright 1991 UNIX System Laboratories, Inc.
.\" Copyright 1989, 1990 AT&T
.nr X
.if \nX=0 .ds x} more 1 "Directory and File Management Utilities" "\&"
.if \nX=1 .ds x} more 1 "Directory and File Management Utilities"
.if \nX=2 .ds x} more 1 "" "\&"
.if \nX=3 .ds x} more "" "" "\&"
.TH \*(x}
.\" Copyright (c) 1988 Sun Microsystems, Inc. - All Rights Reserved.
.SH NAME
\f4more\f1, \f4page\f1 \- browse or page through a text file
.\" --------------------------------------------------------------------
.SH SYNOPSIS
\f4more\f1 [\f4\-ceisudfrN\f1] [\f4\-n \f2lines\f1] [\f4\-p \f2posn\f1]
[\f4\-t \f2tag\f1] [\f4\-x \f2tabs\f1]
.if n .ti +0.5i
[\f4+/\f2pattern\f1] [\f4\-\f2lines\f1]
[\f4+\f2linenumber\f1] [\f2file \f1...]
.br
\f4page\f1 [\f4\-ceisudfrN\f1] [\f4\-n \f2lines\f1] [\f4\-p \f2posn\f1]
[\f4\-t \f2tag\f1] [\f4\-x \f2tabs\f1]
.if n .ti +0.5i
[\f4+/\f2pattern\f1] [\f4\-\f2lines\f1]
[\f4+\f2linenumber\f1] [\f2file \f1...]
.\" --------------------------------------------------------------------
.SH DESCRIPTION
\f4more\f1
is a filter that displays the contents of a file
on the terminal, one screenful at a time.
After each screenful \f4more\f1 prints a prompt and pauses awaiting user
commands.
The prompt usually contains the name of the file and an indication
(percentage) of the current location within the file.
.PP
\f4more\f1
scrolls up to display one more line in response to a
.SM RETURN
character; it displays another screenful in response to a
.SM SPACE
character.
Other commands are listed below.
.PP
When used to move to a specific line (by line number or pattern search)
the target line is displayed as the third line from the top of
the display.
If it lies within the last screen then that final screen is displayed.
.PP
\f4page\f1
functions identically to \f4more\f1.
.PP
If the standard output is not a terminal,
\f4more\f1
acts just like
\f4cat\f1(1V).
.\" --------------------------------------------------------------------
.SH OPTIONS
The \f4more\f1 has the following options:
.\" --------------------------------------------------------------------
.TP 12n
\f4\-c\f1
Clear before displaying.
Redrawing the screen instead of scrolling
for faster displays.
This option is ignored if
the terminal does not have the ability to clear to the end of a line.
.\" --------------------------------------------------------------------
.TP
\f4\-d\f1
Display error messages rather than ringing the terminal bell if
an unrecognized command is used.
This is helpful for inexperienced users.
.\" --------------------------------------------------------------------
.TP
\f4\-e\f1
Exit immediately at the end of input.
By default \f4more\f1 waits at the end of the last screen.
.\" --------------------------------------------------------------------
.TP
\f4\-i\f1
Ignore case when performing pattern searches.
.\" --------------------------------------------------------------------
.TP
\f4\-f\f1
Do not fold long lines.
This is useful when lines contain
nonprinting characters or escape sequences, such as those generated
when
\f4nroff\f1(1)
output is piped through
\f4ul\f1(1).
.\" --------------------------------------------------------------------
.\" XXX .TP
.\" XXX \f4\-l\f1
.\" XXX Do not treat
.\" XXX .SM FORMFEED
.\" XXX characters (CTRL-d) as \(lqpage breaks.\(rq If
.\" XXX \f4\-l\f1
.\" XXX is not used,
.\" XXX \f4more\f1
.\" XXX pauses to accept commands after any line containing a
.\" XXX \f4^L\f1
.\" XXX character (CTRL-d).
.\" XXX Also, if a file begins with a
.\" XXX .SM FORMFEED\s0,
.\" XXX the screen is cleared before the file is printed.
.\" --------------------------------------------------------------------
.TP
\f4\-n \f2lines\f1
Use a screen of the indicated size rather than the default.
The lines displayed will be one less than this number.
.\" --------------------------------------------------------------------
.TP
\f4\-p \f2posn\f1
The \f2posn\f1 string is a positioning command which is executed at
the start of each input file.
Examples are line numbers and pattern searches.
.\" --------------------------------------------------------------------
.TP
\f4\-r\f1
Normally,
\f4more\f1
ignores control characters that it does not interpret in some way.
The
\f4\-r\f1
option causes these to be displayed as
\f4^\f2C\f1
where
.I C
stands for any such control character.
.\" --------------------------------------------------------------------
.TP
\f4\-s\f1
Squeeze.
Replace multiple blank lines with a single
blank line.
This is helpful when viewing
\f4nroff\f1(1)
output.
.\" --------------------------------------------------------------------
.TP
\f4\-t \f2tag\f1
Start output with the screen containing the specified tag.
.\" --------------------------------------------------------------------
.TP
\f4\-u\f1
Suppress generation of underlining escape sequences.
Normally, \f4more\f1
handles underlining, such as that produced by \f4nroff\f1(1),
in a manner appropriate to the terminal.
If the terminal can
perform underlining or has a stand-out mode,
\f4more\f1
supplies appropriate escape sequences.
.\" --------------------------------------------------------------------
.\" XXX .TP
.\" XXX \f4\-w\f1
.\" XXX Normally,
.\" XXX \f4more\f1
.\" XXX exits when it comes to the end of its input.
.\" XXX With
.\" XXX \f4\-w\f1,
.\" XXX however,
.\" XXX \f4more\f1 prompts and waits for any key to be struck before exiting.
.\" --------------------------------------------------------------------
.TP
\f4\-x \f2tabs\f1
Change the tabstop from 8 to \f2tabs\f1.
.\" --------------------------------------------------------------------
.TP
\f4\-N\f1
By default line numbers are remembered by \f4more\f1,
this option disables the line number facility which can
slow down access to very large files.
.\" --------------------------------------------------------------------
.TP
\f4+/\f2pattern\fP\f1
Start output two lines above the line containing the
regular expression \f2pattern\f1.
This pattern does
.I not
end with a
\f1`\f4/\f1';
a trailing slash is interpreted as a character in the
search pattern.
.\" --------------------------------------------------------------------
.TP
\f4\-\f2lines\f1
Display the indicated number of
.I lines
in each screenful (see \f4\-n \f2lines\f1).
.\" --------------------------------------------------------------------
.TP
\f4+\f2linenumber\fP\f1
Start output at
.IR linenumber .
.br
.\" --------------------------------------------------------------------
.ne 8
.SH USAGE
.SS Environment
.LP
\f4more\f1
uses the terminal's
\f4termcap\f1(5)
entry to determine its display characteristics.
Environment variables modify this behaviour which may be further altered
by command line options.
.\" --------------------------------------------------------------------
.TP .9i
\f4EDITOR\f1
Specify the editor command to invoke (see \f4v\f1 command), the
default is \f4vi\f1(1).
.\" --------------------------------------------------------------------
.TP
\f4COLUMNS\f1
Specify screen width.
.\" --------------------------------------------------------------------
.TP
\f4LINES\f1
Specify screen length (depth).
.\" --------------------------------------------------------------------
.TP
\f4MORE\f1
Specify preset command line options.
For instance, to page through files using
the
\f4\-c\f1
mode by default, set the value of this variable to
\f4\-c\f1.
When \f4more\f1 is invoked any command line options are processed
after those of the \f4MORE\f1 environment variable.
.br
.\" --------------------------------------------------------------------
.SS Commands
.LP
Single character commands take effect immediately;
\f4more\f1 does not expect a carriage return character.
Multi-character commands are echoed on the prompt line as they
are typed.
.\" XXX Up to the time when the command character itself is given,
.\" XXX the user may type the line kill character to cancel the numerical
.\" XXX argument being formed.
.LP
In the following commands,
.I i
is an optional numerical argument.
.\" --------------------------------------------------------------------
.TP 12n
\f4h\f1
Show command help information.
.\" --------------------------------------------------------------------
.TP
\f2i\f4f\f1
.PD 0
.TP
\f2i\f4^F\f1
.TP
\f2i\f1SPACE
.TP
\f2i\f4z\f1
.PD
Display next screenful, or \f2i\f1 lines.
.\" --------------------------------------------------------------------
.\" XXX .TP
.\" XXX \f2i\f4z\f1
.\" XXX Same as
.\" XXX .SM SPACE,
.\" XXX except that
.\" XXX \f2i\f4\| ,
.\" XXX if present, becomes the new default number
.\" XXX of lines per screenful.
.\" --------------------------------------------------------------------
.TP
\f2i\f4d\f1
.PD 0
.TP
\f2i\f4^D\f1
.PD
Display next half-screen, or \f2i\f1 lines.
If \f2i\f1 is specified it becomes the new half-screen scroll value.
.\" --------------------------------------------------------------------
.TP
\f2i\f4j\f1
.PD 0
.TP
\f2i\f1RETURN
.PD
Display next line, or \f2i\f1 lines.
.\" --------------------------------------------------------------------
.TP
\f2i\f4b\f1
.PD 0
.TP
\f2i\f4^B\f1
.PD
Display previous screenful, or \f2i\f1 lines.
.\" --------------------------------------------------------------------
.TP
\f2i\f4u\f1
.PD 0
.TP
\f2i\f4^U\f1
.PD
Display previous half-screen, or \f2i\f1 lines.
If \f2i\f1 is specified it becomes the new half-screen scroll value.
.\" --------------------------------------------------------------------
.TP
\f2i\f4j\f1
Display previous line, or \f2i\f1 lines.
.\" --------------------------------------------------------------------
.TP
\f2i\f4s\f1
Skip 1 line forward, or \f2i\f1 lines.
.\" --------------------------------------------------------------------
.TP
\f2i\f4g\f1
Skip to the beginning of the file, or \f2i\f1th line.
.\" --------------------------------------------------------------------
.TP
\f2i\f4G\f1
Skip to the end of the file, or \f2i\f1th line.
.\" --------------------------------------------------------------------
.TP
\f2i\f4%\f1
.PD 0
.TP
\f2i\f4p\f1
.PD
Skip to beginning of the file, or \f2i\f1 per cent into the file.
This command does not work when reading from a pipeline.
.\" --------------------------------------------------------------------
.TP
\f4r\f1
.PD 0
.TP
\f4^L\f1
.PD
Refresh the screen.
.\" --------------------------------------------------------------------
.TP
\f4R\f1
Refresh the screen and flush buffered input if reading from
a pipeline.
.\" --------------------------------------------------------------------
.TP
\f4m\f2letter\f1
Attach a mark, named as \f2letter\f1 (lower case letter), to the
current line in the file.
.\" --------------------------------------------------------------------
.TP
\f4\'\f2letter\f1
Return to the mark named by \f2letter\f1.
.\" --------------------------------------------------------------------
.TP
\f4\'\'\f1
Return to the place in the file at which the last positioning
command was issued.
.\" --------------------------------------------------------------------
.TP
\f4=\f1
.PD 0
.TP
\f4^G\f1
.TP
\f4:f\f1
.PD
Display details of the current location in the file.
.\" --------------------------------------------------------------------
.TP
\f2i\f4/\f2pattern\f1
Search forward for the next (or \f2i\f1th)
occurrence of the regular expression \f2pattern\f1.
Display the screenful starting two lines before the line
that contains the
match for the regular expression \f2pattern\f1.
The previous search \f2pattern\f1 is used if the current command omits it.
If \f2pattern\f1 is prefixed with a \f2!\f1 (exclamation mark)
then the search is negated, that is, it locates lines which
do not match \f2pattern\f1.
.\" --------------------------------------------------------------------
.TP
\f2i\f4?\f2pattern\f1
As for \f2i\f4/\f2pattern\f1 but the search starts toward the start
of the file (backwards).
.\" --------------------------------------------------------------------
.TP
\f2i\f4n\f1
Repeat the last search command.
.\" --------------------------------------------------------------------
.TP
\f2i\f4N\f1
Repeat the last search but reverse the direction.
.\" --------------------------------------------------------------------
.\" XXX .TP
.\" XXX \f4\'\f1
.\" XXX Single quote.
.\" XXX Go to the point from which the last search started.
.\" XXX If no search has been performed in the current file,
.\" XXX go to the beginning of the file.
.\" --------------------------------------------------------------------
.TP
\f4:e\f2filename\f1
.PD 0
.TP
\f4E\f2filename\f1
.PD
Display new file.
If \f2filename\f1 is omitted \f2more\f1 returns to the original file.
A \f2filename\f1 of \f4#\f1 is requested \f2more\f1 returns to the
previously displayed file.
.\" --------------------------------------------------------------------
.TP
\f2i\f4:n\f1
Display the next (or \f2i\f1th next)
filename given on the command line.
.\" --------------------------------------------------------------------
.TP
\f2i\f4:p\f1
.PD 0
.TP
\f2i\f4P\f1
.PD
Display the previous (or \f2i\f1th previous)
filename given on the command line.
.\" --------------------------------------------------------------------
.TP
\f4:a\f1
List the filenames given on the command line.
.\" --------------------------------------------------------------------
.TP
\f2i\f4:t\f2tag\f1
Display the file and line named by \f2tag\f1.
.\" --------------------------------------------------------------------
.TP
\f4v\f1
Start the editor indicated by the \f4EDITOR\f1 environment variable
with current file.
If the editor is \f4ex\f1(1) or \f4vi\f1(1) editing will start at
the current line.
The default editor is \f4vi\f1(1).
Exiting the editor resumes \f4more\f1.
.\" --------------------------------------------------------------------
.TP
\f4!\f2command\f1
Invoke a shell to execute
.IR command\| .
The characters
\f4%\f1
and
\f4!\f1,
when used within
.I command
are replaced with the current filename
and the previous shell command,
respectively.
If there is no current filename,
\f4%\f1
is not expanded.
Prepend a backslash to these characters to
escape expansion.
.\" --------------------------------------------------------------------
.TP
\f4\&.\f1
Repeat the previous command.
.\" --------------------------------------------------------------------
.TP
\f4q\f1
.PD 0
.TP
\f4Q\f1
.TP
\f4:q\f1
.TP
\f4:Q\f1
.TP
\f4ZZ\f1
.PD
Exit from \f4more\f1.
.\" --------------------------------------------------------------------
.\" XXX .TP
.\" XXX \f4\s+3^\s0\|\e\f1
.\" XXX Halt a partial display of text.
.\" XXX \f4more\f1
.\" XXX stops sending output, and displays the usual
.\" XXX \f4--More--\f1
.\" XXX prompt.
.\" XXX Unfortunately, some output is lost as a result.
.\" XXX .sp -.5
.\" --------------------------------------------------------------------
.SH FILES
.PD 0
.\" --------------------------------------------------------------------
.TP 10P
\f4/usr/share/lib/termcap\f1
terminal data base
.\" --------------------------------------------------------------------
.TP
\f4/usr/lib/more.help\f1
help file
.PD
.sp -.5
.\" --------------------------------------------------------------------
.SH "SEE ALSO"
\f4cat\fP(1),
\f4ctags\fP(1),
\f4man\fP(1),
\f4sh\fP(1),
\f4vi\fP(1),
\f4environ\fP(5V),
\f4termcap\fP(5)
.br
.\" --------------------------------------------------------------------
.SH NOTES
A few old IRIX features do not exist in the current
XPG4 version.
.PP
The -l and -w options have been dropped (incompatible with XPG4).
.PP
The v edit command defaults to vi(1) and not ed(1).
.br
The z command does not change the size of the screen if given a count.
.br
The single-quote command clashes with XPG4 commands which replace it.
.PP
If stderr is not readable more will exit with an error message; it
will not try to use /dev/tty instead.
.br
Headers are no longer printed when stdout is not a tty.
.br
There is no overlap between forward or backward paging.
.br
The CTRL-\\ sequence does not interrupt processing.
