.TH noderun 1
.SH NAME
\f3noderun\f1 \- Run process on specific node (advisory specification)
.SH SYNOPSIS
.nf
noderun \f2node-path\f1 \f2command\f1
.fi

.SH DESCRIPTION
Run a process on a specific SN0 node. The request is advisory. 
To specify mandatory placement, use \f3runon\f1(1) or \f3dplace\f1(1).

.P
.SH EXAMPLE

To run \f3ls\f1(1) on a specific node:
.nf.
   $ noderun /hw/module/1/slot/n2/node ls 
.fi
To run a.out with several arguments:
.nf
   $ noderun /hw/module/1/slot/n1/node a.out a b c
.fi

.P
.SH COMMENTS

Noderun is implemented as a \f3sh\f1(1) script using \f3dplace\f1(1) as
follows:
.nf

if ! test -f /usr/sbin/dplace
then
echo "Cannot find /usr/sbin/dplace -- please install"
exit 1
fi

if test $# -lt 2 
then
echo "Usage: $0 <node-name> command"
exit 1
fi

if ! test -d $1
then
echo "Usage: $0 <node-name> command"
echo "The node can only be one of the following:"
find /hw -name node -print
exit 1
fi

TMP=/usr/tmp/ndrun$$
echo "memories 1 topology physical near $1" > $TMP
echo "threads 1" >> $TMP
echo "run thread 0 on memory 0" >> $TMP

shift
/usr/sbin/dplace -migration 0 -place $TMP $@

rm -f $TMP
exit 0	
.fi


.SH SEE ALSO

\f3dplace\f1(1), 
The Memory Management Control Interface User's Manual (Books).

