.TH NUMA_VIEW 1
.SH NAME
\f3numa_view\f1 \- a tool for showing NUMA placement information
.SH SYNOPSIS
.nf
numa_view [\f3-l\f1] [\f3-a\f1] \f3pid\f1 
.fi

.SH DESCRIPTION
This command retrieves the current NUMA placement strategies
for the process specified by \f3pid\f1. Information displayed
includes current placement policies, MLDSETs and MLDs.
.SH OPTIONS
.TP
\f3-l\f1
Show information about non-executable mapped memory.
.TP
\f3-a\f1
Show information about all mapped memory.
.SH SEE ALSO
.IR dlook(1),
.IR mmci(5)
