'\"macro stdmacro
.if n .pH g2.pathconf @(#)pathconf	30.2 of 12/25/85
.TH PATHCONF 1
.SH NAME
pathconf \- get configurable pathname variables (POSIX)
.SH SYNOPSIS
.nf
.PP
.B "pathconf [-p path][name...]"
.fi
.SH DESCRIPTION
.I pathconf\^
provides a shell interface to the \f4pathconf\fP(2) system call for
determining the current
value of a configurable limit or option (\f2variable\fP) that is associated
with a file or directory.
.PP
The
.I name
argument represents the variable to be queried.
The list of supported variables can be obtained by invoking \f4pathconf\fP
without any arguments.
By default, the values pertain to the root file system (``/''),
to query the values of a different file or directory, use the \f4\-p\fP option.
.PP
When invoked with a
.I name
argument,
.I pathconf
displays the system value of each of the requested variables,
one per line.  Otherwise, it displays the entire set
with accompanying labels.
A printed value of \-1 means that there is no limit for \f2name\fP for the
given \f2path\fP.
If an error is encountered from \f4pathconf\fP(2),
the system error message is printed in place of
the value.
.P
\f4pathconf\fP exits with a status of 1 if any errors are encountered,
otherwise it exits with status 0.
.SH "SEE ALSO"
sysconf(1), pathconf(2), sysconf(2), limits(4)
