'\"macro stdmacro
.\" $Id: pmdate.1,v 1.1 1999/04/28 10:06:17 kenmcd Exp $
.nr X
.if \nX=0 .ds x} PMDATE 1 "Performance Co-Pilot" "\&"
.if \nX=1 .ds x} PMDATE 1 "Performance Co-Pilot"
.if \nX=2 .ds x} PMDATE 1 "" "\&"
.if \nX=3 .ds x} PMDATE "" "" "\&"
.TH \*(x}
.SH NAME
\f3pmdate\f1 \- display an offset date
.\" literals use .B or \f3
.\" arguments use .I or \f2
.SH SYNOPSIS
.B pmdate
[ \fIoffset\fR ... ]
.I format
.SH DESCRIPTION
.B pmdate
displays the current date and/or time, with an optional offset.
.PP
An
.I offset
is specified with a leading sign (``+'' or ``-''), followed by an
integer value, followed by one of the following ``scale'' specifiers;
.IP S
seconds
.PD 0
.IP M
minutes
.IP H
hours
.IP d
days
.IP m
months
.IP y
years
.PD
.PP
The output
.I format
follows the same rules as for
.BR date (1)
and
.BR strftime (3).
.PP
For example, the following will display the date a week ago as DDMMYYYY;
.in+8n
.ftCW
pmdate -7d %d%m%Y
.ftR
.in-8n
.SH SEE ALSO
.BR date (1)
and
.BR strftime (3).
