'\"macro stdmacro
.\" $Id: pmdbg.1,v 1.2 1999/05/28 03:45:16 kenmcd Exp $
.nr X
.if \nX=0 .ds x} PMDBG 1 "Performance Co-Pilot" "\&"
.if \nX=1 .ds x} PMDBG 1 "Performance Co-Pilot"
.if \nX=2 .ds x} PMDBG 1 "" "\&"
.if \nX=3 .ds x} PMDBG "" "" "\&"
.TH \*(x}
.SH NAME
\f3pmdbg\f1 \- translate Performance Co-Pilot debug control flags
.\" literals use .B or \f3
.\" arguments use .I or \f2
.SH SYNOPSIS
\f3pmdbg\f1
\f2code\f1 ...
.br
\f3pmdbg\f1
\f3\-l\f1
.SH DESCRIPTION
The components of the Performance Co-Pilot (PCP) use
a global vector of bit-fields
to control diagnostic and debug output.
.PP
.B pmdbg
with a
.B \-l
argument prints out the mnemonic and decimal values of all
the bit-fields in the debug control vector.
.PP
In the alternative usage, the
.I code
arguments are values for the debug vector, and the bit-fields that
are enabled by each of these values is listed.
.PP
Each
.I code
may be an integer, a hexadecimal value or a hexadecimal value prefixed
by either ``0x'' or ``0X''.
.PP
Most applications using the facilities of the PCP support
a
.BI \-D N
command-line syntax to enable debug control.
.B pmdbg
is designed to help choose an appropriate value for
.IR N .
.SH SEE ALSO
.BR PCPIntro (1).
