'\"macro stdmacro
.nr X
.if \nX=0 .ds x} PMLOGCONF 1 "Performance Co-Pilot" "\&"
.if \nX=1 .ds x} PMLOGCONF 1 "Performance Co-Pilot"
.if \nX=2 .ds x} PMLOGCONF 1 "" "\&"
.if \nX=3 .ds x} PMLOGCONF "" "" "\&"
.TH \*(x}
.SH NAME
\f3pmlogconf\f1 \- create/edit a pmlogger configuration file
.SH SYNOPSIS
\f3/usr/pcp/bin/pmlogconf\f1
\f2configfile\f1
.SH DESCRIPTION
.B pmlogconf
may be used to create and modify a generic configuration file for
the PCP archive logger,
.BR pmlogger (1).
.PP
.I configfile
may be used with the
.B \-c
option to
.BR pmlogger (1)
to select performance metrics and specify
logging frequencies for a PCP archive.
.PP
If
.I configfile
does not exist,
.B pmlogconf
will create a generic configuration file with the
default set of enabled metrics and logging frequencies.
.PP
If
.I configfile
does exist,
.B pmlogconf
will prompt for input from the user to enable or disable groups
of related performance metrics, and to control the logging frequency
for each enabled group.
.PP
Group selection requires a simple
.B y
(yes)
or
.B n
(no) response to the prompt
.BR "Log this group?" .
.PP
Logging frequency is specified by responding to the
.B "Logging interval?"
prompt with the keywords
.B once
or
.B default
or a valid
.BR pmlogger (1)
interval specification of the form ``\c
.B every
.IR "N timeunits" ''
or simply ``\c
.IR "N timeunits" '',
where
.B every
is optional,
.I N
is an unsigned integer, and
.I timeunits
is one of the keywords
.BR msec ,
.BR millisecond ,
.BR sec ,
.BR second ,
.BR min ,
.BR minute ,
.BR hour
or the plural form of one of the above.
.SH SEE ALSO
.BR pmlogger (1).
