'\"macro stdmacro
.\" $Id: pmpost.1,v 1.2 1997/09/25 08:11:52 markgw Exp $
.nr X
.if \nX=0 .ds x} PMPOST 1 "Performance Co-Pilot" "\&"
.if \nX=1 .ds x} PMPOST 1 "Performance Co-Pilot"
.if \nX=2 .ds x} PMPOST 1 "" "\&"
.if \nX=3 .ds x} PMPOST "" "" "\&"
.TH \*(x}
.SH NAME
\f3pmpost\f1 \- append messages to the Performance Co-Pilot notice board
.\" literals use .B or \f3
.\" arguments use .I or \f2
.SH SYNOPSIS
.B /usr/pcp/bin/pmpost
.I message
.SH DESCRIPTION
.B pmpost
will append the text
.I message
to the end of the
Performance Co-Pilot (PCP) notice board file (\c
.IR /var/adm/pcplog/NOTICES )
in an atomic manner that guards against corruption of
the notice board file
by concurrent invocations of
.BR pmpost .
.PP
The PCP notice board is intended to be a persistent store
and clearing house for important messages relating to the
operation of the PCP and the notification of performance
alerts from
.BR pmie (1)
when other notification options are either unavailable or
unsuitable.
.PP
Before being written, messages are prefixed by the current
time, and when the current day is different to the last
time the notice board file was written,
.B pmpost
will prepend the message with the full date.
.PP
If the notice board file does not exist,
.B pmpost
will create it.
Due to the importance of the notice board file,
.B pmpost
is typically installed as a
.BR setuid (2)
root program and so the
notice board is owned by, and writable only by, root.
.SH FILES
.TP 24
.I /var/adm/pcplog/NOTICES
the PCP notice board file
.SH SEE ALSO
.BR logger (1),
.BR pmie (1)
and
.BR setuid (2).
