'\"! mmdoc
'\"macro stdmacro
.tr ~"
.if t .ds i \(fm\(fm
.if n .ds i ""
.TH PRIOINFO 1
.SH NAME
prioinfo \- print priority IO allocation information.
.SH SYNOPSIS
.B prioinfo
.SH DESCRIPTION
.I prioinfo
prints out the priority IO allocation table of the system. Each entry
represents an allocation, with a blank line in between entries.
Within each entry, the first
row is the bandwidth allocation handle, the process id of the process which 
owns the allocation, followed by the bandwidth in bytes/second. 
The second row is the source name, the third row is the sink
name.
.SH NOTES
.PP
In IRIX 6.5, Priority I/O has been merged with GRIO. As
a result, the use of the Priority I/O APIs is deprecated. Please refer
to grio(5) for further details.
.SH SEE ALSO
prio(5), 
prio(3x)
