'\"macro stdmacro
.TH ProclaimRelayMgr 1M "29 Jan 1996"
.UC 5
.SH NAME
ProclaimRelayMgr \- graphical interface for the proclaim relay-agent
.SH SYNOPSIS
\fB/usr/sbin/ProclaimRelayMgr\fR 
.SH DESCRIPTION
.I ProclaimRelayMgr
is a graphical front end that displays the status and configuration
of the \fIproclaim\fR relay-agent running on the local host.
It also displays the set of \fIproclaim\fR servers
to which requests are forwarded.
Proclaim is an implementation of DHCP (dynamic host configuration protocol).
.P
The main window allows you to add and delete
addresses and names of \fIproclaim\fR servers.
You can enable or disable the relay-agent
by clicking the \fBRelay On/Off\fR button in the main window. 
.P
The \fBFile\fR button opens a pull-down menu for saving
the options and server addresses displayed in the main window
to a file (using the \fBSave\fR button).
To view messages logged by the relay-agent in the system log file
(\fI/var/adm/SYSLOG\fR), launch \fIsysmon(1M)\fR from the pull-down menu
by choosing the \fBSystem Log Viewer\fR item.
.P
For more details about the relay-agent, see \fIdhcp_relay(1M)\fR.
.SH FILES
.nf
/etc/config/dhcp_relay.options
/var/adm/SYSLOG
/var/dhcp/config/dhcp_relay.servers
.fi
.SH "SEE ALSO"
chkconfig(1M), dhcp_bootp(1M), dhcp_relay(1M), proclaim(1M),
ProclaimServerMgr(1M), syslogd(1M)
