'\"macro stdmacro
.if n .pH g1.pwd @(#)pwd	41.7 of 5/26/91
.\" Copyright 1991 UNIX System Laboratories, Inc.
.\" Copyright 1989, 1990 AT&T
.nr X
.if \nX=0 .ds x} pwd 1 "Essential Utilities" "\&"
.if \nX=1 .ds x} pwd 1 "Essential Utilities"
.if \nX=2 .ds x} pwd 1 "" "\&"
.if \nX=3 .ds x} pwd "" "" "\&"
.TH \*(x}
.SH NAME
\f4pwd\f1 \- print working directory name
.SH SYNOPSIS
\f4pwd\f1
.sp
\f4/usr/bin/pwd\f1
.SH DESCRIPTION
\f4pwd\fP
prints the path name of the working (current) directory.
.I pwd
is both an explicit command (invoked as
.IR /usr/bin/pwd ),
as well as a builtin command to each shell (invoked as
.IR pwd ).

.SH FILES
.TP
\f4/usr/lib/locale/\f2locale\f4/LC_MESSAGES/uxcore.abi\f1
language-specific message file [See \f4LANG\fP on \f4environ\f1(5).]
.SH "SEE ALSO"
\f4cd\fP(1), \f4csh\fp(1), \f4sh\fp(1), \f4getcwd\fp(3C)
.SH DIAGNOSTICS
\f4UX:pwd:ERROR: cannot open ...
.br
\f4UX:pwd:ERROR: read error in ...\f1
.sp .5
indicate possible file system trouble and should be
referred to a UNIX system administrator.
.SH NOTES
If you move the current directory or one above it, 
\f4pwd\^\f1
may not give the correct response.
Use the \f4cd\f1(1)
command with a full path name
to correct this situation.
.\"	@(#)pwd.1	6.2 of 9/2/83
.Ee
