'\"macro stdmacro
.if n .pH g1.rmdel @(#)rmdel	30.3 of 2/1/86
.nr X
.if \nX=0 .ds x} RMDEL 1 "Source Code Control System Utilities" "\&"
.if \nX=1 .ds x} RMDEL 1 "Source Code Control System Utilities"
.if \nX=2 .ds x} RMDEL 1 "" "\&"
.if \nX=3 .ds x} RMDEL "" "" "\&"
.TH \*(x}
.SH NAME
rmdel \- remove a delta from an \s-1SCCS\s+1 file
.SH SYNOPSIS
.B rmdel
.if n .ul
\f3\-r\f1\c
.if n .ul 0
\s-1SID\s0
files
.SH DESCRIPTION
.I rmdel\^
removes the delta specified by the
.SM \f2SID\fP
from each
named \s-1SCCS\s+1 file.
The delta to be removed must be the newest (most recent) delta
in its branch in the delta chain of each
named \s-1SCCS\s+1 file.
In addition,
the \*(I) specified must
.I not\^
be that of a version being edited for the purpose of
making a delta (i. e.,
if a
.I p-file\^
[see
.IR get (1)]
exists for the named \s-1SCCS\s+1 file,
the \*(I) specified must
.I not\^
appear in any entry of the
.I p-file\c\^
).
.PP
The
.B \-r
option is used for
specifying the
.I SID
(\f3S\f1CCS \f3ID\f1entification)
level of the delta to be removed.
.PP
If a directory is named,
.I rmdel\^
behaves as though each file in the directory were
specified as a named file,
except that non-\s-1SCCS\s+1 files
(last component of the path name does not begin with \f3s.\f1)
and unreadable files
are silently ignored.
If a name of \f3\-\f1 is given, the standard input is read;
each line of the standard input is taken to be the name of an \s-1SCCS\s+1 file
to be processed;
non-\s-1SCCS\s+1 files and unreadable files are silently ignored.
.PP
Simply stated,
they are either (1)
if you make a delta you can remove it;
or (2)
if you own the file and directory you can remove a delta.
.SH FILES
.PD 0
.TP 10
x.file
[see
.IR delta (1)]
.TP 10
z.file
[see
.IR delta (1)]
.PD
.SH "SEE ALSO"
delta(1),
get(1),
help(1),
prs(1),
sccsfile(4)
.SH DIAGNOSTICS
Use
.IR help (1)
for explanations.
.\"	@(#)rmdel.1	6.2 of 9/2/83
.Ee
'\".so /pubs/tools/origin.att
