.TH showapi 1
.SH NAME
showapi \- show name space for various APIs
.SH SYNOPSIS
\f3showapi\f1
[\f3-D\f1xx\f3=\f1yy]
[\f3-l c\f1|\f3c++\f1|\f3a\f1]
[\f3-c\f1]
[\f3-m o32\f1|\f332\f1|\f3n32\f1|\f364\f1]
\f2api\f1
\f2file\f1
.SH DESCRIPTION
\f3showapi\fP
shows what \f2file\fP would look like if it was interpreted with the specified
\f2api\fP.
This is especially useful to check out header files that must conform
to the strict name space rules imposed by standards such as \f4POSIX\fP
and \f4XPG4\fP.
To get a list of currently supported \f2api\f1s, invoke the commands
usage message by issuing: \f3showapi -?\fP.
\f3showapi\fP can operate in two main modes - one uses \f3unifdef\fP(1),
the other uses \f3cc -E\fP.
Each has benefits, and neither alone is sufficient.
\f3unifdef\fP shows data declarations, macros, function declarations, etc.,
however it doesn't
follow any \f3#include\fP statements that might be in the file.
When \f3showapi\fP uses \f3cc\fP, \f3#include\fP statements are followed,
however no macros or other pre-processor definitions are shown.
.PP
The following options are understood:
.TP 10
\f3-c\fP
Use the "C" pre-processor to handle the file. This is done by
invoking the \f3cc\fP command with the \f3-E\fP option.
.TP
\f3-D\fP
Add additional macro definitions.
.TP
\f3-l\fP
Specifies which language is assumed - the default is "C".
\f3a\fP stands for assembler.
.TP
\f3-m\fP
Specifies an ABI.
.SH "SEE ALSO"
\f3unifdef\f1(1).
