'\"macro stdmacro
.if n .pH g1.sleep @(#)sleep	41.7 of 5/26/91
.\" Copyright 1991 UNIX System Laboratories, Inc.
.\" Copyright 1989, 1990 AT&T
.nr X
.if \nX=0 .ds x} sleep 1 "Essential Utilities" "\&"
.if \nX=1 .ds x} sleep 1 "Essential Utilities"
.if \nX=2 .ds x} sleep 1 "" "\&"
.if \nX=3 .ds x} sleep "" "" "\&"
.TH \*(x}
.SH NAME
\f4sleep\f1 \- suspend execution for an interval
.SH SYNOPSIS
\f4sleep\f1
\f2time\f1
.SH DESCRIPTION
\f4sleep\fP
suspends execution for
.I time\^
seconds.
It is used to execute a command
after a certain amount of time, as in:
.PP
	(\f4sleep 105; \f2command\fP\^)&\f1
.PP
or to execute a command every so often, as in:
.PP
	\f4while true
.br
	do
.br
		\f2command\fP
.br
		sleep 37
.br
	done\f1
.SH FILES
.TP
\f4/usr/lib/locale/\f2locale\f4/LC_MESSAGES/uxcore.abi\f1
language-specific message file (see \f4LANG\fP on \f4environ\f1(5))
.SH "SEE ALSO"
\f4alarm\fP(2), \f4sleep\fP(3C)
.\"	@(#)sleep.1	6.2 of 9/2/83
.Ee
