'\"macro stdmacro
.if n .pH g2.sysconf @(#)sysconf	30.2 of 12/25/85
.TH SYSCONF 1
.SH NAME
sysconf \- get configurable system variables (POSIX)
.SH SYNOPSIS
.nf
.PP
.B sysconf [name...]
.fi
.SH DESCRIPTION
.B sysconf\^
provides a method to determine the current
values of certain configurable system limits, options and parameters.
.PP
If the optional
.I name
argument or list is given, \f4sysconf\fP(1) will print the value of
each requested system parameter, one per line.
If
.I name
is not supplied, \f4sysconf\fP(1) will print all known values
with accompanying parameter names.
In some cases the value will be 1 or \-1, indicating that the system
does (1) or does not (\-1) implement that particular feature.
Refer to the manual entry for \f4sysconf\fP(3C) for information
about the meaning of the individual parameters.
.P
\f4sysconf\fP exits with a status of 1 if any errors are encountered,
otherwise it exits with status 0.
.SH "SEE ALSO"
\f4pathconf\fP(1), \f4sysconf\fP(3C), \f4pathconf\fP(2), \f4limits\fP(4)
