'\"macro stdmacro
.if n .pH g1.tee @(#)tee	41.8 of 5/26/91
.\" Copyright 1991 UNIX System Laboratories, Inc.
.\" Copyright 1989, 1990 AT&T
.nr X
.if \nX=0 .ds x} tee 1 "Essential Utilities" "\&"
.if \nX=1 .ds x} tee 1 "Essential Utilities"
.if \nX=2 .ds x} tee 1 "" "\&"
.if \nX=3 .ds x} tee "" "" "\&"
.TH \*(x}
.SH NAME
\f4tee\f1 \- pipe fitting
.SH SYNOPSIS
\f4tee\f1 [\f4-i\f1] [\f4-a\f1] [\f2file\fP] . . .
.SH DESCRIPTION
\f4tee\fP
transcribes the standard input to the standard
output and makes copies in the 
.IR files .
The sole purpose of 
\f4tee\fP
is to serve, as its name implies, as a ``T'' in a pipe.  For example, the
command
.P
.RS
\f4grep\f2 pattern file1\f4 | tee\f2 file2\f4 | wc -l\f1
.RE
.P
catches the output of \f4grep\fP in \f2file2\fP without having to reexecute
the command.
.PP
The available options are:
.TP
\f4\-i\f1
ignore interrupts;
.TP
\f4\-a\f1
causes the output to be appended to the
.I files\^
rather than overwriting them.
.SH FILES
.TP
\f4/usr/lib/locale/\f2locale\f4/LC_MESSAGES/uxcore.abi\f1
language-specific message file [See \f4LANG\fP on \f4environ\f1 (5).]
.\"	@(#)tee.1	6.2 of 9/2/83
.Ee
