'\"macro stdmacro
.if n .pH g1.hash @(#)hash      30.2 of 12/25/85
.nr X
.if \nX=0 .ds x} hash 1 "Essential Utilities" "\&"
.if \nX=1 .ds x} hash 1 "Essential Utilities"
.if \nX=2 .ds x} hash 1 "" "\&"
.if \nX=3 .ds x} hash "" "" "\&"
.ds OK [\|
.ds CK \|]
.TH \*(x}
.SH NAME
\f3unalias\f1 - remove alias definitions
.SH SYNOPSIS
.nf
unalias alias-name...

unalias -a
.fi
.SH DESCRIPTION
The \f3unalias\f1 utility removes the definition for each alias name
specified. The aliases are removed from the
current shell execution environment.
.SH OPTIONS
The \f3unalias\f1 utility supports the XBD specification, Utility Syntax
Guidelines.
.PP
The following option is supported:
.TP 4
\f3-a\f1
Remove all alias definitions from the current shell execution
environment.
.SH OPERANDS
The following operand is supported:
.TP 12
\f3alias-name\f1
The name of an alias to be removed.
.SH EXIT STATUS
The following exit values are returned:
.TP 4
0
Successful completion.
.TP 4
>0
One of the alias-name operands specified did not represent a valid
alias definition, or an error occurred.
.SH APPLICATION USAGE
Since \f3unalias\f1 affects the current shell execution environment, it is
generally provided as a shell regular built-in.
.SH SEE ALSO
\f3sh(1), alias(1).\f1
