'\"macro stdmacro
.if n .pH g1.val @(#)val	30.3 of 2/3/86
.nr X
.if \nX=0 .ds x} VAL 1 "Source Code Control System Utilities" "\&"
.if \nX=1 .ds x} VAL 1 "Source Code Control System Utilities"
.if \nX=2 .ds x} VAL 1 "" "\&"
.if \nX=3 .ds x} VAL "" "" "\&"
.TH \*(x}
.SH NAME
val \- validate \s-1SCCS\s0 file
.SH SYNOPSIS
\f3val \-\f1
.br
.B val
[\f3\-s\f1]
[\f3\-r \f1\s-1SID\s0]
[\f3\-m \f1name]
[\f3\-y \f1type]
files
.SH DESCRIPTION
.I val\^
determines if the specified
.I file\^
is an \s-1SCCS\s0 file meeting the characteristics specified by the optional
argument list.
Arguments to
.I val\^
may appear in any order.
The arguments consist of keyletter arguments, which begin with a \f3\-\f1, and
named files.
.PP
.I val\^
has a special argument, \f3\-\f1, which causes reading of the standard input
until an end-of-file condition is detected.
Each line read is independently processed as if it were a command line argument
list.
.PP
.I val\^
generates diagnostic messages on the standard output for each command line
and file processed, and also returns a single 8\f3-\f1bit code upon exit as
described below.
.PP
The keyletter arguments are defined as follows.
The effects of any keyletter argument apply independently to each named file
on the command line.
.TP 12
\f3\-s\f1
The presence of this argument silences the diagnostic message normally
generated on the standard output for any error that is detected while processing each named file on
a given command line.
.TP 12 
\f3\-r\f1\f2SID\f1 
The argument value
\f2SID\f1
.RI ( S \s-1CCS\s+1 " ID" entification
String) is an \s-1SCCS\s0 delta number.
A check is made to determine if the
\f2SID\f1
is ambiguous (e. g.,
.B \*-r\c
1 is ambiguous because it physically does not exist but implies 1.1, 1.2,
etc., which may exist) or invalid (e. g.,
.B \*-r\c
1.0 or
.B \*-r\c
1.1.0 are invalid because neither case can exist as a valid delta number).
If the
\f2SID\f1
is valid and not ambiguous, a check is made
to determine if it actually exists.
.TP 12 
\f3\-m\f1name 
The argument value
.I name\^
is compared with the \ s-1SCCS\s0 %\&M% keyword in
.IR file .
.TP 12 
\f3\-y\f1type 
The argument value
.I type\^
is compared with the \s-1SCCS\s0 %\&Y% keyword in
.IR file .
.RE
.PP
The 8\f3-\f1bit code returned by
.I val\^
is a disjunction of the possible errors, i.\ e., can be interpreted as
a bit string where (moving from left to right) set bits are interpreted as follows:
.nf
.PP
.RS
bit 0 = missing file argument;
bit 1 = unknown or duplicate keyletter argument;
bit 2 = corrupted \s-1SCCS\s0 file;
bit 3 = cannot open file or file not \s-1SCCS\s0;
bit 4 = \f2SID\f1 is invalid or ambiguous;
bit 5 = \f2SID\f1 does not exist;
bit 6 = %\&Y%, \f3\-y\f1 mismatch;
bit 7 = %\&M%, \f3\-m\f1 mismatch;
.RE
.fi
.PP
Note that
.I val\^
can process two or more files on a given command line and in turn can
process multiple command lines (when reading the standard input).
In these cases an aggregate code is returned \- a logical \f3\s-1OR\s0\f1 of the
codes generated for each command line and file processed.
.SH "SEE ALSO"
admin(1),
delta(1),
get(1),
help(1),
prs(1)
.SH DIAGNOSTICS
Use
.IR help (1)
for explanations.
.SH BUGS
.I val\^
can process up to 50 files on a single command line.
Any number above 50 will produce a
.B core
dump.
.\"	@(#)val.1	6.2 of 9/2/83
.Ee
'\".so /pubs/tools/origin.att
