'\"macro stdmacro
.if n .pH g1.wall @(#)wall	30.2 of 12/25/85
.nr X
.if \nX=0 .ds x} WALL 1 "Essential Utilities" "\&"
.if \nX=1 .ds x} WALL 1 "Essential Utilities"
.if \nX=2 .ds x} WALL 1 "" "\&"
.if \nX=3 .ds x} WALL "" "" "\&"
.TH \*(x}
.SH NAME
wall \- write to all users
.SH SYNOPSIS
.B /sbin/wall [-g group] [msg_file]
.SH DESCRIPTION
.I wall\^
reads
.I msg_file
(or its standard input if none specified) until an end-of-file.
It then sends this message to all currently
logged-in users preceded by:
.PP
.RS
Broadcast Message from \f3.\|.\|.\fP
.RE
.PP
If the
.I -g
option is used then only those users in the specified group
as defined in the file
.BR /etc/group
or the NIS
.I group
map are sent the
message.
The list of logged-on users is derived from the file
.BR /var/adm/utmp .
.PP
It is used to warn all users,
typically prior to shutting down the system.
.PP
The sender must be super-user to override
any protections the users may have invoked
(see
.IR mesg (1)).
.SH NOTE
.I wall\^
does not send messages to \f2ftp\f1 users.
.SH FILES
/dev/\(**
.br
/var/adm/utmp
.SH "SEE ALSO"
mesg(1), write(1), who(1).
.SH DIAGNOSTICS
``Cannot send to ...'' when the open on
a user's tty file fails.
.\"	@(#)wall.1m	6.2 of 9/2/83
.Ee
'\".so /pubs/tools/origin.att
