'\"macro stdmacro
.TH "Frame Scheduler" 3
.SH NAME
frs \- The REACT/Pro Frame Scheduler
.fi
.SH "DESCRIPTION"
.P
The REACT/Pro Frame Scheduler is an execution manager that schedules
pthreads or processes on one or more CPUs in a predefined cyclic order.
.P
The Frame Scheduler interfaces are as follows:
.TP 13
Setup:
\f4frs_create\f1(3),
\f4frs_create_master\f1(3),
\f4frs_create_vmaster\f1(3),
\f4frs_create_slave\f1(3),
\f4frs_enqueue\f1(3),
\f4frs_pthread_enqueue\f1(3),
\f4frs_pinsert\f1(3),
\f4frs_pthread_insert\f1(3),
\f4frs_setattr\f1(3),
\f4frs_pthread_setattr\f1(3)
.TP
Execution:
\f4frs_start\f1(3),
\f4frs_join\f1(3),
\f4frs_yield\f1(3),
\f4frs_stop\f1(3),
\f4frs_resume\f1(3),
\f4frs_userintr\f1(3)
.TP
Query:
\f4frs_getqueuelen\f1(3),
\f4frs_readqueue\f1(3),
\f4frs_pthread_readqueue\f1(3),
\f4frs_getattr\f1(3),
\f4frs_pthread_getattr\f1(3)
.TP
Destruction:
\f4frs_destroy\f1(3),
\f4frs_premove\f1(3),
\f4frs_pthread_remove\f1(3)
.SH SEE ALSO
The REACT Real-Time Programmer's Guide (insight(1)) covers Frame Scheduler
principles and usage in detail.
.P
Frame scheduler programming examples (if installed) can be found in the
following directory: /usr/share/src/react/examples.
