'\"macro stdmacro
.TH "Frame Scheduler" 3
.SH NAME
\f4frs_getqueuelen\f1 \- get the length of a frame scheduler minor frame queue
.SH SYNOPSIS
\f4#include <sys/frs.h>\f1
.PP
\f4int frs_getqueuelen (frs_t* \f2frs\fP, int \f2minor_index\fP);\f1
.fi
.SH DESCRIPTION
\f4frs_getqueuelen\fP returns the length (number of threads/processes queued)
on the minor frame \f2minor_index\fP of the \f2frs\fP frame scheduler object.
.P
\f4frs_getqueuelen\fP will fail if one or more of the following
conditions are true:
.TP 15
.SM
\%[EINVAL]
Invalid frame scheduler object.
.TP 15
.SM
\%[EPERM]
No permission to execute frame scheduler functions.
.TP 15
.SM
\%[EPERM]
The calling thread/process is an FRS controller.
.TP 15
.SM
\%[ENODEV]
The REACT/Pro Frame Scheduler Subsystem has not been installed.
.SH "DIAGNOSTICS"
Upon successful completion, \f4frs_getqueuelen\fP will return the
queue length.
Otherwise, -1 is returned and errno is set to indicate the error.
.SH "SEE ALSO"
\f4frs_readqueue\f1(3),
\f4frs_pthread_readqueue\f1(3),
\f4frs_getattr\f1(3),
\f4frs_pthread_getattr\f1(3)
\f4frs_enqueue\f1(3),
\f4frs_pthread_enqueue\f1(3),
\f4frs_pinsert\f1(3),
\f4frs_pthread_insert\f1(3)
.P
The REACT Real-Time Programmer's Guide (insight(1)) covers Frame Scheduler
principles and usage in detail.
.P
Frame scheduler programming examples (if installed) can be found in the
following directory: /usr/share/src/react/examples.
