'\"macro stdmacro
.TH "Frame Scheduler" 3
.SH NAME
\f4frs_yield\f1 \- yields control of a frame scheduled cpu
.SH SYNOPSIS
.nf
\f4#include <sys/frs.h>\f1
.PP
\f4int frs_yield(frs_t\(** \f2frs\fP);\f1
.fi
.SH DESCRIPTION
\f4frs_yield\fP causes the calling activity thread/process to relinquish
control of its frame scheduled processor, represented by \f2frs\fP, after
completing execution of its per-frame real-time code.
.P
Controller and dequeued threads/processes cannot call \f4frs_yield\fP.
.P
\f4frs_yield\fP will fail if one or more of the following
conditions are true:
.TP 15
.SM
\%[EINVAL]
Invalid frame scheduler object.
.TP 15
.SM
\%[EINVALSTATE]
The frame scheduler has not been started or is terminating.
.TP 15
.SM
\%[EPERM]
No permission to execute frame scheduler functions.
.TP 15
.SM
\%[EPERM]
The calling thread/process is an FRS controller.
.TP 15
.SM
\%[EPERM]
The calling pthread is not system scope.
.TP 15
.SM
\%[ENODEV]
The REACT/Pro Frame Scheduler Subsystem has not been installed.
.SH "DIAGNOSTICS"
Upon successful completion, \f4frs_yield\fP will return the number of
the previous minor frame.
Otherwise, -1 is returned and errno is set to indicate the error.
.SH "SEE ALSO"
\f4frs_start\f1(3),
\f4frs_join\f1(3),
\f4frs_stop\f1(3),
\f4frs_resume\f1(3),
.P
The REACT Real-Time Programmer's Guide (insight(1)) covers Frame Scheduler
principles and usage in detail.
.P
Frame scheduler programming examples (if installed) can be found in the
following directory: /usr/share/src/react/examples.
