'\"macro stdmacro
.TH BSUMMARY 1
.SH NAME
bsummary \- branch coverage tool reporting program to calculate summary
information
.SH SYNOPSIS
.B bsummary
[
.I filename 
]

.SH DESCRIPTION
.LP
.B bsummary
gives summary information about a report created by \f4breport\fP or
\f4btell\fP. The
following numbers are calculated:
.IP \(bu
number and percentage of branches taken in TRUE and FALSE direction
.IP \(bu
number and percentage of branches taken only in TRUE direction
.IP \(bu
number and percentage of branches taken only in FALSE direction
.IP \(bu
number and percentage of branches not taken at all
.IP \(bu
total number of branches
.IP \(bu
number and percentage of cases taken
.IP \(bu
total number of cases
.IP \(bu
number and percentage of functions called
.IP \(bu
total number of functions
.LP
\fBbsummary\fR reads from the standard input if no file is specified.
The input file format is the output format of \fBbreport\fR or
\f4btell\fP.
.LP
Example:
.RS
host-1% breport test3_log | bsummary
.br
Branches taken in true and false direction 68 (34%)
.br
Branches taken only in true direction 34 (17%)
.br
Branches taken only in false direction 32 (16%)
.br
Branches not taken at all 66 (33%)
.br
Total number of branches 200
.br
Cases taken 942 (19.9%)
.br
Total number of cases 4711
.br
Functions called 2176 (32.96%)
.br
Total number of functions 6602
.RE
.SH "SEE ALSO"
.BR breport (1),
.BR bmerge (1),
.BR btell (1),
.BR btool (1).
.SH DIAGNOSTICS
"bsummary: Can't open file \fIfilename\fR."
.br
"bsummary: Wrong input format."







