'\"macro stdmacro
.TH BTELL 1
.SH NAME
btell \- branch tool report generator
.SH SYNOPSIS
\f4btell [\-czw][\-f \f2func\f4][\-F \f2File\f4][\-m \f2mapfile\f4] \f2logfile...\fP
.SH DESCRIPTION
\f4btell\fP processes one or more \f2logfile\f1s and prints a report subject
to the various filtering options.
The output report is in text file format that can be viewed with a
text editor or passed as input to \f4bsummary\fP(1).
.P
\f4btell\fP uses the file \f2btool_map\fP as the mapping information
unless the \f4\-m\fP option is given.
.P
The various filtering options are:
.TP 10
\f4\-z\fP
print only branches, loops, and functions that are never taken.
.TP
\f4\-c\fP
print only branches, loops, and functions that have been taken.
.TP
\f4\-w\fP
print warnings for missing log entries (i.e. entries in the map file
that have no corresponding entry - zero or otherwise) in any of the
\f2logfile\fPs.
.TP
\f4\-f\f2 func\f1
limit output to branches and loops withing \f2func\fP.
.TP
\f4\-F\f2 file\f1
limit output to functions, branches and loops withing \f2file\fP.
.SH SEE ALSO
\f4bsummary\fP(1),
\f4btool\fP(1),
\f4kbtool\fP(1).
