extern 	device_node_t 	*devinfo_from_cache(dev_t);
extern 	device_node_t 	*disk_setup(dev_t, int);
extern 	int 		insert_info_in_cache(dev_t, void *);
extern 	void 		init_cache(void);
extern 	int 		add_grio_disk_info(dev_t, int, int, int);
extern 	void 		ggd_fatal_error( char * );
extern 	int 		insert_info(dev_t, void *);
extern 	int 		start_new_device_reservations(device_node_t *, time_t);
extern 	int 		update_ggd_info_node( device_node_t *, int );
extern 	int 		get_vdisk_fd(dev_t );
extern 	int 		unreserve_path_bandwidth( dev_t, stream_id_t *, __uint64_t );
extern 	int 		reserve_path_bandwidth( dev_t , dev_t, int , int , int, time_t , time_t , stream_id_t *, int *, time_t *, char*, int, __uint64_t);
extern 	int 		get_grio_iosize_for_filesys( dev_t, int );
extern 	int 		determine_remaining_bandwidth( device_node_t *, time_t, __int64_t *, __int64_t *);
extern 	void 		remove_expired_reservations(device_node_t *, time_t);
extern 	void 		update_device_reservations(time_t);
extern 	int 		init_ggd_info_node(device_node_t *);
extern 	dev_t 		get_diskid(dev_t);
extern	reservations_t 	*get_resv_from_id(reservations_t *, dev_t, stream_id_t *);
extern	int 		reserve_bandwidth(device_node_t *, dev_t, int, int, int, int, time_t, time_t, dev_t, stream_id_t *, int *, time_t *, char *, int);
extern	int 		remove_reservation_with_id(device_node_t *, dev_t, stream_id_t *);
extern int		add_admin_info(char *, dev_info_t *);
extern int		start_guaranteed_disk_stream(reservations_t *);
extern int		access_guaranteed_registers(device_node_t *, reservations_t *);
extern int		mark_disk_noretry(dev_t);
extern void 		errorlog(char *, ...);
