
/*
 * linc.h
 *
 * LINC chip register definitions.  This header file is intended to be
 * useful for kernel drivers, linc firmware, and diagnostics.  _LINC_FIRMWARE
 * should be defined when building software for LINCs controller.
 *
 * Most of this file is generated automatically from LINC chip source
 * code.
 *
 * Copyright 1996, Silicon Graphics, Inc.
 * ALL RIGHTS RESERVED
 *
 * UNPUBLISHED -- Rights reserved under the copyright laws of the United
 * States.   Use of a copyright notice is precautionary only and does not
 * imply publication or disclosure.
 *
 * U.S. GOVERNMENT RESTRICTED RIGHTS LEGEND:
 * Use, duplication or disclosure by the Government is subject to restrictions
 * as set forth in FAR 52.227.19(c)(2) or subparagraph (c)(1)(ii) of the Rights
 * in Technical Data and Computer Software clause at DFARS 252.227-7013 and/or
 * in similar or successor clauses in the FAR, or the DOD or NASA FAR
 * Supplement.  Contractor/manufacturer is Silicon Graphics, Inc.,
 * 2011 N. Shoreline Blvd. Mountain View, CA 94039-7311.
 *
 * THE CONTENT OF THIS WORK CONTAINS CONFIDENTIAL AND PROPRIETARY
 * INFORMATION OF SILICON GRAPHICS, INC. ANY DUPLICATION, MODIFICATION,
 * DISTRIBUTION, OR DISCLOSURE IN ANY FORM, IN WHOLE, OR IN PART, IS STRICTLY
 * PROHIBITED WITHOUT THE PRIOR EXPRESS WRITTEN PERMISSION OF SILICON
 * GRAPHICS, INC.
 */


#ifndef __PCI_LINC_H__
#define __PCI_LINC_H__

#ident "$Revision: 1.9 $"

#define LINC_VENDOR_ID_NUM	0x10a9
#define LINC_DEVICE_ID_NUM	0x0002

/*
** Constant definitions related to DMA.
** Max cmd count in the fifo is 4.
*/

#define LINC_MAX_DMA_COUNT     4

/* Address regions of LINC:
 */
#define LINC_SDRAM_ADDR			0x00000000
#define LINC_SDRAM_WG2_ADDR		0x08000000	/* r4650 only */
#define LINC_SDRAM_WG4_ADDR		0x0c000000	/* r4650 only */
#define LINC_SDRAM_WG8_ADDR		0x10000000	/* r4650 only */
#define LINC_SSRAM_ADDR			0x04000000	/* r4650 only */

#define LINC_MAILBOX_ADDR		0x04400000
#define LINC_CPCI_CONFIG_ADDR		0x04c00000
#define LINC_CPCI_PIO_ADDR		0x05000000
#define LINC_CPCI_PIO_BSWAP_ADDR	0x06000000

#define LINC_DMA0_ADDR			0x07000000
#define LINC_DMA1_ADDR			0x07400000
#define LINC_MISC_REGS_ADDR		0x07800000
#ifndef _LINC_FIRMWARE
#define LINC_PROM_ADDR			0x07c00000	/* host access */
#else
#define LINC_PROM_ADDR			0x1fc00000	/* r4650 only */
#endif
#define LINC_BYTEBUS_ADDR		0x07e00000


/* Child PCI address attributes.
 */
#define CPCI_ATTR_SDRAM			0x80000000
#define CPCI_ATTR_SDRAM_SHFT		31
#define CPCI_ATTR_CHANNEL		0x40000000
#define CPCI_ATTR_CHANNEL_SHFT		30
#define CPCI_ATTR_FLUSH			0x20000000
#define CPCI_ATTR_FLUSH_SHFT		29
#define CPCI_ATTR_PFTCH_W(X)		((X)<<CPCI_ATTR_PFTCH_SHFT)
#define CPCI_ATTR_PFTCH_SHFT		27
#define CPCI_ATTR_PFTCH_MASK		0x18000000
#define CPCI_ATTR_BSWP			0x04000000
#define CPCI_ATTR_MASK			0xfc000003	/* all non-addr bits */

/* Note: These register names are automatically generated from
 * the verilog definition of the LINC chip.
 */

/* ------------  Register Names and Addresses ------------
 */

#define LINC_DMA0			0x07000000
#define LINC_DMA1			0x07400000
#define LINC_DMA_TRANSFER_CONTROL	0x0000
#define LINC_DMA_TRANSFER_CONTROL_0	0x07000000
#define LINC_DMA_TRANSFER_CONTROL_1	0x07400000
#define LINC_DTC			0x0000
#define LINC_DTC_0			0x07000000
#define LINC_DTC_1			0x07400000
#define LINC_DMA_BUFMEM_ADDR		0x0008
#define LINC_DMA_BUFMEM_ADDR_0		0x07000008
#define LINC_DMA_BUFMEM_ADDR_1		0x07400008
#define LINC_DBMA			0x0008
#define LINC_DBMA_0			0x07000008
#define LINC_DBMA_1			0x07400008
#define LINC_DMA_HIGH_PPCI_ADDR		0x0010
#define LINC_DMA_HIGH_PPCI_ADDR_0	0x07000010
#define LINC_DMA_HIGH_PPCI_ADDR_1	0x07400010
#define LINC_DHPA			0x0010
#define LINC_DHPA_0			0x07000010
#define LINC_DHPA_1			0x07400010
#define LINC_DMA_LOW_PPCI_ADDR		0x0018
#define LINC_DMA_LOW_PPCI_ADDR_0	0x07000018
#define LINC_DMA_LOW_PPCI_ADDR_1	0x07400018
#define LINC_DLPA			0x0018
#define LINC_DLPA_0			0x07000018
#define LINC_DLPA_1			0x07400018
#define LINC_DMA_RES_CHECKSUM		0x0020
#define LINC_DMA_RES_CHECKSUM_0		0x07000020
#define LINC_DMA_RES_CHECKSUM_1		0x07400020
#define LINC_DRCK			0x0020
#define LINC_DRCK_0			0x07000020
#define LINC_DRCK_1			0x07400020
#define LINC_DMA_CHECKSUM		0x0028
#define LINC_DMA_CHECKSUM_0		0x07000028
#define LINC_DMA_CHECKSUM_1		0x07400028
#define LINC_DCK			0x0028
#define LINC_DCK_0			0x07000028
#define LINC_DCK_1			0x07400028
#define LINC_DMA_CONTROL_STATUS		0x0040
#define LINC_DMA_CONTROL_STATUS_0	0x07000040
#define LINC_DMA_CONTROL_STATUS_1	0x07400040
#define LINC_DCSR			0x0040
#define LINC_DCSR_0			0x07000040
#define LINC_DCSR_1			0x07400040
#define LINC_DMA_DIAG_WCOUNT		0x0048
#define LINC_DMA_DIAG_WCOUNT_0		0x07000048
#define LINC_DMA_DIAG_WCOUNT_1		0x07400048
#define LINC_DDWC			0x0048
#define LINC_DDWC_0			0x07000048
#define LINC_DDWC_1			0x07400048
#define LINC_LINC_CONTROL_STATUS_RESET	0x07800000
#define LINC_LCSR			0x07800000
#define LINC_CONTROLLER_INTERRUPT_STATUS 0x07800008
#define LINC_CISR			0x07800008
#define LINC_CONTROLLER_INTERRUPT_MASK	0x07800010
#define LINC_CIMR			0x07800010
#define LINC_HOST_INTERRUPT_STATUS	0x07800018
#define LINC_HISR			0x07800018
#define LINC_HOST_INTERRUPT_MASK	0x07800020
#define LINC_HIMR			0x07800020
#define LINC_CONTROLLER_COMMAND_STATUS	0x07800028
#define LINC_SCSR			0x07800028
#define LINC_CONTROLLER_ERROR_ADDR	0x07800030
#define LINC_SCEA			0x07800030
#define LINC_INDIRECT_DMA_CSR		0x07800100
#define LINC_ICSR			0x07800100
#define LINC_INDIRECT_DMA_HIGH_ADDR	0x07800108
#define LINC_IHA			0x07800108
#define LINC_INDIRECT_DMA_LOW_ADDR	0x07800110
#define LINC_ILA			0x07800110
#define LINC_INDIRECT_DMA_WRITE_DATA_HIGH 0x07800118
#define LINC_IWDH			0x07800118
#define LINC_INDIRECT_DMA_WRITE_DATA_LOW 0x0780011C
#define LINC_IWDL			0x0780011C
#define LINC_INDIRECT_RD_DATA_POINTER	0x07800120
#define LINC_IRDP			0x07800120
#define LINC_CHILD_PCI_CSR		0x07800200
#define LINC_CCSR			0x07800200
#define LINC_CHILD_PCI_ERR		0x07800208
#define LINC_CERR			0x07800208
#define LINC_CHILD_PCI_ERR_ADDR		0x07800210
#define LINC_CEA			0x07800210
#define LINC_CPCI_PREFETCH_CSR		0x07800220
#define LINC_CPCSR			0x07800220
#define LINC_MAILBOX_BASE_ADDRESS	0x07800400
#define LINC_MBB			0x07800400
#define LINC_MAILBOX_STATUS		0x07800408
#define LINC_MBS			0x07800408
#define LINC_MAILBOX_MASK		0x07800410
#define LINC_MBM			0x07800410
#define LINC_BUFMEM_CONTROL		0x07800800
#define LINC_BMC			0x07800800
#define LINC_BUFMEM_OPERATION		0x07800810
#define LINC_BMO			0x07800810
#define LINC_BUFMEM_ERROR		0x07800818
#define LINC_BME			0x07800818
#define LINC_BUFMEM_ERROR_ADDRESS	0x07800820
#define LINC_BMEA			0x07800820
#define LINC_BYTEBUS_CONTROL		0x07802000
#define LINC_BBCSR			0x07802000
#define LINC_LED			0x07802008
#define LINC_LED			0x07802008
#define LINC_GENERIC_PINS		0x07802010
#define LINC_GPIO			0x07802010
#define LINC_PPCI_CONFIG_VENDOR_DEVICE_ID 0x07810000
#define LINC_PCVEND			0x07810000
#define LINC_PPCI_CONFIG_COMMAND_STATUS	0x07810004
#define LINC_PCCSR			0x07810004
#define LINC_PPCI_CONFIG_REV_ID_CLASS	0x07810008
#define LINC_PCREV			0x07810008
#define LINC_PPCI_CONFIG_HEADER_LATENCY	0x0781000C
#define LINC_PCHDR			0x0781000C
#define LINC_PPCI_CONFIG_BASE_ADDRESS	0x07810010
#define LINC_PCBASE			0x07810010
#define LINC_PPCI_CONFIG_MISC		0x0781003C
#define LINC_PCMISC			0x0781003C
#define LINC_PPCI_ERROR			0x07811000
#define LINC_PERR			0x07811000
#define LINC_PPCI_ERROR_ADDRESS_HIGH	0x07811008
#define LINC_PEAH			0x07811008
#define LINC_PPCI_ERROR_ADDRESS_LOW	0x07811010
#define LINC_PEAL			0x07811010

/*  Register Bit Definitions
 * -------  Register PPCI_CONFIG_VENDOR_DEVICE_ID Bit Definitions -------
 */

#define LINC_PCVEND_DEV_ID_MASK		0xffff0000
#define LINC_PCVEND_DEV_ID_W(X)		((X)<<LINC_PCVEND_DEV_ID_SHFT)
#define LINC_PCVEND_DEV_ID_R(X) \
	(((X)&LINC_PCVEND_DEV_ID_MASK)>>LINC_PCVEND_DEV_ID_SHFT)
#define LINC_PCVEND_DEV_ID_SHFT		16
#define LINC_PCVEND_VEN_ID_MASK		0x0000ffff
#define LINC_PCVEND_VEN_ID_W(X)		((X)<<LINC_PCVEND_VEN_ID_SHFT)
#define LINC_PCVEND_VEN_ID_R(X) \
	(((X)&LINC_PCVEND_VEN_ID_MASK)>>LINC_PCVEND_VEN_ID_SHFT)
#define LINC_PCVEND_VEN_ID_SHFT		0

/* -------  Register PPCI_CONFIG_COMMAND_STATUS Bit Definitions -------
 */

#define LINC_PCCSR_PAR_ERR		0x80000000
#define LINC_PCCSR_PAR_ERR_SHFT		31
#define LINC_PCCSR_SIG_SERR		0x40000000
#define LINC_PCCSR_SIG_SERR_SHFT	30
#define LINC_PCCSR_RX_MST_ABRT		0x20000000
#define LINC_PCCSR_RX_MST_ABRT_SHFT	29
#define LINC_PCCSR_RX_TAR_ABRT		0x10000000
#define LINC_PCCSR_RX_TAR_ABRT_SHFT	28
#define LINC_PCCSR_SIG_TAR_ABRT		0x08000000
#define LINC_PCCSR_SIG_TAR_ABRT_SHFT	27
#define LINC_PCCSR_DEVSEL_TIMING_MASK	0x06000000
#define LINC_PCCSR_DEVSEL_TIMING_W(X)	((X)<<LINC_PCCSR_DEVSEL_TIMING_SHFT)
#define LINC_PCCSR_DEVSEL_TIMING_R(X) \
	(((X)&LINC_PCCSR_DEVSEL_TIMING_MASK)>>LINC_PCCSR_DEVSEL_TIMING_SHFT)
#define LINC_PCCSR_DEVSEL_TIMING_SHFT	25
#define LINC_PCCSR_PERR_DETECTED	0x01000000
#define LINC_PCCSR_PERR_DETECTED_SHFT	24
#define LINC_PCCSR_FAST_BB		0x00800000
#define LINC_PCCSR_FAST_BB_SHFT		23
#define LINC_PCCSR_UDF_SUPPORTED	0x00400000
#define LINC_PCCSR_UDF_SUPPORTED_SHFT	22
#define LINC_PCCSR_66MHZ_CAPABLE	0x00200000
#define LINC_PCCSR_66MHZ_CAPABLE_SHFT	21
#define LINC_PCCSR_RD_ONLY		0x00020000
#define LINC_PCCSR_RD_ONLY_SHFT		17
#define LINC_PCCSR_RX_SERR		0x00010000
#define LINC_PCCSR_RX_SERR_SHFT		16
#define LINC_PCCSR_FAST_BB_EN		0x00000200
#define LINC_PCCSR_FAST_BB_EN_SHFT	9
#define LINC_PCCSR_SERR_EN		0x00000100
#define LINC_PCCSR_SERR_EN_SHFT		8
#define LINC_PCCSR_ADDR_STEP		0x00000080
#define LINC_PCCSR_ADDR_STEP_SHFT	7
#define LINC_PCCSR_PAR_RESP_EN		0x00000040
#define LINC_PCCSR_PAR_RESP_EN_SHFT	6
#define LINC_PCCSR_MASTER_EN		0x00000004
#define LINC_PCCSR_MASTER_EN_SHFT	2
#define LINC_PCCSR_MEM_SPACE		0x00000002
#define LINC_PCCSR_MEM_SPACE_SHFT	1
#define LINC_PCCSR_IO_SPACE		0x00000001
#define LINC_PCCSR_IO_SPACE_SHFT	0

/* -------  Register PPCI_CONFIG_REV_ID_CLASS Bit Definitions -------
 */

#define LINC_PCREV_BASE_CLASS_MASK	0xff000000
#define LINC_PCREV_BASE_CLASS_W(X)	((X)<<LINC_PCREV_BASE_CLASS_SHFT)
#define LINC_PCREV_BASE_CLASS_R(X) \
	(((X)&LINC_PCREV_BASE_CLASS_MASK)>>LINC_PCREV_BASE_CLASS_SHFT)
#define LINC_PCREV_BASE_CLASS_SHFT	24
#define LINC_PCREV_SUB_CLASS_MASK	0x00ff0000
#define LINC_PCREV_SUB_CLASS_W(X)	((X)<<LINC_PCREV_SUB_CLASS_SHFT)
#define LINC_PCREV_SUB_CLASS_R(X) \
	(((X)&LINC_PCREV_SUB_CLASS_MASK)>>LINC_PCREV_SUB_CLASS_SHFT)
#define LINC_PCREV_SUB_CLASS_SHFT	16
#define LINC_PCREV_PROG_IF_MASK		0x0000ff00
#define LINC_PCREV_PROG_IF_W(X)		((X)<<LINC_PCREV_PROG_IF_SHFT)
#define LINC_PCREV_PROG_IF_R(X) \
	(((X)&LINC_PCREV_PROG_IF_MASK)>>LINC_PCREV_PROG_IF_SHFT)
#define LINC_PCREV_PROG_IF_SHFT		8
#define LINC_PCREV_REV_ID_MASK		0x000000ff
#define LINC_PCREV_REV_ID_W(X)		((X)<<LINC_PCREV_REV_ID_SHFT)
#define LINC_PCREV_REV_ID_R(X) \
	(((X)&LINC_PCREV_REV_ID_MASK)>>LINC_PCREV_REV_ID_SHFT)
#define LINC_PCREV_REV_ID_SHFT		0

/* -------  Register PPCI_CONFIG_HEADER_LATENCY Bit Definitions -------
 */

#define LINC_PCHDR_BIST_MASK		0xff000000
#define LINC_PCHDR_BIST_W(X)		((X)<<LINC_PCHDR_BIST_SHFT)
#define LINC_PCHDR_BIST_R(X) \
	(((X)&LINC_PCHDR_BIST_MASK)>>LINC_PCHDR_BIST_SHFT)
#define LINC_PCHDR_BIST_SHFT		24
#define LINC_PCHDR_MULT			0x00800000
#define LINC_PCHDR_MULT_SHFT		23
#define LINC_PCHDR_LAYOUT_CODE_MASK	0x007f0000
#define LINC_PCHDR_LAYOUT_CODE_W(X)	((X)<<LINC_PCHDR_LAYOUT_CODE_SHFT)
#define LINC_PCHDR_LAYOUT_CODE_R(X) \
	(((X)&LINC_PCHDR_LAYOUT_CODE_MASK)>>LINC_PCHDR_LAYOUT_CODE_SHFT)
#define LINC_PCHDR_LAYOUT_CODE_SHFT	16
#define LINC_PCHDR_COUNT_MASK		0x0000f800
#define LINC_PCHDR_COUNT_W(X)		((X)<<LINC_PCHDR_COUNT_SHFT)
#define LINC_PCHDR_COUNT_R(X) \
	(((X)&LINC_PCHDR_COUNT_MASK)>>LINC_PCHDR_COUNT_SHFT)
#define LINC_PCHDR_COUNT_SHFT		11
#define LINC_PCHDR_CACHE_SIZE_MASK	0x000000ff
#define LINC_PCHDR_CACHE_SIZE_W(X)	((X)<<LINC_PCHDR_CACHE_SIZE_SHFT)
#define LINC_PCHDR_CACHE_SIZE_R(X) \
	(((X)&LINC_PCHDR_CACHE_SIZE_MASK)>>LINC_PCHDR_CACHE_SIZE_SHFT)
#define LINC_PCHDR_CACHE_SIZE_SHFT	0

/* -------  Register PPCI_CONFIG_BASE_ADDRESS Bit Definitions -------
 */

#define LINC_PCBASE_BASE_ADDR_MASK	0xf8000000
#define LINC_PCBASE_BASE_ADDR_W(X)	((X)<<LINC_PCBASE_BASE_ADDR_SHFT)
#define LINC_PCBASE_BASE_ADDR_R(X) \
	(((X)&LINC_PCBASE_BASE_ADDR_MASK)>>LINC_PCBASE_BASE_ADDR_SHFT)
#define LINC_PCBASE_BASE_ADDR_SHFT	27
#define LINC_PCBASE_PREFETCHABLE	0x00000008
#define LINC_PCBASE_PREFETCHABLE_SHFT	3
#define LINC_PCBASE_TYPE_MASK		0x00000006
#define LINC_PCBASE_TYPE_W(X)		((X)<<LINC_PCBASE_TYPE_SHFT)
#define LINC_PCBASE_TYPE_R(X) \
	(((X)&LINC_PCBASE_TYPE_MASK)>>LINC_PCBASE_TYPE_SHFT)
#define LINC_PCBASE_TYPE_SHFT		1
#define LINC_PCBASE_MEM_SPACE		0x00000001
#define LINC_PCBASE_MEM_SPACE_SHFT	0

/* -------  Register PPCI_CONFIG_MISC Bit Definitions -------
 */

#define LINC_PCMISC_PCI_MAX_LAT_MASK	0xff000000
#define LINC_PCMISC_PCI_MAX_LAT_W(X)	((X)<<LINC_PCMISC_PCI_MAX_LAT_SHFT)
#define LINC_PCMISC_PCI_MAX_LAT_R(X) \
	(((X)&LINC_PCMISC_PCI_MAX_LAT_MASK)>>LINC_PCMISC_PCI_MAX_LAT_SHFT)
#define LINC_PCMISC_PCI_MAX_LAT_SHFT	24
#define LINC_PCMISC_PCI_MIN_GNT_MASK	0x00ff0000
#define LINC_PCMISC_PCI_MIN_GNT_W(X)	((X)<<LINC_PCMISC_PCI_MIN_GNT_SHFT)
#define LINC_PCMISC_PCI_MIN_GNT_R(X) \
	(((X)&LINC_PCMISC_PCI_MIN_GNT_MASK)>>LINC_PCMISC_PCI_MIN_GNT_SHFT)
#define LINC_PCMISC_PCI_MIN_GNT_SHFT	16
#define LINC_PCMISC_INTERRUPT_PIN_MASK	0x0000ff00
#define LINC_PCMISC_INTERRUPT_PIN_W(X)	((X)<<LINC_PCMISC_INTERRUPT_PIN_SHFT)
#define LINC_PCMISC_INTERRUPT_PIN_R(X) \
	(((X)&LINC_PCMISC_INTERRUPT_PIN_MASK)>>LINC_PCMISC_INTERRUPT_PIN_SHFT)
#define LINC_PCMISC_INTERRUPT_PIN_SHFT	8
#define LINC_PCMISC_INTERRUPT_LINE_MASK	0x000000ff
#define LINC_PCMISC_INTERRUPT_LINE_W(X)	((X)<<LINC_PCMISC_INTERRUPT_LINE_SHFT)
#define LINC_PCMISC_INTERRUPT_LINE_R(X) \
	(((X)&LINC_PCMISC_INTERRUPT_LINE_MASK)>>LINC_PCMISC_INTERRUPT_LINE_SHFT)
#define LINC_PCMISC_INTERRUPT_LINE_SHFT	0

/* -------  Register PPCI_ERROR Bit Definitions -------
 */

#define LINC_PERR_VALID			0x80000000
#define LINC_PERR_VALID_SHFT		31
#define LINC_PERR_MUL_ERR		0x40000000
#define LINC_PERR_MUL_ERR_SHFT		30
#define LINC_PERR_MASTER_ID_MASK	0x30000000
#define LINC_PERR_MASTER_ID_W(X)	((X)<<LINC_PERR_MASTER_ID_SHFT)
#define LINC_PERR_MASTER_ID_R(X) \
	(((X)&LINC_PERR_MASTER_ID_MASK)>>LINC_PERR_MASTER_ID_SHFT)
#define LINC_PERR_MASTER_ID_SHFT	28
#define LINC_PERR_BE_MASK		0x0ff00000
#define LINC_PERR_BE_W(X)		((X)<<LINC_PERR_BE_SHFT)
#define LINC_PERR_BE_R(X) \
	(((X)&LINC_PERR_BE_MASK)>>LINC_PERR_BE_SHFT)
#define LINC_PERR_BE_SHFT		20
#define LINC_PERR_CMD_MASK		0x000f0000
#define LINC_PERR_CMD_W(X)		((X)<<LINC_PERR_CMD_SHFT)
#define LINC_PERR_CMD_R(X) \
	(((X)&LINC_PERR_CMD_MASK)>>LINC_PERR_CMD_SHFT)
#define LINC_PERR_CMD_SHFT		16
#define LINC_PERR_A64			0x00008000
#define LINC_PERR_A64_SHFT		15
#define LINC_PERR_D64			0x00004000
#define LINC_PERR_D64_SHFT		14
#define LINC_PERR_RD_DPAR		0x00001000
#define LINC_PERR_RD_DPAR_SHFT		12
#define LINC_PERR_TAR_ABORT		0x00000800
#define LINC_PERR_TAR_ABORT_SHFT	11
#define LINC_PERR_MAST_ABORT		0x00000400
#define LINC_PERR_MAST_ABORT_SHFT	10
#define LINC_PERR_PERR			0x00000200
#define LINC_PERR_PERR_SHFT		9
#define LINC_PERR_SERR			0x00000100
#define LINC_PERR_SERR_SHFT		8
#define LINC_PERR_ACK32_ERR		0x00000080
#define LINC_PERR_ACK32_ERR_SHFT	7
#define LINC_PERR_SDRAM_ERR		0x00000040
#define LINC_PERR_SDRAM_ERR_SHFT	6
#define LINC_PERR_RD_SIZE_ERR		0x00000020
#define LINC_PERR_RD_SIZE_ERR_SHFT	5
#define LINC_PERR_WR_SIZE_ERR		0x00000010
#define LINC_PERR_WR_SIZE_ERR_SHFT	4
#define LINC_PERR_RD_TO_WO		0x00000008
#define LINC_PERR_RD_TO_WO_SHFT		3
#define LINC_PERR_CPCI_ERR		0x00000002
#define LINC_PERR_CPCI_ERR_SHFT		1
#define LINC_PERR_BBUS_TO		0x00000001
#define LINC_PERR_BBUS_TO_SHFT		0

/* -------  Register PPCI_ERROR_ADDRESS_HIGH Bit Definitions -------
 */

#define LINC_PEAH_ADDR_MASK		0xffffffff
#define LINC_PEAH_ADDR_W(X)		((X)<<LINC_PEAH_ADDR_SHFT)
#define LINC_PEAH_ADDR_R(X) \
	(((X)&LINC_PEAH_ADDR_MASK)>>LINC_PEAH_ADDR_SHFT)
#define LINC_PEAH_ADDR_SHFT		0

/* -------  Register PPCI_ERROR_ADDRESS_LOW Bit Definitions -------
 */

#define LINC_PEAL_ADDR_MASK		0xffffffff
#define LINC_PEAL_ADDR_W(X)		((X)<<LINC_PEAL_ADDR_SHFT)
#define LINC_PEAL_ADDR_R(X) \
	(((X)&LINC_PEAL_ADDR_MASK)>>LINC_PEAL_ADDR_SHFT)
#define LINC_PEAL_ADDR_SHFT		0

/* -------  Register LINC_CONTROL_STATUS_RESET Bit Definitions -------
 */

#define LINC_LCSR_IGNORE_ERRORS		0x00800000
#define LINC_LCSR_IGNORE_ERRORS_SHFT	23
#define LINC_LCSR_FORCE_SERR		0x00400000
#define LINC_LCSR_FORCE_SERR_SHFT	22
#define LINC_LCSR_FORCE_PAR_64		0x00200000
#define LINC_LCSR_FORCE_PAR_64_SHFT	21
#define LINC_LCSR_FORCE_PAR_32		0x00100000
#define LINC_LCSR_FORCE_PAR_32_SHFT	20
#define LINC_LCSR_FORCE_PERR		0x00080000
#define LINC_LCSR_FORCE_PERR_SHFT	19
#define LINC_LCSR_LINC_RST		0x00000400
#define LINC_LCSR_LINC_RST_SHFT		10
#define LINC_LCSR_BOOT_MEM		0x00000200
#define LINC_LCSR_BOOT_MEM_SHFT		9
#define LINC_LCSR_FATAL_ERROR		0x00000100
#define LINC_LCSR_FATAL_ERROR_SHFT	8
#define LINC_LCSR_BOOT_ERROR		0x00000080
#define LINC_LCSR_BOOT_ERROR_SHFT	7
#define LINC_LCSR_BOOTING		0x00000040
#define LINC_LCSR_BOOTING_SHFT		6
#define LINC_LCSR_BOOT_MODE		0x00000020
#define LINC_LCSR_BOOT_MODE_SHFT	5
#define LINC_LCSR_BOOT_INHIBIT		0x00000010
#define LINC_LCSR_BOOT_INHIBIT_SHFT	4
#define LINC_LCSR_COLD_RST		0x00000008
#define LINC_LCSR_COLD_RST_SHFT		3
#define LINC_LCSR_WARM_RST		0x00000004
#define LINC_LCSR_WARM_RST_SHFT		2
#define LINC_LCSR_RESET_CPCI		0x00000002
#define LINC_LCSR_RESET_CPCI_SHFT	1
#define LINC_LCSR_BBUS_RST		0x00000001
#define LINC_LCSR_BBUS_RST_SHFT		0

/* -------  Register CHILD_PCI_CSR Bit Definitions -------
 */

#define LINC_CCSR_NO_WRT_FLUSH		0x00800000
#define LINC_CCSR_NO_WRT_FLUSH_SHFT	23
#define LINC_CCSR_PIPE_MODE		0x00200000
#define LINC_CCSR_PIPE_MODE_SHFT	21
#define LINC_CCSR_OPT_GRANT		0x00100000
#define LINC_CCSR_OPT_GRANT_SHFT	20
#define LINC_CCSR_EN_PREEMPT		0x00080000
#define LINC_CCSR_EN_PREEMPT_SHFT	19
#define LINC_CCSR_EN_MAST_TIMEOUT	0x00040000
#define LINC_CCSR_EN_MAST_TIMEOUT_SHFT	18
#define LINC_CCSR_FRC_PERR		0x00020000
#define LINC_CCSR_FRC_PERR_SHFT		17
#define LINC_CCSR_MEM_SPACE_EN		0x00010000
#define LINC_CCSR_MEM_SPACE_EN_SHFT	16
#define LINC_CCSR_MASTER_EN		0x00008000
#define LINC_CCSR_MASTER_EN_SHFT	15
#define LINC_CCSR_SERR_EN		0x00004000
#define LINC_CCSR_SERR_EN_SHFT		14
#define LINC_CCSR_ARB_EN_MASK		0x00003000
#define LINC_CCSR_ARB_EN_W(X)		((X)<<LINC_CCSR_ARB_EN_SHFT)
#define LINC_CCSR_ARB_EN_R(X) \
	(((X)&LINC_CCSR_ARB_EN_MASK)>>LINC_CCSR_ARB_EN_SHFT)
#define LINC_CCSR_ARB_EN_SHFT		12
#define LINC_CCSR_PAR_RESP_EN		0x00000800
#define LINC_CCSR_PAR_RESP_EN_SHFT	11
#define LINC_CCSR_FRC_SERR		0x00000400
#define LINC_CCSR_FRC_SERR_SHFT		10
#define LINC_CCSR_FRC_PAR_ERR_R		0x00000200
#define LINC_CCSR_FRC_PAR_ERR_R_SHFT	9
#define LINC_CCSR_FRC_PAR_ERR_W		0x00000100
#define LINC_CCSR_FRC_PAR_ERR_W_SHFT	8
#define LINC_CCSR_FRC_DMA_PAR_R		0x00000080
#define LINC_CCSR_FRC_DMA_PAR_R_SHFT	7
#define LINC_CCSR_FRC_DMA_PAR_W		0x00000040
#define LINC_CCSR_FRC_DMA_PAR_W_SHFT	6
#define LINC_CCSR_PAR_CHK_EN		0x00000020
#define LINC_CCSR_PAR_CHK_EN_SHFT	5

/* -------  Register CHILD_PCI_ERR Bit Definitions -------
 */

#define LINC_CERR_VALID			0x80000000
#define LINC_CERR_VALID_SHFT		31
#define LINC_CERR_MUL_ERR		0x40000000
#define LINC_CERR_MUL_ERR_SHFT		30
#define LINC_CERR_MASTER_MASK		0x30000000
#define LINC_CERR_MASTER_W(X)		((X)<<LINC_CERR_MASTER_SHFT)
#define LINC_CERR_MASTER_R(X) \
	(((X)&LINC_CERR_MASTER_MASK)>>LINC_CERR_MASTER_SHFT)
#define LINC_CERR_MASTER_SHFT		28
#define LINC_CERR_CMD_MASK		0x000f0000
#define LINC_CERR_CMD_W(X)		((X)<<LINC_CERR_CMD_SHFT)
#define LINC_CERR_CMD_R(X) \
	(((X)&LINC_CERR_CMD_MASK)>>LINC_CERR_CMD_SHFT)
#define LINC_CERR_CMD_SHFT		16
#define LINC_CERR_BE_MASK		0x0000f000
#define LINC_CERR_BE_W(X)		((X)<<LINC_CERR_BE_SHFT)
#define LINC_CERR_BE_R(X) \
	(((X)&LINC_CERR_BE_MASK)>>LINC_CERR_BE_SHFT)
#define LINC_CERR_BE_SHFT		12
#define LINC_CERR_EN_ERR		0x00000800
#define LINC_CERR_EN_ERR_SHFT		11
#define LINC_CERR_RST_ERR		0x00000400
#define LINC_CERR_RST_ERR_SHFT		10
#define LINC_CERR_RCV_PERR		0x00000200
#define LINC_CERR_RCV_PERR_SHFT		9
#define LINC_CERR_RCV_SERR		0x00000100
#define LINC_CERR_RCV_SERR_SHFT		8
#define LINC_CERR_RCV_MAST_ABORT	0x00000080
#define LINC_CERR_RCV_MAST_ABORT_SHFT	7
#define LINC_CERR_MAST_TIMEOUT		0x00000040
#define LINC_CERR_MAST_TIMEOUT_SHFT	6
#define LINC_CERR_RCV_TAR_ABORT		0x00000020
#define LINC_CERR_RCV_TAR_ABORT_SHFT	5
#define LINC_CERR_WR_DPAR		0x00000008
#define LINC_CERR_WR_DPAR_SHFT		3
#define LINC_CERR_RD_DPAR		0x00000004
#define LINC_CERR_RD_DPAR_SHFT		2
#define LINC_CERR_SIG_SERR		0x00000002
#define LINC_CERR_SIG_SERR_SHFT		1

/* -------  Register CHILD_PCI_ERR_ADDR Bit Definitions -------
 */

#define LINC_CEA_ADR_MASK		0xffffffff
#define LINC_CEA_ADR_W(X)		((X)<<LINC_CEA_ADR_SHFT)
#define LINC_CEA_ADR_R(X) \
	(((X)&LINC_CEA_ADR_MASK)>>LINC_CEA_ADR_SHFT)
#define LINC_CEA_ADR_SHFT		0

/* -------  Register CPCI_PREFETCH_CSR Bit Definitions -------
 */

#define LINC_CPCSR_BUF_1_BSY		0x80000000
#define LINC_CPCSR_BUF_1_BSY_SHFT	31
#define LINC_CPCSR_BUF_0_BSY		0x40000000
#define LINC_CPCSR_BUF_0_BSY_SHFT	30
#define LINC_CPCSR_FLUSH		0x20000000
#define LINC_CPCSR_FLUSH_SHFT		29
#define LINC_CPCSR_PERSISTENT_2		0x04000000
#define LINC_CPCSR_PERSISTENT_2_SHFT	26
#define LINC_CPCSR_PERSISTENT_1		0x02000000
#define LINC_CPCSR_PERSISTENT_1_SHFT	25
#define LINC_CPCSR_PERSISTENT_0		0x01000000
#define LINC_CPCSR_PERSISTENT_0_SHFT	24
#define LINC_CPCSR_PF_LTH2_MASK		0x00ff0000
#define LINC_CPCSR_PF_LTH2_W(X)		((X)<<LINC_CPCSR_PF_LTH2_SHFT)
#define LINC_CPCSR_PF_LTH2_R(X) \
	(((X)&LINC_CPCSR_PF_LTH2_MASK)>>LINC_CPCSR_PF_LTH2_SHFT)
#define LINC_CPCSR_PF_LTH2_SHFT		16
#define LINC_CPCSR_PF_LTH1_MASK		0x0000ff00
#define LINC_CPCSR_PF_LTH1_W(X)		((X)<<LINC_CPCSR_PF_LTH1_SHFT)
#define LINC_CPCSR_PF_LTH1_R(X) \
	(((X)&LINC_CPCSR_PF_LTH1_MASK)>>LINC_CPCSR_PF_LTH1_SHFT)
#define LINC_CPCSR_PF_LTH1_SHFT		8
#define LINC_CPCSR_PF_LTH0_MASK		0x000000ff
#define LINC_CPCSR_PF_LTH0_W(X)		((X)<<LINC_CPCSR_PF_LTH0_SHFT)
#define LINC_CPCSR_PF_LTH0_R(X) \
	(((X)&LINC_CPCSR_PF_LTH0_MASK)>>LINC_CPCSR_PF_LTH0_SHFT)
#define LINC_CPCSR_PF_LTH0_SHFT		0

/* -------  Register BYTEBUS_CONTROL Bit Definitions -------
 */

#define LINC_BBCSR_EN_ERR		0x80000000
#define LINC_BBCSR_EN_ERR_SHFT		31
#define LINC_BBCSR_RST_ERR		0x40000000
#define LINC_BBCSR_RST_ERR_SHFT		30
#define LINC_BBCSR_PROM_SZ_ERR		0x20000000
#define LINC_BBCSR_PROM_SZ_ERR_SHFT	29
#define LINC_BBCSR_FRC_PAR		0x10000000
#define LINC_BBCSR_FRC_PAR_SHFT		28
#define LINC_BBCSR_PAR_ERR		0x08000000
#define LINC_BBCSR_PAR_ERR_SHFT		27
#define LINC_BBCSR_PAR_EN1		0x04000000
#define LINC_BBCSR_PAR_EN1_SHFT		26
#define LINC_BBCSR_PAR_EN0		0x02000000
#define LINC_BBCSR_PAR_EN0_SHFT		25
#define LINC_BBCSR_BBUS_EN		0x01000000
#define LINC_BBCSR_BBUS_EN_SHFT		24
#define LINC_BBCSR_GEN_ACK		0x00800000
#define LINC_BBCSR_GEN_ACK_SHFT		23
#define LINC_BBCSR_WR_TO		0x00400000
#define LINC_BBCSR_WR_TO_SHFT		22
#define LINC_BBCSR_TSU			0x00200000
#define LINC_BBCSR_TSU_SHFT		21
#define LINC_BBCSR_THO			0x00100000
#define LINC_BBCSR_THO_SHFT		20
#define LINC_BBCSR_PULS_WID_MASK	0x000ff800
#define LINC_BBCSR_PULS_WID_W(X)	((X)<<LINC_BBCSR_PULS_WID_SHFT)
#define LINC_BBCSR_PULS_WID_R(X) \
	(((X)&LINC_BBCSR_PULS_WID_MASK)>>LINC_BBCSR_PULS_WID_SHFT)
#define LINC_BBCSR_PULS_WID_SHFT	11
#define LINC_BBCSR_SELF_TIMED		0x00000400
#define LINC_BBCSR_SELF_TIMED_SHFT	10
#define LINC_BBCSR_A_TO_CS_MASK		0x00000300
#define LINC_BBCSR_A_TO_CS_W(X)		((X)<<LINC_BBCSR_A_TO_CS_SHFT)
#define LINC_BBCSR_A_TO_CS_R(X) \
	(((X)&LINC_BBCSR_A_TO_CS_MASK)>>LINC_BBCSR_A_TO_CS_SHFT)
#define LINC_BBCSR_A_TO_CS_SHFT		8
#define LINC_BBCSR_CS_TO_EN_MASK	0x000000c0
#define LINC_BBCSR_CS_TO_EN_W(X)	((X)<<LINC_BBCSR_CS_TO_EN_SHFT)
#define LINC_BBCSR_CS_TO_EN_R(X) \
	(((X)&LINC_BBCSR_CS_TO_EN_MASK)>>LINC_BBCSR_CS_TO_EN_SHFT)
#define LINC_BBCSR_CS_TO_EN_SHFT	6
#define LINC_BBCSR_EN_WID_MASK		0x0000003c
#define LINC_BBCSR_EN_WID_W(X)		((X)<<LINC_BBCSR_EN_WID_SHFT)
#define LINC_BBCSR_EN_WID_R(X) \
	(((X)&LINC_BBCSR_EN_WID_MASK)>>LINC_BBCSR_EN_WID_SHFT)
#define LINC_BBCSR_EN_WID_SHFT		2
#define LINC_BBCSR_CS_TO_A_MASK		0x00000003
#define LINC_BBCSR_CS_TO_A_W(X)		((X)<<LINC_BBCSR_CS_TO_A_SHFT)
#define LINC_BBCSR_CS_TO_A_R(X) \
	(((X)&LINC_BBCSR_CS_TO_A_MASK)>>LINC_BBCSR_CS_TO_A_SHFT)
#define LINC_BBCSR_CS_TO_A_SHFT		0

/* -------  Register LED Bit Definitions -------
 */

#define LINC_LED_LED_MASK		0x0000000f
#define LINC_LED_LED_W(X)		((X)<<LINC_LED_LED_SHFT)
#define LINC_LED_LED_R(X) \
	(((X)&LINC_LED_LED_MASK)>>LINC_LED_LED_SHFT)
#define LINC_LED_LED_SHFT		0

/* -------  Register GENERIC_PINS Bit Definitions -------
 */

#define LINC_GPIO_DIAG_SLCT_MASK	0xf0000000
#define LINC_GPIO_DIAG_SLCT_W(X)	((X)<<LINC_GPIO_DIAG_SLCT_SHFT)
#define LINC_GPIO_DIAG_SLCT_R(X) \
	(((X)&LINC_GPIO_DIAG_SLCT_MASK)>>LINC_GPIO_DIAG_SLCT_SHFT)
#define LINC_GPIO_DIAG_SLCT_SHFT	28
#define LINC_GPIO_DATA_IN_MASK		0x000f0000
#define LINC_GPIO_DATA_IN_W(X)		((X)<<LINC_GPIO_DATA_IN_SHFT)
#define LINC_GPIO_DATA_IN_R(X) \
	(((X)&LINC_GPIO_DATA_IN_MASK)>>LINC_GPIO_DATA_IN_SHFT)
#define LINC_GPIO_DATA_IN_SHFT		16
#define LINC_GPIO_DATA_OUT_MASK		0x00000f00
#define LINC_GPIO_DATA_OUT_W(X)		((X)<<LINC_GPIO_DATA_OUT_SHFT)
#define LINC_GPIO_DATA_OUT_R(X) \
	(((X)&LINC_GPIO_DATA_OUT_MASK)>>LINC_GPIO_DATA_OUT_SHFT)
#define LINC_GPIO_DATA_OUT_SHFT		8
#define LINC_GPIO_OUT_EN_MASK		0x0000000f
#define LINC_GPIO_OUT_EN_W(X)		((X)<<LINC_GPIO_OUT_EN_SHFT)
#define LINC_GPIO_OUT_EN_R(X) \
	(((X)&LINC_GPIO_OUT_EN_MASK)>>LINC_GPIO_OUT_EN_SHFT)
#define LINC_GPIO_OUT_EN_SHFT		0

/* -------  Register DMA_CONTROL_STATUS Bit Definitions -------
 */

#define LINC_DCSR_ERROR			0x80000000
#define LINC_DCSR_ERROR_SHFT		31
#define LINC_DCSR_BUFMEM_ERR		0x40000000
#define LINC_DCSR_BUFMEM_ERR_SHFT	30
#define LINC_DCSR_PPCI_ERROR		0x20000000
#define LINC_DCSR_PPCI_ERROR_SHFT	29
#define LINC_DCSR_RES_OVFL		0x08000000
#define LINC_DCSR_RES_OVFL_SHFT		27
#define LINC_DCSR_RES_UFLO		0x04000000
#define LINC_DCSR_RES_UFLO_SHFT		26
#define LINC_DCSR_CMD_OVFL		0x02000000
#define LINC_DCSR_CMD_OVFL_SHFT		25
#define LINC_DCSR_ADR_OVFL		0x01000000
#define LINC_DCSR_ADR_OVFL_SHFT		24
#define LINC_DCSR_DONE_INT		0x00800000
#define LINC_DCSR_DONE_INT_SHFT		23
#define LINC_DCSR_DONE_INT_MASK		0x00400000
#define LINC_DCSR_DONE_INT_MASK_SHFT	22
#define LINC_DCSR_NUM_CHK_MASK		0x00000700
#define LINC_DCSR_NUM_CHK_W(X)		((X)<<LINC_DCSR_NUM_CHK_SHFT)
#define LINC_DCSR_NUM_CHK_R(X) \
	(((X)&LINC_DCSR_NUM_CHK_MASK)>>LINC_DCSR_NUM_CHK_SHFT)
#define LINC_DCSR_NUM_CHK_SHFT		8
#define LINC_DCSR_POP_FIFO		0x00000080
#define LINC_DCSR_POP_FIFO_SHFT		7
#define LINC_DCSR_VAL_DESC_MASK		0x00000070
#define LINC_DCSR_VAL_DESC_W(X)		((X)<<LINC_DCSR_VAL_DESC_SHFT)
#define LINC_DCSR_VAL_DESC_R(X) \
	(((X)&LINC_DCSR_VAL_DESC_MASK)>>LINC_DCSR_VAL_DESC_SHFT)
#define LINC_DCSR_VAL_DESC_SHFT		4
#define LINC_DCSR_BUSY			0x00000008
#define LINC_DCSR_BUSY_SHFT		3
#define LINC_DCSR_FIN_HALT		0x00000004
#define LINC_DCSR_FIN_HALT_SHFT		2
#define LINC_DCSR_EN_DMA		0x00000002
#define LINC_DCSR_EN_DMA_SHFT		1
#define LINC_DCSR_RESET			0x00000001
#define LINC_DCSR_RESET_SHFT		0

/* -------  Register DMA_CHECKSUM Bit Definitions -------
 */

#define LINC_DCK_CHECKSUM_MASK		0x0003ffff
#define LINC_DCK_CHECKSUM_W(X)		((X)<<LINC_DCK_CHECKSUM_SHFT)
#define LINC_DCK_CHECKSUM_R(X) \
	(((X)&LINC_DCK_CHECKSUM_MASK)>>LINC_DCK_CHECKSUM_SHFT)
#define LINC_DCK_CHECKSUM_SHFT		0

/* -------  Register DMA_TRANSFER_CONTROL Bit Definitions -------
 */

#define LINC_DTC_TO_PARENT		0x08000000
#define LINC_DTC_TO_PARENT_SHFT		27
#define LINC_DTC_CHAIN_BA		0x04000000
#define LINC_DTC_CHAIN_BA_SHFT		26
#define LINC_DTC_CHAIN_PA		0x02000000
#define LINC_DTC_CHAIN_PA_SHFT		25
#define LINC_DTC_CHAIN_CS		0x01000000
#define LINC_DTC_CHAIN_CS_SHFT		24
#define LINC_DTC_SAVE_CS		0x00800000
#define LINC_DTC_SAVE_CS_SHFT		23
#define LINC_DTC_RD_CMD_MASK		0x00600000
#define LINC_DTC_RD_CMD_W(X)		((X)<<LINC_DTC_RD_CMD_SHFT)
#define LINC_DTC_RD_CMD_R(X) \
	(((X)&LINC_DTC_RD_CMD_MASK)>>LINC_DTC_RD_CMD_SHFT)
#define LINC_DTC_RD_CMD_READ		(0<<LINC_DTC_RD_CMD_SHFT)
#define LINC_DTC_RD_CMD_READ_LINE	(1<<LINC_DTC_RD_CMD_SHFT)
#define LINC_DTC_RD_CMD_READ_MULTIPLE	(2<<LINC_DTC_RD_CMD_SHFT)
#define LINC_DTC_RD_CMD_SHFT		21
#define LINC_DTC_D64			0x00100000
#define LINC_DTC_D64_SHFT		20
#define LINC_DTC_SWAP_W			0x00080000
#define LINC_DTC_SWAP_W_SHFT		19
#define LINC_DTC_SWAP_B			0x00040000
#define LINC_DTC_SWAP_B_SHFT		18
#define LINC_DTC_INT_DONE		0x00020000
#define LINC_DTC_INT_DONE_SHFT		17
#define LINC_DTC_WORD_CNT_MASK		0x0001fffc
#define LINC_DTC_WORD_CNT_W(X)		((X)<<LINC_DTC_WORD_CNT_SHFT)
#define LINC_DTC_WORD_CNT_R(X) \
	(((X)&LINC_DTC_WORD_CNT_MASK)>>LINC_DTC_WORD_CNT_SHFT)
#define LINC_DTC_WORD_CNT_SHFT		2

/* -------  Register DMA_HIGH_PPCI_ADDR Bit Definitions -------
 */

#define LINC_DHPA_ADR_ATTRIB_MASK	0xffffff00
#define LINC_DHPA_ADR_ATTRIB_W(X)	((X)<<LINC_DHPA_ADR_ATTRIB_SHFT)
#define LINC_DHPA_ADR_ATTRIB_R(X) \
	(((X)&LINC_DHPA_ADR_ATTRIB_MASK)>>LINC_DHPA_ADR_ATTRIB_SHFT)
#define LINC_DHPA_ADR_ATTRIB_SHFT	8
#define LINC_DHPA_H_ADDR_HI_MASK	0x000000ff
#define LINC_DHPA_H_ADDR_HI_W(X)	((X)<<LINC_DHPA_H_ADDR_HI_SHFT)
#define LINC_DHPA_H_ADDR_HI_R(X) \
	(((X)&LINC_DHPA_H_ADDR_HI_MASK)>>LINC_DHPA_H_ADDR_HI_SHFT)
#define LINC_DHPA_H_ADDR_HI_SHFT	0

/* -------  Register DMA_LOW_PPCI_ADDR Bit Definitions -------
 */

#define LINC_DLPA_H_ADDR_CTR_MASK	0xfffffffc
#define LINC_DLPA_H_ADDR_CTR_W(X)	((X)<<LINC_DLPA_H_ADDR_CTR_SHFT)
#define LINC_DLPA_H_ADDR_CTR_R(X) \
	(((X)&LINC_DLPA_H_ADDR_CTR_MASK)>>LINC_DLPA_H_ADDR_CTR_SHFT)
#define LINC_DLPA_H_ADDR_CTR_SHFT	2

/* -------  Register DMA_BUFMEM_ADDR Bit Definitions -------
 */

#define LINC_DBMA_BUFMEM_ADDR_MASK	0x03fffffc
#define LINC_DBMA_BUFMEM_ADDR_W(X)	((X)<<LINC_DBMA_BUFMEM_ADDR_SHFT)
#define LINC_DBMA_BUFMEM_ADDR_R(X) \
	(((X)&LINC_DBMA_BUFMEM_ADDR_MASK)>>LINC_DBMA_BUFMEM_ADDR_SHFT)
#define LINC_DBMA_BUFMEM_ADDR_SHFT	2

/* -------  Register DMA_RES_CHECKSUM Bit Definitions -------
 */

#define LINC_DRCK_CHECKSUM_MASK		0x0003ffff
#define LINC_DRCK_CHECKSUM_W(X)		((X)<<LINC_DRCK_CHECKSUM_SHFT)
#define LINC_DRCK_CHECKSUM_R(X) \
	(((X)&LINC_DRCK_CHECKSUM_MASK)>>LINC_DRCK_CHECKSUM_SHFT)
#define LINC_DRCK_CHECKSUM_SHFT		0

/* -------  Register DMA_DIAG_WCOUNT Bit Definitions -------
 */

#define LINC_DDWC_MATCH			0x80000000
#define LINC_DDWC_MATCH_SHFT		31
#define LINC_DDWC_REG_CNT_MASK		0x7fff0000
#define LINC_DDWC_REG_CNT_W(X)		((X)<<LINC_DDWC_REG_CNT_SHFT)
#define LINC_DDWC_REG_CNT_R(X) \
	(((X)&LINC_DDWC_REG_CNT_MASK)>>LINC_DDWC_REG_CNT_SHFT)
#define LINC_DDWC_REG_CNT_SHFT		16
#define LINC_DDWC_UP_CNT_MASK		0x00007fff
#define LINC_DDWC_UP_CNT_W(X)		((X)<<LINC_DDWC_UP_CNT_SHFT)
#define LINC_DDWC_UP_CNT_R(X) \
	(((X)&LINC_DDWC_UP_CNT_MASK)>>LINC_DDWC_UP_CNT_SHFT)
#define LINC_DDWC_UP_CNT_SHFT		0

/* -------  Register INDIRECT_DMA_CSR Bit Definitions -------
 */

#define LINC_ICSR_ERROR			0x01000000
#define LINC_ICSR_ERROR_SHFT		24
#define LINC_ICSR_PPCI_REQ		0x00800000
#define LINC_ICSR_PPCI_REQ_SHFT		23
#define LINC_ICSR_RD_CMD_MASK		0x00600000
#define LINC_ICSR_RD_CMD_W(X)		((X)<<LINC_ICSR_RD_CMD_SHFT)
#define LINC_ICSR_RD_CMD_R(X) \
	(((X)&LINC_ICSR_RD_CMD_MASK)>>LINC_ICSR_RD_CMD_SHFT)
#define LINC_ICSR_RD_CMD_READ		(0<<LINC_ICSR_RD_CMD_SHFT)
#define LINC_ICSR_RD_CMD_READ_LINE	(1<<LINC_ICSR_RD_CMD_SHFT)
#define LINC_ICSR_RD_CMD_READ_MULTIPLE	(2<<LINC_ICSR_RD_CMD_SHFT)
#define LINC_ICSR_RD_CMD_SHFT		21
#define LINC_ICSR_USE_D64		0x00100000
#define LINC_ICSR_USE_D64_SHFT		20
#define LINC_ICSR_WSWAP			0x00080000
#define LINC_ICSR_WSWAP_SHFT		19
#define LINC_ICSR_BSWAP			0x00040000
#define LINC_ICSR_BSWAP_SHFT		18
#define LINC_ICSR_BUSY			0x00020000
#define LINC_ICSR_BUSY_SHFT		17
#define LINC_ICSR_TO_PARENT		0x00010000
#define LINC_ICSR_TO_PARENT_SHFT	16
#define LINC_ICSR_RD_SIZE_MASK		0x0000c000
#define LINC_ICSR_RD_SIZE_W(X)		((X)<<LINC_ICSR_RD_SIZE_SHFT)
#define LINC_ICSR_RD_SIZE_R(X) \
	(((X)&LINC_ICSR_RD_SIZE_MASK)>>LINC_ICSR_RD_SIZE_SHFT)
#define LINC_ICSR_RD_SIZE_4		(0<<LINC_ICSR_RD_SIZE_SHFT)
#define LINC_ICSR_RD_SIZE_8		(1<<LINC_ICSR_RD_SIZE_SHFT)
#define LINC_ICSR_RD_SIZE_64		(2<<LINC_ICSR_RD_SIZE_SHFT)
#define LINC_ICSR_RD_SIZE_128		(3<<LINC_ICSR_RD_SIZE_SHFT)
#define LINC_ICSR_RD_SIZE_SHFT		14
#define LINC_ICSR_FLUSH			0x00000100
#define LINC_ICSR_FLUSH_SHFT		8
#define LINC_ICSR_BYTE_MASK_MASK	0x000000ff
#define LINC_ICSR_BYTE_MASK_W(X)	((X)<<LINC_ICSR_BYTE_MASK_SHFT)
#define LINC_ICSR_BYTE_MASK_R(X) \
	(((X)&LINC_ICSR_BYTE_MASK_MASK)>>LINC_ICSR_BYTE_MASK_SHFT)
#define LINC_ICSR_BYTE_MASK_SHFT	0

/* -------  Register INDIRECT_DMA_HIGH_ADDR Bit Definitions -------
 */

#define LINC_IHA_ATTR_MASK		0xffffff00
#define LINC_IHA_ATTR_W(X)		((X)<<LINC_IHA_ATTR_SHFT)
#define LINC_IHA_ATTR_R(X) \
	(((X)&LINC_IHA_ATTR_MASK)>>LINC_IHA_ATTR_SHFT)
#define LINC_IHA_ATTR_SHFT		8
#define LINC_IHA_HOST_ADDR_MASK		0x000000ff
#define LINC_IHA_HOST_ADDR_W(X)		((X)<<LINC_IHA_HOST_ADDR_SHFT)
#define LINC_IHA_HOST_ADDR_R(X) \
	(((X)&LINC_IHA_HOST_ADDR_MASK)>>LINC_IHA_HOST_ADDR_SHFT)
#define LINC_IHA_HOST_ADDR_SHFT		0

/* -------  Register INDIRECT_DMA_LOW_ADDR Bit Definitions -------
 */

#define LINC_ILA_HOST_ADDR_MASK		0xfffffffc
#define LINC_ILA_HOST_ADDR_W(X)		((X)<<LINC_ILA_HOST_ADDR_SHFT)
#define LINC_ILA_HOST_ADDR_R(X) \
	(((X)&LINC_ILA_HOST_ADDR_MASK)>>LINC_ILA_HOST_ADDR_SHFT)
#define LINC_ILA_HOST_ADDR_SHFT		2

/* -------  Register INDIRECT_DMA_WRITE_DATA_HIGH Bit Definitions -------
 */

#define LINC_IWDH_DATA_MASK		0xffffffff
#define LINC_IWDH_DATA_W(X)		((X)<<LINC_IWDH_DATA_SHFT)
#define LINC_IWDH_DATA_R(X) \
	(((X)&LINC_IWDH_DATA_MASK)>>LINC_IWDH_DATA_SHFT)
#define LINC_IWDH_DATA_SHFT		0

/* -------  Register INDIRECT_DMA_WRITE_DATA_LOW Bit Definitions -------
 */

#define LINC_IWDL_DATA_MASK		0xffffffff
#define LINC_IWDL_DATA_W(X)		((X)<<LINC_IWDL_DATA_SHFT)
#define LINC_IWDL_DATA_R(X) \
	(((X)&LINC_IWDL_DATA_MASK)>>LINC_IWDL_DATA_SHFT)
#define LINC_IWDL_DATA_SHFT		0

/* -------  Register INDIRECT_RD_DATA_POINTER Bit Definitions -------
 */

#define LINC_IRDP_POINTER_MASK		0x03fffffc
#define LINC_IRDP_POINTER_W(X)		((X)<<LINC_IRDP_POINTER_SHFT)
#define LINC_IRDP_POINTER_R(X) \
	(((X)&LINC_IRDP_POINTER_MASK)>>LINC_IRDP_POINTER_SHFT)
#define LINC_IRDP_POINTER_SHFT		2

/* -------  Register CONTROLLER_COMMAND_STATUS Bit Definitions -------
 */

#define LINC_SCSR_PAR_BYTE_ERR_MASK	0x000f0000
#define LINC_SCSR_PAR_BYTE_ERR_W(X)	((X)<<LINC_SCSR_PAR_BYTE_ERR_SHFT)
#define LINC_SCSR_PAR_BYTE_ERR_R(X) \
	(((X)&LINC_SCSR_PAR_BYTE_ERR_MASK)>>LINC_SCSR_PAR_BYTE_ERR_SHFT)
#define LINC_SCSR_PAR_BYTE_ERR_SHFT	16
#define LINC_SCSR_WG_BUSY		0x00000040
#define LINC_SCSR_WG_BUSY_SHFT		6
#define LINC_SCSR_RD_ONLY		0x00000020
#define LINC_SCSR_RD_ONLY_SHFT		5
#define LINC_SCSR_PAR_CHK_EN		0x00000010
#define LINC_SCSR_PAR_CHK_EN_SHFT	4
#define LINC_SCSR_FORCE_RPAR_MASK	0x0000000f
#define LINC_SCSR_FORCE_RPAR_W(X)	((X)<<LINC_SCSR_FORCE_RPAR_SHFT)
#define LINC_SCSR_FORCE_RPAR_R(X) \
	(((X)&LINC_SCSR_FORCE_RPAR_MASK)>>LINC_SCSR_FORCE_RPAR_SHFT)
#define LINC_SCSR_FORCE_RPAR_SHFT	0

/* -------  Register CONTROLLER_ERROR_ADDR Bit Definitions -------
 */

#define LINC_SCEA_ERR_ADR_MASK		0x1fffffff
#define LINC_SCEA_ERR_ADR_W(X)		((X)<<LINC_SCEA_ERR_ADR_SHFT)
#define LINC_SCEA_ERR_ADR_R(X) \
	(((X)&LINC_SCEA_ERR_ADR_MASK)>>LINC_SCEA_ERR_ADR_SHFT)
#define LINC_SCEA_ERR_ADR_SHFT		0

/* -------  Register CONTROLLER_INTERRUPT_STATUS Bit Definitions -------
 */

#define LINC_CISR_SYSAD_DPAR		0x40000000
#define LINC_CISR_SYSAD_DPAR_SHFT	30
#define LINC_CISR_BUFMEM_RD_ERR		0x20000000
#define LINC_CISR_BUFMEM_RD_ERR_SHFT	29
#define LINC_CISR_REG_SIZE		0x10000000
#define LINC_CISR_REG_SIZE_SHFT		28
#define LINC_CISR_WR_TO_RO		0x08000000
#define LINC_CISR_WR_TO_RO_SHFT		27
#define LINC_CISR_CPCI_RD_ERR		0x02000000
#define LINC_CISR_CPCI_RD_ERR_SHFT	25
#define LINC_CISR_BBUS_RTO		0x01000000
#define LINC_CISR_BBUS_RTO_SHFT		24
#define LINC_CISR_IDMA_BUSY_ERR		0x00800000
#define LINC_CISR_IDMA_BUSY_ERR_SHFT	23
#define LINC_CISR_NMI_BUTTON		0x00400000
#define LINC_CISR_NMI_BUTTON_SHFT	22
#define LINC_CISR_SET_NMI		0x00200000
#define LINC_CISR_SET_NMI_SHFT		21
#define LINC_CISR_CLR_NMI		0x00100000
#define LINC_CISR_CLR_NMI_SHFT		20
#define LINC_CISR_BBUS_PARERR		0x00080000
#define LINC_CISR_BBUS_PARERR_SHFT	19
#define LINC_CISR_BBUS_ERR		0x00002000
#define LINC_CISR_BBUS_ERR_SHFT		13
#define LINC_CISR_BUFMEM_ERR		0x00001000
#define LINC_CISR_BUFMEM_ERR_SHFT	12
#define LINC_CISR_CPCI_ERROR		0x00000800
#define LINC_CISR_CPCI_ERROR_SHFT	11
#define LINC_CISR_PPCI_ERROR		0x00000400
#define LINC_CISR_PPCI_ERROR_SHFT	10
#define LINC_CISR_DMA1_ERR		0x00000200
#define LINC_CISR_DMA1_ERR_SHFT		9
#define LINC_CISR_DMA0_ERR		0x00000100
#define LINC_CISR_DMA0_ERR_SHFT		8
#define LINC_CISR_MAILBOX_INT		0x00000080
#define LINC_CISR_MAILBOX_INT_SHFT	7
#define LINC_CISR_CPCI_INT_MASK		0x00000060
#define LINC_CISR_CPCI_INT_W(X)		((X)<<LINC_CISR_CPCI_INT_SHFT)
#define LINC_CISR_CPCI_INT_R(X) \
	(((X)&LINC_CISR_CPCI_INT_MASK)>>LINC_CISR_CPCI_INT_SHFT)
#define LINC_CISR_CPCI_INT_1            0x00000040
#define LINC_CISR_CPCI_INT_0            0x00000020
#define LINC_CISR_CPCI_INT_SHFT		5
#define LINC_CISR_BBUS_INT		0x00000010
#define LINC_CISR_BBUS_INT_SHFT		4
#define LINC_CISR_DMA1_INT		0x00000008
#define LINC_CISR_DMA1_INT_SHFT		3
#define LINC_CISR_DMA0_INT		0x00000004
#define LINC_CISR_DMA0_INT_SHFT		2
#define LINC_CISR_CLR_FIRM_INT		0x00000002
#define LINC_CISR_CLR_FIRM_INT_SHFT	1
#define LINC_CISR_FIRM_INTR		0x00000001
#define LINC_CISR_FIRM_INTR_SHFT	0

/* -------  Register CONTROLLER_INTERRUPT_MASK Bit Definitions -------
 */

#define LINC_CIMR_MASK1_MASK		0x78000000
#define LINC_CIMR_MASK1_W(X)		((X)<<LINC_CIMR_MASK1_SHFT)
#define LINC_CIMR_MASK1_R(X) \
	(((X)&LINC_CIMR_MASK1_MASK)>>LINC_CIMR_MASK1_SHFT)
#define LINC_CIMR_MASK1_SHFT		27
#define LINC_CIMR_MASK2_MASK		0x03e00000
#define LINC_CIMR_MASK2_W(X)		((X)<<LINC_CIMR_MASK2_SHFT)
#define LINC_CIMR_MASK2_R(X) \
	(((X)&LINC_CIMR_MASK2_MASK)>>LINC_CIMR_MASK2_SHFT)
#define LINC_CIMR_MASK2_SHFT		21
#define LINC_CIMR_MASK3			0x00080000
#define LINC_CIMR_MASK3_SHFT		19
#define LINC_CIMR_MASK4_MASK		0x00003ffc
#define LINC_CIMR_MASK4_W(X)		((X)<<LINC_CIMR_MASK4_SHFT)
#define LINC_CIMR_MASK4_R(X) \
	(((X)&LINC_CIMR_MASK4_MASK)>>LINC_CIMR_MASK4_SHFT)
#define LINC_CIMR_MASK4_SHFT		2
#define LINC_CIMR_MASK5			0x00000001
#define LINC_CIMR_MASK5_SHFT		0

/* -------  Register HOST_INTERRUPT_STATUS Bit Definitions -------
 */

#define LINC_HISR_FATAL_INT		0x01000000
#define LINC_HISR_FATAL_INT_SHFT	24
#define LINC_HISR_TO_HOST_INT_MASK	0x00f00000
#define LINC_HISR_TO_HOST_INT_W(X)	((X)<<LINC_HISR_TO_HOST_INT_SHFT)
#define LINC_HISR_TO_HOST_INT_R(X) \
	(((X)&LINC_HISR_TO_HOST_INT_MASK)>>LINC_HISR_TO_HOST_INT_SHFT)
#define LINC_HISR_TO_HOST_INT_SHFT	20
#define LINC_HISR_TO_HOST_INT_0		(1<<LINC_HISR_TO_HOST_INT_SHFT)
#define LINC_HISR_TO_HOST_INT_1		(2<<LINC_HISR_TO_HOST_INT_SHFT)
#define LINC_HISR_TO_HOST_INT_2		(4<<LINC_HISR_TO_HOST_INT_SHFT)
#define LINC_HISR_TO_HOST_INT_3		(8<<LINC_HISR_TO_HOST_INT_SHFT)
#define LINC_HISR_BBUS_PARERR		0x00004000
#define LINC_HISR_BBUS_PARERR_SHFT	14
#define LINC_HISR_BBUS_WERR		0x00002000
#define LINC_HISR_BBUS_WERR_SHFT	13
#define LINC_HISR_BUFMEM_ERR		0x00001000
#define LINC_HISR_BUFMEM_ERR_SHFT	12
#define LINC_HISR_CPCI_ERR		0x00000800
#define LINC_HISR_CPCI_ERR_SHFT		11
#define LINC_HISR_PPCI_ERR		0x00000400
#define LINC_HISR_PPCI_ERR_SHFT		10
#define LINC_HISR_DMA1_ERR		0x00000200
#define LINC_HISR_DMA1_ERR_SHFT		9
#define LINC_HISR_DMA0_ERR		0x00000100
#define LINC_HISR_DMA0_ERR_SHFT		8
#define LINC_HISR_CPCI_INT_MASK		0x00000060
#define LINC_HISR_CPCI_INT_W(X)		((X)<<LINC_HISR_CPCI_INT_SHFT)
#define LINC_HISR_CPCI_INT_R(X) \
	(((X)&LINC_HISR_CPCI_INT_MASK)>>LINC_HISR_CPCI_INT_SHFT)
#define LINC_HISR_CPCI_INT_SHFT		5
#define LINC_HISR_BBUS_INT		0x00000010
#define LINC_HISR_BBUS_INT_SHFT		4
#define LINC_HISR_DMA1_INT		0x00000008
#define LINC_HISR_DMA1_INT_SHFT		3
#define LINC_HISR_DMA0_INT		0x00000004
#define LINC_HISR_DMA0_INT_SHFT		2

/* -------  Register HOST_INTERRUPT_MASK Bit Definitions -------
 */

#define LINC_HIMR_MASK1_MASK		0x01f00000
#define LINC_HIMR_MASK1_W(X)		((X)<<LINC_HIMR_MASK1_SHFT)
#define LINC_HIMR_MASK1_R(X) \
	(((X)&LINC_HIMR_MASK1_MASK)>>LINC_HIMR_MASK1_SHFT)
#define LINC_HIMR_MASK1_SHFT		20
#define LINC_HIMR_MASK2_MASK		0x00007f00
#define LINC_HIMR_MASK2_W(X)		((X)<<LINC_HIMR_MASK2_SHFT)
#define LINC_HIMR_MASK2_R(X) \
	(((X)&LINC_HIMR_MASK2_MASK)>>LINC_HIMR_MASK2_SHFT)
#define LINC_HIMR_MASK2_SHFT		8
#define LINC_HIMR_MASK3_MASK		0x0000007c
#define LINC_HIMR_MASK3_W(X)		((X)<<LINC_HIMR_MASK3_SHFT)
#define LINC_HIMR_MASK3_R(X) \
	(((X)&LINC_HIMR_MASK3_MASK)>>LINC_HIMR_MASK3_SHFT)
#define LINC_HIMR_MASK3_SHFT		2

/* -------  Register MAILBOX_BASE_ADDRESS Bit Definitions -------
 */

#define LINC_MBB_BASE_ADDR_MASK		0x03ffff00
#define LINC_MBB_BASE_ADDR_W(X)		((X)<<LINC_MBB_BASE_ADDR_SHFT)
#define LINC_MBB_BASE_ADDR_R(X) \
	(((X)&LINC_MBB_BASE_ADDR_MASK)>>LINC_MBB_BASE_ADDR_SHFT)
#define LINC_MBB_BASE_ADDR_SHFT		8
#define LINC_MBB_ADDR_MASK		0x000000ff
#define LINC_MBB_ADDR_W(X)		((X)<<LINC_MBB_ADDR_SHFT)
#define LINC_MBB_ADDR_R(X) \
	(((X)&LINC_MBB_ADDR_MASK)>>LINC_MBB_ADDR_SHFT)
#define LINC_MBB_ADDR_SHFT		0

/* -------  Register MAILBOX_STATUS Bit Definitions -------
 */

#define LINC_MBS_CHG_MASK		0xffffffff
#define LINC_MBS_CHG_W(X)		((X)<<LINC_MBS_CHG_SHFT)
#define LINC_MBS_CHG_R(X) \
	(((X)&LINC_MBS_CHG_MASK)>>LINC_MBS_CHG_SHFT)
#define LINC_MBS_CHG_SHFT		0

/* -------  Register MAILBOX_MASK Bit Definitions -------
 */

#define LINC_MBM_MASK_MASK		0xffffffff
#define LINC_MBM_MASK_W(X)		((X)<<LINC_MBM_MASK_SHFT)
#define LINC_MBM_MASK_R(X) \
	(((X)&LINC_MBM_MASK_MASK)>>LINC_MBM_MASK_SHFT)
#define LINC_MBM_MASK_SHFT		0

/* -------  Register BUFMEM_CONTROL Bit Definitions -------
 */

#define LINC_BMC_REFRESH_MASK		0xffff0000
#define LINC_BMC_REFRESH_W(X)		((X)<<LINC_BMC_REFRESH_SHFT)
#define LINC_BMC_REFRESH_R(X) \
	(((X)&LINC_BMC_REFRESH_MASK)>>LINC_BMC_REFRESH_SHFT)
#define LINC_BMC_REFRESH_SHFT		16
#define LINC_BMC_REF_EN			0x00008000
#define LINC_BMC_REF_EN_SHFT		15
#define LINC_BMC_REFR_TO_ACT_MASK	0x00007000
#define LINC_BMC_REFR_TO_ACT_W(X)	((X)<<LINC_BMC_REFR_TO_ACT_SHFT)
#define LINC_BMC_REFR_TO_ACT_R(X) \
	(((X)&LINC_BMC_REFR_TO_ACT_MASK)>>LINC_BMC_REFR_TO_ACT_SHFT)
#define LINC_BMC_REFR_TO_ACT_SHFT	12
#define LINC_BMC_64MB			0x00000800
#define LINC_BMC_64MB_SHFT		11
#define LINC_BMC_PR_TO_ACT_MASK		0x00000700
#define LINC_BMC_PR_TO_ACT_W(X)		((X)<<LINC_BMC_PR_TO_ACT_SHFT)
#define LINC_BMC_PR_TO_ACT_R(X) \
	(((X)&LINC_BMC_PR_TO_ACT_MASK)>>LINC_BMC_PR_TO_ACT_SHFT)
#define LINC_BMC_PR_TO_ACT_SHFT		8
#define LINC_BMC_PAR_CHK_EN		0x00000080
#define LINC_BMC_PAR_CHK_EN_SHFT	7
#define LINC_BMC_ACT_TO_PR_MASK		0x00000070
#define LINC_BMC_ACT_TO_PR_W(X)		((X)<<LINC_BMC_ACT_TO_PR_SHFT)
#define LINC_BMC_ACT_TO_PR_R(X) \
	(((X)&LINC_BMC_ACT_TO_PR_MASK)>>LINC_BMC_ACT_TO_PR_SHFT)
#define LINC_BMC_ACT_TO_PR_SHFT		4
#define LINC_BMC_RAS_TO_CAS_MASK	0x0000000c
#define LINC_BMC_RAS_TO_CAS_W(X)	((X)<<LINC_BMC_RAS_TO_CAS_SHFT)
#define LINC_BMC_RAS_TO_CAS_R(X) \
	(((X)&LINC_BMC_RAS_TO_CAS_MASK)>>LINC_BMC_RAS_TO_CAS_SHFT)
#define LINC_BMC_RAS_TO_CAS_SHFT	2
#define LINC_BMC_CAS_LATENCY_MASK	0x00000003
#define LINC_BMC_CAS_LATENCY_W(X)	((X)<<LINC_BMC_CAS_LATENCY_SHFT)
#define LINC_BMC_CAS_LATENCY_R(X) \
	(((X)&LINC_BMC_CAS_LATENCY_MASK)>>LINC_BMC_CAS_LATENCY_SHFT)
#define LINC_BMC_CAS_LATENCY_SHFT	0

/* -------  Register BUFMEM_OPERATION Bit Definitions -------
 */

#define LINC_BMO_DO_REF			0x00002000
#define LINC_BMO_DO_REF_SHFT		13
#define LINC_BMO_DO_PRECH		0x00001000
#define LINC_BMO_DO_PRECH_SHFT		12
#define LINC_BMO_MODE_SET		0x00000800
#define LINC_BMO_MODE_SET_SHFT		11
#define LINC_BMO_MODE_RSVD_MASK		0x00000780
#define LINC_BMO_MODE_RSVD_W(X)		((X)<<LINC_BMO_MODE_RSVD_SHFT)
#define LINC_BMO_MODE_RSVD_R(X) \
	(((X)&LINC_BMO_MODE_RSVD_MASK)>>LINC_BMO_MODE_RSVD_SHFT)
#define LINC_BMO_MODE_RSVD_SHFT		7
#define LINC_BMO_MODE_LAT_MASK		0x00000070
#define LINC_BMO_MODE_LAT_W(X)		((X)<<LINC_BMO_MODE_LAT_SHFT)
#define LINC_BMO_MODE_LAT_R(X) \
	(((X)&LINC_BMO_MODE_LAT_MASK)>>LINC_BMO_MODE_LAT_SHFT)
#define LINC_BMO_MODE_LAT_SHFT		4
#define LINC_BMO_MODE_WRAP		0x00000008
#define LINC_BMO_MODE_WRAP_SHFT		3
#define LINC_BMO_MODE_BURST_MASK	0x00000007
#define LINC_BMO_MODE_BURST_W(X)	((X)<<LINC_BMO_MODE_BURST_SHFT)
#define LINC_BMO_MODE_BURST_R(X) \
	(((X)&LINC_BMO_MODE_BURST_MASK)>>LINC_BMO_MODE_BURST_SHFT)
#define LINC_BMO_MODE_BURST_SHFT	0

/* -------  Register BUFMEM_ERROR Bit Definitions -------
 */

#define LINC_BME_VALID			0x80000000
#define LINC_BME_VALID_SHFT		31
#define LINC_BME_MUL_ERR		0x40000000
#define LINC_BME_MUL_ERR_SHFT		30
#define LINC_BME_MSTR_ID_MASK		0x38000000
#define LINC_BME_MSTR_ID_W(X)		((X)<<LINC_BME_MSTR_ID_SHFT)
#define LINC_BME_MSTR_ID_R(X) \
	(((X)&LINC_BME_MSTR_ID_MASK)>>LINC_BME_MSTR_ID_SHFT)
#define LINC_BME_MSTR_ID_SHFT		27
#define LINC_BME_FRC_PE_MASK		0x00000f00
#define LINC_BME_FRC_PE_W(X)		((X)<<LINC_BME_FRC_PE_SHFT)
#define LINC_BME_FRC_PE_R(X) \
	(((X)&LINC_BME_FRC_PE_MASK)>>LINC_BME_FRC_PE_SHFT)
#define LINC_BME_FRC_PE_SHFT		8
#define LINC_BME_RMW_PE			0x00000020
#define LINC_BME_RMW_PE_SHFT		5
#define LINC_BME_RD_PE			0x00000010
#define LINC_BME_RD_PE_SHFT		4
#define LINC_BME_SYND_MASK		0x0000000f
#define LINC_BME_SYND_W(X)		((X)<<LINC_BME_SYND_SHFT)
#define LINC_BME_SYND_R(X) \
	(((X)&LINC_BME_SYND_MASK)>>LINC_BME_SYND_SHFT)
#define LINC_BME_SYND_SHFT		0

/* -------  Register BUFMEM_ERROR_ADDRESS Bit Definitions -------
 */

#define LINC_BMEA_ADDR_MASK		0x03ffffff
#define LINC_BMEA_ADDR_W(X)		((X)<<LINC_BMEA_ADDR_SHFT)
#define LINC_BMEA_ADDR_R(X) \
	(((X)&LINC_BMEA_ADDR_MASK)>>LINC_BMEA_ADDR_SHFT)
#define LINC_BMEA_ADDR_SHFT		0

/* -------- End of automatically generated definitions. ----------- */

#if defined(SIM) && defined(_LINC_FIRMWARE)
/* firmware running in DV environment uses these three magic locations
 * to pass,fail, or suspend a diag.
 */
#define LINC_SIMPASS		0x1fc54321
#define LINC_SIMFAIL		0x1fc64321
#define LINC_SIMSTOP		0x1fc74321
#endif

/*
 * defines to facilitate accessing mailboxes
 */
#define LINC_MAILBOX_PGSIZE	(64 * 1024)
#define LINC_NUM_MAILBOXES      32

/* return the base address of mailbox X */
#define LINC_MAILBOX(X)		(LINC_MAILBOX_ADDR + (X)*LINC_MAILBOX_PGSIZE)


#ifdef _LANGUAGE_C

#ifdef _LINC_FIRMWARE
#define LINC_READREG(x)		( *( (volatile u_int *) PHYS_TO_K1(x) ) )
#define LINC_WRITEREG(x,y)	( *( (volatile u_int *) PHYS_TO_K1(x) ) = (y) )
#endif /* _LINC_FIRMWARE */

#endif /* _LANGUAGE_C */
#endif /* __PCI_LINC_H__ */
