/* Layout file created by tedit */

#ifndef TUDONTAUTOINCLUDE
#include "tuLabel.h"
#include "tuRadioButton.h"
#include "tuRowColumn.h"
#include "tuCheckBox.h"
#include "tuTextField.h"
#include "tuFrame.h"
#include "tuDeck.h"
#include "tuSeparator.h"
#include "tuLabelButton.h"
#endif /* TUDONTAUTOINCLUDE */

#ifdef TUREGISTERGADGETS
#undef TUREGISTERGADGETS
#endif /* TUREGISTERGADGETS */
#define TUREGISTERGADGETS { \
    tuLabel::registerForPickling(); \
    tuRadioButton::registerForPickling(); \
    tuRowColumn::registerForPickling(); \
    tuCheckBox::registerForPickling(); \
    tuTextField::registerForPickling(); \
    tuFrame::registerForPickling(); \
    tuDeck::registerForPickling(); \
    tuSeparator::registerForPickling(); \
    tuLabelButton::registerForPickling(); \
}

static char* layoutstr =
"(RowColumn "
 "(rows 3) "
 "(cols 1) "
 "(defaultAlignment 0) "
 "(resources "
  "((topInset 10) "
   "(bottomInset 10) "
   "(leftInset 10) "
   "(rightInset 10) "
   "(horizontalOffset 10) "
   "(verticalOffset 10) "
   "(fixedWidth True) "
   "(fixedHeight True))) "
 "(child "
  "(RowColumn "
   "(rows 9) "
   "(cols 3) "
   "(defaultAlignment 0) "
   "(resources "
    "((horizontalOffset 10) "
     "(verticalOffset 10))) "
   "(child "
    "(Label "
     "(resources "
      "((labelString Time\\ legend:))))) "
   "(constraint R0C0A6) "
   "(child "
    "(RowColumn "
     "(rows 1) "
     "(cols 4) "
     "(defaultAlignment 0) "
     "(resources "
      "((horizontalOffset 5) "
       "(fixedHeight True))) "
     "(child "
      "(RadioButton "
       "(instanceName absolute) "
       "(resources "
        "((callback _whatTime) "
         "(multichoice timeMulti) "
         "(labelString Absolute))))) "
     "(constraint R0C0A0) "
     "(child "
      "(RadioButton "
       "(instanceName relative) "
       "(resources "
        "((callback _whatTime) "
         "(multichoice timeMulti) "
         "(labelString Relative))))) "
     "(constraint R0C1A0) "
     "(child "
      "(RadioButton "
       "(instanceName scrolling) "
       "(resources "
        "((callback _whatTime) "
         "(multichoice timeMulti) "
         "(labelString Scrolling))))) "
     "(constraint R0C2A0) "
     "(child "
      "(RadioButton "
       "(instanceName none) "
       "(resources "
        "((callback _whatTime) "
         "(multichoice timeMulti) "
         "(labelString None))) "
       "(selected True))) "
     "(constraint R0C3A0))) "
   "(constraint R0C1A4) "
   "(child "
    "(Label "
     "(resources "
      "((labelString Keep\\ maximum\\ scale:))))) "
   "(constraint R1C0A6) "
   "(child "
    "(CheckBox "
     "(instanceName maxButton) "
     "(resources "
      "((callback _keepMax) "
       "(labelString ))))) "
   "(constraint R1C1A4) "
   "(child "
    "(Label "
     "(resources "
      "((labelString Lock\\ percentage\\ scales:))))) "
   "(constraint R2C0A6) "
   "(child "
    "(CheckBox "
     "(instanceName percButton) "
     "(resources "
      "((callback _lockPercScales) "
       "(labelString ))))) "
   "(constraint R2C1A4) "
   "(child "
    "(Label "
     "(resources "
      "((labelString Synchronize\\ scales:))))) "
   "(constraint R3C0A6) "
   "(child "
    "(CheckBox "
     "(instanceName syncButton) "
     "(resources "
      "((callback _syncScales) "
       "(labelString ))))) "
   "(constraint R3C1A4) "
   "(child "
    "(Label "
     "(resources "
      "((labelString Interface:))))) "
   "(constraint R4C0A6) "
   "(child "
    "(Deck "
     "(instanceName interfaceDeck) "
     "(child "
      "(Frame "
       "(instanceName interfaceFrame) "
       "(resources "
        "((frame Innie))) "
       "(child "
        "(TextField "
         "(instanceName interfaceField) "
         "(text ) "
         "(resources "
          "((terminatorCallBack _interfaceType) "
           "(keepAllTextVisible False))))))) "
     "(child "
      "(Label "
       "(instanceName interfaceLabel) "
       "(resources "
        "((labelString Label))))))) "
   "(constraint R4C1A4) "
   "(child "
    "(Label "
     "(resources "
      "((labelString Time\\ interval:))))) "
   "(constraint R5C0A6) "
   "(child "
    "(Deck "
     "(instanceName intervalDeck) "
     "(child "
      "(RowColumn "
       "(instanceName intervalRC) "
       "(rows 1) "
       "(cols 3) "
       "(defaultAlignment 4) "
       "(resources "
        "((rightInset 150) "
         "(horizontalOffset 10) "
         "(fixedHeight True))) "
       "(child "
        "(Frame "
         "(resources "
          "((frame Innie))) "
         "(child "
          "(TextField "
           "(instanceName intervalField) "
           "(text ) "
           "(resources "
            "((terminatorCallBack _intervalType) "
             "(keepAllTextVisible False))))))) "
       "(constraint R0C0A4) "
       "(child "
        "(Label "
         "(resources "
          "((labelString seconds))))) "
       "(constraint R0C1A4))) "
     "(child "
      "(Label "
       "(instanceName intervalLabel) "
       "(resources "
        "((labelString Label))))))) "
   "(constraint R5C1A4) "
   "(child "
    "(Label "
     "(resources "
      "((labelString Average\\ period:))))) "
   "(constraint R6C0A6) "
   "(child "
    "(RowColumn "
     "(rows 1) "
     "(cols 3) "
     "(defaultAlignment 4) "
     "(resources "
      "((rightInset 150) "
       "(horizontalOffset 10) "
       "(fixedHeight True))) "
     "(child "
      "(Frame "
       "(resources "
        "((frame Innie))) "
       "(child "
        "(TextField "
         "(instanceName avgPeriodField) "
         "(text ) "
         "(resources "
          "((terminatorCallBack _avgPerType) "
           "(keepAllTextVisible False))))))) "
     "(constraint R0C0A4) "
     "(child "
      "(Label "
       "(resources "
        "((labelString seconds))))) "
     "(constraint R0C1A4))) "
   "(constraint R6C1A4) "
   "(child "
    "(Label "
     "(resources "
      "((labelString Time\\ period:))))) "
   "(constraint R7C0A6) "
   "(child "
    "(RowColumn "
     "(rows 1) "
     "(cols 3) "
     "(defaultAlignment 4) "
     "(resources "
      "((rightInset 150) "
       "(horizontalOffset 10) "
       "(fixedHeight True))) "
     "(child "
      "(Frame "
       "(resources "
        "((frame Innie))) "
       "(child "
        "(TextField "
         "(instanceName periodField) "
         "(text ) "
         "(resources "
          "((terminatorCallBack _perType) "
           "(keepAllTextVisible False))))))) "
     "(constraint R0C0A4) "
     "(child "
      "(Label "
       "(resources "
        "((labelString seconds))))) "
     "(constraint R0C1A4))) "
   "(constraint R7C1A4) "
   "(child "
    "(Label "
     "(instanceName updateLabel) "
     "(resources "
      "((labelString Update\\ time:))))) "
   "(constraint R8C0A6) "
   "(child "
    "(RowColumn "
     "(instanceName updateRC) "
     "(rows 1) "
     "(cols 3) "
     "(defaultAlignment 4) "
     "(resources "
      "((rightInset 150) "
       "(horizontalOffset 10) "
       "(fixedHeight True))) "
     "(child "
      "(Frame "
       "(resources "
        "((frame Innie))) "
       "(child "
        "(TextField "
         "(instanceName updateField) "
         "(text ) "
         "(resources "
          "((terminatorCallBack _updateTimeType) "
           "(keepAllTextVisible False))))))) "
     "(constraint R0C0A4) "
     "(child "
      "(Label "
       "(resources "
        "((labelString seconds))))) "
     "(constraint R0C1A4))) "
   "(constraint R8C1A4))) "
 "(constraint R0C0A0) "
 "(child "
  "(Separator "
   "(orientation horizontal))) "
 "(constraint R1C0A0) "
 "(child "
  "(RowColumn "
   "(rows 1) "
   "(cols 3) "
   "(defaultAlignment 0) "
   "(resources "
    "((horizontalOffset 8) "
     "(fixedHeight True))) "
   "(child "
    "(LabelButton "
     "(resources "
      "((callback __ParamControl_close) "
       "(accelerator Alt\\ c) "
       "(labelString Close))))) "
   "(constraint R0C1A0) "
   "(child "
    "(LabelButton "
     "(resources "
      "((callback __ParamControl_help) "
       "(accelerator Alt\\ h) "
       "(labelString Help))))) "
   "(constraint R0C2A0))) "
 "(constraint R2C0A0))";
