/* Layout file created by tedit */

#ifndef TUDONTAUTOINCLUDE
#include "tuScrollBar.h"
#include "tuDecoratedButton.h"
#include "tuBBoard.h"
#include "tuRowColumn.h"
#include "tuFrame.h"
#endif /* TUDONTAUTOINCLUDE */

#ifdef TUREGISTERGADGETS
#undef TUREGISTERGADGETS
#endif /* TUREGISTERGADGETS */
#define TUREGISTERGADGETS { \
    tuScrollBar::registerForPickling(); \
    tuDecoratedButton::registerForPickling(); \
    tuBBoard::registerForPickling(); \
    tuRowColumn::registerForPickling(); \
    tuFrame::registerForPickling(); \
}

static char* layoutstr =
"(Frame "
 "(resources "
  "((frame Innie))) "
 "(child "
  "(RowColumn "
   "(rows 2) "
   "(cols 1) "
   "(defaultAlignment 0) "
   "(resources "
    "((topInset 10) "
     "(bottomInset 10) "
     "(leftInset 10) "
     "(rightInset 10) "
     "(verticalOffset 10) "
     "(fixedHeight True))) "
   "(child "
    "(ScrollBar "
     "(instanceName scroller) "
     "(orientation horizontal) "
     "(resources "
      "((dragCallBack _dragCB) "
       "(pageIncCallBack _pageIncCB) "
       "(pageDecCallBack _pageDecCB) "
       "(incCallBack _incCB) "
       "(decCallBack _decCB))))) "
   "(constraint R0C0A0) "
   "(child "
    "(RowColumn "
     "(rows 1) "
     "(cols 7) "
     "(defaultAlignment 0) "
     "(resources "
      "((horizontalOffset 8) "
       "(fixedHeight True))) "
     "(child "
      "(BBoard "
       "(child "
        "(DecoratedButton "
         "(resources "
          "((callback _fastbackCB) "
           "(labelString ) "
           "(decoration Rewind))))) "
       "(constraint 34x30+0+0))) "
     "(constraint R0C1A0) "
     "(child "
      "(BBoard "
       "(child "
        "(DecoratedButton "
         "(resources "
          "((callback _backCB) "
           "(labelString ) "
           "(decoration Reverse))))) "
       "(constraint 34x30+0+0))) "
     "(constraint R0C2A0) "
     "(child "
      "(BBoard "
       "(child "
        "(DecoratedButton "
         "(resources "
          "((callback _stopCB) "
           "(labelString ))))) "
       "(constraint 34x30+0+0))) "
     "(constraint R0C3A0) "
     "(child "
      "(BBoard "
       "(child "
        "(DecoratedButton "
         "(resources "
          "((callback _forwardCB) "
           "(labelString ) "
           "(decoration Play))))) "
       "(constraint 34x30+0+0))) "
     "(constraint R0C4A0) "
     "(child "
      "(BBoard "
       "(child "
        "(DecoratedButton "
         "(resources "
          "((callback _fastforwardCB) "
           "(labelString ) "
           "(decoration FastForward))))) "
       "(constraint 34x30+0+0))) "
     "(constraint R0C5A0))) "
   "(constraint R1C0A0))))";
