/* Layout file created by tedit */

#ifndef TUDONTAUTOINCLUDE
#include "tuLabel.h"
#include "tuRowColumn.h"
#include "tuFrame.h"
#include "tuBBoard.h"
#include "tuGap.h"
#endif /* TUDONTAUTOINCLUDE */

#ifdef TUREGISTERGADGETS
#undef TUREGISTERGADGETS
#endif /* TUREGISTERGADGETS */
#define TUREGISTERGADGETS { \
    myLabel::registerForPickling(); \
    tuLabel::registerForPickling(); \
    tuRowColumn::registerForPickling(); \
    tuFrame::registerForPickling(); \
    tuBBoard::registerForPickling(); \
    tuGap::registerForPickling(); \
}

static char* layoutstr =
"(Frame "
 "(resources "
  "((frame Innie))) "
 "(child "
  "(RowColumn "
   "(instanceName stripRC) "
   "(rows 3) "
   "(cols 2) "
   "(defaultAlignment 0) "
   "(resources "
    "((topInset 5) "
     "(leftInset 10) "
     "(rightInset 10) "
     "(horizontalOffset 10) "
     "(verticalOffset 1))) "
   "(child "
    "(RowColumn "
     "(rows 1) "
     "(cols 3) "
     "(defaultAlignment 0) "
     "(resources "
      "((bottomInset 1) "
       "(horizontalOffset 5) "
       "(fixedHeight True))) "
     "(child "
      "(RowColumn "
       "(rows 2) "
       "(cols 1) "
       "(defaultAlignment 0) "
       "(resources "
        "((horizontalOffset 5) "
         "(verticalOffset 1) "
         "(fixedHeight True))) "
       "(child "
        "(Label "
         "(instanceName filterLabel) "
         "(resources "
          "((labelString total) "
           "(font -*-helvetica-bold-r-normal--12-*-*-*-p-70-iso8859-1))))) "
       "(constraint R0C0A0) "
       "(child "
        "(Label "
         "(instanceName typeLabel) "
         "(resources "
          "((labelString \\(bytes\\ /\\ second\\)) "
           "(font -*-helvetica-bold-r-normal--12-*-*-*-p-70-iso8859-1))))) "
       "(constraint R1C0A4))) "
     "(constraint R0C0A0) "
     "(child "
      "(RowColumn "
       "(rows 2) "
       "(cols 3) "
       "(defaultAlignment 0) "
       "(resources "
        "((horizontalOffset 5) "
         "(verticalOffset 1) "
         "(fixedWidth True) "
         "(fixedHeight True))) "
       "(child "
        "(Label "
         "(resources "
          "((labelString High:) "
           "(font -*-helvetica-medium-r-normal--12-*-*-*-p-67-iso8859-1))))) "
       "(constraint R0C0A0) "
       "(child "
        "(myLabel "
         "(instanceName maxValLabel) "
         "(resources "
          "((labelString 123456789xx\\ ) "
           "(font -*-screen-medium-r-normal--16-*-*-*-m-80-iso8859-1))))) "
       "(constraint R0C1A0) "
       "(child "
        "(Label "
         "(resources "
          "((labelString Now:) "
           "(font -*-helvetica-medium-r-normal--12-*-*-*-p-67-iso8859-1))))) "
       "(constraint R1C0A0) "
       "(child "
        "(myLabel "
         "(instanceName curValLabel) "
         "(resources "
          "((labelString 12345.67890\\ ) "
           "(font -*-screen-medium-r-normal--16-*-*-*-m-80-iso8859-1))))) "
       "(constraint R1C1A0))) "
     "(constraint R0C2A0))) "
   "(constraint R0C0A0) "
   "(child "
    "(Frame "
     "(instanceName GLparent) "
     "(resources "
      "((frame Innie2))))) "
   "(constraint R1C0A16) "
   "(child "
    "(RowColumn "
     "(rows 4) "
     "(cols 2) "
     "(growdir vertical) "
     "(defaultAlignment 10) "
     "(resources "
      "((fixedWidth True))) "
     "(child "
      "(BBoard "
       "(child "
        "(myLabel "
         "(instanceName scaleLabel) "
         "(resources "
          "((labelString 12345000) "
           "(font -*-screen-medium-r-normal--16-*-*-*-m-80-iso8859-1))))) "
       "(constraint 69x15+0+0))) "
     "(constraint R0C0A10) "
     "(child "
      "(Label "
       "(resources "
        "((labelString 0) "
         "(font -*-screen-medium-r-normal--16-*-*-*-m-80-iso8859-1))))) "
     "(constraint R3C0A8))) "
   "(constraint R1C1A16) "
   "(child "
    "(Gap "
     "(orientation horizontal) "
     "(resources "
      "((minWidth 200))))) "
   "(constraint R2C0A0) "
   "(child "
    "(RowColumn "
     "(rows 1) "
     "(cols 1) "
     "(defaultAlignment 0) "
     "(resources "
      "((fixedWidth True) "
       "(fixedHeight True))) "
     "(child "
      "(Gap "
       "(orientation horizontal) "
       "(resources "
        "((minWidth 70))))) "
     "(constraint R0C0A0))) "
   "(constraint R2C1A0))))";
