/**************************************************************************
 *									  *
 *		 Copyright (C) 1995-1996 Silicon Graphics, Inc.		  *
 *									  *
 *  These coded instructions, statements, and computer programs  contain  *
 *  unpublished  proprietary  information of Silicon Graphics, Inc., and  *
 *  are protected by Federal copyright law.  They  may  not be disclosed  *
 *  to  third  parties  or copied or duplicated in any form, in whole or  *
 *  in part, without the prior written consent of Silicon Graphics, Inc.  *
 *									  *
 **************************************************************************/

#ident	"$Id: spec_ds.idl,v 1.7 1998/05/14 15:01:29 jtk Exp $"

/*
 * Message interfaces exported by the server-side 'specfs' structure.
 */
#include "ksys/cell/subsysid.h"

subsystem	"spec_ds"	DSSPECFS_SUBSYSID

import <sys/strsubr.h>
import <ksys/cell/tkm.h>
import <ksys/cell/service.h>
import <ksys/cell.h>

import <sys/vnode.h>

import <ksys/ddmap.h>
import <ksys/vop_backdoor.h>

import <os/as/region.h>

import <fs/specfs/spec_ops.h>

synchronous void
attach(
	in	valueof		dev_t		dev,
	in	valueof		vtype_t		type,
	out	pointerto	spec_handle_t	handle,
	out	pointerto	spec_handle_t	commonvp,
	out	pointerto	long		gen,
	out	pointerto	long		size,
	out	pointerto	spec_handle_t	stream)

synchronous void
clone(
	in	pointerto	spec_handle_t	handle,
	in	pointerto	spec_handle_t	stp,
	in	pointerto	spec_handle_t	ovp_handle,
	in	valueof		int		flag,
	out	pointerto	spec_handle_t	stream)

synchronous int
open(
	in	pointerto	spec_handle_t	handle,
	in	valueof		long		gen,
	in	valueof		mode_t		flag,		
	in 	valueof		credid_t	credid,
	inout	pointerto	dev_t		newdev,
	inout	pointerto	long		cs_size,
	out	pointerto	spec_handle_t	stp)

synchronous int
read(
	in	pointerto	spec_handle_t 	handle,
	in	valueof		long		gen,
	in	pointerto	<struct uio>	uiop,
	in	bufferof	<struct iovec>	iovp,
	in	valueof		int		ioflag,
	in 	valueof		credid_t	credid,
	in	pointerto	<struct flid>	fl,
	out	pointerto	off_t		uio_offset,
	out	pointerto	short		uio_sigpipe,
	out	pointerto	ssize_t		uio_resid)

synchronous int
list_read(
	in	pointerto	spec_handle_t 	handle,
	in	valueof		long		gen,
	in	pointerto	<struct uio>	uiop,
	in	bufferof	<struct iovec>	iovp,
	in	bufferof	<struct external_alenlist> alist,
	in	valueof		int		ioflag,
	in 	valueof		credid_t	credid,
	in	pointerto	<struct flid>	fl,
	out	pointerto	off_t		uio_offset,
	out	pointerto	short		uio_sigpipe,
	out	pointerto	ssize_t		uio_resid)

synchronous int
write(
	in	pointerto	spec_handle_t 	handle,
	in	valueof		long		gen,
	in	pointerto	<struct uio>	uiop,
	in	bufferof	<struct iovec>	iovp,
	in	valueof		int		ioflag,
	in 	valueof		credid_t	credid,
	in	pointerto	<struct flid>	fl,
	out	pointerto	off_t		uio_offset,
	out	pointerto	short		uio_sigpipe,
	out	pointerto	ssize_t		uio_resid)

synchronous int
list_write(
	in	pointerto	spec_handle_t 	handle,
	in	valueof		long		gen,
	in	pointerto	<struct uio>	uiop,
	in	bufferof	<struct iovec>	iovp,
	in	bufferof	<struct external_alenlist> alist,
	in	valueof		int		ioflag,
	in 	valueof		credid_t	credid,
	in	pointerto	<struct flid>	fl,
	out	pointerto	off_t		uio_offset,
	out	pointerto	short		uio_sigpipe,
	out	pointerto	ssize_t		uio_resid)

synchronous int
close(
	in	pointerto	spec_handle_t 	handle,
	in	valueof		int		flag,
	in	valueof		lastclose_t	lastclose,
	in 	valueof		credid_t	credid)

synchronous int
poll(
	in	pointerto	spec_handle_t	handle,
	in	valueof		long		gen,
	in	valueof		short		events,
	in	valueof		int		anyyet,
	inout	pointerto	short		reventsp,
	inout	pointerto	spec_handle_t	phpp,
	out	pointerto	uint		genp)

asynchronous
strategy(
	in	pointerto	spec_handle_t	handle,
	in	pointerto	spec_handle_t	bp_handle,
	in	pointerto	<struct buf>	bp,
	in	bufferof	<struct external_alenlist> alist)

synchronous int
bmap(
	in	pointerto	spec_handle_t	handle,
	in	valueof		off_t		offset,
	in	valueof		ssize_t		count,
	in	valueof		int		rw,
	in 	valueof		credid_t	credid,
	out	pointerto	<struct bmapval> bmap,
	out	pointerto	int		nbmap)

synchronous int
ioctl(
	in	pointerto	spec_handle_t	handle,
	in	valueof		long		gen,
	in	valueof		int		cmd,
	in	valueof 	<void *>	arg,
	in	valueof		int		mode,
	in 	valueof		credid_t	credid,
	inout	pointerto	int		rvalp,
        out     pointerto       <struct vopbd>  vbd)

synchronous int
strgetmsg(
	in	pointerto	spec_handle_t	handle,
	in	pointerto	<struct strbuf>	mctl,
	in	pointerto	<struct strbuf>	mdata,
	in	pointerto 	<unsigned char>	prip,
	in 	pointerto	int		flagsp,
	in	valueof		int		fmode,
	inout	pointerto	<union rval>	rvp)

synchronous int
strputmsg(
	in	pointerto	spec_handle_t	handle,
	in	pointerto	<struct strbuf>	mctl,
	in	pointerto	<struct strbuf>	mdata,
	in	valueof 	<unsigned char>	pri,
	in 	valueof		int		flags,
	in	valueof		int		fmode)

synchronous int
addmap(
	in	pointerto	spec_handle_t	handle,
	in	valueof		vaddmap_t	op,
	in	pointerto	<struct __vhandl_s>	vt,
	in	valueof		off_t		off,
	in	valueof		size_t		len,
	in	valueof		mprot_t		prot,
	in 	valueof		credid_t	credid,
	out	pointerto	pgno_t		pgno)

synchronous int
delmap(
	in	pointerto	spec_handle_t	handle,
	in	pointerto	<struct __vhandl_s>	vt,
	in	valueof		size_t		len,
	in 	valueof		credid_t	credid)

synchronous int
cmp_gen(
	in	pointerto	spec_handle_t	handle,
	in	valueof		long		lsp_gen)

synchronous int
get_gen(
	in	pointerto	spec_handle_t	handle)

synchronous int
get_opencnt(
	in	pointerto	spec_handle_t	handle)

synchronous void
get_size(
	in	pointerto	spec_handle_t	handle,
	out	pointerto	daddr_t		size)

synchronous int
ismounted(
	in	pointerto	spec_handle_t	handle)

synchronous void
mountedflag(
	in	pointerto	spec_handle_t	handle,
	in	valueof		int		set)

synchronous void
teardown(
	in	pointerto	spec_handle_t	handle)


/*
 * ======================================================================
 * Any interface defined below this comment block is left-over from
 * originally "ripping" a copy of fs/cfs/dsvn.idl as a template to
 * start from.	XXXjtk
 * ======================================================================
 */

#ifdef	LATER_MAYBE
/*
 * Token interfaces.
 */
synchronous  void
return(
	in	valueof		objid_t 	objid,
	in	valueof		cell_t		client,
	in	valueof		tk_set_t	retset,
	in	valueof		tk_set_t	unknownset,
	in	valueof		tk_disp_t	why)

synchronous  void
refuse(
	in	valueof		objid_t 	objid,
	in	valueof		cell_t		client,
	in	valueof		tk_set_t	refset,
	in	valueof		tk_disp_t	why)

synchronous  void
notfound(
	in	pointerto	spec_handle_t 	handlep,
	in	valueof		cell_t		client,
	in	valueof		tk_set_t	notfound_set,
	in	valueof		tk_disp_t	why)

synchronous  void
obtain_exist(
	in	pointerto	spec_handle_t 	handlep,
	in	valueof		cell_t		client,
	out	pointerto	tk_set_t	obtset,
	out	pointerto	<enum vtype>	vtype,
	out	pointerto	dev_t		dev,
	out	pointerto	int		flags,	
	out	pointerto	spec_handle_t	vfs_handle)
#endif 	/* LATER_MAYBE */
