/**************************************************************************
 *									  *
 *		 Copyright (C) 1995-1996 Silicon Graphics, Inc.		  *
 *									  *
 *  These coded instructions, statements, and computer programs  contain  *
 *  unpublished  proprietary  information of Silicon Graphics, Inc., and  *
 *  are protected by Federal copyright law.  They  may  not be disclosed  *
 *  to  third  parties  or copied or duplicated in any form, in whole or  *
 *  in part, without the prior written consent of Silicon Graphics, Inc.  *
 *									  *
 **************************************************************************/

#ident	"$Id: spec_dc.idl,v 1.1 1997/09/08 18:25:33 jtk Exp $"

/*
 * Message interfaces exported by the client-side 'specfs' structure.
 */
#include "ksys/cell/subsysid.h"

subsystem	"spec_dc"	DCSPECFS_SUBSYSID

import <sys/strsubr.h>
import <ksys/cell/tkm.h>
import <ksys/cell/service.h>
import <ksys/cell.h>

import <sys/vnode.h>

import <ksys/ddmap.h>
import <ksys/vop_backdoor.h>

import <fs/specfs/spec_ops.h>

asynchronous
strategy(
	in	pointerto	spec_handle_t	handle,
	in	pointerto	spec_handle_t	bp_handle,
	in	pointerto	<struct buf>	bp)
