#!/bin/sh -x

BLANA=jhunter@192.26.81.86:/var/www/htdocs/SQA/xperform/scripts
MACHNAME=treefrog
MACHIPADDR=192.26.81.102

# prepare for network
echo $MACHNAME > /etc/sys_id
grep -v IRIS /etc/hosts > /etc/hostsold
echo "$MACHIPADDR      $MACHNAME        $MACHNAME.engr.sgi.com" > /etc/hostsnew
cat /etc/hostsold /etc/hostsnew > /etc/hosts
rm /etc/hostsold /etc/hostsnew
chkconfig network on
chkconfig yp on
echo engr.sgi.com > /var/yp/ypdomain

init 6
