'\"macro stdmacro
.TH BCsource 5
.SH NAME
BCsource \- archive of bc and dc sources
.SH DESCRIPTION
The file
.B /usr/src/rcs/BCsource.Z
contains
the compressed cpio archive of compilable
sources for the port of GNU bc version 1.03 and GNU dc version 1.0 to
Silicon Graphics systems.
This source is provided to you under the terms of
the GNU General Public License, as described below.
.P
To decompress this source archive
create a new directory, change to that
directory (cd), and issue the command:
.PP
zcat /usr/src/rcs/BCsource.Z | cpio -icv
.PP
View the decompressed file README for further instructions
on how to rebuild this product.
.PP
bc and dc are free software; you can redistribute them and/or modify
them under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.
.PP
bc and dc are distributed in the hope that they will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the
GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License
along with this software; see the file COPYING.
If not, write to
the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
.SH FILES
.PD 0
.TP 12
.B /usr/src/rcs/BCsource.Z
Compressed cpio archive
of sources for port of bc version 1.03 and dc version 1.0 to
Silicon Graphics systems.
.SH SEE ALSO
bc(1),
dc(1)
