'\"macro stdmacro
.if n .pH g5.nl_types @(#)nl_types	40.7 of 5/1/91
.\" Copyright 1989 AT&T
.nr X
.if \nX=0 .ds x} nl_types 5 "" "\&"
.if \nX=1 .ds x} nl_types 5 ""
.if \nX=2 .ds x} nl_types 5 "" "\&"
.if \nX=3 .ds x} nl_types "" "" "\&"
.TH \*(x}
.SH NAME
\f4nl_types\f1 \- native language data types
.SH "SYNOPSIS"
.nf
\f4#include <nl_types.h>\f1\f4\f1
.fi
.SH "DESCRIPTION"
This header file contains the following definitions:
.PP
.TP 15
\f4nl_catd\fP
used by the message catalog functions \f4catopen\fP, \f4catgets\fP and
\f4catclose\fP to identify a catalog
.TP
\f4nl_item\fP
used by \f4nl_langinfo\fP to identify items of \f4langinfo\fP data.
Values for objects of type \f4nl_item\fP are defined in \f4langinfo.h\fP
.TP
\f4NL_SETD\fP
used by \f4gencat\fP when no \f4$set\f1 directive is specified in a
message text source file.
This constant can be used in subsequent calls
to \f4catgets\fP as the value of the set identifier parameter.
.TP
\f4NL_MGSMAX\fP
maximum number of messages per set
.TP
\f4NL_SETMAX\fP
maximum number of sets per catalog
.TP
\f4NL_TEXTMAX\fP
maximum size of a message
.TP
\f4DEF_NLSPATH\fP
the default search path for locating catalogs
.TP
\f4NL_CAT_LOCALE\fP
used by the X/Open Release 4 Version 2 standard and is set to a value of one.
.SH "SEE ALSO"
gencat(1M),
catgets(3C),
catopen(3C),
nl_langinfo(3C),
langinfo(5)
