'\"! tbl | mmdoc
'\"macro stdmacro
.if n .pH g5.term @(#)term	30.13 of 2/20/86
.nr X
.if \nX=0 .ds x} term 5 ""  "\&"
.if \nX=1 .ds x} term 5 ""
.if \nX=2 .ds x} term 5 "" "\&"
.if \nX=3 .ds x} term "" "" "\&"
.TH \*(x}
.SH NAME
term \- conventional names for terminals
.SH DESCRIPTION
These names are used by certain commands (e.g.,
.IR man (1) ,
.IR tabs (1) ,
.IR tput (1) ,
.IR vi (1)
and
.IR curses (3X))
and are maintained as part of the shell environment
in the environment variable
.B TERM
(see
.IR sh (1),
.IR profile (4),
and
.IR environ (5)).
.PP
Entries in
.IR terminfo (4)
source files
consist of a number of comma-separated fields.
(To obtain the source description for a terminal,
use the
.B \-I
option of
.IR infocmp (1M).)
White space after each comma is ignored.
The first line of each terminal description
in the
.IR terminfo (4)
database gives the
names by which
.IR terminfo (4)
knows the terminal,
separated by bar ( | ) characters.
The first name given is the most common abbreviation for the terminal
(this is the one to use to set the environment
variable
.B TERMINFO
in
.IR $HOME/.profile ;
see \f2profile\f1(4)),
the last name given should be a long name fully identifying the terminal,
and all others are understood as synonyms for the terminal name.
All names but the last should contain no blanks
and must be unique in the first 14 characters;
the last name may contain blanks for readability.
.P
Terminal names
(except for the last, verbose entry)
should be chosen using the following conventions.
The particular piece of hardware making up the terminal should
have a root name chosen, for example,
for the AT&T 4425 terminal, \f3att4425\f1.
This name should not contain hyphens, except that synonyms may
be chosen that do not conflict with other names.
Up to 8 characters, chosen from [a\-z0\-9],
make up a basic terminal name.
Names should generally be based on original vendors,
rather than local distributors.
A terminal acquired from one vendor should not have more than
one distinct basic name.
Terminal sub-models, operational modes that the hardware can be in, or user
preferences, should be indicated by appending a hyphen and an indicator of
the mode.
Thus, an AT&T 4425 terminal in 132 column mode would be \f3att4425\-w\f1.
The following suffixes should be used where possible:
.PP
.columns 2 4 2
.TS
l c l
l l l.
\f3Suffix\f1	\f3Meaning\f1	\f3Example\f1
\f3\-w\f1	Wide mode (more than 80 columns)	att4425\-w
\f3\-am\f1	With auto. margins (usually default)	vt100\-am
\f3\-nam\f1	Without automatic margins	vt100\-nam
\-n	Number of lines on the screen	aaa\-60
\f3\-na\f1	No arrow keys (leave them in local)	c100\-na
\-n\f3p\f1	Number of pages of memory	c100\-4p
\f3\-rv\f1	Reverse video	att4415\-rv
.TE
.P
To avoid conflicts with the naming conventions used in
describing the different modes of a terminal (e.g.,
\f3\-w\f1), it is recommended that a terminal's
root name not contain hyphens.
Further, it is good practice to make all terminal
names used in the \f2terminfo\f1(4) database unique.
Terminal entries that are present only for
inclusion in other entries via the
\f3use\f1= facilities should have a '+' in their name,
as in
.BR 4415+nl .
.PP
Some of the known terminal names may include the following
(for a complete list, type:
.BR "ls -C /usr/lib/terminfo/?" ):
.PP
.columns 3 5
.TS
l l.
2621,hp2621	Hewlett-Packard 2621 series
2631	Hewlett-Packard 2631 line printer
2631\-c	Hewlett-Packard 2631
	line printer - compressed mode
2631\-e	Hewlett-Packard 2631
	line printer - expanded mode
2640,hp2640	Hewlett-Packard 2640 series
2645,hp2645	Hewlett-Packard 2645 series
3270	IBM Model 3270
33,tty33	AT&T Teletype Model 33 KSR
35,tty35	AT&T Teletype Model 35 KSR
37,tty37	AT&T Teletype Model 37 KSR
4000a	Trendata 4000a
4014,tek4014	TEKTRONIX 4014
40,tty40	AT&T Teletype Dataspeed 40/2
43,tty43	AT&T Teletype Model 43 KSR
4410,5410	AT&T 4410/5410 terminal
	in 80-column mode - version 2
4410\-nfk,5410\-nfk	AT&T 4410/5410
	without function keys - version 1
4410\-nsl,5410\-nsl	AT&T 4410/5410 without pln defined
4410\-w,5410\-w	AT&T 4410/5410 in 132-column mode
4410v1,5410v1	AT&T 4410/5410 terminal
	in 80-column mode - version 1
4410v1\-w,5410v1\-w	AT&T 4410/5410 terminal
	in 132-column mode - version 1
4415,5420	AT&T 4415/5420 in 80-column mode
4415\-nl,5420\-nl	AT&T 4415/5420 without changing labels
4415\-rv,5420\-rv	AT&T 4415/5420 80 columns in reverse video
4415\-rv\-nl,5420\-rv\-nl	AT&T 4415/5420 reverse video
	without changing labels
4415\-w,5420\-w	AT&T 4415/5420 in 132-column mode
4415\-w\-nl,5420\-w\-nl	AT&T 4415/5420 in 132-column mode
	without changing labels
4415\-w\-rv,5420\-w\-rv	AT&T 4415/5420 132 columns in reverse video
4415\-w\-rv\-nl,5420\-w\-rv\-nl	AT&T 4415/5420 132 columns reverse video
	without changing labels
4418,5418	AT&T 5418 in 80-column mode
4418\-w,5418\-w	AT&T 5418 in 132-column mode
4420	AT&T Teletype Model 4420
4424	AT&T Teletype Model 4424
4424-2	AT&T Teletype Model 4424
	in display function group ii
4425,5425	AT&T 4425/5425
4425\-fk,5425\-fk	AT&T 4425/5425 without function keys
4425\-nl,5425\-nl	AT&T 4425/5425 without changing labels
	in 80-column mode
4425\-w,5425\-w	AT&T 4425/5425 in 132-column mode
4425\-w\-fk,5425\-w\-fk	AT&T 4425/5425 without function keys
	in 132-column mode
4425\-nl\-w,5425\-nl\-w	AT&T 4425/5425 without changing labels
	in 132-column mode
4426	AT&T Teletype Model 4426S
450	DASI 450 (same as Diablo 1620)
450\-12	DASI 450 in 12-pitch mode
500,att500	AT&T-IS 500 terminal
510,510a	AT&T 510/510a in 80-column mode
513bct,att513	AT&T 513 bct terminal
5320	AT&T 5320 hardcopy terminal
5420_2	AT&T 5420 model 2 in 80-column mode
5420_2\-w	AT&T 5420 model 2 in 132-column mode
5620,dmd	AT&T 5620 terminal 88 columns
5620\-24,dmd\-24	AT&T Teletype Model DMD 5620 in a 24x80 layer
5620\-34,dmd\-34	AT&T Teletype Model DMD 5620 in a 34x80 layer
610,610bct	AT&T 610 bct terminal in 80-column mode
610\-w,610bct\-w	AT&T 610 bct terminal in 132-column mode
7300,pc7300,unix_pc	AT&T UNIX PC Model 7300
735,ti	Texas Instruments TI35 and TI25
745	Texas Instruments TI45
dumb	generic name for terminals that lack reverse
	line-feed and other special escape sequences
hp	Hewlett-Packard (same as 2645)
iris\-ansi	SGI \f2wsh\f1(1) ANSI emulator (40 lines)
iris\-ansi\-24	SGI \f2wsh\f1(1) ANSI emulator (24 lines)
iris\-ansi\-66	SGI \f2wsh\f1(1) ANSI emulator (66 lines)
iris\-ansi\-net	SGI remote login from \f2wsh\f1(1) window
lp	generic name for a line printer
pt505	AT&T Personal Terminal 505 (22 lines)
pt505\-24	AT&T Personal Terminal 505 (24-line mode)
rwsiris	SGI remote login from visual 50 emulator
sync	generic name for synchronous Teletype Model
	4540-compatible terminals
wsiris	SGI visual 50 terminal emulator
.TE
.PP
Commands whose behavior depends on the type of terminal
should accept arguments of the form
.BI \-T term
where
.I term
is one of the names given above;
if no such argument is present,
such commands should
obtain the terminal type from
the environment variable
.BR TERM ,
which, in turn, should contain
.IR term .
.SH FILES
.nf
/usr/lib/terminfo/?/\(** compiled terminal description database
.fi
.SH SEE ALSO
infocmp(1M),
man(1),
sh(1),
stty(1),
tabs(1),
tplot(1G),
tput(1),
vi(1),
curses(3X),
profile(4),
terminfo(4),
environ(5)
.SH NOTES
Not all programs follow the above naming conventions.
.\"	@(#)term.5	6.2 of 9/6/83
