'\"macro stdmacro
.if n .pH g5.values @(#)values	30.2 of 12/25/85
.nr X
.if \nX=0 .ds x} values 5 ""  "\&"
.if \nX=1 .ds x} values 5 ""
.if \nX=2 .ds x} values 5 "" "\&"
.if \nX=3 .ds x} values "" "" "\&"
.TH \*(x}
.SH NAME
values \- machine-dependent values
.SH SYNOPSIS
.nf
\f3#include <values.h>\f1
.fi
.SH DESCRIPTION
This file contains a set of manifest constants,
conditionally defined for particular processor architectures.
.P
The model assumed for integers is binary representation
(one's or two's complement),
where the sign is represented by the value of the high-order bit.
.P
.TP 20
.RI BITS( type )
The number of bits in a specified type (e.g., int).
.TP 20
HIBITS
The value of a short integer with only the high-order bit set
(in most implementations, 0x8000).
.TP 20
HIBITL
The value of a long integer with only the high-order bit set
(in most implementations, 0x80000000).
.TP 20
HIBITI
The value of a regular integer with only the high-order bit set
(usually the same as HIBITS or HIBITL).
.TP 20
MAXSHORT
The maximum value of a signed short integer
(in most implementations, 0x7FFF \(== 32767).
.TP 20
MAXLONG
The maximum value of a signed long integer
(in most implementations, 0x7FFFFFFF \(== 2147483647).
.TP 20
MAXINT
The maximum value of a signed regular integer
(usually the same as MAXSHORT or MAXLONG).
.TP 30
MAXFLOAT, LN_MAXFLOAT
The maximum value of a single-precision floating-point number,
and its natural logarithm.
.TP 30
MAXDOUBLE, LN_MAXDOUBLE
The maximum value of a double-precision floating-point number,
and its natural logarithm.
.TP 30
MINFLOAT, LN_MINFLOAT
The minimum positive value of a single-precision floating-point number,
and its natural logarithm.
.TP 30
MINDOUBLE, LN_MINDOUBLE
The minimum positive value of a double-precision floating-point number,
and its natural logarithm.
.TP 20
FSIGNIF
The number of significant bits in the mantissa of a single-precision
floating-point number.
.TP 20
DSIGNIF
The number of significant bits in the mantissa of a double-precision
floating-point number.
.SH "SEE ALSO"
intro(3),
math(5)
.\"	@(#)values.5	6.4 of 4/2/84
