/* Layout file created by tedit */

#ifndef TUDONTAUTOINCLUDE
#include "tuRowColumn.h"
#include "tuTextField.h"
#include "tuFrame.h"
#include "tuGap.h"
#include "tuDefaultButton.h"
#include "tuLabelButton.h"
#include "tuDeck.h"
#endif /* TUDONTAUTOINCLUDE */

#ifdef TUREGISTERGADGETS
#undef TUREGISTERGADGETS
#endif /* TUREGISTERGADGETS */
#define TUREGISTERGADGETS { \
    tuRowColumn::registerForPickling(); \
    tuTextField::registerForPickling(); \
    tuFrame::registerForPickling(); \
    tuGap::registerForPickling(); \
    tuDefaultButton::registerForPickling(); \
    tuLabelButton::registerForPickling(); \
    tuDeck::registerForPickling(); \
}

static char* layoutstr =
"(RowColumn "
 "(rows 3) "
 "(cols 1) "
 "(growdir vertical) "
 "(defaultAlignment 0) "
 "(resources "
  "((topInset 8) "
   "(bottomInset 8) "
   "(leftInset 8) "
   "(rightInset 8) "
   "(horizontalOffset 8) "
   "(verticalOffset 8))) "
 "(child "
  "(RowColumn "
   "(instanceName _text_container) "
   "(rows 1) "
   "(cols 1) "
   "(growdir vertical) "
   "(defaultAlignment 0) "
   "(resources "
    "((rightInset 64))))) "
 "(constraint R0C0A0) "
 "(child "
  "(Frame "
   "(resources "
    "((frame Innie))) "
   "(child "
    "(TextField "
     "(instanceName _text_field) "
     "(text ) "
     "(resources "
      "((terminatorCallBack __tuPromptBox_textfield) "
       "(keepAllTextVisible False))))))) "
 "(constraint R1C0A0) "
 "(child "
  "(Deck "
   "(instanceName _deck) "
   "(child "
    "(RowColumn "
     "(instanceName __ok) "
     "(rows 1) "
     "(cols 3) "
     "(defaultAlignment 0) "
     "(resources "
      "((horizontalOffset 8))) "
     "(child "
      "(Gap "
       "(orientation horizontal) "
       "(resources "
        "((minWidth 50))))) "
     "(constraint R0C0A0) "
     "(child "
      "(DefaultButton "
       "(resources "
        "((callback __tuPromptBox_ok) "
         "(labelString OK))))) "
     "(constraint R0C1A0) "
     "(child "
      "(LabelButton "
       "(instanceName _map_button) "
       "(resources "
        "((callback __tuPromptBox_cancel) "
         "(labelString Cancel))))) "
     "(constraint R0C2A0))) "
   "(child "
    "(RowColumn "
     "(instanceName __reset_help) "
     "(rows 1) "
     "(cols 6) "
     "(defaultAlignment 0) "
     "(resources "
      "((horizontalOffset 8))) "
     "(child "
      "(Gap "
       "(orientation horizontal) "
       "(resources "
        "((minWidth 50))))) "
     "(constraint R0C0A0) "
     "(child "
      "(DefaultButton "
       "(resources "
        "((callback __tuPromptBox_ok) "
         "(labelString OK))))) "
     "(constraint R0C1A0) "
     "(child "
      "(LabelButton "
       "(resources "
        "((callback __tuPromptBox_apply) "
         "(labelString Apply))))) "
     "(constraint R0C2A0) "
     "(child "
      "(LabelButton "
       "(resources "
        "((callback __tuPromptBox_reset) "
         "(labelString Reset))))) "
     "(constraint R0C3A0) "
     "(child "
      "(LabelButton "
       "(instanceName _map_button) "
       "(resources "
        "((callback __tuPromptBox_cancel) "
         "(labelString Cancel))))) "
     "(constraint R0C4A0) "
     "(child "
      "(LabelButton "
       "(resources "
        "((callback __tuPromptBox_help) "
         "(labelString Help))))) "
     "(constraint R0C5A0))) "
   "(child "
    "(RowColumn "
     "(instanceName __reset) "
     "(rows 1) "
     "(cols 5) "
     "(defaultAlignment 0) "
     "(resources "
      "((horizontalOffset 8))) "
     "(child "
      "(Gap "
       "(orientation horizontal) "
       "(resources "
        "((minWidth 50))))) "
     "(constraint R0C0A0) "
     "(child "
      "(DefaultButton "
       "(resources "
        "((callback __tuPromptBox_ok) "
         "(labelString OK))))) "
     "(constraint R0C1A0) "
     "(child "
      "(LabelButton "
       "(resources "
        "((callback __tuPromptBox_apply) "
         "(labelString Apply))))) "
     "(constraint R0C2A0) "
     "(child "
      "(LabelButton "
       "(resources "
        "((callback __tuPromptBox_reset) "
         "(labelString Reset))))) "
     "(constraint R0C3A0) "
     "(child "
      "(LabelButton "
       "(instanceName _map_button) "
       "(resources "
        "((callback __tuPromptBox_cancel) "
         "(labelString Cancel))))) "
     "(constraint R0C4A0))) "
   "(child "
    "(RowColumn "
     "(instanceName __apply_help) "
     "(rows 1) "
     "(cols 5) "
     "(defaultAlignment 0) "
     "(resources "
      "((horizontalOffset 8))) "
     "(child "
      "(Gap "
       "(orientation horizontal) "
       "(resources "
        "((minWidth 50))))) "
     "(constraint R0C0A0) "
     "(child "
      "(DefaultButton "
       "(resources "
        "((callback __tuPromptBox_ok) "
         "(labelString OK))))) "
     "(constraint R0C1A0) "
     "(child "
      "(LabelButton "
       "(resources "
        "((callback __tuPromptBox_apply) "
         "(labelString Apply))))) "
     "(constraint R0C2A0) "
     "(child "
      "(LabelButton "
       "(instanceName _map_button) "
       "(resources "
        "((callback __tuPromptBox_cancel) "
         "(labelString Cancel))))) "
     "(constraint R0C3A0) "
     "(child "
      "(LabelButton "
       "(resources "
        "((callback __tuPromptBox_help) "
         "(labelString Help))))) "
     "(constraint R0C4A0))) "
   "(child "
    "(RowColumn "
     "(instanceName __apply) "
     "(rows 1) "
     "(cols 4) "
     "(defaultAlignment 0) "
     "(resources "
      "((horizontalOffset 8))) "
     "(child "
      "(Gap "
       "(orientation horizontal) "
       "(resources "
        "((minWidth 50))))) "
     "(constraint R0C0A0) "
     "(child "
      "(DefaultButton "
       "(resources "
        "((callback __tuPromptBox_ok) "
         "(labelString OK))))) "
     "(constraint R0C1A0) "
     "(child "
      "(LabelButton "
       "(resources "
        "((callback __tuPromptBox_apply) "
         "(labelString Apply))))) "
     "(constraint R0C2A0) "
     "(child "
      "(LabelButton "
       "(instanceName _map_button) "
       "(resources "
        "((callback __tuPromptBox_cancel) "
         "(labelString Cancel))))) "
     "(constraint R0C3A0))) "
   "(child "
    "(RowColumn "
     "(instanceName __ok_help) "
     "(rows 1) "
     "(cols 4) "
     "(defaultAlignment 0) "
     "(resources "
      "((horizontalOffset 8))) "
     "(child "
      "(Gap "
       "(orientation horizontal) "
       "(resources "
        "((minWidth 50))))) "
     "(constraint R0C0A0) "
     "(child "
      "(DefaultButton "
       "(resources "
        "((callback __tuPromptBox_ok) "
         "(labelString OK))))) "
     "(constraint R0C1A0) "
     "(child "
      "(LabelButton "
       "(instanceName _map_button) "
       "(resources "
        "((callback __tuPromptBox_cancel) "
         "(labelString Cancel))))) "
     "(constraint R0C2A0) "
     "(child "
      "(LabelButton "
       "(resources "
        "((callback __tuPromptBox_help) "
         "(labelString Help))))) "
     "(constraint R0C3A0))))) "
 "(constraint R2C0A0))";
