'\"macro stdmacro
.TH GZDIFF 1
.SH NAME
gzcmp, gzdiff \- compare compressed files
.SH SYNOPSIS
.B gzcmp
[ cmp_options ] file1
[ file2 ]
.br
.B gzdiff
[ diff_options ] file1
[ file2 ]
.SH DESCRIPTION
.I  Gzcmp
and 
.I gzdiff
are used to invoke the
.I cmp
or the
.I diff
program on compressed files.  All options specified are passed directly to
.I cmp
or
.IR diff "."
If only 1 file is specified, then the files compared are
.I file1
and an uncompressed
.IR file1 ".gz."
If two files are specified, then they are uncompressed if necessary and fed to
.I cmp
or
.IR diff "."
The exit status from 
.I cmp
or
.I diff
is preserved.
.SH "SEE ALSO"
cmp(1), diff(1), gzmore(1), gzgrep(1), gznew(1), gzforce(1), gzip(1), gzexe(1)
.SH BUGS
Messages from the
.I cmp
or
.I diff
programs refer to temporary filenames instead of those specified.
