'\"macro stdmacro
.TH GZGREP 1
.SH NAME
gzgrep \- search possibly compressed files for a regular expression
.SH SYNOPSIS
.B gzgrep
[ grep_options ]
.BI  [\ -e\ ] " pattern"
.IR filename ".\|.\|."
.SH DESCRIPTION
.IR  Gzgrep
is used to invoke the
.I grep
on compress'ed or gzip'ed files. All options specified are passed directly to
.I grep.
If no file is specified, then the standard input is decompressed
if necessary and fed to grep.
Otherwise the given files are uncompressed if necessary and fed to
.I grep.
.PP
If
.I gzgrep
is invoked as
.I gzegrep
or
.I gzfgrep
then
.I egrep
or
.I fgrep
is used instead of
.I grep.
If the GREP environment variable is set,
.I gzgrep
uses it as the
.I grep
program to be invoked. For example:

    for sh:  GREP=fgrep  gzgrep string files
    for csh: (setenv GREP fgrep; gzgrep string files)
.SH AUTHOR
Charles Levert (charles@comm.polymtl.ca)
.SH "SEE ALSO"
grep(1), egrep(1), fgrep(1), gzdiff(1), gzmore(1), gznew(1), gzforce(1),
gzip(1), gzexe(1)
