DIAGDEPTH= ../../..
include ${DIAGDEPTH}/Makedefs

LINCLUDES = -I../ 

CFILES= vino_regtest.c vino_i2ctest.c vino_i2c.c vino_dmatest.c

COMMONPREF = VINO
_lib ${COMMONTARGS}: ${COMMONPREF}$$@

include ${DIAGDEPTH}/Makerules

