#ident  "ide/godzilla/xbow/Makefile:  $Revision: 1.5 $"
#
# xbow diag makefile

DIAGDEPTH= ../..
include ${DIAGDEPTH}/Makedefs

ASFILES= asm_routines.s
CFILES=	x_regs.c 	\
	x_acc.c		\
	hx_badllp.c 	\
	x_util.c				\
  dxb.c
  

include ${DIAGDEPTH}/Makerules
LINCLUDES = -I../include
