# teton diag makefile

DIAGDEPTH= ../..
include ${DIAGDEPTH}/Makedefs

LDEFINES=-D_USE_SURESH_TEST

MIPSVERS=-mips4
ASFILES= tfpmisc.s fasttest.s
CFILES= tccfifo.c tccpref.c fast_iu.c

include ${DIAGDEPTH}/Makerules
