void helpOnContextCallback( Widget, XtPointer, XtPointer );
void aboutXdiffCallback( Widget, XtPointer, XtPointer );
void exitCallback( Widget, XtPointer, XtPointer );
void saveAsCallback( Widget, XtPointer, XtPointer );
void confirmCallback( Widget, XtPointer, XtPointer );
void xdConfirmSaveFile( ApplicationData *, char * );
void saveAsRightCallback( Widget, XtPointer, XtPointer );
void saveAsLeftCallback( Widget, XtPointer, XtPointer );
void selectGlobalLeftCallback( Widget, XtPointer, XtPointer );
void selectGlobalRightCallback( Widget, XtPointer, XtPointer );
void unselectGlobalCallback( Widget, XtPointer, XtPointer );
void selectGlobalNeitherCallback( Widget, XtPointer, XtPointer );
void tabsAt4Callback( Widget, XtPointer, XtPointer );
void tabsAt8Callback( Widget, XtPointer, XtPointer );
void postDrawingAreaMenu( Widget, XtPointer, XEvent *, Boolean * );
void rightWindowExposeCallback( Widget, XtPointer, XtPointer );
void leftWindowExposeCallback( Widget, XtPointer, XtPointer );
void viewAreaExposeCallback( Widget, XtPointer, XtPointer );
void viewAreaInputCallback( Widget, XtPointer, XtPointer );
void leftWindowInputCallback( Widget, XtPointer, XtPointer );
void rightWindowInputCallback( Widget, XtPointer, XtPointer );
void scrollVerticalCallback( Widget, XtPointer, XtPointer );
void scrollLeftCallback( Widget, XtPointer, XtPointer );
void scrollRightCallback( Widget, XtPointer, XtPointer );
void resizeEventHandler( Widget, XtPointer, XEvent *, Boolean * );
void listerOkCallback( Widget, XtPointer, XtPointer );
void listerCancelCallback( Widget, XtPointer, XtPointer );
void nextDifferenceCallback( Widget, XtPointer, XtPointer );
void previousDifferenceCallback( Widget, XtPointer, XtPointer );
void nextUnselectedCallback( Widget, XtPointer, XtPointer );
void previousUnselectedCallback( Widget, XtPointer, XtPointer );
void selectRegionRightCallback( Widget, XtPointer, XtPointer );
void selectRegionLeftCallback( Widget, XtPointer, XtPointer );
void selectRegionNeitherCallback( Widget, XtPointer, XtPointer );
void unselectRegionCallback( Widget, XtPointer, XtPointer );
void splitRightCallback( Widget, XtPointer, XtPointer );
void splitLeftCallback( Widget, XtPointer, XtPointer );
void lineNumbersCallback( Widget, XtPointer, XtPointer );
void selectLineRightCallback( Widget, XtPointer, XtPointer );
void selectLineLeftCallback( Widget, XtPointer, XtPointer );
void selectLineNeitherCallback( Widget, XtPointer, XtPointer );
void unselectLineCallback( Widget, XtPointer, XtPointer );
void cursorDownCallback( Widget, XtPointer, XtPointer );
void cursorUpCallback( Widget, XtPointer, XtPointer );
void scrollDownCallback( Widget, XtPointer, XtPointer );
void scrollUpCallback( Widget, XtPointer, XtPointer );
void cursorTopCallback( Widget, XtPointer, XtPointer );
void cursorBottomCallback( Widget, XtPointer, XtPointer );
#ifdef __RedoDiff__
void redoDiffCallback( Widget, XtPointer, XtPointer );
#endif /* __RedoDiff__ */
XDdiff *xdFindDiff( XDlist *, int );
XDdiff *xdAnyUnselected( XDlist * );
int xdAllocDiff( XDlist *, int, int, FILE *, int, FILE *, int );
int xdDiffFiles( XDlist *, FILE *, FILE *, FILE * );
char *xdMakeTemporaryFile( FILE * );
int xdBuildDiffs( XDlist * );
int xdWriteFile( char *, XDlist *, int );
void xdSplitDifferences( XDlist *, int );
void xdHelpDialogCallback( Widget, XtPointer, XtPointer );
void xdShowHelpMessage( Widget, char * );
void helpCallback( Widget, XtPointer, XtPointer );
void attachScrollBarCallbacks( Widget, XtCallbackProc, XtPointer );
void createMainForm( ApplicationData * );
void createPullDown( ApplicationData *, Widget, xdPullDown * );
void createMenuBar( ApplicationData *, Widget, xdPullDown [], int );
void createTransients( ApplicationData * );
void createApplicationWidgets( ApplicationData * );
void xdLoadAttributes( ApplicationData * );
void xdUseage( char * );
Boolean xdBuildFileNames( ApplicationData * );
Boolean xdParseArgs( ApplicationData *, int, char *[] );
void setPointer( Widget, XEvent *, String *, Cardinal * );
void selectAction( Widget, XEvent *, String *, Cardinal * );
int main( int, char *[], char *[] );
void xdRegError( int );
void xdSearchText( ApplicationData *, char * );
void xdSearchCallback( Widget, XtPointer, XtPointer );
void createSearchShell( ApplicationData * );
void searchCallback( Widget, XtPointer, XtPointer );
void searchNextCallback( Widget, XtPointer, XtPointer );
void searchPreviousCallback( Widget, XtPointer, XtPointer );
XDattribute *xdGetAttributes( ApplicationData *, XDdiff *, int );
void xdDrawView( ApplicationData * );
int expandTabs( char *, char *, int, int, int );
void xdDrawText( ApplicationData *, int );
Boolean xdFileWritable( ApplicationData *, int );
void xdSetMessageLine( ApplicationData *, char * );
void xdResizeSliders( ApplicationData * );
void xdMoveToCurrentLine( ApplicationData * );
void xdFindLine( ApplicationData *, int, int );
void xdFindMatch( ApplicationData *, int );
void xdFindDifference( ApplicationData *, Boolean, int );
void xdSelectGlobal( ApplicationData *, int );
void xdSelectRegion( ApplicationData *, int );
void xdSelectLine( ApplicationData *, int );
int xdSetCurrentDifference( ApplicationData *, int );
Boolean xdCheckAllSelected( ApplicationData * );
int xdSaveFile( ApplicationData *, char *, int );
Boolean xdSetCursorOnScreen( ApplicationData * );
void xdMoveCursor( ApplicationData *, int );
char *xdGetDefault( Display *, char *, char * );
