/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 * HISTORY
 * $Log: krb5_err.h,v $
 * Revision 65.2  1999/02/03 22:44:25  mek
 * Convert from IDL to C style include format.
 *
 * Revision 65.1  1997/10/20 19:47:43  jdoak
 * *** empty log message ***
 *
 * Revision 1.1.16.5  1996/11/13  18:07:03  arvind
 * 	Merge to DCE 1.2.2
 * 	[1996/10/30  23:05 UTC  mullan_s  /main/DCE_1.2.2/mullan_dce12_tp_preauth2/1]
 *
 * 	Add KRB5KRB_AP_ERR_V4_REPLY.
 * 	[1996/10/14  19:02 UTC  sommerfeld  /main/DCE_1.2.2/3]
 *
 * 	Add KRB5KDC_ERR_MUST_USE_USER2USER
 * 	[1996/01/03  19:14 UTC  psn  /main/DCE_1.2/1]
 *
 * Revision 1.1.16.4  1996/10/15  20:51:44  arvind
 * 	Partial fix to CHFts20154 (real error codes)
 * 	[1996/10/04  22:15 UTC  sommerfeld  /main/DCE_1.2.2/sommerfeld_pk_kdc_2/1]
 * 
 * 	Add KRB5KDC_ERR_MUST_USE_USER2USER
 * 	[1996/01/03  19:14 UTC  psn  /main/DCE_1.2/1]
 * 
 * Revision 1.1.16.3  1996/07/08  18:36:45  arvind
 * 	Merge krb5 work to DCE1.2.2 mainline
 * 	[1996/05/30  21:15 UTC  mullan_s  /main/DCE_1.2.2/1]
 * 
 * 	Kerb5Beta5 KRB5_FCC_FVNO_3 merge.
 * 	[1996/05/24  20:25 UTC  mullan_s  /main/DCE_1.2/mullan_dce_k5_bsd44_rutils/1]
 * 
 * 	Add KRB5KDC_ERR_MUST_USE_USER2USER
 * 	[1996/01/03  19:14 UTC  psn  /main/DCE_1.2/1]
 * 
 * Revision 1.1.16.2  1996/06/10  17:46:13  arvind
 * 	DCE1.2.2 Drop 2 to OSF
 * 	[1996/06/10  17:45:17  arvind]
 * 
 * Revision /main/DCE_1.2.2/1  1996/05/30  21:15 UTC  mullan_s
 * 	Merge krb5 work to DCE1.2.2 mainline
 * 
 * Revision /main/mullan_dce1.2.2_krb5_drop/1  1996/05/29  20:31 UTC  mullan_s
 * 	Update OSF copyright year
 * 	[1996/03/09  22:45:09  marty]
 * 	#
 * 
 * 	Submit OSF/DCE 1.2.1
 * 
 * 	HP revision /main/HPDCE02/2  1995/04/15  00:02 UTC  rps
 * 	# merge up to nightly
 * 	# [1995/04/10  17:38 UTC  rps  /main/MOTHRA_panic/2]
 * 
 * 	HP revision /main/HPDCE02/1  1995/03/01  20:01 UTC  mullan_s
 * 	Merge chfts14397
 * 
 * 	HP revision /main/mullan_chfts14397/1  1995/03/01  19:50 UTC  mullan_s
 * 	CHFts14397: move new error codes to end of file.
 * 	[1995/12/08  16:58:43  root]
 * 
 * Revision /main/DCE_1.2/mullan_dce_k5_bsd44_rutils/1  1996/05/24  20:25 UTC  mullan_s
 * 	Kerb5Beta5 KRB5_FCC_FVNO_3 merge.
 * 
 * Revision /main/DCE_1.2/1  1996/01/03  19:14 UTC  psn
 * 	# merge up to nightly
 * 	# [1995/04/10  17:38 UTC  rps  /main/MOTHRA_panic/2]
 * 	[1995/04/15  00:02 UTC  rps  /main/HPDCE02/2]
 * 
 * 	Merge chfts14397
 * 	[1995/03/01  20:01 UTC  mullan_s  /main/HPDCE02/1]
 * 
 * 	CHFts14397: move new error codes to end of file.
 * 	[1995/03/01  19:50 UTC  mullan_s  /main/mullan_chfts14397/1]
 * 
 * Revision 1.1.10.1  1994/10/25  22:10:22  mullan_s
 * 	[OT12495] Plaintext third party preauth fixes: add KDC_PREAUTH_REQUIRED
 * 	error type for preauth retries.
 * 	[1994/10/25  22:09:50  mullan_s]
 * 
 * Revision 1.1.6.1  1994/05/11  19:20:42  ahop
 * 	hp_sec_to_osf_2 drop
 * 	[1994/04/29  21:19:17  ahop]
 * 
 * Revision 1.1.4.3  1993/02/06  15:05:28  sommerfeld
 * 	[OT4523] Add status code for missing key table file..
 * 	[1993/02/06  01:11:36  sommerfeld]
 * 
 * Revision 1.1.4.2  1992/12/29  14:25:55  zeliff
 * 	Embedding copyright notice
 * 	[1992/12/28  21:07:21  zeliff]
 * 
 * Revision 1.1.2.2  1992/05/13  22:08:11  sommerfeld
 * 	Add krb5v5 status codes.
 * 	[1992/05/11  21:41:54  sommerfeld]
 * 
 * Revision 1.1  1992/01/19  19:42:12  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
 * krb5_err.h:
 * This file is automatically generated; please do not edit it.
 */
#define KRB5KDC_ERR_NONE                         (336760832L)
#define KRB5KDC_ERR_NAME_EXP                     (336760833L)
#define KRB5KDC_ERR_SERVICE_EXP                  (336760834L)
#define KRB5KDC_ERR_BAD_PVNO                     (336760835L)
#define KRB5KDC_ERR_C_OLD_MAST_KVNO              (336760836L)
#define KRB5KDC_ERR_S_OLD_MAST_KVNO              (336760837L)
#define KRB5KDC_ERR_C_PRINCIPAL_UNKNOWN          (336760838L)
#define KRB5KDC_ERR_S_PRINCIPAL_UNKNOWN          (336760839L)
#define KRB5KDC_ERR_PRINCIPAL_NOT_UNIQUE         (336760840L)
#define KRB5KDC_ERR_NULL_KEY                     (336760841L)
#define KRB5KDC_ERR_CANNOT_POSTDATE              (336760842L)
#define KRB5KDC_ERR_NEVER_VALID                  (336760843L)
#define KRB5KDC_ERR_POLICY                       (336760844L)
#define KRB5KDC_ERR_BADOPTION                    (336760845L)
#define KRB5KDC_ERR_ETYPE_NOSUPP                 (336760846L)
#define KRB5KDC_ERR_SUMTYPE_NOSUPP               (336760847L)
#define KRB5KDC_ERR_PADATA_TYPE_NOSUPP           (336760848L)
#define KRB5KDC_ERR_TRTYPE_NOSUPP                (336760849L)
#define KRB5KDC_ERR_CLIENT_REVOKED               (336760850L)
#define KRB5KDC_ERR_SERVICE_REVOKED              (336760851L)
#define KRB5KDC_ERR_TGT_REVOKED                  (336760852L)
#define KRB5KDC_ERR_CLIENT_NOTYET                (336760853L)
#define KRB5KDC_ERR_SERVICE_NOTYET               (336760854L)
#define KRB5KDC_ERR_KEY_EXP                      (336760855L)
#define KRB5KDC_ERR_PREAUTH_FAILED               (336760856L)
#define KRB5KDC_ERR_PREAUTH_REQUIRED             (336760857L)
#define KRB5KDC_ERR_SERVER_NOMATCH               (336760858L)
#define KRB5KDC_ERR_MUST_USE_USER2USER           (336760859L)
#define KRB5PLACEHOLD_28                         (336760860L)
#define KRB5PLACEHOLD_29                         (336760861L)
#define KRB5PLACEHOLD_30                         (336760862L)
#define KRB5KRB_AP_ERR_BAD_INTEGRITY             (336760863L)
#define KRB5KRB_AP_ERR_TKT_EXPIRED               (336760864L)
#define KRB5KRB_AP_ERR_TKT_NYV                   (336760865L)
#define KRB5KRB_AP_ERR_REPEAT                    (336760866L)
#define KRB5KRB_AP_ERR_NOT_US                    (336760867L)
#define KRB5KRB_AP_ERR_BADMATCH                  (336760868L)
#define KRB5KRB_AP_ERR_SKEW                      (336760869L)
#define KRB5KRB_AP_ERR_BADADDR                   (336760870L)
#define KRB5KRB_AP_ERR_BADVERSION                (336760871L)
#define KRB5KRB_AP_ERR_MSG_TYPE                  (336760872L)
#define KRB5KRB_AP_ERR_MODIFIED                  (336760873L)
#define KRB5KRB_AP_ERR_BADORDER                  (336760874L)
#define KRB5KRB_AP_ERR_ILL_CR_TKT                (336760875L)
#define KRB5KRB_AP_ERR_BADKEYVER                 (336760876L)
#define KRB5KRB_AP_ERR_NOKEY                     (336760877L)
#define KRB5KRB_AP_ERR_MUT_FAIL                  (336760878L)
#define KRB5KRB_AP_ERR_BADDIRECTION              (336760879L)
#define KRB5KRB_AP_ERR_METHOD                    (336760880L)
#define KRB5KRB_AP_ERR_BADSEQ                    (336760881L)
#define KRB5KRB_AP_ERR_INAPP_CKSUM               (336760882L)
#define KRB5PLACEHOLD_51                         (336760883L)
#define KRB5PLACEHOLD_52                         (336760884L)
#define KRB5PLACEHOLD_53                         (336760885L)
#define KRB5PLACEHOLD_54                         (336760886L)
#define KRB5PLACEHOLD_55                         (336760887L)
#define KRB5PLACEHOLD_56                         (336760888L)
#define KRB5PLACEHOLD_57                         (336760889L)
#define KRB5PLACEHOLD_58                         (336760890L)
#define KRB5PLACEHOLD_59                         (336760891L)
#define KRB5KRB_ERR_GENERIC                      (336760892L)
#define KRB5KRB_ERR_FIELD_TOOLONG                (336760893L)
#define KRB5PLACEHOLD_62                         (336760894L)
#define KRB5PLACEHOLD_63                         (336760895L)
#define KRB5PLACEHOLD_64                         (336760896L)
#define KRB5PLACEHOLD_65                         (336760897L)
#define KRB5PLACEHOLD_66                         (336760898L)
#define KRB5PLACEHOLD_67                         (336760899L)
#define KRB5PLACEHOLD_68                         (336760900L)
#define KRB5PLACEHOLD_69                         (336760901L)
#define KRB5PLACEHOLD_70                         (336760902L)
#define KRB5PLACEHOLD_71                         (336760903L)
#define KRB5PLACEHOLD_72                         (336760904L)
#define KRB5PLACEHOLD_73                         (336760905L)
#define KRB5PLACEHOLD_74                         (336760906L)
#define KRB5PLACEHOLD_75                         (336760907L)
#define KRB5PLACEHOLD_76                         (336760908L)
#define KRB5PLACEHOLD_77                         (336760909L)
#define KRB5PLACEHOLD_78                         (336760910L)
#define KRB5PLACEHOLD_79                         (336760911L)
#define KRB5PLACEHOLD_80                         (336760912L)
#define KRB5PLACEHOLD_81                         (336760913L)
#define KRB5PLACEHOLD_82                         (336760914L)
#define KRB5PLACEHOLD_83                         (336760915L)
#define KRB5PLACEHOLD_84                         (336760916L)
#define KRB5PLACEHOLD_85                         (336760917L)
#define KRB5PLACEHOLD_86                         (336760918L)
#define KRB5PLACEHOLD_87                         (336760919L)
#define KRB5PLACEHOLD_88                         (336760920L)
#define KRB5PLACEHOLD_89                         (336760921L)
#define KRB5PLACEHOLD_90                         (336760922L)
#define KRB5PLACEHOLD_91                         (336760923L)
#define KRB5PLACEHOLD_92                         (336760924L)
#define KRB5PLACEHOLD_93                         (336760925L)
#define KRB5PLACEHOLD_94                         (336760926L)
#define KRB5PLACEHOLD_95                         (336760927L)
#define KRB5PLACEHOLD_96                         (336760928L)
#define KRB5PLACEHOLD_97                         (336760929L)
#define KRB5PLACEHOLD_98                         (336760930L)
#define KRB5PLACEHOLD_99                         (336760931L)
#define KRB5PLACEHOLD_100                        (336760932L)
#define KRB5PLACEHOLD_101                        (336760933L)
#define KRB5PLACEHOLD_102                        (336760934L)
#define KRB5PLACEHOLD_103                        (336760935L)
#define KRB5PLACEHOLD_104                        (336760936L)
#define KRB5PLACEHOLD_105                        (336760937L)
#define KRB5PLACEHOLD_106                        (336760938L)
#define KRB5PLACEHOLD_107                        (336760939L)
#define KRB5PLACEHOLD_108                        (336760940L)
#define KRB5PLACEHOLD_109                        (336760941L)
#define KRB5PLACEHOLD_110                        (336760942L)
#define KRB5PLACEHOLD_111                        (336760943L)
#define KRB5PLACEHOLD_112                        (336760944L)
#define KRB5PLACEHOLD_113                        (336760945L)
#define KRB5PLACEHOLD_114                        (336760946L)
#define KRB5PLACEHOLD_115                        (336760947L)
#define KRB5PLACEHOLD_116                        (336760948L)
#define KRB5PLACEHOLD_117                        (336760949L)
#define KRB5PLACEHOLD_118                        (336760950L)
#define KRB5PLACEHOLD_119                        (336760951L)
#define KRB5PLACEHOLD_120                        (336760952L)
#define KRB5PLACEHOLD_121                        (336760953L)
#define KRB5PLACEHOLD_122                        (336760954L)
#define KRB5PLACEHOLD_123                        (336760955L)
#define KRB5PLACEHOLD_124                        (336760956L)
#define KRB5PLACEHOLD_125                        (336760957L)
#define KRB5PLACEHOLD_126                        (336760958L)
#define KRB5PLACEHOLD_127                        (336760959L)
#define KRB5_ERR_RCSID                           (336760960L)
#define KRB5_LIBOS_BADLOCKFLAG                   (336760961L)
#define KRB5_LIBOS_CANTREADPWD                   (336760962L)
#define KRB5_LIBOS_BADPWDMATCH                   (336760963L)
#define KRB5_LIBOS_PWDINTR                       (336760964L)
#define KRB5_PARSE_ILLCHAR                       (336760965L)
#define KRB5_PARSE_MALFORMED                     (336760966L)
#define KRB5_CONFIG_CANTOPEN                     (336760967L)
#define KRB5_CONFIG_BADFORMAT                    (336760968L)
#define KRB5_CONFIG_NOTENUFSPACE                 (336760969L)
#define KRB5_BADMSGTYPE                          (336760970L)
#define KRB5_CC_BADNAME                          (336760971L)
#define KRB5_CC_UNKNOWN_TYPE                     (336760972L)
#define KRB5_CC_NOTFOUND                         (336760973L)
#define KRB5_CC_END                              (336760974L)
#define KRB5_NO_TKT_SUPPLIED                     (336760975L)
#define KRB5KRB_AP_WRONG_PRINC                   (336760976L)
#define KRB5KRB_AP_ERR_TKT_INVALID               (336760977L)
#define KRB5_PRINC_NOMATCH                       (336760978L)
#define KRB5_KDCREP_MODIFIED                     (336760979L)
#define KRB5_PROG_ETYPE_NOSUPP                   (336760980L)
#define KRB5_PROG_KEYTYPE_NOSUPP                 (336760981L)
#define KRB5_WRONG_ETYPE                         (336760982L)
#define KRB5_PROG_SUMTYPE_NOSUPP                 (336760983L)
#define KRB5_REALM_UNKNOWN                       (336760984L)
#define KRB5_KDC_UNREACH                         (336760985L)
#define KRB5_NO_LOCALNAME                        (336760986L)
#define KRB5_RC_TYPE_EXISTS                      (336760987L)
#define KRB5_RC_MALLOC                           (336760988L)
#define KRB5_RC_TYPE_NOTFOUND                    (336760989L)
#define KRB5_RC_UNKNOWN                          (336760990L)
#define KRB5_RC_REPLAY                           (336760991L)
#define KRB5_RC_IO                               (336760992L)
#define KRB5_RC_NOIO                             (336760993L)
#define KRB5_RC_PARSE                            (336760994L)
#define KRB5_RC_IO_EOF                           (336760995L)
#define KRB5_RC_IO_MALLOC                        (336760996L)
#define KRB5_RC_IO_PERM                          (336760997L)
#define KRB5_RC_IO_IO                            (336760998L)
#define KRB5_RC_IO_UNKNOWN                       (336760999L)
#define KRB5_RC_IO_SPACE                         (336761000L)
#define KRB5_TRANS_CANTOPEN                      (336761001L)
#define KRB5_TRANS_BADFORMAT                     (336761002L)
#define KRB5_LNAME_CANTOPEN                      (336761003L)
#define KRB5_LNAME_NOTRANS                       (336761004L)
#define KRB5_LNAME_BADFORMAT                     (336761005L)
#define KRB5_CRYPTO_INTERNAL                     (336761006L)
#define KRB5_KT_BADNAME                          (336761007L)
#define KRB5_KT_UNKNOWN_TYPE                     (336761008L)
#define KRB5_KT_NOTFOUND                         (336761009L)
#define KRB5_KT_END                              (336761010L)
#define KRB5_KT_NOWRITE                          (336761011L)
#define KRB5_KT_IOERR                            (336761012L)
#define KRB5_NO_TKT_IN_RLM                       (336761013L)
#define KRB5DES_BAD_KEYPAR                       (336761014L)
#define KRB5DES_WEAK_KEY                         (336761015L)
#define KRB5_BAD_KEYTYPE                         (336761016L)
#define KRB5_BAD_KEYSIZE                         (336761017L)
#define KRB5_BAD_MSIZE                           (336761018L)
#define KRB5_CC_TYPE_EXISTS                      (336761019L)
#define KRB5_KT_TYPE_EXISTS                      (336761020L)
#define KRB5_CC_IO                               (336761021L)
#define KRB5_FCC_PERM                            (336761022L)
#define KRB5_FCC_NOFILE                          (336761023L)
#define KRB5_FCC_INTERNAL                        (336761024L)
#define KRB5_CC_NOMEM                            (336761025L)
#define KRB5_INVALID_FLAGS                       (336761026L)
#define KRB5_NO_2ND_TKT                          (336761027L)
#define KRB5_NOCREDS_SUPPLIED                    (336761028L)
#define KRB5_SENDAUTH_BADAUTHVERS                (336761029L)
#define KRB5_SENDAUTH_BADAPPLVERS                (336761030L)
#define KRB5_SENDAUTH_BADRESPONSE                (336761031L)
#define KRB5_SENDAUTH_REJECTED                   (336761032L)
#define KRB5_SENDAUTH_MUTUAL_FAILED              (336761033L)
#define KRB5_RCACHE_BADVNO                       (336761034L)
#define KRB5_CCACHE_BADVNO                       (336761035L)
#define KRB5_KEYTAB_BADVNO                       (336761036L)
#define KRB5_PROG_ATYPE_NOSUPP                   (336761037L)
#define KRB5_RC_REQUIRED                         (336761038L)
#define KRB5_ERR_BAD_HOSTNAME                    (336761039L)
#define KRB5_ERR_HOST_REALM_UNKNOWN              (336761040L)
#define KRB5_KT_NOFILE                           (336761041L)
#define KRB5_PREAUTH_BAD_TYPE                    (336761042L)
#define KRB5_PREAUTH_NO_KEY                      (336761043L)
#define KRB5_PREAUTH_FAILED                      (336761044L)
#define KRB5_SNAME_UNSUPP_NAMETYPE               (336761045L)
#define KRB5_KDCREP_SKEW                         (336761046L)
#define KRB5_IN_TKT_REALM_MISMATCH               (336761047L)
#define KRB5_CC_WRITE                            (336761048L)
#define KRB5_GET_IN_TKT_LOOP                     (336761049L)
#define KRB5KRB_AP_ERR_V4_REPLY                  (336761050L)
#define initialize_krb5_error_table()
#define ERROR_TABLE_BASE_krb5 (336760832L)

/* for compatibility with older versions... */
#define init_krb5_err_tbl initialize_krb5_error_table
#define krb5_err_base ERROR_TABLE_BASE_krb5
