
/* unixperf - an x11perf-style Unix performance benchmark */

/* describe.c outputs a prologue to unixperf's performance output listing
   the host machine configuration, executable type, time, and load. */

#include "unixperf.h"

#include <string.h>
#include <sys/utsname.h>	/* for uname */
#include <time.h>		/* for ctime */

#ifndef EX_OK /* if new EX_OK does not exist... */
#define EX_OK X_OK
#endif

void
DescribeSystem(void)
{
    struct utsname uinfo;
    time_t t;
    char *abi;

    rc = uname(&uinfo);
    t = time(NULL);
    printf("UNIX PERFORMANCE REPORT (generated by unixperf v%0.1f)\n", TestVersion);
    printf("------------------------------------------------------\n");
    printf("Hostname: %s\n", uinfo.nodename);
    printf("Operating system: %s %s\n", uinfo.sysname, uinfo.release);
#ifdef _COMPILER_VERSION
    printf("Compiler version: %g\n", _COMPILER_VERSION / 100.0);
#else
    printf("Compiler version: unknown\n");
#endif
#ifdef __mips
    printf("Instruction set: MIPS %d\n", __mips);
#else
    printf("Instruction set: unknown (probably not MIPS)\n");
#endif
#ifdef _MIPS_SIM
    switch(_MIPS_SIM) {
    case 1:
      abi = "O32";
      break;
    case 2:
      abi = "N32";
      break;
    case 3:
      abi = "64-bit";
      break;
    default:
      abi = "unknown";
      break;
    }
    printf("Application binary interface: %s\n", abi);
#else
    printf("Application binary interface: unknown\n");
#endif
    fflush(stdout);
#ifdef sgi
    if(access("/bin/hinv", EX_OK) == 0) system("/bin/hinv");
    if(access("/usr/sbin/versions", EX_OK) == 0) {
      printf("Installed SGI Patches\n");
      fflush(stdout);
      system("/usr/sbin/versions 'patchSG*' | grep '^I  ' | sed 's/^I  //'");
    }
#endif
    if(access("/usr/bsd/uptime", EX_OK) == 0) {
	FILE *uptime;

	uptime = popen("/usr/bsd/uptime", "r");
	if(uptime != NULL) {
	    char buffer[256];
	    char *line, *life, *users, *end, *load;
	    int numusers;

	    line = fgets(buffer, sizeof(buffer), uptime);
	    if(line != NULL) {
		life = strstr(line, "up ");
		if(life != NULL) {
		    users = strstr(life, "user");
		    if(users != NULL) {
			end = users;
			while((*end != ',') && (end > line))  end--;
			*end = '\0';
			printf("Uptime: %s\n", &life[3]);
		    }
		    end++;
		    numusers = atoi(end);
		    printf("Users: %d\n", numusers);
		    load = strstr(users, "load average: ");
		    if(load != NULL) {
			*load = 'L'; /* capitalize L in "load" */
			end = strchr(load, '\n');
			if(end != NULL) {
			    *end = '\0'; /* clobber newline */
			}
			printf("%s\n", load);
		    }
		}
	    }
	    pclose(uptime);
	}
    }
    printf("File IO test directory: %s\n", TmpDir);
    if(access("/bin/df", EX_OK) == 0) {
	FILE *df;
	char command[1024];
	char filesystem[1024];
	char fstype[256];
	long long total, used, avail;
	int percent;
	char where[1024];
	int cnt, ch;

        sprintf(command, "/bin/df -lk %s", TmpDir);
	df = popen(command, "r");
	if(df != NULL) {
	  /* Skip first line saying: "Filesystem Type kbytes use avail %use Mounted on" */
	  do {
	    ch = getc(df);
	  } while(ch != EOF && ch != '\n');
	  cnt = fscanf(df, "%s %s %lld %lld %lld %d %s\n",
	    filesystem, fstype, &total, &used, &avail, &percent, where);
	  if (cnt == 7) {
	    printf("File IO test filesystem: %s (%.2f MB total, %.2f MB available)\n",
	      fstype, total/1024.0, avail/1024.0);
	  } else {
	    printf("File IO test filesystem: unknown (parsing output of \"%s\" failed)\n", command);
	  }
	  pclose(df);
	} else {
	  printf("File IO test filesystem: unknown (running \"%s\" failed)\n", command);
	}
    }
    printf("Date: %s", ctime(&t)); /* ctime generates a newline */
    printf("\n");
}
