#ident  "ide/godzilla/x_test/Makefile:  $Revision: 1.3 $"
#
# to build widget to widget diags

DIAGDEPTH= ../..
include ${DIAGDEPTH}/Makedefs

ASFILES=
CFILES=	xbow_arb.c test_xbow_arb.c xbow_test.c linc.c

include ${DIAGDEPTH}/Makerules
LINCLUDES = -I../include 

