#! /bin/ksh

charts="$1"
if [ "x$charts" = "x" ]; then
	charts="charts"
else
	shift
fi

dirs="$*"
if [ "x$dirs" = "x" ]; then
	dirs="ip*"
fi

if [ -z "$BENCH" ]; then
	BENCH=`dirname $0`
fi

dirs1=`echo $dirs | awk '{print $1}'`
dirs2=`echo $dirs | awk '{print $2}'`

echo Matching chart scales...

for x in $charts/${dirs1}_*.txt
do
	suffix=${x##$charts/$dirs1}

	$BENCH/rescale $x $charts/${dirs2}${suffix}
done

echo Generating single images...

cmd=Wingz

for x in $charts/*.txt
do
	cmd="$cmd $x $BENCH/makechart.scz $BENCH/savechart.scz"
done

cmd="$cmd -quit"

exec $cmd
