#! /bin/sh

charts="$1"
if [ "x$charts" = "x" ]; then
	charts="charts"
else
	shift
fi

dirs="$*"
if [ "x$dirs" = "x" ]; then
	dirs="ip*"
fi

BENCH=`dirname $0`
export BENCH

$BENCH/gen_charts $charts $dirs
$BENCH/gen_single $charts $dirs
$BENCH/gen_composite $charts $dirs
