/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/types.h>

#define SM_STATDIR "/var/statmon"
#define SM_CUR "sm"
#define SM_MAXSTRLEN 1024

struct sm_name {
	char *mon_name;
};
typedef struct sm_name sm_name;
extern bool_t xdr_sm_name(XDR *, sm_name *);


struct my_id {
	char *my_name;
	int my_prog;
	int my_vers;
	int my_proc;
};
typedef struct my_id my_id;
extern bool_t xdr_my_id(XDR *, my_id *);


struct mon_id {
	char *mon_name;
	struct my_id my_id;
};
typedef struct mon_id mon_id;
extern bool_t xdr_mon_id(XDR *, mon_id *);

#define SM_PRIVLEN 16

struct mon {
	struct mon_id mon_id;
	char priv[SM_PRIVLEN];
};
typedef struct mon mon;
extern bool_t xdr_mon(XDR *, mon *);


struct sm_stat {
	int state;
};
typedef struct sm_stat sm_stat;
extern bool_t xdr_sm_stat(XDR *, sm_stat *);


enum res {
	stat_succ = 0,
	stat_fail = 1
};
typedef enum res res;
extern bool_t xdr_res(XDR *, res *);


struct sm_stat_res {
	res res_stat;
	int state;
};
typedef struct sm_stat_res sm_stat_res;
extern bool_t xdr_sm_stat_res(XDR *, sm_stat_res *);


struct status {
	char *mon_name;
	int state;
	char priv[SM_PRIVLEN];
};
typedef struct status status;
extern bool_t xdr_status(XDR *, status *);


#define SM_PROG ((u_long)100024)
#define SM_VERS ((u_long)1)
#define SM_STAT ((u_long)1)
#define SM_MON ((u_long)2)
#define SM_UNMON ((u_long)3)
#define SM_UNMON_ALL ((u_long)4)
#define SM_SIMU_CRASH ((u_long)5)

#ifdef _RPCGEN_SVC
extern struct sm_stat_res *sm_stat_1(sm_name *, struct svc_req *);
extern struct sm_stat_res *sm_mon_1(mon *, struct svc_req *);
extern struct sm_stat *sm_unmon_1(mon_id *, struct svc_req *);
extern struct sm_stat *sm_unmon_all_1(my_id *, struct svc_req *);
extern void *sm_simu_crash_1(void *, struct svc_req *);
#endif
#ifdef _RPCGEN_CLNT
extern struct sm_stat_res *sm_stat_1(sm_name *, CLIENT *);
extern struct sm_stat_res *sm_mon_1(mon *, CLIENT *);
extern struct sm_stat *sm_unmon_1(mon_id *, CLIENT *);
extern struct sm_stat *sm_unmon_all_1(my_id *, CLIENT *);
extern void *sm_simu_crash_1(void *, CLIENT *);
#endif

