/* Layout file created by tedit */

#ifndef TUDONTAUTOINCLUDE
#include "tuLabel.h"
#include "tuTextField.h"
#include "tuFrame.h"
#include "tuGap.h"
#include "tuLabelButton.h"
#include "tuRowColumn.h"
#endif /* TUDONTAUTOINCLUDE */

#ifdef TUREGISTERGADGETS
#undef TUREGISTERGADGETS
#endif /* TUREGISTERGADGETS */
#define TUREGISTERGADGETS { \
    tuLabel::registerForPickling(); \
    tuTextField::registerForPickling(); \
    tuFrame::registerForPickling(); \
    tuGap::registerForPickling(); \
    tuLabelButton::registerForPickling(); \
    tuRowColumn::registerForPickling(); \
}

static char* layoutstr =
"(RowColumn "
 "(rows 5) "
 "(cols 2) "
 "(growdir vertical) "
 "(defaultAlignment 0) "
 "(resources "
  "((topInset 8) "
   "(bottomInset 8) "
   "(leftInset 8) "
   "(rightInset 8) "
   "(horizontalOffset 8) "
   "(verticalOffset 8))) "
 "(child "
  "(Label "
   "(resources "
    "((labelString Vendor\\ ID:) "
     "(font -*-helvetica-bold-r-normal--14-*-*-*-p-82-iso8859-1))))) "
 "(constraint R0C0A6) "
 "(child "
  "(Frame "
   "(resources "
    "((frame Innie))) "
   "(child "
    "(TextField "
     "(instanceName _vendorid) "
     "(text ) "
     "(resources "
      "((background ReadOnlyBackground) "
       "(readOnly True) "
       "(keepAllTextVisible False))))))) "
 "(constraint R0C1A0) "
 "(child "
  "(Label "
   "(resources "
    "((labelString System\\ ID:) "
     "(font -*-helvetica-bold-r-normal--14-*-*-*-p-82-iso8859-1))))) "
 "(constraint R1C0A6) "
 "(child "
  "(Frame "
   "(resources "
    "((frame Innie))) "
   "(child "
    "(TextField "
     "(instanceName _systemid) "
     "(text ) "
     "(resources "
      "((background ReadOnlyBackground) "
       "(readOnly True) "
       "(keepAllTextVisible False))))))) "
 "(constraint R1C1A0) "
 "(child "
  "(Label "
   "(resources "
    "((labelString Password:) "
     "(font -*-helvetica-bold-r-normal--14-*-*-*-p-82-iso8859-1))))) "
 "(constraint R2C0A6) "
 "(child "
  "(Frame "
   "(resources "
    "((frame Innie))) "
   "(child "
    "(TextField "
     "(instanceName _password) "
     "(text ) "
     "(resources "
      "((terminatorCallBack ) "
       "(keepAllTextVisible False))))))) "
 "(constraint R2C1A0) "
 "(child "
  "(Label "
   "(resources "
    "((labelString Data\\ Stations:) "
     "(font -*-helvetica-bold-r-normal--14-*-*-*-p-82-iso8859-1))))) "
 "(constraint R3C0A6) "
 "(child "
  "(Frame "
   "(resources "
    "((frame Innie))) "
   "(child "
    "(TextField "
     "(instanceName _datastations) "
     "(text ) "
     "(resources "
      "((terminatorCallBack ) "
       "(keepAllTextVisible False))))))) "
 "(constraint R3C1A0) "
 "(child "
  "(RowColumn "
   "(rows 1) "
   "(cols 4) "
   "(defaultAlignment 0) "
   "(resources "
    "((topInset 8) "
     "(horizontalOffset 8))) "
   "(child "
    "(Gap "
     "(orientation horizontal) "
     "(resources "
      "((minWidth 200))))) "
   "(constraint R0C0A0) "
   "(child "
    "(LabelButton "
     "(resources "
      "((callback _accept) "
       "(accelerator Alt\\ c) "
       "(labelString Create))))) "
   "(constraint R0C1A0) "
   "(child "
    "(LabelButton "
     "(resources "
      "((callback _cancel) "
       "(accelerator Alt\\ q) "
       "(labelString Quit))))) "
   "(constraint R0C2A0) "
   "(child "
    "(LabelButton "
     "(resources "
      "((callback _help) "
       "(accelerator Alt\\ h) "
       "(labelString Help))))) "
   "(constraint R0C3A0))) "
 "(constraint R4C1A0))";
