#!smake
#
# Makefile for libpkg.
#
#ident	"$Revision: 1.1 $"

DEPTH=.
CFILES=canonize.c ckparam.c ckvolseq.c cvtpath.c devtype.c dstream.c \
	gpkglist.c gpkgmap.c isdir.c logerr.c mappath.c pkgexecl.c pkgexecv.c \
	pkgmount.c pkgtrans.c pkgxpand.c ppkgmap.c progerr.c \
	putcfile.c rrmdir.c runcmd.c srchcfile.c tputcfent.c verify.c

include	$(ROOT)/usr/include/make/libleafdefs
include $(LIBLEAFRULES)
