'\"macro stdmacro
.TH KLOG 7
.SH NAME
eg \- gigabit ethernet driver
.SH DESCRIPTION
.I eg
is the driver for gigabit Ethernet interfaces.
.I eg
presently supports 1000baseFX interfaces.
.PP
For more information about Ethernet, see
.IR ethernet (7).
.SH FILES
/hw/net/egN	special file
.SH "SEE ALSO"
egcmd(1M), egconfig(1M), ifconfig(1M), network(1M), ethernet(7).
