.TH mouse 7
.SH NAME
mouse \- mouse specifications
.SH DESCRIPTION
A serial mouse is used on the SGI 4D series, Indigo, Crimson and Onyx systems.
This mouse differs from other systems which use the mouse described in
\f2pcmouse\f1(7).
.SS Signals
The serial data interface signal level is
compatible with RS-423, which has roughly a 10V swing centered about ground.
The idle state and true data bits for the interface
are Mark level or \-5V whereas false data bits and the start bit
are spaces or +5V.
The serial data is transmitted at 4800
baud with one start bit, eight data bits, and no parity.
.SS Protocol
The mouse provides a five-byte data block whenever
there is a change of position or button state.
The first byte is a sync byte
that has its upper five bits set to 10000 and its lower three bits indicating
the button states where a 0 indicates depression.
The sync byte
looks like this: 10000LMR.
The next four bytes contain two difference
updates of the mouse's change in position: X1, Y1, X2, and Y2.
Positive
values indicate movement to the right or upward.
System software
ignores bytes beyond the first five until reception of the next
sync byte.
.SS Pinout
The pinout of the mouse connector on the keyboard is on
the
.IR keyboard (7)
reference page.
.SH NOTE
Indy, Indigo2, O2, OCTANE and Onyx2 use a PS/2 style mouse,
which is described in \f2pcmouse\f1(7).
.SH SEE ALSO
keyboard(7),
pckeyboard(7),
pcmouse(7).
