.TH NPROCESS 1 "" "Testing"
.SH NAME
nprocess \- simulated database access by a number of processes
.br
nprocess_svc \- test server
.SH SYNOPSIS
.B nprocess
[-v] [-o options] [locatlpath] [host:remotepath]
.br
.B nprocess_svc
.SH DESCRIPTION
.I nprocess
is an RPC client/server application designed to test the file
and record locking functionality of a UNIX file system.  The client,
.IR nprocess ,
and the server,
.IR nprocess_svc ,
form a pair of processes cooperating in the testing.  The
client is the active process in that the test phases are initiated by
the client.  The server is passive, waiting for the client to make
requests of it.
.P
All testing is performed in the current working directory for each
process unless a directory or test file has been specified by the argument
.IR localpath .
If
.I host:remotepath
has been supplied, the host name and the remote directory are taken
to be
.I host
and
.I remotepath
respectively.  Otherwise, the host name and the remote directory name
are determined from
.I localpath
or the current directory.  This is done by extracting the information
from the mounted file system table.
.P
If the host and remote path are to be specified, the local path must
also be specified, even if it is ".".
.P
Testing consists of simulated database access by a number of processes.
The database accesses consist of locking and unlocking files.  This
is based on a test case used to demonstrate a bug found in the IRIX
version of
.IR rpc.lockd (1M).
.P
When testing a distributed file system such as NFS, the following
test scenarios must be executed (with three different systems):
.IP 1)
run
.B nprocess_svc
and
.B nprocess
on one client;
.IP 2)
run
.B nprocess_svc
on the file system server and
.B nprocess
on a single client;
.IP 3)
run
.B nprocess_svc
on one client and
.B nprocess
on a second client, with neither client being the file system server.
.SH OPTIONS
.I nprocess
accepts the following options.
.TP 12
.B \-v
turn on verbose mode
.TP 12
\fB-o\fP \fIsubopts\fP
Specify a comma-separated list of sub-option settings of the form opt=val.
.P
The sub-options currently supported for the
.B -o
option are as follows.
.TP 12
\fBprocs\fP=\fIn\fP
Set the number of processes to
.IR n .
The default number of processes is 3.  The process count determines how
many processes there will be each on the client and the server.  For a
setting of 3, there will be 3 processes on the client and 3 on the server.
.TP 12
\fBtime\fP=\fIt\fP
Set the run time for the test to
.I t
seconds.  The default is indefinite run time with termination determined
by the receipt of a signal such as SIGINT.
.P
.I nprocess_svc
accepts no options from the command line.  The
.B -v
option and the working directory name are passed to the server by the client
via an RPC call.
