#ident  "ide/godzilla/util/Makefile:  $Revision: 1.6 $"
#
# godzilla utility makefile for diags

DIAGDEPTH= ../..
include ${DIAGDEPTH}/Makedefs

ASFILES=
CFILES= utility.c voltage.c xtalk_nic_probe.c gparser.c gz_errorcodes.c

include ${DIAGDEPTH}/Makerules
LINCLUDES = -I../include
