/****************************************************************/
/*    NAME:                                                     */
/*    ACCT: kostadis                                            */
/*    FILE: BPSThread.H                                         */
/*    ASGN:                                                     */
/*    DATE: Fri Jul 14 19:47:24 1995                            */
/****************************************************************/


#ifndef BPSTHREAD_HEADER
#define BPSTHREAD_HEADER



#endif
