/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: aclbase.h,v $
 * Revision 65.2  1999/02/03 22:44:19  mek
 * Convert from IDL to C style include format.
 *
 * Revision 65.1  1997/10/20 19:46:29  jdoak
 * *** empty log message ***
 *
 * Revision 1.1.82.2  1996/03/09  23:27:43  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:43:10  marty]
 *
 * Revision 1.1.82.1  1995/12/08  17:30:52  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  16:54:46  root]
 * 
 * Revision 1.1.80.2  1994/06/02  21:28:22  mdf
 * 	hp_sec_to_osf_3 drop, merge up with latest.
 * 	[1994/05/24  15:15:53  mdf]
 * 
 * 	hp_sec_to_osf_3 drop
 * 
 * Revision 1.1.80.1  1994/01/28  23:10:38  burati
 * 	Delegation changes (dlg_bl1)
 * 	[1994/01/18  20:51:36  burati]
 * 
 * Revision 1.1.78.2  1993/10/13  20:39:48  burati
 * 	CR9104 Remove 'default' tag from sec_acl_entry_t union
 * 	[1993/10/13  18:50:51  burati]
 * 
 * Revision 1.1.78.1  1993/10/05  22:30:41  mccann
 * 	CR8651 64 bit porting changes
 * 	[1993/10/04  19:11:34  mccann]
 * 
 * Revision 1.1.6.2  1993/07/07  20:13:07  ganni
 * 	reduced stub idl sources
 * 	[1993/07/07  19:40:55  ganni]
 * 
 * Revision 1.1.4.2  1992/12/29  13:28:50  zeliff
 * 	Embedding copyright notice
 * 	[1992/12/28  20:47:58  zeliff]
 * 
 * Revision 1.1.2.3  1992/05/08  14:47:49  burati
 * 	Added sec_acl_posix_semantics
 * 	[1992/04/29  03:04:12  burati]
 * 
 * Revision 1.1.2.2  1992/03/24  20:31:01  burati
 * 	CR2387 Change sec_acl_perm_owner to sec_acl_perm_control
 * 	[1992/03/24  19:21:01  burati]
 * 
 * Revision 1.1  1992/01/19  14:55:34  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/* Generated by IDL compiler version OSF DCE T1.2.0-09 */
#ifndef sec_acl_base_v0_0_included
#define sec_acl_base_v0_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
#ifndef secsts_v0_0_included
#include <dce/secsts.h>
#endif
#ifndef sec_id_base_v0_0_included
#include <dce/id_base.h>
#endif
typedef idl_void_p_t sec_acl_handle_t;
#define sec_acl_default_handle NULL
typedef struct  {
uuid_t extension_type;
ndr_format_t format_label;
unsigned32 num_bytes;
idl_byte pickled_data[1];
} sec_acl_extend_info_t;
typedef unsigned32 sec_acl_permset_t;
#define sec_acl_perm_read (1)
#define sec_acl_perm_write (2)
#define sec_acl_perm_execute (4)
#define sec_acl_perm_control (8)
#define sec_acl_perm_insert (16)
#define sec_acl_perm_delete (32)
#define sec_acl_perm_test (64)
#define sec_acl_perm_unused_00000080 (128)
#define sec_acl_perm_unused_00000100 (256)
#define sec_acl_perm_unused_00000200 (512)
#define sec_acl_perm_unused_00000400 (1024)
#define sec_acl_perm_unused_00000800 (2048)
#define sec_acl_perm_unused_00001000 (4096)
#define sec_acl_perm_unused_00002000 (8192)
#define sec_acl_perm_unused_00004000 (16384)
#define sec_acl_perm_unused_00008000 (32768)
#define sec_acl_perm_unused_00010000 (65536)
#define sec_acl_perm_unused_00020000 (131072)
#define sec_acl_perm_unused_00040000 (262144)
#define sec_acl_perm_unused_00080000 (524288)
#define sec_acl_perm_unused_00100000 (1048576)
#define sec_acl_perm_unused_00200000 (2097152)
#define sec_acl_perm_unused_00400000 (4194304)
#define sec_acl_perm_unused_00800000 (8388608)
#define sec_acl_perm_unused_01000000 (16777216)
#define sec_acl_perm_unused_02000000 (33554432)
#define sec_acl_perm_unused_04000000 (67108864)
#define sec_acl_perm_unused_08000000 (134217728)
#define sec_acl_perm_unused_10000000 (268435456)
#define sec_acl_perm_unused_20000000 (536870912)
#define sec_acl_perm_unused_40000000 (1073741824)
#define sec_acl_perm_unused_80000000 (-2147483648)
#define sec_acl_perm_owner (8)
typedef unsigned32 sec_acl_posix_semantics_t;
#define sec_acl_posix_no_semantics (0)
#define sec_acl_posix_mask_obj (1)
#define sec_acl_posix_unused_0000002 (2)
#define sec_acl_posix_unused_0000004 (4)
#define sec_acl_posix_unused_0000008 (8)
typedef enum {sec_acl_e_type_user_obj=0,
sec_acl_e_type_group_obj=1,
sec_acl_e_type_other_obj=2,
sec_acl_e_type_user=3,
sec_acl_e_type_group=4,
sec_acl_e_type_mask_obj=5,
sec_acl_e_type_foreign_user=6,
sec_acl_e_type_foreign_group=7,
sec_acl_e_type_foreign_other=8,
sec_acl_e_type_unauthenticated=9,
sec_acl_e_type_extended=10,
sec_acl_e_type_any_other=11,
sec_acl_e_type_user_obj_deleg=12,
sec_acl_e_type_user_deleg=13,
sec_acl_e_type_for_user_deleg=14,
sec_acl_e_type_group_obj_deleg=15,
sec_acl_e_type_group_deleg=16,
sec_acl_e_type_for_group_deleg=17,
sec_acl_e_type_other_obj_deleg=18,
sec_acl_e_type_for_other_deleg=19,
sec_acl_e_type_any_other_deleg=20} sec_acl_entry_type_t;
#define sec_acl_e_type_max_nbr (21)
typedef sec_id_t sec_acl_id_t;
typedef struct  {
sec_acl_permset_t perms;
struct sec_acl_entry_u {
sec_acl_entry_type_t entry_type;
union  {
/* case(s): 5, 0, 1, 2, 9, 11, 12, 15, 18, 20 */
/* Empty arm */
/* case(s): 3, 4, 8, 13, 16, 19 */
sec_id_t id;
/* case(s): 6, 7, 14, 17 */
sec_id_foreign_t foreign_id;
/* case(s): 10 */
sec_acl_extend_info_t *extended_info;
} tagged_union;
} entry_info;
} sec_acl_entry_t;
typedef struct  {
sec_acl_id_t default_realm;
uuid_t sec_acl_manager_type;
unsigned32 num_entries;
sec_acl_entry_t *sec_acl_entries;
} sec_acl_t;
typedef sec_acl_t *sec_acl_p_t;
typedef enum {sec_acl_type_object=0,
sec_acl_type_default_object=1,
sec_acl_type_default_container=2,
sec_acl_type_unspecified_3=3,
sec_acl_type_unspecified_4=4,
sec_acl_type_unspecified_5=5,
sec_acl_type_unspecified_6=6,
sec_acl_type_unspecified_7=7} sec_acl_type_t;
#define sec_acl_printstring_len (16)
#define sec_acl_printstring_help_len (64)
typedef struct  {
idl_char printstring[16];
idl_char helpstring[64];
sec_acl_permset_t permissions;
} sec_acl_printstring_t;
typedef idl_char *sec_acl_component_name_t;
typedef struct  {
unsigned32 num_acls;
sec_acl_p_t sec_acls[1];
} sec_acl_list_t;

#ifdef __cplusplus
    }

#endif
#endif
