/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: oride_base.h,v $
 * Revision 65.2  1999/02/03 22:44:20  mek
 * Convert from IDL to C style include format.
 *
 * Revision 65.1  1997/10/20 19:46:31  jdoak
 * *** empty log message ***
 *
 * Revision 1.1.8.2  1996/03/09  23:27:58  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:43:27  marty]
 *
 * Revision 1.1.8.1  1995/12/08  17:31:49  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  16:55:00  root]
 * 
 * Revision 1.1.6.2  1994/08/31  19:54:28  rsalz
 * 	Add scd bindings file to oride_base.idl and use it (OT CR 10976).
 * 	[1994/08/31  19:31:36  rsalz]
 * 
 * Revision 1.1.6.1  1994/05/05  20:44:36  hasbrouc
 * 	add group override support (RFC 55)
 * 	[1994/05/05  19:11:47  hasbrouc]
 * 
 * Revision 1.1.4.2  1992/12/29  13:29:29  zeliff
 * 	Embedding copyright notice
 * 	[1992/12/28  20:48:21  zeliff]
 * 
 * Revision 1.1.2.2  1992/05/14  18:58:51  burati
 * 	Add sec_override_pw_all
 * 	[1992/05/14  01:52:36  burati]
 * 
 * Revision 1.1  1992/01/19  14:55:11  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/* Generated by IDL compiler version OSF DCE T1.2.0-09 */
#ifndef oride_base_v0_0_included
#define oride_base_v0_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
#define OVERRIDE_FILE "/etc/passwd_override"
#define OVERRIDE_FILE_LEN (20)
#define GROUP_OVERRIDE_FILE "/etc/group_override"
#define GROUP_OVERRIDE_FILE_LEN (19)
#define SCD_BINDINGS_FILE "/var/security/sec_clientd.binding"
#define SCD_BINDINGS_FILE_LEN (33)
typedef unsigned32 sec_override_fields_t;
typedef unsigned32 sec_group_override_fields_t;
#define sec_override_pw_uid (1)
#define sec_override_pw_gid (2)
#define sec_override_pw_passwd (4)
#define sec_override_pw_gecos (8)
#define sec_override_pw_dir (16)
#define sec_override_pw_shell (32)
#define sec_override_pw_all (63)
#define sec_override_none (0)
#define sec_group_override_none (0)
#define sec_group_override_gr_gid (1)
#define sec_group_override_gr_passwd (2)
#define sec_group_override_member (4)

#ifdef __cplusplus
    }

#endif
#endif
