/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: pkl.h,v $
 * Revision 65.2  1999/02/03 22:44:20  mek
 * Convert from IDL to C style include format.
 *
 * Revision 65.1  1997/10/20 19:46:32  jdoak
 * *** empty log message ***
 *
 * Revision 1.1.4.2  1996/03/09  23:28:02  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:43:30  marty]
 *
 * Revision 1.1.4.1  1995/12/08  17:32:07  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  16:55:04  root]
 * 
 * Revision 1.1.2.2  1992/12/29  13:29:49  zeliff
 * 	Embedding copyright notice
 * 	[1992/12/28  20:16:55  zeliff]
 * 
 * Revision 1.1  1992/01/19  14:55:37  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/* Generated by IDL compiler version OSF DCE T1.2.0-09 */
#ifndef pkl_v1_0_included
#define pkl_v1_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
#ifndef pklbase_v1_0_included
#include <dce/pklbase.h>
#endif
#ifndef rpcbase_v0_0_included
#include <dce/rpcbase.h>
#endif
extern void idl_pkl_get_type_uuid(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_pkl_t pickle,
    /* [out] */ uuid_t *type
#endif
);
extern void idl_pkl_get_header(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_pkl_t pickle,
    /* [out] */ unsigned8 *version,
    /* [out] */ unsigned32 *length,
    /* [out] */ rpc_syntax_id_t *syntax,
    /* [out] */ uuid_t *type
#endif
);
extern void idl_pkl_set_header(
#ifdef IDL_PROTOTYPES
    /* [out] */ idl_pkl_t pickle,
    /* [in] */ unsigned32 version,
    /* [in] */ unsigned32 length,
    /* [in] */ rpc_syntax_id_t *syntax,
    /* [in] */ uuid_t *type
#endif
);

#ifdef __cplusplus
    }

#endif
#endif
