/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 */
/*
 * HISTORY
 * $Log: repadm.h,v $
 * Revision 65.2  1999/02/03 22:44:21  mek
 * Convert from IDL to C style include format.
 *
 * Revision 65.1  1997/10/20 19:46:33  jdoak
 * *** empty log message ***
 *
 * Revision 1.1.8.3  1996/03/09  23:28:11  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:43:39  marty]
 *
 * Revision 1.1.8.2  1995/12/08  17:32:51  root
 * 	Submit OSF/DCE 1.2.1
 * 
 * 	HP revision /main/HPDCE02/2  1995/08/02  20:04 UTC  aha
 * 	CHFts15825: dced pe_site update thread does not rebind
 * 
 * 	HP revision /main/HPDCE02/aha_mothra8/1  1995/08/02  18:39 UTC  aha
 * 	CHFts15825: dced pe_site update thread doesn't rebind;
 * 	 add new API sec_rgy_rep_admin_info_any() that can bind to any working replica
 * 
 * 	HP revision /main/HPDCE02/1  1995/05/15  21:03 UTC  greg
 * 	Create SEC_migrate_merge mainline from SEC_migrate and HPDCE02.
 * 	[1995/04/22  13:35 UTC  greg  /main/SEC_migrate_merge/1]
 * 
 * 	Add prototypes for sw_version API routines.
 * 	[1995/02/22  19:56 UTC  greg  /main/SEC_migrate/2]
 * 
 * 	Merge .../greg_sec_migrate/LATEST --> .../SEC_migrate/LATEST.
 * 	[1995/02/11  22:14 UTC  greg  /main/SEC_migrate/1]
 * 
 * 	Add API routines to support real
 * 	software versioning.
 * 
 * 	[1995/02/06  06:15 UTC  greg  /main/greg_sec_migrate/1]
 * 
 * Revision 1.1.4.1  1994/06/17  18:42:21  devsrc
 * 	cr10872 - fix copyright
 * 	[1994/06/17  18:09:01  devsrc]
 * 
 * Revision 1.1.2.2  1993/01/29  19:45:38  burati
 * 	Initial revision
 * 	[1993/01/14  23:17:00  burati]
 * 
 * $EndLog$
 */
/* Generated by IDL compiler version OSF DCE T1.2.0-09 */
#ifndef sec_rgy_rep_admin_v0_0_included
#define sec_rgy_rep_admin_v0_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
#ifndef rgynbase_v0_0_included
#include <dce/rgynbase.h>
#endif
#ifndef sec_rgy_bind_v0_0_included
#include <dce/binding.h>
#endif
#ifndef rplbase_v0_0_included
#include <dce/rplbase.h>
#endif
extern void sec_rgy_rep_admin_stop(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_rgy_handle_t context,
    /* [out] */ error_status_t *status
#endif
);
extern void sec_rgy_rep_admin_maint(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_rgy_handle_t context,
    /* [in] */ boolean32 in_maintenance,
    /* [out] */ error_status_t *status
#endif
);
extern void sec_rgy_rep_admin_mkey(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_rgy_handle_t context,
    /* [out] */ error_status_t *status
#endif
);
extern void sec_rgy_rep_admin_info(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_rgy_handle_t context,
    /* [out] */ rs_replica_info_t *rep_info,
    /* [out] */ error_status_t *status
#endif
);
extern void sec_rgy_rep_admin_info_any(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_rgy_handle_t context,
    /* [out] */ rs_replica_info_t *rep_info,
    /* [out] */ error_status_t *status
#endif
);
extern void sec_rgy_rep_admin_info_vers(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_rgy_handle_t context,
    /* [out] */ rs_replica_info_t *rep_info,
    /* [out] */ rs_replica_twr_vec_p_t *rep_twrs,
    /* [out] */ rs_replica_twr_vec_p_t *master_twrs,
    /* [out] */ unsigned32 *num_sw_vers,
    /* [out] */ rs_replica_sw_vers_info_t **sw_vers_info,
    /* [out] */ unsigned32 *current_sw_vers_offset,
    /* [out] */ error_status_t *status
#endif
);
extern void sec_rgy_rep_admin_info_full(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_rgy_handle_t context,
    /* [out] */ rs_replica_info_t *rep_info,
    /* [out] */ rs_replica_twr_vec_p_t *rep_twrs,
    /* [out] */ rs_replica_twr_vec_p_t *master_twrs,
    /* [out] */ error_status_t *status
#endif
);
extern void sec_rgy_rep_admin_destroy(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_rgy_handle_t context,
    /* [out] */ error_status_t *status
#endif
);
extern void sec_rgy_rep_admin_init_replica(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_rgy_handle_t context,
    /* [in] */ uuid_p_t rep_id,
    /* [out] */ error_status_t *status
#endif
);
extern void sec_rgy_rep_admin_change_master(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_rgy_handle_t context,
    /* [in] */ uuid_p_t new_master_id,
    /* [out] */ error_status_t *status
#endif
);
extern void sec_rgy_rep_admin_become_master(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_rgy_handle_t context,
    /* [out] */ error_status_t *status
#endif
);
extern void sec_rgy_rep_admin_become_slave(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_rgy_handle_t context,
    /* [out] */ error_status_t *status
#endif
);
extern void sec_rgy_rep_admin_set_sw_vers(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_rgy_handle_t context,
    /* [in] */ unsigned32 sw_rev,
    /* [out] */ error_status_t *status
#endif
);
extern void sec_rgy_rep_admin_get_sw_vers(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_rgy_handle_t context,
    /* [out] */ unsigned32 *num_sw_vers,
    /* [out] */ rs_replica_sw_vers_info_t **sw_vers_info,
    /* [out] */ unsigned32 *current_sw_vers_offset,
    /* [out] */ error_status_t *status
#endif
);

#ifdef __cplusplus
    }

#endif
#endif
