/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: rpladmn.h,v $
 * Revision 65.2  1999/02/03 22:44:21  mek
 * Convert from IDL to C style include format.
 *
 * Revision 65.1  1997/10/20 19:46:33  jdoak
 * *** empty log message ***
 *
 * Revision 1.1.4.2  1996/03/09  23:28:16  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:43:44  marty]
 *
 * Revision 1.1.4.1  1995/12/08  17:33:16  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  16:55:17  root]
 * 
 * Revision 1.1.2.3  1992/12/29  13:30:34  zeliff
 * 	Embedding copyright notice
 * 	[1992/12/28  20:48:41  zeliff]
 * 
 * Revision 1.1.2.2  1992/11/04  22:26:23  burati
 * 	rgybase.idl must be imported from dce/
 * 	[1992/11/04  21:19:07  burati]
 * 
 * Revision 1.1  1992/01/19  14:55:18  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/* Generated by IDL compiler version OSF DCE T1.2.0-09 */
#ifndef sec_rgy_rep_admin_v0_0_included
#define sec_rgy_rep_admin_v0_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
#ifndef rgybase_v0_0_included
#include <dce/rgybase.h>
#endif
extern void sec_rgy_rep_admin_stop(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_rgy_handle_t context,
    /* [out] */ error_status_t *status
#endif
);
extern void sec_rgy_rep_admin_maint(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_rgy_handle_t context,
    /* [in] */ boolean32 in_maintenance,
    /* [out] */ error_status_t *status
#endif
);
extern void sec_rgy_rep_admin_mkey(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_rgy_handle_t context,
    /* [out] */ error_status_t *status
#endif
);

#ifdef __cplusplus
    }

#endif
#endif
