/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: rplbase.h,v $
 * Revision 65.2  1999/02/03 22:44:21  mek
 * Convert from IDL to C style include format.
 *
 * Revision 65.1  1997/10/20 19:46:34  jdoak
 * *** empty log message ***
 *
 * Revision 1.1.10.3  1996/03/09  23:28:17  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:43:45  marty]
 *
 * Revision 1.1.10.2  1995/12/08  17:33:22  root
 * 	Submit OSF/DCE 1.2.1
 * 
 * 	HP revision /main/HPDCE02/2  1995/05/15  21:03 UTC  greg
 * 	Create SEC_migrate_merge mainline from SEC_migrate and HPDCE02.
 * 	[1995/04/22  13:35 UTC  greg  /main/HPDCE02/SEC_migrate_merge/1]
 * 
 * 	Merge .../greg_sec_migrate/LATEST --> .../SEC_migrate/LATEST.
 * 	[1995/02/11  22:14 UTC  greg  /main/HPDCE02/SEC_migrate/2]
 * 
 * 	Add rs_replica_sw_vers_info_t.
 * 	[1995/02/05  19:51 UTC  greg  /main/HPDCE02/SEC_migrate/greg_sec_migrate/2]
 * 
 * 	Create initial SEC_migrate mainline.
 * 	Compiled but not tested.
 * 	[1995/01/27  21:15 UTC  greg  /main/HPDCE02/SEC_migrate/1]
 * 
 * 	[1995/01/21  22:07 UTC  greg  /main/HPDCE02/greg_migration2/2]
 * 
 * 	add new replica prop types for sw versioning.
 * 	[1995/01/21  22:01 UTC  greg  /main/HPDCE02/greg_migration2/1]
 * 
 * 	HP revision /main/HPDCE02/1  1994/11/15  21:22 UTC  mullan_s
 * 	Merge.
 * 	[1995/12/08  16:55:17  root]
 * 
 * Revision 1.1.6.2  1994/09/20  20:14:37  rps
 * 	[OT11944] fix rs_update_seqno_t comment
 * 	[1994/09/20  20:08:31  rps]
 * 
 * Revision 1.1.6.1  1994/06/02  21:28:27  mdf
 * 	hp_sec_to_osf_3 drop, merge up with latest.
 * 	[1994/05/24  15:16:01  mdf]
 * 
 * 	hp_sec_to_osf_3 drop
 * 
 * Revision 1.1.8.3  1993/12/17  22:30:33  hanfei
 * 	state_dup_master
 * 	[1993/12/17  22:08:16  hanfei]
 * 
 * Revision 1.1.8.2  1993/12/16  19:01:25  hanfei
 * 	add rs_c_state_becoming_slave
 * 	[1993/12/10  16:20:56  hanfei]
 * 
 * Revision 1.1.6.3  1993/09/15  15:41:36  root
 * 	    Loading drop DCE1_0_3b03
 * 
 * Revision 1.1.2.6  1993/02/26  23:48:56  emartin
 * 	add sw_rev to rs_replica_info_t
 * 	[1993/02/22  22:44:24  emartin]
 * 
 * Revision 1.1.2.5  1992/12/29  13:30:37  zeliff
 * 	Embedding copyright notice
 * 	[1992/12/28  20:48:44  zeliff]
 * 
 * Revision 1.1.2.4  1992/12/18  22:10:58  sekhar
 * 	[OT 6540] Replication code drop bl6c
 * 	[1992/12/18  21:47:13  sekhar]
 * 
 * Revision 1.1.4.2  1992/12/11  21:35:44  emartin
 * 	bl6c: rs_replica_info_t - base_propq_seqno field
 * 
 * Revision 1.1.2.3  1992/10/07  20:29:36  sekhar
 * 	[OT 5566]  Bl5 Replication code drop from HP.
 * 	[1992/10/07  19:13:44  sekhar]
 * 
 * Revision 1.1.3.2  1992/10/06  15:49:17  burati
 * 	 Second replication code drop: bl5
 * 
 * Revision 1.1.2.2  1992/08/31  18:20:55  sekhar
 * 	First security replication code drop
 * 	[1992/08/31  15:08:53  sekhar]
 * 
 * Revision 1.1  1992/01/19  14:54:59  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/* Generated by IDL compiler version OSF DCE T1.2.0-09 */
#ifndef rplbase_v0_0_included
#define rplbase_v0_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
#ifndef rgynbase_v0_0_included
#include <dce/rgynbase.h>
#endif
#define rs_c_state_unknown_to_master (1)
#define rs_c_state_uninitialized (2)
#define rs_c_state_initializing (3)
#define rs_c_state_in_service (4)
#define rs_c_state_renaming (5)
#define rs_c_state_copying_dbase (6)
#define rs_c_state_in_maintenance (7)
#define rs_c_state_mkey_changing (8)
#define rs_c_state_becoming_master (9)
#define rs_c_state_closed (10)
#define rs_c_state_deleted (11)
#define rs_c_state_becoming_slave (12)
#define rs_c_state_dup_master (13)
typedef idl_char *rs_replica_name_p_t;
typedef idl_char rs_sw_version_t[64];
typedef struct  {
unsigned32 sw_vers;
rs_sw_version_t sw_vers_printstring;
} rs_replica_sw_vers_info_t;
#define rs_c_auth_info_krb5_ptgt (1)
typedef struct  {
unsigned32 info_type;
unsigned32 info_len;
idl_byte info[1];
} rs_replica_auth_t;
typedef rs_replica_auth_t *rs_replica_auth_p_t;
typedef struct  {
unsigned32 num_towers;
twr_p_t towers[1];
} rs_replica_twr_vec_t;
typedef rs_replica_twr_vec_t *rs_replica_twr_vec_p_t;
typedef unsigned32 rs_replica_prop_t;
#define rs_c_replica_prop_unknown (0)
#define rs_c_replica_prop_init (1)
#define rs_c_replica_prop_initing (2)
#define rs_c_replica_prop_update (3)
#define rs_c_replica_prop_delete (4)
#define rs_c_replica_prop_bad_sw_rev (5)
typedef struct  {
unsigned32 high;
unsigned32 low;
} rs_update_seqno_t;
typedef struct  {
rs_replica_prop_t prop_type;
boolean32 last_upd_inited;
rs_update_seqno_t last_upd_seqno;
sec_timeval_t last_upd_ts;
unsigned32 num_updates;
} rs_replica_prop_info_t;
typedef rs_replica_prop_info_t *rs_replica_prop_info_p_t;
typedef unsigned32 rs_replica_comm_t;
#define rs_c_replica_comm_ok (1)
#define rs_c_replica_comm_short_failure (2)
#define rs_c_replica_comm_long_failure (3)
typedef struct  {
rs_replica_comm_t comm_state;
error_status_t last_status;
signed32 twr_offset;
} rs_replica_comm_info_t;
typedef rs_replica_comm_info_t *rs_replica_comm_info_p_t;
typedef struct  {
uuid_t rep_id;
rs_replica_name_p_t rep_name;
boolean32 master;
boolean32 deleted;
rs_replica_twr_vec_p_t rep_twrs;
} rs_replica_item_t;
typedef rs_replica_item_t *rs_replica_item_p_t;
typedef struct  {
uuid_t rep_id;
rs_replica_name_p_t rep_name;
boolean32 master;
boolean32 deleted;
rs_replica_prop_info_t prop_info;
rs_replica_comm_info_t comm_info;
rs_replica_twr_vec_p_t rep_twrs;
} rs_replica_item_full_t;
typedef rs_replica_item_full_t *rs_replica_item_full_p_t;
typedef struct  {
unsigned32 rep_state;
uuid_t cell_sec_id;
uuid_t rep_id;
uuid_t init_id;
rs_update_seqno_t last_upd_seqno;
sec_timeval_t last_upd_ts;
rs_sw_version_t sw_rev;
unsigned32 compat_sw_rev;
rs_update_seqno_t base_propq_seqno;
boolean32 master;
boolean32 master_known;
uuid_t master_id;
rs_update_seqno_t master_seqno;
} rs_replica_info_t;
typedef rs_replica_info_t *rs_replica_info_p_t;
typedef struct  {
uuid_t master_id;
rs_update_seqno_t master_seqno;
unsigned32 master_compat_sw_rev;
sec_timeval_t update_ts;
rs_update_seqno_t update_seqno;
rs_update_seqno_t previous_update_seqno;
} rs_replica_master_info_t;
typedef rs_replica_master_info_t *rs_replica_master_info_p_t;

#ifdef __cplusplus
    }

#endif
#endif
