/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 */
/*
 * HISTORY
 * $Log: rpriv_1_0.h,v $
 * Revision 65.2  1999/02/03 22:44:21  mek
 * Convert from IDL to C style include format.
 *
 * Revision 65.1  1997/10/20 19:46:34  jdoak
 * *** empty log message ***
 *
 * Revision 1.1.4.2  1996/03/09  23:28:19  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:43:47  marty]
 *
 * Revision 1.1.4.1  1995/12/08  17:33:34  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  16:55:19  root]
 * 
 * Revision 1.1.2.2  1994/06/17  18:42:24  devsrc
 * 	cr10872 - fix copyright
 * 	[1994/06/17  18:09:02  devsrc]
 * 
 * Revision 1.1.2.1  1994/05/11  19:11:55  ahop
 * 	hp_sec_to_osf_2 drop
 * 	Version 1.0 rpriv  wire interface.
 * 	[1994/04/29  21:07:02  ahop]
 * 
 * $EndLog$
 */
/* Generated by IDL compiler version OSF DCE T1.2.0-09 */
#ifndef rpriv_v1_0_included
#define rpriv_v1_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif
#include <dce/rpc.h>

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
#ifndef prvnbase_v0_0_included
#include <dce/prvnbase.h>
#endif
extern void rpriv_get_ptgt(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t handle,
    /* [in] */ unsigned32 authn_svc,
    /* [in] */ unsigned32 authz_svc,
    /* [in] */ rpriv_pickle_t *ptgt_req,
    /* [out] */ rpriv_pickle_t **ptgt_rep,
    /* [out] */ error_status_t *status
#endif
);
typedef struct rpriv_v1_0_epv_t {
void (*rpriv_get_ptgt)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t handle,
    /* [in] */ unsigned32 authn_svc,
    /* [in] */ unsigned32 authz_svc,
    /* [in] */ rpriv_pickle_t *ptgt_req,
    /* [out] */ rpriv_pickle_t **ptgt_rep,
    /* [out] */ error_status_t *status
#endif
);
} rpriv_v1_0_epv_t;
extern rpc_if_handle_t rpriv_v1_0_c_ifspec;
extern rpc_if_handle_t rpriv_v1_0_s_ifspec;

#ifdef __cplusplus
    }

#else
#endif
#endif
