/*
 * @OSF_COPYRIGHT@
 */
/*
 * HISTORY
 * $Log: rsec_pk_cache.h,v $
 * Revision 65.3  1999/07/21 19:01:14  gwehrman
 * Defined SGIMIPS for this development header.  Fix for bug 657352.
 *
 * Revision 65.2  1999/02/03 22:44:22  mek
 * Convert from IDL to C style include format.
 *
 * Revision 65.1  1997/10/20 19:46:38  jdoak
 * *** empty log message ***
 *
 * Revision 1.1.2.3  1996/10/03  14:53:26  arvind
 * 	CHFts19896: public key version support
 * 	[1996/09/13  23:45 UTC  aha  /main/DCE_1.2.2/aha_pk9_3/1]
 *
 * 	Modify to support public key version numbers
 * 	[1996/09/10  21:09 UTC  aha  /main/DCE_1.2.2/aha_pk9_2/1]
 *
 * 	Bug fixes for rsec_pk_cache
 * 	[1996/07/15  19:43 UTC  aha  /main/DCE122_PK/aha_pk6/4]
 *
 * Revision 1.1.2.2  1996/08/09  12:06:36  arvind
 * 	Bug fixes for rsec_pk_cache
 * 	[1996/07/15  19:43 UTC  aha  /main/DCE122_PK/aha_pk6/4]
 * 
 * 	Changes for Public Key Login; fix rsec_pk_cache_kdc_key() problems
 * 	[1996/06/19  20:33 UTC  aha  /main/DCE122_PK/aha_pk6/2]
 * 
 * 	Changes for Public Key Login; update header for rsec_pk_cache_kdc_key()
 * 	to reflect new location for cache file.
 * 	[1996/06/18  20:56 UTC  aha  /main/DCE122_PK/aha_pk6/1]
 * 
 * 	Merge PSM, sec_pvtkey, sec_pubkey, dced, base defs for Public Key Login
 * 	[1996/06/11  17:59 UTC  aha  /main/DCE_1.2.2/1]
 * 
 * Revision 1.1.2.1  1996/07/08  20:19:57  arvind
 * 	OSF DCE1.2.2 Drop3
 * 	rsec_pk_cache.idl,v
 * 	Revision /main/DCE_1.2.2/2  1996/06/13  21:30 UTC  sommerfeld
 * 	Fix comment.
 * 	[1996/06/11  18:42 UTC  sommerfeld  /main/DCE122_PK/sommerfeld_pk_indir/1]
 * 
 * Revision /main/DCE_1.2.2/1  1996/06/11  17:59 UTC  aha
 * 	Merge PSM, sec_pvtkey, sec_pubkey, dced, base defs for Public Key Login
 * 
 * Revision /main/DCE122_PK/1  1996/06/04  18:53 UTC  psn
 * 	Merge PK work from DCE12_PK off of DCE_1.2 to DCE122_PK off of DCE_1.2.2.
 * 
 * Revision /main/DCE12_PK/3  1996/05/16  14:19 UTC  aha
 * 	Merge changes from aha_pk2 - remove the refresh parameter
 * 	from rsec_pk_cache_kdc_key()
 * 
 * Revision /main/DCE12_PK/2  1996/04/17  16:54 UTC  aha
 * 	Fix log comments
 * 
 * Revision /main/DCE12_PK/1  1996/04/12  19:36 UTC  aha
 * 	rsec_pk_cache interface
 * 
 * Revision /main/DCE_1.2/1  1996/04/11  13:40 UTC  aha
 * 	Additions for public key login
 * 
 * Revision /main/aha_mothra12/1  1996/03/07  16:37 UTC  aha
 * 	Remote interface for sec_login to request
 * 	dced to cache a particular KDC public key
 * 
 * $EndLog$
 */
/* Generated by IDL compiler version OSF DCE T1.2.0-09 */
#ifndef rsec_pk_cache_v1_1_included
#define rsec_pk_cache_v1_1_included
#ifndef SGIMIPS
#define SGIMIPS
#endif /* !SGIMIPS */
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif
#include <dce/rpc.h>

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
#ifndef rgynbase_v0_0_included
#include <dce/rgynbase.h>
#endif
extern error_status_t rsec_pk_cache_kdc_key(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t handle,
    /* [in] */ sec_rgy_name_t cell,
    /* [in] */ sec_pk_usage_flags_t usage,
    /* [in, out] */ unsigned32 *kvno,
    /* [out] */ sec_pk_pubkey_t *pubkey_p
#endif
);
typedef struct rsec_pk_cache_v1_1_epv_t {
error_status_t (*rsec_pk_cache_kdc_key)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t handle,
    /* [in] */ sec_rgy_name_t cell,
    /* [in] */ sec_pk_usage_flags_t usage,
    /* [in, out] */ unsigned32 *kvno,
    /* [out] */ sec_pk_pubkey_t *pubkey_p
#endif
);
} rsec_pk_cache_v1_1_epv_t;
extern rsec_pk_cache_v1_1_epv_t rsec_pk_cache_v1_1_c_epv;
extern rpc_if_handle_t rsec_pk_cache_v1_1_c_ifspec;
extern rpc_if_handle_t rsec_pk_cache_v1_1_s_ifspec;

#ifdef __cplusplus
    }

#else
#endif
#endif
