/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: sec_pvtkey.h,v $
 * Revision 65.2  1999/02/03 22:44:23  mek
 * Convert from IDL to C style include format.
 *
 * Revision 65.1  1997/10/20 19:46:41  jdoak
 * *** empty log message ***
 *
 * Revision 1.1.2.3  1996/11/13  18:03:03  arvind
 * 	Add/modify copyright info
 * 	[1996/08/05  17:41 UTC  cuti  /main/DCE_1.2.2/4]
 *
 * 	Merge in CHFts19722 fix.
 * 	[1996/08/05  13:33 UTC  cuti  /main/DCE122_PK/cuti_pk_migration/1]
 *
 * 	CHFts19722
 * 	[1996/07/03  12:47 UTC  cuti  /main/DCE122_PK/3]
 *
 * Revision 1.1.2.2  1996/08/09  21:22:42  arvind
 * 	Merge in CHFts19722 fix.
 * 	[1996/08/05  13:33 UTC  cuti  /main/DCE122_PK/cuti_pk_migration/1]
 * 
 * 	CHFts19722
 * 	[1996/07/03  12:47 UTC  cuti  /main/DCE122_PK/3]
 * 
 * 	Merge from cuti_pk_export to DCE_1.2.2
 * 	[1996/06/30  21:59 UTC  cuti  /main/DCE_1.2.2/3]
 * 
 * 	Merge PSM, sec_pvtkey, sec_pubkey, dced, base defs for Public Key Login
 * 	[1996/06/11  17:59 UTC  aha  /main/DCE_1.2.2/1]
 * 
 * Revision 1.1.2.1  1996/07/08  20:20:39  arvind
 * 	OSF DCE1.2.2 Drop3
 * 	sec_pvtkey.idl,v
 * 	Revision /main/DCE_1.2.2/3  1996/06/30  21:59 UTC  cuti
 * 	Merge from cuti_pk_export to DCE_1.2.2
 * 	[1996/07/08  19:58:22  arvind]
 * 
 * Revision /main/DCE122_PK/cuti_pk_export/2  1996/06/27  19:42 UTC  cuti
 * 	Merge out from DCE122
 * 
 * 	Modify DES capability's API
 * 	[1996/06/27  14:02 UTC  cuti  /main/DCE122_PK/cuti_pk_export/1]
 * 	Revision /main/DCE_1.2.2/2  1996/06/13  21:29 UTC  sommerfeld
 * 	remove double indirection.
 * 	[1996/06/11  18:58 UTC  sommerfeld  /main/DCE122_PK/sommerfeld_pk_indir/1]
 * 
 * Revision /main/DCE_1.2.2/1  1996/06/11  17:59 UTC  aha
 * 	Merge PSM, sec_pvtkey, sec_pubkey, dced, base defs for Public Key Login
 * 
 * Revision /main/DCE122_PK/1  1996/06/04  18:53 UTC  psn
 * 	Merge PK work from DCE12_PK off of DCE_1.2 to DCE122_PK off of DCE_1.2.2.
 * 
 * Revision /main/DCE12_PK/4  1996/05/28  17:59 UTC  cuti
 * 	Merge psm, pvtkey work
 * 
 * 	Update the error status name
 * 	[1996/05/23  18:47 UTC  cuti  /main/DCE12_PK/cuti_pk_new/1]
 * 	Revision /main/DCE12_PK/3  1996/05/08  15:06 UTC  cuti
 * 	Add psm components
 * 
 * Revision /main/cuti_pk_work/3  1996/05/08  14:26 UTC  cuti
 * 	Prepare for review of pvtkey.
 * 
 * $EndLog$
 */
/* Generated by IDL compiler version OSF DCE T1.2.0-09 */
#ifndef sec_pvtkey_v0_0_included
#define sec_pvtkey_v0_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
#ifndef rgybase_v0_0_included
#include <dce/rgybase.h>
#endif
typedef idl_void_p_t sec_pk_mechanism_handle_t;
typedef uuid_t sec_pk_pvtkey_capability;
extern error_status_t sec_pvtkey_open(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *name,
    /* [in] */ sec_pk_domain_t *domain_id,
    /* [out] */ sec_pk_mechanism_handle_t *handle
#endif
);
extern error_status_t sec_pvtkey_close(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_pk_mechanism_handle_t handle
#endif
);
extern error_status_t sec_pvtkey_capabilities(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_pk_mechanism_handle_t handle,
    /* [in] */ idl_void_p_t capability_parameter,
    /* [in] */ sec_pk_pvtkey_capability *feature,
    /* [out] */ boolean32 *supported
#endif
);
extern error_status_t sec_pvtkey_store(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_pk_mechanism_handle_t handle,
    /* [in] */ idl_char *pwd,
    /* [in] */ sec_pk_usage_flags_t key_usage,
    /* [in] */ unsigned32 key_vno,
    /* [in] */ sec_pk_data_t *private_key,
    /* [in] */ sec_pk_data_t *public_key
#endif
);
extern error_status_t sec_pvtkey_delete(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_pk_mechanism_handle_t handle,
    /* [in] */ idl_char *pwd,
    /* [in] */ sec_pk_usage_flags_t key_usage,
    /* [in] */ unsigned32 key_vno
#endif
);
extern error_status_t sec_pvtkey_generate(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_pk_mechanism_handle_t handle,
    /* [in] */ idl_char *pwd,
    /* [in] */ sec_pk_algorithm_id_t *alg_id,
    /* [in] */ unsigned32 key_length,
    /* [in] */ sec_pk_usage_flags_t key_usage,
    /* [in] */ unsigned32 key_vno,
    /* [out] */ sec_pk_data_t *public_key
#endif
);
extern error_status_t sec_pvtkey_get(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_pk_mechanism_handle_t handle,
    /* [in] */ idl_char *pwd,
    /* [in] */ sec_pk_usage_flags_t key_usage,
    /* [in, out] */ unsigned32 *key_vno,
    /* [out] */ sec_pk_data_t *private_key,
    /* [out] */ sec_pk_data_t *public_key
#endif
);
extern error_status_t sec_pvtkey_update(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_pk_mechanism_handle_t handle,
    /* [in] */ idl_char *current_pwd,
    /* [in] */ idl_char *new_pwd,
    /* [in] */ sec_pk_usage_flags_t key_usage,
    /* [out] */ unsigned32 *key_vno,
    /* [in] */ sec_pk_data_t *private_key,
    /* [in] */ sec_pk_data_t *public_key
#endif
);
extern error_status_t sec_pvtkey_update_generate(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_pk_mechanism_handle_t handle,
    /* [in] */ idl_char *current_pwd,
    /* [in] */ idl_char *new_pwd,
    /* [in] */ sec_pk_algorithm_id_t *alg_id,
    /* [in] */ unsigned32 key_length,
    /* [in] */ sec_pk_usage_flags_t key_usages,
    /* [out] */ unsigned32 *key_vno,
    /* [out] */ sec_pk_data_t *public_key
#endif
);

#ifdef __cplusplus
    }

#endif
#endif
