/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: sec_psm.h,v $
 * Revision 65.2  1999/02/03 22:44:23  mek
 * Convert from IDL to C style include format.
 *
 * Revision 65.1  1997/10/20 19:46:40  jdoak
 * *** empty log message ***
 *
 * Revision 1.1.2.3  1996/11/13  18:02:37  arvind
 * 	Add/modify copyright info
 * 	[1996/08/23  14:44 UTC  aha  /main/DCE_1.2.2/4]
 *
 * 	[1996/05/08  14:25 UTC  cuti  /main/cuti_pk_work/4]
 *
 * Revision 1.1.2.2  1996/10/03  14:54:27  arvind
 * 	Merge Bill's change
 * 	[1996/08/13  13:48 UTC  cuti  /main/DCE_1.2.2/cuti_pk_bugfix/1]
 * 
 * 	Merge from cuti_pk_export to DCE_1.2.2
 * 	[1996/06/30  21:59 UTC  cuti  /main/DCE_1.2.2/3]
 * 
 * 	Merge PSM, sec_pvtkey, sec_pubkey, dced, base defs for Public Key Login
 * 	[1996/06/11  17:59 UTC  aha  /main/DCE_1.2.2/1]
 * 
 * 	change interface for public key domain.
 * 	make kvno's visible.
 * 	[1996/08/09  17:47 UTC  sommerfeld  /main/DCE122_PK/sommerfeld_pk_kdc/1]
 * 
 * 	[1996/05/08  14:25 UTC  cuti  /main/cuti_pk_work/4]
 * 
 * Revision 1.1.2.1  1996/07/08  20:20:18  arvind
 * 	OSF DCE1.2.2 Drop3
 * 	sec_psm.idl,v
 * 	Revision /main/DCE_1.2.2/3  1996/06/30  21:59 UTC  cuti
 * 	Merge from cuti_pk_export to DCE_1.2.2
 * 	[1996/07/08  19:56:10  arvind]
 * 
 * Revision /main/DCE122_PK/cuti_pk_export/3  1996/06/27  19:42 UTC  cuti
 * 	Merge out from DCE122
 * 
 * 	Change modulus_bit_sixe from in/out to in
 * 	[1996/06/27  15:14 UTC  cuti  /main/DCE122_PK/cuti_pk_export/2]
 * 
 * 	Merge out from cuti_pk_new to cuti_pk_export
 * 
 * 	Change modulus_size to in/out
 * 	[1996/06/11  19:50 UTC  cuti  /main/DCE12_PK/cuti_pk_new/4]
 * 
 * 	Update from review
 * 	[1996/05/24  20:37 UTC  cuti  /main/DCE12_PK/cuti_pk_new/3]
 * 
 * 	Change from local algorithm_id to real ASN.1 algorithm_id
 * 	[1996/05/24  19:26 UTC  cuti  /main/DCE12_PK/cuti_pk_new/2]
 * 
 * 	Update error status.
 * 	[1996/05/23  18:49 UTC  cuti  /main/DCE12_PK/cuti_pk_new/1]
 * 	Revision /main/DCE_1.2.2/2  1996/06/13  21:29 UTC  sommerfeld
 * 	remove double indirection.
 * 	[1996/06/11  18:58 UTC  sommerfeld  /main/DCE122_PK/sommerfeld_pk_indir/1]
 * 
 * Revision /main/DCE_1.2.2/1  1996/06/11  17:59 UTC  aha
 * 	Merge PSM, sec_pvtkey, sec_pubkey, dced, base defs for Public Key Login
 * 
 * Revision /main/DCE122_PK/1  1996/06/04  18:53 UTC  psn
 * 	Merge PK work from DCE12_PK off of DCE_1.2 to DCE122_PK off of DCE_1.2.2.
 * 
 * Revision /main/DCE12_PK/4  1996/05/28  17:59 UTC  cuti
 * 	Merge psm, pvtkey work
 * 
 * 	Update from review
 * 	[1996/05/24  20:37 UTC  cuti  /main/DCE12_PK/cuti_pk_new/3]
 * 
 * 	Change from local algorithm_id to real ASN.1 algorithm_id
 * 	[1996/05/24  19:26 UTC  cuti  /main/DCE12_PK/cuti_pk_new/2]
 * 
 * 	Update error status.
 * 	[1996/05/23  18:49 UTC  cuti  /main/DCE12_PK/cuti_pk_new/1]
 * 	Revision /main/DCE12_PK/3  1996/05/08  15:05 UTC  cuti
 * 	Add psm components
 * 
 * $EndLog$
 */
/* Generated by IDL compiler version OSF DCE T1.2.0-09 */
#ifndef sec_psm_v0_0_included
#define sec_psm_v0_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
#ifndef sec_pk_base_v0_0_included
#include <dce/sec_pk_base.h>
#endif
typedef idl_void_p_t sec_psm_handle_t;
extern error_status_t sec_psm_open(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_void_p_t name,
    /* [in] */ idl_char *pwd,
    /* [in] */ sec_pk_domain_t *domain_id,
    /* [out] */ sec_psm_handle_t *psm_handle
#endif
);
extern error_status_t sec_psm_close(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_psm_handle_t psm_handle
#endif
);
extern error_status_t sec_psm_sign_data(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_psm_handle_t psm_handle,
    /* [in] */ sec_pk_algorithm_id_t *signature_alg_id,
    /* [in] */ sec_pk_usage_flags_t key_usage,
    /* [in] */ sec_pk_gen_data_t *data,
    /* [out] */ unsigned32 *kvno,
    /* [out] */ sec_pk_signed_t *signature
#endif
);
extern error_status_t sec_psm_verify_data(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_psm_handle_t psm_handle,
    /* [in] */ sec_pk_domain_t *signer_domain_id,
    /* [in] */ idl_void_p_t signer_name,
    /* [in] */ unsigned32 kvno,
    /* [in] */ sec_pk_algorithm_id_t *signature_alg_id,
    /* [in] */ sec_pk_usage_flags_t key_usage,
    /* [in] */ sec_pk_gen_data_t *data,
    /* [in] */ sec_pk_signed_t *signature
#endif
);
extern error_status_t sec_psm_encrypt_data(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_psm_handle_t psm_handle,
    /* [in] */ sec_pk_domain_t *encryptee_domain,
    /* [in] */ idl_void_p_t encryptee_name,
    /* [in, out] */ unsigned32 *kvno,
    /* [in] */ sec_pk_algorithm_id_t *encryption_alg_id,
    /* [in] */ sec_pk_usage_flags_t key_usage,
    /* [in] */ sec_pk_gen_data_t *clear_data,
    /* [out] */ sec_pk_encrypted_t *cipher_data
#endif
);
extern error_status_t sec_psm_decrypt_data(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_psm_handle_t psm_handle,
    /* [in] */ unsigned32 kvno,
    /* [in] */ sec_pk_algorithm_id_t *encryption_alg_id,
    /* [in] */ sec_pk_usage_flags_t key_usage,
    /* [in] */ sec_pk_encrypted_t *cipher_data,
    /* [out] */ sec_pk_gen_data_t *clear_data
#endif
);
extern error_status_t sec_psm_gen_pub_key(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_pk_algorithm_id_t *key_type,
    /* [in] */ unsigned32 modulus_bit_size,
    /* [in] */ sec_pk_gen_data_t *seed,
    /* [out] */ sec_pk_data_t *public_key,
    /* [out] */ sec_pk_data_t *private_key
#endif
);
extern error_status_t sec_psm_put_pub_key(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_psm_handle_t psm_handle,
    /* [in] */ idl_char *pwd,
    /* [in] */ sec_pk_usage_flags_t key_usage,
    /* [in] */ sec_pk_pubkey_t *public_key,
    /* [in] */ sec_pk_pvtkey_t *private_key
#endif
);
extern error_status_t sec_psm_update_pub_key(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_psm_handle_t psm_handle,
    /* [in] */ idl_char *oldpwd,
    /* [in] */ idl_char *newpwd,
    /* [in] */ sec_pk_usage_flags_t key_usage,
    /* [in] */ sec_pk_pubkey_t *public_key,
    /* [in] */ sec_pk_pvtkey_t *private_key
#endif
);

#ifdef __cplusplus
    }

#endif
#endif
