/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 */
/*
 * HISTORY
 * $Log: sec_pwd_mgmt.h,v $
 * Revision 65.2  1999/02/03 22:44:23  mek
 * Convert from IDL to C style include format.
 *
 * Revision 65.1  1997/10/20 19:46:41  jdoak
 * *** empty log message ***
 *
 * Revision 1.1.4.2  1996/03/09  23:29:18  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:44:41  marty]
 *
 * Revision 1.1.4.1  1995/12/08  17:38:04  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  16:56:12  root]
 * 
 * Revision 1.1.2.3  1994/07/15  15:00:23  mdf
 * 	Hewlett Packard Security Code Drop
 * 	[1994/07/14  17:17:37  mdf]
 * 
 * Revision 1.1.2.2  1994/06/17  18:42:35  devsrc
 * 	cr10872 - fix copyright
 * 	[1994/06/17  18:10:40  devsrc]
 * 
 * Revision 1.1.2.1  1994/05/11  19:14:25  ahop
 * 	hp_sec_to_osf_2 drop
 * 	sec_password interface definitions.
 * 	[1994/04/29  21:10:01  ahop]
 * 
 * $EndLog$
 */
/* Generated by IDL compiler version OSF DCE T1.2.0-09 */
#ifndef sec_pwd_mgmt_v0_0_included
#define sec_pwd_mgmt_v0_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
#ifndef passwd_v0_0_included
#include <dce/passwd.h>
#endif
#ifndef rgybase_v0_0_included
#include <dce/rgybase.h>
#endif
#ifndef sec_login_v0_0_included
#include <dce/sec_login.h>
#endif
typedef idl_void_p_t sec_pwd_mgmt_handle_t;
extern void sec_pwd_mgmt_setup(
#ifdef IDL_PROTOTYPES
    /* [out] */ sec_pwd_mgmt_handle_t *pwd_mgmt_h,
    /* [in] */ sec_rgy_handle_t context,
    /* [in] */ sec_rgy_login_name_t login_name,
    /* [in] */ sec_login_handle_t your_lc,
    /* [in] */ rpc_binding_handle_t pwd_mgmt_bind_h,
    /* [out] */ error_status_t *stp
#endif
);
extern void sec_pwd_mgmt_get_val_type(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_pwd_mgmt_handle_t pwd_mgmt_h,
    /* [out] */ signed32 *pwd_val_type,
    /* [out] */ error_status_t *stp
#endif
);
extern void sec_pwd_mgmt_gen_pwd(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_pwd_mgmt_handle_t pwd_mgmt_h,
    /* [in] */ unsigned32 num_pwds,
    /* [out] */ unsigned32 *num_returned,
    /* [out] */ sec_passwd_rec_t gen_pwds[],
    /* [out] */ error_status_t *stp
#endif
);
extern void sec_pwd_mgmt_free_handle(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_pwd_mgmt_handle_t *pwd_mgmt_h,
    /* [out] */ error_status_t *stp
#endif
);

#ifdef __cplusplus
    }

#endif
#endif
