/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: sec_pk_base.h,v $
 * Revision 65.2  1999/02/03 22:44:23  mek
 * Convert from IDL to C style include format.
 *
 * Revision 65.1  1997/10/20 19:46:40  jdoak
 * *** empty log message ***
 *
 * Revision 1.1.2.2  1996/10/03  14:54:14  arvind
 * 	CHFts19896: public key version support
 * 	[1996/09/13  23:45 UTC  aha  /main/DCE_1.2.2/aha_pk9_3/1]
 *
 * 	Test uuid
 * 	[1996/09/10  21:09 UTC  aha  /main/DCE_1.2.2/aha_pk9_2/1]
 *
 * Revision 1.1.2.1  1996/07/08  20:20:08  arvind
 * 	OSF DCE1.2.2 Drop3
 * 	sec_pk_base.idl,v
 * 	Revision /main/DCE_1.2.2/3  1996/06/30  21:59 UTC  cuti
 * 	Merge from cuti_pk_export to DCE_1.2.2
 * 	[1996/07/08  19:54:56  arvind]
 * 
 * Revision /main/DCE_1.2.2/cuti_pk_export/1  1996/06/27  19:42 UTC  cuti
 * 	Change ref to ptr in sec_pk_data_t
 * 
 * Revision /main/DCE_1.2.2/2  1996/06/13  21:30 UTC  sommerfeld
 * 	make pk_gen_data_t be an alias for pk_data_t
 * 	[1996/06/11  18:59 UTC  sommerfeld  /main/DCE122_PK/sommerfeld_pk_indir/1]
 * 
 * Revision /main/DCE_1.2.2/1  1996/06/11  17:59 UTC  aha
 * 	Merge PSM, sec_pvtkey, sec_pubkey, dced, base defs for Public Key Login
 * 
 * Revision /main/DCE122_PK/1  1996/06/04  18:53 UTC  psn
 * 	Merge PK work from DCE12_PK off of DCE_1.2 to DCE122_PK off of DCE_1.2.2.
 * 
 * Revision /main/DCE12_PK/5  1996/05/28  17:59 UTC  cuti
 * 	Merge psm, pvtkey work
 * 
 * 	Update after review
 * 	[1996/05/24  20:37 UTC  cuti  /main/DCE12_PK/cuti_pk_new/1]
 * 	Revision /main/DCE12_PK/4  1996/05/21  18:34 UTC  aha
 * 	Merge bugfixes for dced and sec_pubkey based on code review
 * 
 * Revision /main/DCE12_PK/aha_pk3/1  1996/05/21  13:05 UTC  aha
 * 	Remove sec_pk_BindKeyInfo_t and sec_pk_ObjectIdentifier_t
 * 
 * Revision /main/DCE12_PK/3  1996/05/08  14:34 UTC  cuti
 * 	Add sec_pk_gen_data_t
 * 
 * Revision /main/DCE12_PK/cuti_pk_work/1  1996/05/08  14:27 UTC  cuti
 * 	Add sec_pk_gen_data_t.
 * 
 * Revision /main/DCE12_PK/2  1996/04/17  16:44 UTC  aha
 * 	Shorten field names in sec_pk_data_t structure.
 * 
 * Revision /main/DCE12_PK/1  1996/04/12  19:34 UTC  aha
 * 	sec_pk_base interface
 * 
 * Revision /main/DCE_1.2/1  1996/04/11  13:40 UTC  aha
 * 	Additions for public key login
 * 
 * $EndLog$
 */
/* Generated by IDL compiler version OSF DCE T1.2.0-09 */
#ifndef sec_pk_base_v0_0_included
#define sec_pk_base_v0_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
typedef uuid_t sec_pk_domain_t;
typedef unsigned32 sec_pk_usage_flags_t;
#define sec_pk_usage_digitalSignature (1)
#define sec_pk_usage_nonRepudiation (2)
#define sec_pk_usage_keyEncipherment (4)
#define sec_pk_usage_dataEncipherment (8)
#define sec_pk_usage_keyAgreement (16)
#define sec_pk_usage_keyCertSign (32)
#define sec_pk_usage_offLineCRLSign (64)
#define MAX_USAGES (7)
typedef struct  {
unsigned32 len;
idl_byte *data;
} sec_pk_data_t;
typedef sec_pk_data_t *sec_pk_data_p_t;
typedef sec_pk_data_t sec_pk_gen_data_t;
typedef sec_pk_data_t sec_pk_pubkey_t;
typedef sec_pk_pubkey_t *sec_pk_pubkey_p_t;
typedef sec_pk_data_t sec_pk_pvtkey_t;
typedef sec_pk_pvtkey_t *sec_pk_pvtkey_p_t;
typedef sec_pk_data_t sec_pk_signed_t;
typedef sec_pk_signed_t *sec_pk_signed_p_t;
typedef sec_pk_data_t sec_pk_encrypted_t;
typedef sec_pk_encrypted_t *sec_pk_encrypted_p_t;
typedef sec_pk_data_t sec_pk_algorithm_id_t;
typedef sec_pk_algorithm_id_t *sec_pk_algorithm_id_p_t;

#ifdef __cplusplus
    }

#endif
#endif
