/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: unix.h,v $
 * Revision 65.2  1999/02/03 22:44:24  mek
 * Convert from IDL to C style include format.
 *
 * Revision 65.1  1997/10/20 19:46:42  jdoak
 * *** empty log message ***
 *
 * Revision 1.1.7.2  1996/03/09  23:29:26  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:44:48  marty]
 *
 * Revision 1.1.7.1  1995/12/08  17:38:39  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  16:56:19  root]
 * 
 * Revision 1.1.5.2  1992/12/29  13:54:33  zeliff
 * 	Embedding copyright notice
 * 	[1992/12/28  20:49:45  zeliff]
 * 
 * Revision 1.1.3.2  1992/06/02  21:05:41  sekhar
 * 	Drop the Unix interfaces changes made by frisco.
 * 	[1992/06/01  20:20:14  sekhar]
 * 
 * Revision 1.1.1.2  1992/05/22  19:20:01  frisco
 * 	Initial revision - Client Unix interface
 * 
 * $EndLog$
 */
/* Generated by IDL compiler version OSF DCE T1.2.0-09 */
#ifndef sec_rgy_unix_v0_0_included
#define sec_rgy_unix_v0_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
#ifndef rgybase_v0_0_included
#include <dce/rgybase.h>
#endif
extern void sec_rgy_unix_getpwent(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_rgy_handle_t context,
    /* [in, out] */ sec_rgy_cursor_t *marker,
    /* [out] */ sec_rgy_unix_passwd_t *passwd_entry,
    /* [out] */ error_status_t *status
#endif
);
extern void sec_rgy_unix_getpwuid(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_rgy_handle_t context,
    /* [in] */ signed32 uid,
    /* [in, out] */ sec_rgy_cursor_t *marker,
    /* [out] */ sec_rgy_unix_passwd_t *passwd_entry,
    /* [out] */ error_status_t *status
#endif
);
extern void sec_rgy_unix_getpwnam(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_rgy_handle_t context,
    /* [in] */ sec_rgy_name_t name,
    /* [in] */ unsigned32 name_len,
    /* [in, out] */ sec_rgy_cursor_t *marker,
    /* [out] */ sec_rgy_unix_passwd_t *passwd_entry,
    /* [out] */ error_status_t *status
#endif
);
extern void sec_rgy_unix_getgrent(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_rgy_handle_t context,
    /* [in] */ signed32 max_num_members,
    /* [in, out] */ sec_rgy_cursor_t *marker,
    /* [out] */ sec_rgy_unix_group_t *group_entry,
    /* [out] */ signed32 *num_members,
    /* [out] */ sec_rgy_member_t members[],
    /* [out] */ error_status_t *status
#endif
);
extern void sec_rgy_unix_getgrgid(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_rgy_handle_t context,
    /* [in] */ signed32 gid,
    /* [in] */ signed32 max_num_members,
    /* [in, out] */ sec_rgy_cursor_t *marker,
    /* [out] */ sec_rgy_unix_group_t *group_entry,
    /* [out] */ signed32 *num_members,
    /* [out] */ sec_rgy_member_t members[],
    /* [out] */ error_status_t *status
#endif
);
extern void sec_rgy_unix_getgrnam(
#ifdef IDL_PROTOTYPES
    /* [in] */ sec_rgy_handle_t context,
    /* [in] */ sec_rgy_name_t name,
    /* [in] */ signed32 name_len,
    /* [in] */ signed32 max_num_members,
    /* [in, out] */ sec_rgy_cursor_t *marker,
    /* [out] */ sec_rgy_unix_group_t *group_entry,
    /* [out] */ signed32 *num_members,
    /* [out] */ sec_rgy_member_t members[],
    /* [out] */ error_status_t *status
#endif
);

#ifdef __cplusplus
    }

#endif
#endif
