/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: mgmt.h,v $
 * Revision 65.2  1999/02/04 22:37:20  mek
 * Provide C style include file for IRIX kernel integration.
 *
 * Revision 65.1  1997/10/20 19:16:18  jdoak
 * *** empty log message ***
 *
 * Revision 1.1.8.1  1996/06/04  21:56:53  arvind
 * 	merge u2u addition of rpc__mgmt_inq_svr_name_tgt
 * 	[1996/05/06  20:09 UTC  burati  /main/DCE_1.2/1]
 *
 * 	merge u2u work
 * 	[1996/04/29  19:48 UTC  burati  /main/mb_u2u/1]
 *
 * 	u2u work off Mothra, before 1.2 branch is available
 * 	[1996/04/29  19:46 UTC  burati  /main/mb_mothra8/1]
 *
 * Revision 1.1.6.2  1996/03/09  23:26:40  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:42:12  marty]
 * 
 * Revision 1.1.6.1  1995/12/08  00:23:21  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  00:01:07  root]
 * 
 * Revision 1.1.4.1  1993/09/29  17:42:24  markar
 * 	     OT CR 7550 fix:  make mgmt inquiry interfaces idempotent
 * 	[1993/09/29  16:13:56  markar]
 * 
 * Revision 1.1.2.3  1993/01/03  23:56:33  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/03  20:15:15  bbelch]
 * 
 * Revision 1.1.2.2  1992/12/23  21:20:12  zeliff
 * 	Embedding copyright notice
 * 	[1992/12/23  15:46:55  zeliff]
 * 
 * Revision 1.1  1992/01/19  03:13:36  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */

/* Generated by IDL compiler version OSF DCE T1.2.0-09 */
#ifndef mgmt_v1_0_included
#define mgmt_v1_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif
#include <dce/rpc.h>

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
#ifndef rpctypes_v0_0_included
#include <dce/rpctypes.h>
#endif
extern void rpc__mgmt_inq_if_ids(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t binding_handle,
    /* [out] */ rpc_if_id_vector_p_t *if_id_vector,
    /* [out] */ error_status_t *status
#endif
);
extern void rpc__mgmt_inq_stats(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t binding_handle,
    /* [in, out] */ unsigned32 *count,
    /* [out] */ unsigned32 statistics[],
    /* [out] */ error_status_t *status
#endif
);
extern boolean32 rpc__mgmt_is_server_listening(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t binding_handle,
    /* [out] */ error_status_t *status
#endif
);
extern void rpc__mgmt_stop_server_listening(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t binding_handle,
    /* [out] */ error_status_t *status
#endif
);
extern void rpc__mgmt_inq_princ_name(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t binding_handle,
    /* [in] */ unsigned32 authn_proto,
    /* [in] */ unsigned32 princ_name_size,
    /* [out] */ idl_char princ_name[],
    /* [out] */ error_status_t *status
#endif
);
extern void rpc__mgmt_inq_svr_name_tgt(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t binding_handle,
    /* [in] */ unsigned32 authn_proto,
    /* [in] */ unsigned32 princ_name_size,
    /* [in] */ unsigned32 tkt_size_avail,
    /* [out] */ idl_char princ_name[],
    /* [out] */ unsigned32 *tkt_length,
    /* [out] */ idl_char *data,
    /* [out] */ error_status_t *status
#endif
);
typedef struct mgmt_v1_0_epv_t {
void (*rpc__mgmt_inq_if_ids)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t binding_handle,
    /* [out] */ rpc_if_id_vector_p_t *if_id_vector,
    /* [out] */ error_status_t *status
#endif
);
void (*rpc__mgmt_inq_stats)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t binding_handle,
    /* [in, out] */ unsigned32 *count,
    /* [out] */ unsigned32 statistics[],
    /* [out] */ error_status_t *status
#endif
);
boolean32 (*rpc__mgmt_is_server_listening)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t binding_handle,
    /* [out] */ error_status_t *status
#endif
);
void (*rpc__mgmt_stop_server_listening)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t binding_handle,
    /* [out] */ error_status_t *status
#endif
);
void (*rpc__mgmt_inq_princ_name)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t binding_handle,
    /* [in] */ unsigned32 authn_proto,
    /* [in] */ unsigned32 princ_name_size,
    /* [out] */ idl_char princ_name[],
    /* [out] */ error_status_t *status
#endif
);
void (*rpc__mgmt_inq_svr_name_tgt)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t binding_handle,
    /* [in] */ unsigned32 authn_proto,
    /* [in] */ unsigned32 princ_name_size,
    /* [in] */ unsigned32 tkt_size_avail,
    /* [out] */ idl_char princ_name[],
    /* [out] */ unsigned32 *tkt_length,
    /* [out] */ idl_char *data,
    /* [out] */ error_status_t *status
#endif
);
} mgmt_v1_0_epv_t;
extern mgmt_v1_0_epv_t mgmt_v1_0_c_epv;
extern rpc_if_handle_t mgmt_v1_0_c_ifspec;
extern rpc_if_handle_t mgmt_v1_0_s_ifspec;

#ifdef __cplusplus
    }

#else
#endif
#endif
