/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: nbase.h,v $
 * Revision 65.2  1999/02/04 22:37:20  mek
 * Provide C style include file for IRIX kernel integration.
 *
 * Revision 65.1  1997/10/20 19:16:19  jdoak
 * *** empty log message ***
 *
 * Revision 1.1.4.2  1996/03/09  23:26:43  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:42:15  marty]
 *
 * Revision 1.1.4.1  1995/12/08  00:23:23  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  00:01:09  root]
 * 
 * Revision 1.1.2.3  1993/01/04  00:10:06  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/03  20:15:23  bbelch]
 * 
 * Revision 1.1.2.2  1992/12/23  21:20:22  zeliff
 * 	Embedding copyright notice
 * 	[1992/12/23  15:47:02  zeliff]
 * 
 * Revision 1.1  1992/01/19  03:13:47  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */

/* Generated by IDL compiler version OSF DCE T1.2.0-09 */
#ifndef nbase_v0_0_included
#define nbase_v0_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif

#ifdef __cplusplus
    extern "C" {
#endif

#include <dce/nbase.h>
typedef idl_usmall_int unsigned8;
typedef idl_ushort_int unsigned16;
typedef idl_ulong_int unsigned32;
typedef idl_small_int signed8;
typedef idl_short_int signed16;
typedef idl_long_int signed32;
typedef unsigned32 boolean32;
typedef idl_ulong_int error_status_t;
#define error_status_ok (0)
typedef struct  {
unsigned32 time_low;
unsigned16 time_mid;
unsigned16 time_hi_and_version;
unsigned8 clock_seq_hi_and_reserved;
unsigned8 clock_seq_low;
idl_byte node[6];
} uuid_t;
typedef uuid_t *uuid_p_t;
typedef struct  {
idl_ulong_int time_high;
idl_ushort_int time_low;
idl_ushort_int reserved;
idl_byte family;
idl_byte host[7];
} uuid_old_t;
typedef struct  {
unsigned32 tower_length;
idl_byte tower_octet_string[1];
} twr_t;
typedef twr_t *twr_p_t;
#define ndr_c_int_big_endian (0)
#define ndr_c_int_little_endian (1)
#define ndr_c_float_ieee (0)
#define ndr_c_float_vax (1)
#define ndr_c_float_cray (2)
#define ndr_c_float_ibm (3)
#define ndr_c_char_ascii (0)
#define ndr_c_char_ebcdic (1)
typedef struct  {
unsigned8 int_rep;
unsigned8 char_rep;
unsigned8 float_rep;
idl_byte reserved;
} ndr_format_t;
typedef ndr_format_t *ndr_format_p_t;
typedef struct ndr_context_handle {
unsigned32 context_handle_attributes;
uuid_t context_handle_uuid;
} ndr_context_handle;
typedef idl_byte ISO_LATIN_1;
typedef struct  {
idl_byte row;
idl_byte column;
} ISO_MULTI_LINGUAL;
typedef struct  {
idl_byte group;
idl_byte plane;
idl_byte row;
idl_byte column;
} ISO_UCS;
#define dce_c_rpc_authn_protocol_none (0)
#define dce_c_rpc_authn_protocol_krb5 (1)
#define dce_c_rpc_authn_protocol_dummy (2)
#define dce_c_rpc_authn_protocol_dssa (3)
typedef unsigned8 dce_rpc_authn_protocol_id_t;

#ifdef __cplusplus
    }

#endif
#endif
