/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: ncastat.h,v $
 * Revision 65.2  1999/02/04 22:37:20  mek
 * Provide C style include file for IRIX kernel integration.
 *
 * Revision 65.1  1997/10/20 19:16:19  jdoak
 * *** empty log message ***
 *
 * Revision 1.1.10.2  1996/03/09  23:26:44  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:42:16  marty]
 *
 * Revision 1.1.10.1  1995/12/08  00:23:25  root
 * 	Submit OSF/DCE 1.2.1
 * 
 * 	HP revision /main/dat_xidl2/1  1995/11/17  17:10 UTC  dat
 * 	Merge second XIDL drop for DCE 1.2.1
 * 	[1995/12/08  00:01:09  root]
 * 
 * Revision 1.1.6.1  1994/08/23  20:19:10  tom
 * 	Add fault: nca_s_fault_codeset_conv_error (OT 10410)
 * 	[1994/08/23  20:17:24  tom]
 * 
 * Revision 1.1.4.3  1993/08/17  21:06:58  hinxman
 * 	Add a fault type for transactional RPC
 * 	[1993/08/17  21:04:57  hinxman]
 * 
 * Revision 1.1.4.2  1993/07/07  20:12:22  ganni
 * 	reduced stub idl sources
 * 	[1993/07/07  19:40:31  ganni]
 * 
 * Revision 1.1.2.3  1993/01/04  00:10:08  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/03  20:15:26  bbelch]
 * 
 * Revision 1.1.2.2  1992/12/23  21:20:26  zeliff
 * 	Embedding copyright notice
 * 	[1992/12/23  15:47:07  zeliff]
 * 
 * Revision 1.1  1992/01/19  03:13:48  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */

/* Generated by IDL compiler version OSF DCE T1.2.0-09 */
#ifndef nca_status_v0_0_included
#define nca_status_v0_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
#define nca_s_comm_failure (469827585)
#define nca_s_op_rng_error (469827586)
#define nca_s_unk_if (469827587)
#define nca_s_wrong_boot_time (469827590)
#define nca_s_you_crashed (469827593)
#define nca_s_proto_error (469827595)
#define nca_s_out_args_too_big (469827603)
#define nca_s_server_too_busy (469827604)
#define nca_s_fault_string_too_long (469827605)
#define nca_s_unsupported_type (469827607)
#define nca_s_fault_int_div_by_zero (469762049)
#define nca_s_fault_addr_error (469762050)
#define nca_s_fault_fp_div_zero (469762051)
#define nca_s_fault_fp_underflow (469762052)
#define nca_s_fault_fp_overflow (469762053)
#define nca_s_fault_invalid_tag (469762054)
#define nca_s_fault_invalid_bound (469762055)
#define nca_s_rpc_version_mismatch (469762056)
#define nca_s_unspec_reject (469762057)
#define nca_s_bad_actid (469762058)
#define nca_s_who_are_you_failed (469762059)
#define nca_s_manager_not_entered (469762060)
#define nca_s_fault_cancel (469762061)
#define nca_s_fault_ill_inst (469762062)
#define nca_s_fault_fp_error (469762063)
#define nca_s_fault_int_overflow (469762064)
#define nca_s_fault_unspec (469762066)
#define nca_s_fault_remote_comm_failure (469762067)
#define nca_s_fault_pipe_empty (469762068)
#define nca_s_fault_pipe_closed (469762069)
#define nca_s_fault_pipe_order (469762070)
#define nca_s_fault_pipe_discipline (469762071)
#define nca_s_fault_pipe_comm_error (469762072)
#define nca_s_fault_pipe_memory (469762073)
#define nca_s_fault_context_mismatch (469762074)
#define nca_s_fault_remote_no_memory (469762075)
#define nca_s_invalid_pres_context_id (469762076)
#define nca_s_unsupported_authn_level (469762077)
#define nca_s_invalid_checksum (469762079)
#define nca_s_invalid_crc (469762080)
#define nca_s_fault_user_defined (469762081)
#define nca_s_fault_tx_open_failed (469762082)
#define nca_s_fault_codeset_conv_error (469762083)
#define nca_s_fault_object_not_found (469762084)
#define nca_s_fault_no_client_stub (469762085)

#ifdef __cplusplus
    }

#endif
#endif
