/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: rpc.h,v $
 * Revision 65.3  1999/02/04 22:37:20  mek
 * Provide C style include file for IRIX kernel integration.
 *
 * Revision 65.2  1998/04/01 14:17:06  gwehrman
 * 	Cleanup of errors turned on by -diag_error flags in kernel cflags.
 * 	Added rpc_mgmt_inq_svr_princ_name_tgt().  Accroding to comments
 * 	in rpc/runtime/mgmt.c, it should be defined in rpc.idl.
 *
 * Revision 65.1  1997/10/20  19:16:20  jdoak
 * *** empty log message ***
 *
 * Revision 1.1.9.1  1996/06/04  21:57:05  arvind
 * 	Merge prototype for u2u rtn rpc_server_register_auth_ident() from mb_u2u
 * 	[1996/05/06  19:53 UTC  burati  /main/DCE_1.2/1]
 *
 * 	merge u2u work
 * 	[1996/04/29  19:43 UTC  burati  /main/mb_u2u/1]
 *
 * 	u2u work off Mothra, before 1.2 branch is available
 * 	[1996/04/29  19:41 UTC  burati  /main/mb_mothra8/1]
 *
 * 	u2u work off Mothra, before 1.2 branch is available
 * 	[1996/04/29  19:40 UTC  burati  /main/mb_mothra8/1]
 *
 * Revision 1.1.7.2  1996/03/09  23:26:46  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:42:17  marty]
 * 
 * Revision 1.1.7.1  1995/12/08  00:23:33  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  00:01:13  root]
 * 
 * Revision 1.1.5.6  1994/07/28  18:30:33  mori_m
 * 	CR 11294  Changed attr_type to a uuid_t* for codesets attribute operations
 * 	[1994/07/28  18:21:07  mori_m]
 * 
 * Revision 1.1.5.5  1994/05/18  21:24:03  tom
 * 	Bug 6849 - Remove rpc_if_register_auth_info declaration.
 * 	This interface has never been supported (or implemented).
 * 	[1994/05/13  17:58:55  tom]
 * 
 * Revision 1.1.5.4  1994/04/12  16:52:09  mori_m
 * 	CR 9701:  Second submission for RPC runtime I18N support.
 * 	[1994/04/12  16:35:30  mori_m]
 * 
 * Revision 1.1.5.3  1994/02/10  21:39:37  mori_m
 * 	CR 9925  Changed free_func to cs_free_func.  This is a conflict with
 * 		 a typedef within usr/include/krb5/mvr/encode.h
 * 	[1994/02/10  21:39:20  mori_m]
 * 
 * Revision 1.1.5.2  1994/02/08  21:26:55  mori_m
 * 	CR 9701:  Initial submission for RPC runtime I18N support
 * 	[1994/02/08  21:23:43  mori_m]
 * 
 * Revision 1.1.5.1  1994/01/28  23:09:45  burati
 * 	Delegation/EPAC changes - add rpc_binding_inq_auth_caller (dlg_bl1)
 * 	[1994/01/18  21:03:51  burati]
 * 
 * Revision 1.1.2.7  1993/02/05  16:12:18  raizen
 * 	 26-jan-93 raizen   Remove rpc_ns_mgmt_set_authn.
 * 	[1993/02/04  23:22:51  raizen]
 * 
 * Revision 1.1.2.6  1993/01/04  00:10:15  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/03  20:15:39  bbelch]
 * 
 * Revision 1.1.2.5  1992/12/23  21:20:39  zeliff
 * 	Embedding copyright notice
 * 	[1992/12/23  15:47:19  zeliff]
 * 
 * Revision 1.1.2.4  1992/12/21  19:32:03  wei_hu
 * 	Resubmitting this change.
 * 	[1992/12/21  19:28:51  wei_hu]
 * 
 * Revision 1.1.2.2  1992/12/18  20:30:59  wei_hu
 * 	      09-dec-92 raizen    Add rpc_ns_mgmt_set_authn.  [OT4854]
 * 	[1992/12/18  20:12:44  wei_hu]
 * 
 * Revision 1.1  1992/01/19  03:13:51  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */

/* Generated by IDL compiler version OSF DCE T1.2.0-09 */
#ifndef rpc_v0_0_included
#define rpc_v0_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
#ifndef lbase_v0_0_included
#include <dce/lbase.h>
#endif
#ifndef rpcsts_v0_0_included
#include <dce/rpcsts.h>
#endif
#ifndef rpcbase_v0_0_included
#include <dce/rpcbase.h>
#endif
#ifndef rpcpvt_v0_0_included
#include <dce/rpcpvt.h>
#endif
#ifndef nca_status_v0_0_included
#include <dce/ncastat.h>
#endif
#ifndef uuid_v0_0_included
#include <dce/uuid.h>
#endif
#ifndef ndrold_v0_0_included
#include <dce/ndrold.h>
#endif
#ifndef twr_v0_0_included
#include <dce/twr.h>
#endif
extern void rpc_binding_copy(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_binding_handle_t src_binding_handle,
    /* [out] */ rpc_binding_handle_t *dst_binding_handle,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_binding_free(
#ifdef IDL_PROTOTYPES
    /* [in, out] */ rpc_binding_handle_t *binding_handle,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_binding_from_string_binding(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned_char_p_t string_binding,
    /* [out] */ rpc_binding_handle_t *binding_handle,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_binding_inq_object(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_binding_handle_t binding_handle,
    /* [out] */ uuid_t *object_uuid,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_binding_reset(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_binding_handle_t binding_handle,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_binding_set_object(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_binding_handle_t binding_handle,
    /* [in] */ uuid_p_t object_uuid,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_binding_to_string_binding(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_binding_handle_t binding_handle,
    /* [out] */ unsigned_char_p_t *string_binding,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_binding_vector_free(
#ifdef IDL_PROTOTYPES
    /* [in, out] */ rpc_binding_vector_p_t *binding_vector,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_string_binding_compose(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned_char_p_t string_object_uuid,
    /* [in] */ unsigned_char_p_t string_protseq,
    /* [in] */ unsigned_char_p_t string_netaddr,
    /* [in] */ unsigned_char_p_t string_endpoint,
    /* [in] */ unsigned_char_p_t string_options,
    /* [out] */ unsigned_char_p_t *string_binding,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_string_binding_parse(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned_char_p_t string_binding,
    /* [out] */ unsigned_char_p_t *string_object_uuid,
    /* [out] */ unsigned_char_p_t *string_protseq,
    /* [out] */ unsigned_char_p_t *string_netaddr,
    /* [out] */ unsigned_char_p_t *string_endpoint,
    /* [out] */ unsigned_char_p_t *string_options,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_binding_set_auth_info(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_binding_handle_t binding_handle,
    /* [in] */ unsigned_char_p_t server_princ_name,
    /* [in] */ unsigned32 protect_level,
    /* [in] */ unsigned32 authn_svc,
    /* [in] */ rpc_auth_identity_handle_t auth_identity,
    /* [in] */ unsigned32 authz_svc,
    /* [out] */ unsigned32 *st
#endif
);
extern void rpc_binding_inq_auth_info(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_binding_handle_t binding_handle,
    /* [out] */ unsigned_char_p_t *server_princ_name,
    /* [out] */ unsigned32 *protect_level,
    /* [out] */ unsigned32 *authn_svc,
    /* [out] */ rpc_auth_identity_handle_t *auth_identity,
    /* [out] */ unsigned32 *authz_svc,
    /* [out] */ unsigned32 *st
#endif
);
extern void rpc_binding_inq_auth_caller(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_binding_handle_t binding_handle,
    /* [out] */ rpc_authz_cred_handle_t *privs,
    /* [out] */ unsigned_char_p_t *server_princ_name,
    /* [out] */ unsigned32 *protect_level,
    /* [out] */ unsigned32 *authn_svc,
    /* [out] */ unsigned32 *authz_svc,
    /* [out] */ unsigned32 *st
#endif
);
extern void rpc_binding_inq_auth_client(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_binding_handle_t binding_handle,
    /* [out] */ rpc_authz_handle_t *privs,
    /* [out] */ unsigned_char_p_t *server_princ_name,
    /* [out] */ unsigned32 *protect_level,
    /* [out] */ unsigned32 *authn_svc,
    /* [out] */ unsigned32 *authz_svc,
    /* [out] */ unsigned32 *st
#endif
);
extern void rpc_binding_server_from_client(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_binding_handle_t cbinding_handle,
    /* [out] */ rpc_binding_handle_t *sbinding_handle,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_if_id_vector_free(
#ifdef IDL_PROTOTYPES
    /* [in, out] */ rpc_if_id_vector_p_t *if_id_vector,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_if_inq_id(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_if_handle_t if_spec,
    /* [out] */ rpc_if_id_t *if_id,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_network_inq_protseqs(
#ifdef IDL_PROTOTYPES
    /* [out] */ rpc_protseq_vector_p_t *protseq_vector,
    /* [out] */ unsigned32 *status
#endif
);
extern boolean32 rpc_network_is_protseq_valid(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned_char_p_t protseq,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_object_set_type(
#ifdef IDL_PROTOTYPES
    /* [in] */ uuid_p_t object_uuid,
    /* [in] */ uuid_p_t type_uuid,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_object_inq_type(
#ifdef IDL_PROTOTYPES
    /* [in] */ uuid_p_t object_uuid,
    /* [out] */ uuid_t *type_uuid,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_object_set_inq_fn(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_object_inq_fn_t inq_fn,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_protseq_vector_free(
#ifdef IDL_PROTOTYPES
    /* [in, out] */ rpc_protseq_vector_p_t *protseq_vector,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_server_inq_bindings(
#ifdef IDL_PROTOTYPES
    /* [out] */ rpc_binding_vector_p_t *binding_vector,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_server_listen(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 max_calls_exec,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_server_use_all_protseqs(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 max_call_requests,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_server_use_protseq(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned_char_p_t protseq,
    /* [in] */ unsigned32 max_call_requests,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_server_use_protseq_ep(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned_char_p_t protseq,
    /* [in] */ unsigned32 max_call_requests,
    /* [in] */ unsigned_char_p_t endpoint,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_server_use_protseq_if(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned_char_p_t protseq,
    /* [in] */ unsigned32 max_call_requests,
    /* [in] */ rpc_if_handle_t if_spec,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_server_use_all_protseqs_if(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 max_call_requests,
    /* [in] */ rpc_if_handle_t if_spec,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_server_register_if(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_if_handle_t if_spec,
    /* [in] */ uuid_p_t mgr_type_uuid,
    /* [in] */ rpc_mgr_epv_t mgr_epv,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_server_unregister_if(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_if_handle_t if_spec,
    /* [in] */ uuid_p_t mgr_type_uuid,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_server_inq_if(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_if_handle_t if_spec,
    /* [in] */ uuid_p_t mgr_type_uuid,
    /* [out] */ rpc_mgr_epv_t *mgr_epv,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_server_register_auth_info(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned_char_p_t server_princ_name,
    /* [in] */ unsigned32 auth_svc,
    /* [in] */ rpc_auth_key_retrieval_fn_t get_key_func,
    /* [in] */ idl_void_p_t arg,
    /* [out] */ unsigned32 *st
#endif
);
extern void rpc_server_register_auth_ident(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned_char_p_t server_princ_name,
    /* [in] */ unsigned32 auth_svc,
    /* [in] */ rpc_auth_identity_handle_t id_h,
    /* [out] */ unsigned32 *st
#endif
);
extern void rpc_ep_register(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_if_handle_t if_spec,
    /* [in] */ rpc_binding_vector_p_t binding_vec,
    /* [in] */ uuid_vector_p_t object_uuid_vec,
    /* [in] */ unsigned_char_p_t annotation,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ep_register_no_replace(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_if_handle_t if_spec,
    /* [in] */ rpc_binding_vector_p_t binding_vec,
    /* [in] */ uuid_vector_p_t object_uuid_vec,
    /* [in] */ unsigned_char_p_t annotation,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ep_resolve_binding(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_binding_handle_t binding_h,
    /* [in] */ rpc_if_handle_t if_spec,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ep_unregister(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_if_handle_t if_spec,
    /* [in] */ rpc_binding_vector_p_t binding_vec,
    /* [in] */ uuid_vector_p_t object_uuid_vec,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_mgmt_inq_com_timeout(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_binding_handle_t binding_handle,
    /* [out] */ unsigned32 *timeout,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_mgmt_inq_if_ids(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_binding_handle_t binding_handle,
    /* [out] */ rpc_if_id_vector_p_t *if_id_vector,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_mgmt_inq_stats(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_binding_handle_t binding_handle,
    /* [out] */ rpc_stats_vector_p_t *statistics,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_mgmt_stats_vector_free(
#ifdef IDL_PROTOTYPES
    /* [in, out] */ rpc_stats_vector_p_t *statistics,
    /* [out] */ unsigned32 *status
#endif
);
extern boolean32 rpc_mgmt_is_server_listening(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_binding_handle_t binding_handle,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_mgmt_set_cancel_timeout(
#ifdef IDL_PROTOTYPES
    /* [in] */ signed32 seconds,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_mgmt_set_com_timeout(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_binding_handle_t binding_handle,
    /* [in] */ unsigned32 timeout,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_mgmt_set_server_stack_size(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 thread_stack_size,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_mgmt_stop_server_listening(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_binding_handle_t binding_handle,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_mgmt_inq_dflt_protect_level(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 authn_svc,
    /* [out] */ unsigned32 *protect_level,
    /* [out] */ unsigned32 *st
#endif
);
extern void rpc_mgmt_set_authorization_fn(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_mgmt_authorization_fn_t authorization_fn_arg,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_mgmt_ep_elt_inq_begin(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_binding_handle_t ep_binding,
    /* [in] */ unsigned32 inquiry_type,
    /* [in] */ rpc_if_id_p_t if_id,
    /* [in] */ unsigned32 vers_option,
    /* [in] */ uuid_p_t object_uuid,
    /* [out] */ rpc_ep_inq_handle_t *inquiry_context,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_mgmt_ep_elt_inq_next(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_ep_inq_handle_t inquiry_context,
    /* [out] */ rpc_if_id_t *if_id,
    /* [out] */ rpc_binding_handle_t *binding,
    /* [out] */ uuid_t *object_uuid,
    /* [out] */ unsigned_char_p_t *annotation,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_mgmt_ep_elt_inq_done(
#ifdef IDL_PROTOTYPES
    /* [in, out] */ rpc_ep_inq_handle_t *inquiry_context,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_mgmt_ep_unregister(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_binding_handle_t ep_binding,
    /* [in] */ rpc_if_id_p_t if_id,
    /* [in] */ rpc_binding_handle_t binding,
    /* [in] */ uuid_p_t object_uuid,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_mgmt_inq_server_princ_name(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_binding_handle_t binding_h,
    /* [in] */ unsigned32 authn_svc,
    /* [out] */ unsigned_char_p_t *server_princ_name,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_mgmt_inq_svr_princ_name_tgt(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_binding_handle_t binding_h,
    /* [in] */ unsigned32 authn_protocol,
    /* [out] */ unsigned_char_p_t *server_princ_name,
    /* [out] */ unsigned32 *tgt_length,
    /* [out] */ unsigned_char_p_t *tgt_data,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_binding_export(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 entry_name_syntax,
    /* [in] */ unsigned_char_p_t entry_name,
    /* [in] */ rpc_if_handle_t if_spec,
    /* [in] */ rpc_binding_vector_p_t binding_vector,
    /* [in] */ uuid_vector_p_t object_uuid_vector,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_binding_import_begin(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 entry_name_syntax,
    /* [in] */ unsigned_char_p_t entry_name,
    /* [in] */ rpc_if_handle_t if_spec,
    /* [in] */ uuid_p_t object_uuid,
    /* [out] */ rpc_ns_handle_t *import_context,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_binding_import_done(
#ifdef IDL_PROTOTYPES
    /* [in, out] */ rpc_ns_handle_t *import_context,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_binding_import_next(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_ns_handle_t import_context,
    /* [out] */ rpc_binding_handle_t *binding,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_binding_inq_entry_name(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_binding_handle_t binding,
    /* [in] */ unsigned32 entry_name_syntax,
    /* [out] */ unsigned_char_p_t *entry_name,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_binding_lookup_begin(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 entry_name_syntax,
    /* [in] */ unsigned_char_p_t entry_name,
    /* [in] */ rpc_if_handle_t if_spec,
    /* [in] */ uuid_p_t object_uuid,
    /* [in] */ unsigned32 binding_max_count,
    /* [out] */ rpc_ns_handle_t *lookup_context,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_binding_lookup_done(
#ifdef IDL_PROTOTYPES
    /* [in, out] */ rpc_ns_handle_t *lookup_context,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_binding_lookup_next(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_ns_handle_t lookup_context,
    /* [out] */ rpc_binding_vector_p_t *binding_vector,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_binding_select(
#ifdef IDL_PROTOTYPES
    /* [in, out] */ rpc_binding_vector_t *binding_vector,
    /* [out] */ rpc_binding_handle_t *binding,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_binding_unexport(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 entry_name_syntax,
    /* [in] */ unsigned_char_p_t entry_name,
    /* [in] */ rpc_if_handle_t if_spec,
    /* [in] */ uuid_vector_p_t object_uuid_vector,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_entry_expand_name(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 entry_name_syntax,
    /* [in] */ unsigned_char_p_t entry_name,
    /* [out] */ unsigned_char_p_t *expanded_name,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_entry_object_inq_begin(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 entry_name_syntax,
    /* [in] */ unsigned_char_p_t entry_name,
    /* [out] */ rpc_ns_handle_t *inquiry_context,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_entry_object_inq_done(
#ifdef IDL_PROTOTYPES
    /* [in, out] */ rpc_ns_handle_t *inquiry_context,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_entry_object_inq_next(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_ns_handle_t inquiry_context,
    /* [out] */ uuid_t *object_uuid,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_group_delete(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 group_name_syntax,
    /* [in] */ unsigned_char_p_t group_name,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_group_mbr_add(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 group_name_syntax,
    /* [in] */ unsigned_char_p_t group_name,
    /* [in] */ unsigned32 member_name_syntax,
    /* [in] */ unsigned_char_p_t member_name,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_group_mbr_inq_begin(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 group_name_syntax,
    /* [in] */ unsigned_char_p_t group_name,
    /* [in] */ unsigned32 member_name_syntax,
    /* [out] */ rpc_ns_handle_t *inquiry_context,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_group_mbr_inq_done(
#ifdef IDL_PROTOTYPES
    /* [in, out] */ rpc_ns_handle_t *inquiry_context,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_group_mbr_inq_next(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_ns_handle_t inquiry_context,
    /* [out] */ unsigned_char_p_t *member_name,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_group_mbr_remove(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 group_name_syntax,
    /* [in] */ unsigned_char_p_t group_name,
    /* [in] */ unsigned32 member_name_syntax,
    /* [in] */ unsigned_char_p_t member_name,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_mgmt_binding_unexport(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 entry_name_syntax,
    /* [in] */ unsigned_char_p_t entry_name,
    /* [in] */ rpc_if_id_p_t if_id,
    /* [in] */ unsigned32 vers_option,
    /* [in] */ uuid_vector_p_t object_uuid_vector,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_mgmt_entry_create(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 entry_name_syntax,
    /* [in] */ unsigned_char_p_t entry_name,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_mgmt_entry_delete(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 entry_name_syntax,
    /* [in] */ unsigned_char_p_t entry_name,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_mgmt_entry_inq_if_ids(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 entry_name_syntax,
    /* [in] */ unsigned_char_p_t entry_name,
    /* [out] */ rpc_if_id_vector_p_t *if_id_vector,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_mgmt_inq_exp_age(
#ifdef IDL_PROTOTYPES
    /* [out] */ unsigned32 *expiration_age,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_mgmt_set_exp_age(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 expiration_age,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_mgmt_handle_set_exp_age(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_ns_handle_t ns_handle,
    /* [in] */ unsigned32 expiration_age,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_profile_delete(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 profile_name_syntax,
    /* [in] */ unsigned_char_p_t profile_name,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_profile_elt_add(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 profile_name_syntax,
    /* [in] */ unsigned_char_p_t profile_name,
    /* [in] */ rpc_if_id_p_t if_id,
    /* [in] */ unsigned32 member_name_syntax,
    /* [in] */ unsigned_char_p_t member_name,
    /* [in] */ unsigned32 priority,
    /* [in] */ unsigned_char_p_t annotation,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_profile_elt_inq_begin(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 profile_name_syntax,
    /* [in] */ unsigned_char_p_t profile_name,
    /* [in] */ unsigned32 inquiry_type,
    /* [in] */ rpc_if_id_p_t if_id,
    /* [in] */ unsigned32 if_vers_option,
    /* [in] */ unsigned32 member_name_syntax,
    /* [in] */ unsigned_char_p_t member_name,
    /* [out] */ rpc_ns_handle_t *inquiry_context,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_profile_elt_inq_done(
#ifdef IDL_PROTOTYPES
    /* [in, out] */ rpc_ns_handle_t *inquiry_context,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_profile_elt_inq_next(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_ns_handle_t inquiry_context,
    /* [out] */ rpc_if_id_t *if_id,
    /* [out] */ unsigned_char_p_t *member_name,
    /* [out] */ unsigned32 *priority,
    /* [out] */ unsigned_char_p_t *annotation,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_ns_profile_elt_remove(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 profile_name_syntax,
    /* [in] */ unsigned_char_p_t profile_name,
    /* [in] */ rpc_if_id_p_t if_id,
    /* [in] */ unsigned32 member_name_syntax,
    /* [in] */ unsigned_char_p_t member_name,
    /* [out] */ unsigned32 *status
#endif
);
extern void rpc_string_free(
#ifdef IDL_PROTOTYPES
    /* [in, out] */ unsigned_char_p_t *string,
    /* [out] */ unsigned32 *status
#endif
);
typedef struct rpc_cs_c_set_s_t {
unsigned32 c_set;
unsigned16 c_max_bytes;
} rpc_cs_c_set_t;
typedef struct rpc_codeset_mgmt_s_t {
unsigned32 version;
unsigned32 count;
rpc_cs_c_set_t codesets[1];
} rpc_codeset_mgmt_t;
typedef rpc_codeset_mgmt_t *rpc_codeset_mgmt_p_t;
extern void rpc_ns_mgmt_set_attribute(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 entry_name_syntax,
    /* [in] */ unsigned_char_p_t entry_name,
    /* [in] */ uuid_p_t attr_type,
    /* [in] */ idl_void_p_t attr_val,
    /* [out] */ error_status_t *status
#endif
);
extern void rpc_ns_mgmt_read_attr_begin(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 entry_name_syntax,
    /* [in] */ unsigned_char_p_t entry_name,
    /* [in] */ uuid_p_t attr_type,
    /* [out] */ rpc_ns_handle_t *inquiry_context,
    /* [out] */ error_status_t *status
#endif
);
extern void rpc_ns_mgmt_read_attr_next(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_ns_handle_t inquiry_context,
    /* [in] */ uuid_p_t attr_type,
    /* [out] */ idl_byte **value,
    /* [out] */ unsigned32 *length,
    /* [out] */ error_status_t *status
#endif
);
extern void rpc_ns_mgmt_read_attr_done(
#ifdef IDL_PROTOTYPES
    /* [in] */ rpc_ns_handle_p_t inquiry_context,
    /* [out] */ error_status_t *status
#endif
);
extern void rpc_ns_mgmt_remove_attribute(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 entry_name_syntax,
    /* [in] */ unsigned_char_p_t entry_name,
    /* [in] */ uuid_p_t attr_type,
    /* [out] */ error_status_t *status
#endif
);
extern void rpc_ns_mgmt_read_codesets(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 entry_name_syntax,
    /* [in] */ unsigned_char_p_t entry_name,
    /* [out] */ rpc_codeset_mgmt_p_t *codesets_val,
    /* [out] */ error_status_t *status
#endif
);
extern void rpc_ns_import_ctx_add_eval(
#ifdef IDL_PROTOTYPES
    /* [in, out] */ rpc_ns_handle_t *import_ctx,
    /* [in] */ unsigned32 func_type,
    /* [in] */ idl_void_p_t args,
    /* [in] */ void (*eval_func)(
#ifdef IDL_PROTOTYPES
    /* [out] */ handle_t binding_h,
    /* [out] */ idl_void_p_t args,
    /* [out] */ idl_void_p_t *cntx
#endif
),
    /* [in] */ void (*cs_free_func)(
#ifdef IDL_PROTOTYPES
    /* [out] */ idl_void_p_t cntx
#endif
),
    /* [out] */ error_status_t *status
#endif
);
extern void rpc_cs_eval_with_universal(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t binding_h,
    /* [in] */ idl_void_p_t args,
    /* [in, out] */ idl_void_p_t *cntx
#endif
);
extern void rpc_cs_eval_without_universal(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t binding_h,
    /* [in] */ idl_void_p_t args,
    /* [in, out] */ idl_void_p_t *cntx
#endif
);
extern void rpc_cs_char_set_compat_check(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 client_codeset,
    /* [in] */ unsigned32 server_codeset,
    /* [out] */ error_status_t *status
#endif
);
typedef struct  {
unsigned32 stag;
unsigned32 drtag;
unsigned16 stag_max_bytes;
unsigned32 client_tag;
unsigned16 client_max_bytes;
rpc_ns_handle_t type_handle;
} rpc_cs_tags_eval_t;
typedef rpc_cs_tags_eval_t *rpc_cs_tags_eval_p_t;
typedef struct  {
unsigned32 method;
rpc_cs_tags_eval_t tags;
rpc_codeset_mgmt_t *server;
rpc_codeset_mgmt_t *client;
boolean32 fixed;
void (*cs_stub_eval_func)(
#ifdef IDL_PROTOTYPES
    /* [out] */ unsigned32 *p_stag,
    /* [out] */ unsigned32 *p_drtag,
    /* [out] */ error_status_t *status
#endif
);
} rpc_cs_method_eval_t;
typedef rpc_cs_method_eval_t *rpc_cs_method_eval_p_t;
typedef struct  {
idl_short_int key;
union  {
/* case(s): 0 */
rpc_cs_tags_eval_t tags_key;
/* case(s): 1, default */
rpc_cs_method_eval_t method_key;
} tagged_union;
} rpc_cs_evaluation_t;
typedef struct rpc_eval_lists *rpc_cs_eval_list_p;
typedef struct rpc_eval_lists {
unsigned32 type;
void (*eval_func)(
#ifdef IDL_PROTOTYPES
    /* [out] */ handle_t binding_h,
    /* [out] */ idl_void_p_t args,
    /* [out] */ idl_void_p_t *cntx
#endif
);
void (*cs_free_func)(
#ifdef IDL_PROTOTYPES
    /* [out] */ idl_void_p_t cntx
#endif
);
idl_void_p_t args;
idl_void_p_t cntx;
rpc_cs_eval_list_p next;
} rpc_cs_eval_list_t;
typedef rpc_cs_eval_list_t *rpc_cs_eval_list_p_t;
extern void rpc_cs_binding_set_tags(
#ifdef IDL_PROTOTYPES
    /* [in, out] */ rpc_binding_handle_t *h,
    /* [in] */ unsigned32 stag,
    /* [in] */ unsigned32 drtag,
    /* [in] */ unsigned16 stag_max_bytes,
    /* [out] */ error_status_t *status
#endif
);
extern void rpc_cs_binding_set_eval(
#ifdef IDL_PROTOTYPES
    /* [in, out] */ rpc_binding_handle_t *h,
    /* [in] */ void (*cs_stub_eval_func)(
#ifdef IDL_PROTOTYPES
    /* [out] */ unsigned32 *p_stag,
    /* [out] */ unsigned32 *p_drtag,
    /* [out] */ error_status_t *status
#endif
),
    /* [out] */ error_status_t *status
#endif
);
extern void rpc_rgy_get_codesets(
#ifdef IDL_PROTOTYPES
    /* [out] */ rpc_codeset_mgmt_p_t *codesets_p,
    /* [out] */ error_status_t *status
#endif
);
extern void rpc_rgy_get_max_bytes(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 tag,
    /* [out] */ unsigned16 *max_bytes,
    /* [out] */ error_status_t *status
#endif
);
extern void dce_cs_loc_to_rgy(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *local_code_set_name,
    /* [out] */ unsigned32 *rgy_code_set_value,
    /* [out] */ unsigned16 *rgy_char_sets_number,
    /* [out] */ unsigned16 **rgy_char_sets_value,
    /* [out] */ error_status_t *status
#endif
);
extern void dce_cs_rgy_to_loc(
#ifdef IDL_PROTOTYPES
    /* [in] */ unsigned32 rgy_code_set_value,
    /* [out] */ idl_char **local_code_set_name,
    /* [out] */ unsigned16 *rgy_char_sets_number,
    /* [out] */ unsigned16 **rgy_char_sets_value,
    /* [out] */ error_status_t *status
#endif
);
extern void rpc_ns_mgmt_free_attr_data(
#ifdef IDL_PROTOTYPES
    /* [in, out] */ idl_byte **value,
    /* [out] */ error_status_t *status
#endif
);
extern void rpc_ns_mgmt_free_codesets(
#ifdef IDL_PROTOTYPES
    /* [in, out] */ rpc_codeset_mgmt_p_t *codesets,
    /* [out] */ error_status_t *status
#endif
);

#ifdef __cplusplus
    }

#endif
#endif
