'\"macro stdmacro
.TH AIO_INIT 3 
.SH NAME
aio_init \- asynchronous I/O initialization
.Op c p a
.SH C SYNOPSIS
.nf
.B #include <aio.h>
.PP
.B "void aio_init(void);
.fi
.PP
.Op
.SH DESCRIPTION
.PP
The use of this function has been discontinued. Please use
\f4aio_sgi_init(3)\f1 instead.
.SH "SEE ALSO"
aio_sgi_init(3), aio_write(3), lio_listio(3), aio_error(3), aio_return(3), aio_cancel(3), mpadmin(1), realtime(5).
