#ident $Revision: 1.4 $
#
IDB_PATH=/usr/share/catman/p_man/cat3

include $(ROOT)/usr/include/make/mandefs

include $(ROOT)/usr/include/make/manrules

#               Language that the manual pages will be build for.
LANGOPT=c
