'\"macro stdmacro
.if n .pH g3L.sat_eventtostr
.nr X
.if \nX=0 .ds x} SAT_EVENTTOSTR 3L "Trusted IRIX/B" "\&"
.if \nX=1 .ds x} SAT_EVENTTOSTR 3L "Trusted IRIX/B"
.if \nX=2 .ds x} SAT_EVENTTOSTR 3L "" "\&"
.if \nX=3 .ds x} SAT_EVENTTOSTR "" "" "\&"
.TH \*(x}
.SH NAME
sat_eventtostr, sat_strtoevent \- convert an audit event index to/from an audit event string
.SH SYNOPSIS
.B #include <sys/sat.h>
.PP
.SM
.B char \(**
.B sat_eventtostr (event)
.br
.B int event;
.PP
.B int
.B sat_strtoevent (evstr)
.br
.B char \(**evstr;
.br
.SH DESCRIPTION
.I sat_eventtostr\^
returns a human-readable string which represents
the audit event passed to it in
.IR event .
The value returned points to a static character array.
.PP
.I event
must be a positive integer less than
.B SAT_NTYPES
(defined in
.BR <sys/sat.h> ).
.PP
.I sat_strtoevent\^
returns a machine-readable event index which represents
the string passed to it in
.IR evstr .
.PP
The string returned by
.I sat_eventtostr\^
and passed to
.I sat_strtoevent\^
is a member of the set of known event names.  
For a complete list of known event names, run the command:
.P
	sat_select -h
.P
.SH "SEE ALSO"
sat_reduce(1m)
.br
sat_select(1m)
.br
sat_summarize(1m)
.SH DIAGNOSTICS
.I sat_eventtostr\^
returns
.I "unknown event #%d"
if
.I event
is
not a positive integer less than
.BR SAT_NTYPES .
.I sat_strtoevent\^
returns
.B -1
if
.I evstr
is
.SM NULL
or points to an audit event of unrecognized type.
.PP
.SH NOTES
If this function is used in a program, then the library
.B libmls
must be linked at compile time.
For example the following command will perform this link:
.DS I
.nf

     cc  -DTRUSTEDIRIX  -DLABELLEDSOCKETS  \f2programname\fP.c  -lmls
.fi
.DE
'\".so /pubs/tools/origin.sgi
.\"	#ident
.Ee
