# Makefile for REACT release notes
# $Revision: 1.2 $

# Edit the CMM and AMM macros to contain the list of chapters and appendices
# in this book.  Do not use abbreviations (i.e. ch[1-8].cmm), because the
# Makefile dependencies will not work.

CMM	= ch1.cmm ch2.cmm ch3.cmm
AMM	=
RELPROD	=react

include $(ROOT)/usr/include/make/relnotesrules
