#!/bin/sh
#
# Script to get subroutine/data sizes from a binary.  Since symmon seems
# to keep growing, this will allow us to track their size.
FILE=$1
S4=`file $FILE | egrep '64-bit'`

if [ -z "$S4" ]
then
$TOOLROOT/usr/bin/nm $FILE 					| \
	egrep -v '\|Abs|\End|\|File|\|Label|\.[csh]$'		| \
	awk -F\| '{print $2 "#" $(NF-1) "#" $NF }'		| \
	egrep -v '^#'						| \
	sed 's/[ ]*//g'						| \
	sed 's/#/	/g'					| \
	sort -ru						| \
	awk '{ printf "%d\n%s(%s): ",$1-LA,$3,$2; LA=$1}'	| \
	sed '1d'
else
$TOOLROOT/usr/bin/nm $FILE 					| \
	egrep -v '\|ABS'					| \
	awk -F\| '{print $NF "#" $3}'				| \
	egrep -v '^#'						| \
	sed 's/[ ]*//g'						| \
	sed 's/#/:	/g'
fi
