#!/bin/sh
#
# Copyright 1999, Silicon Graphics, Inc.
# ALL RIGHTS RESERVED
# 
# UNPUBLISHED -- Rights reserved under the copyright laws of the United
# States.   Use of a copyright notice is precautionary only and does not
# imply publication or disclosure.
# 
# U.S. GOVERNMENT RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in FAR 52.227.19(c)(2) or subparagraph (c)(1)(ii) of the Rights
# in Technical Data and Computer Software clause at DFARS 252.227-7013 and/or
# in similar or successor clauses in the FAR, or the DOD or NASA FAR
# Supplement.  Contractor/manufacturer is Silicon Graphics, Inc.,
# 2011 N. Shoreline Blvd. Mountain View, CA 94039-7311.
# 
# THE CONTENT OF THIS WORK CONTAINS CONFIDENTIAL AND PROPRIETARY
# INFORMATION OF SILICON GRAPHICS, INC. ANY DUPLICATION, MODIFICATION,
# DISTRIBUTION, OR DISCLOSURE IN ANY FORM, IN WHOLE, OR IN PART, IS STRICTLY
# PROHIBITED WITHOUT THE PRIOR EXPRESS WRITTEN PERMISSION OF SILICON
# GRAPHICS, INC.
#
# $Id: pmie_email,v 1.1 1999/04/28 10:39:51 kenmcd Exp $
#
# pmie_email is intended for use in pmie actions to send e-mail.
#
# the one argument consists of a multi-line message, separated by
# '|' characters ...
#
# "line" 1	- e-mail addressee, as passed to /bin/mail
# "line" 2	- mail Subject: will be "pmie alert: " and then this
#		  text
# "line" 2,3,..	- body of the message [optional]

# Some degree of paranoia here ...
PATH=/usr/sbin:/usr/bsd:/sbin:/usr/bin:/bin:/usr/pcp/bin
export PATH

prog=`basename $0`

if [ $# -ne 1 ]
then
    echo "Usage: $prog long|format|message|as|one|argument"
    exit 1
fi

cat <<End-of-File | nawk -F\| '
NF < 2	{ print "echo '"'$prog"': need at least \"e-mail addr|subject\" in argument'"'"'"
	  exit 1
	}
	{ print "/bin/mail " $1 " <<'End-of-File'"
	  print "To: " $1
	  print "Subject: pmie alert: " $2
	  print ""
	  for (i = 3; i <= NF; i++)
		print $i
	  print "End-of-File"
	}' | /bin/sh
$1
End-of-File
