#! /sbin/sh
#
#ident "$Revision: 1.36 $"
#
# This script should not be executed after boot because it
# may report system reboot and cause confusion.
#
#
# availmon is always on once it is intalled
#

CMD=$0
AMRVERSIONNUM=2.1
AVAILDIR=/var/adm/avail
SAVEDIR=$AVAILDIR/.save
USRETCDIR=/usr/etc
EVENTFILE=$SAVEDIR/event
SUEVENTFILE=$SAVEDIR/suevent
SCRATCHFILE=$AVAILDIR/init.scratch
AMTIME1970=$USRETCDIR/amtime1970

#
# check for improper installation and corruption
#

if [ ! -d $AVAILDIR ] ; then
    echo "\n$CMD: ERROR: cannot find directory $AVAILDIR"
    echo "Please try re-installing availmon\n"
    logger -t availmon -p err -i cannot find directory $AVAILDIR
    exit
fi

case $1 in
'start')
    if [ ! -x $USRETCDIR/amstart ] ; then
	echo "\n$CMD: ERROR: Can't find $USRETCDIR/amstart."
	echo "Executable files corrupted.  Please try re-installing availmon\n"
	logger -t availmon -p err -i cannot find $USERETCDIR/amstart
    else 
	$USRETCDIR/amstart 2>&1 &
    fi
    ;;
'stop')
    if [ ! -d $SAVEDIR ] ; then
	exit
    fi

    if [ -x $AMTIME1970 ] ; then
	SINCE1970=`$AMTIME1970`
	SINCE1970DATE=`$AMTIME1970 -d $SINCE1970`
    else
	SINCE1970=-1
	SINCE1970DATE=unknown
    fi


    killall amtickerd
    if [ -f $SCRATCHFILE ] ; then
	EVENTCODE=`cat $SCRATCHFILE`
	if [ "$EVENTCODE" -gt 26 -o "$EVENTCODE" -lt -2 -o "$EVENTCODE" -eq 0 ] ; then
	    EVENTCODE=0
	fi
	rm -f $SCRATCHFILE
    else
	EVENTCODE=-2
    fi
    MSG="EVENT|$EVENTCODE|$SINCE1970|$SINCE1970DATE"
    if [ "$EVENTCODE" -ge 19 ] ; then
	echo "$MSG" > $SUEVENTFILE
    else
	echo "$MSG" > $EVENTFILE
    fi
    ;;
esac
