.TH miser_kill 1
.SH NAME
miser_kill \- kill a miser job
.SH SYNOPSIS
.nf
\f3miser_kill \f1 [-j] jid | -h
.fi
.SH DESCRIPTION
The
.I miser_kill
command is used to terminate a miser job.  The command sends a SIGKILL to 
the job and all it's children.  Upon termination of the job, the reserved 
resources are freed immediately. 
.P
A miser job that is killed using other mechanisms, may not properly cleanup 
all it's children and/or the committed resources.
.SH OPTIONS
.TP
.BI [\-j] " jid "
Kill miser job with pid = jid. The '-j' is optional.
.TP
.BI \-h
Print the command's usage message.
.SH RESTRICTIONS
The user must have permission to kill the miser job to successfully use this
command. 
.SH "SEE ALSO"
miser(1),
miser(4),
miser(5),
miser_qinfo(1),
miser_submit(1).
