/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * HISTORY
 * $Log: fshs_errs.h,v $
 * Revision 65.2  1999/02/04 19:19:39  mek
 * Provide C style include file for IRIX kernel integration.
 *
 * Revision 65.1  1997/10/20 19:19:37  jdoak
 * *** empty log message ***
 *
 * Revision 1.1.12.1  1996/10/02  17:46:35  damon
 * 	Newest DFS from Transarc
 * 	[1996/10/01  18:37:22  damon]
 *
 * Revision 1.1.7.1  1994/06/09  14:07:29  annie
 * 	fixed copyright in src/file
 * 	[1994/06/09  13:22:33  annie]
 * 
 * Revision 1.1.5.3  1993/01/21  19:34:57  zeliff
 * 	Embedding copyright notices
 * 	[1993/01/19  19:48:38  zeliff]
 * 
 * Revision 1.1.5.2  1992/08/31  19:44:36  jaffe
 * 	Replace missing RCS Header
 * 	[1992/08/31  14:26:25  jaffe]
 * 
 * Revision 1.1.3.2  1992/05/20  19:51:56  mason
 * 	Transarc delta: cfe-ot2605-tsr-i-f-changes 1.5
 * 	  Files modified:
 * 	    cm: cm_scache.h
 * 	    config: common_data.acf, common_data.idl, common_def.h
 * 	    fshost: fshs_errs.et
 * 	    fsint: afs4int.acf, afs4int.idl, tkn4int.acf, tkn4int.idl
 * 	    host: hs_errs.et; px: px_repops.c; rep: rep_main.c, repser.h
 * 	    userInt/fts: volc_tokens.c; xvolume: volume.h
 * 	  Selected comments:
 * 	    This delta should encompass the interface changes associated with token
 * 	    state recovery (over server crashes, network partitions, fileset moves,
 * 	    and other things).
 * 	    This delta now captures the interface changes for real.  It includes RPC interface
 * 	    changes, new error codes, and new status bits.  It also includes incomplete changes
 * 	    to fts to support the new interface.
 * 	    Add a few appropriate error codes.
 * 	    More TSR interface fallout, mostly to the new model.
 * 	    Fix a merge error.
 * 	    Fixing more merge and syntax errors
 * 	[1992/05/20  11:15:14  mason]
 * 
 * Revision 1.1  1992/01/19  19:42:01  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */

/*
 * fshs_errs.h:
 * This file is automatically generated; please do not edit it.
 */
#define FSHS_RCSID                               (572616704L)
#define FSHS_ERR_STALEHOST                       (572616705L)
#define FSHS_ERR_FATALCONN                       (572616706L)
#define FSHS_ERR_NULLUUID                        (572616707L)
#define FSHS_ERR_REVOKEFAILED                    (572616708L)
#define FSHS_ERR_SERVER_REESTABLISH              (572616709L)
#define FSHS_ERR_SERVER_UP                       (572616710L)
#define FSHS_ERR_MOVE_REESTABLISH                (572616711L)
#define FSHS_ERR_MOVE_FINISHED                   (572616712L)
#define FSHS_ERR_AUTHNLEVEL_S_TOO_HIGH           (572616713L)
#define FSHS_ERR_AUTHNLEVEL_S_TOO_LOW            (572616714L)
#define FSHS_ERR_AUTHNLEVEL_F_TOO_HIGH           (572616715L)
#define FSHS_ERR_AUTHNLEVEL_F_TOO_LOW            (572616716L)
#define FSHS_ERR_AUTHNLEVEL_G_TOO_HIGH           (572616717L)
#define FSHS_ERR_AUTHNLEVEL_G_TOO_LOW            (572616718L)
#define initialize_fsh_error_table()
#define ERROR_TABLE_BASE_fsh (572616704L)

/* for compatibility with older versions... */
#define init_fsh_err_tbl initialize_fsh_error_table
#define fsh_err_base ERROR_TABLE_BASE_fsh
