DIAGDEPTH= ../../..
include ${DIAGDEPTH}/Makedefs

LINCLUDES = -I../ 
LLCOPTS=-woff 315

CFILES= ev1_init.c ev1_displaybus.c ab1_memtest.c cc1_memtest.c cc1_dmatest.c extntrig.c


COMMONPREF = EXPRESS
_lib ${COMMONTARGS}: ${COMMONPREF}$$@

include ${DIAGDEPTH}/Makerules

