#!/sbin/sh
#Tag 0x00000f00
#
# Start CMW Display Manager
#
# $Revision: 1.4 $
#

IS_ON=/sbin/chkconfig
CMW=CMWloop
CONSOLE=/dev/null

REMOTEHOST=
REMOTEUSER=
DISPLAY=:0

export REMOTEHOST
export REMOTEUSER
export DISPLAY

if $IS_ON verbose ; then        # For a verbose startup and shutdown
    ECHO=echo
else                            # For a quiet startup and shutdown
    ECHO=:
fi

if $IS_ON xdm ; then
    $ECHO CMW startup warning: Xdm is not used in the CMW environment.
    $IS_ON xdm off
fi

case "$1" in
  'start')
        $ECHO 'CMW \c'
	/sbin/suattr -C "all=epi" -M dblow -c /usr/bin/X11/"$CMW" > $CONSOLE 2>&1 &
        ;;

  'stop')
	/sbin/killall -TERM $CMW
	/sbin/killall -TERM 4Dwm
	/sbin/killall -TERM xinit
	/sbin/killall -TERM Xsgi

	/sbin/killall -KILL $CMW
	/sbin/killall -KILL 4Dwm
	/sbin/killall -KILL xinit
	/sbin/killall -KILL Xsgi

	/sbin/killall -KILL endsession
	/sbin/killall -KILL xprop
        ;;

  *)
        echo "usage: /etc/init.d/CMW {start|stop}"
        ;;
esac

