#! /sbin/sh
#Tag 0x00000f00

# Start or stop the lp scheduler
# "$Revision: 1.10 $"

case "$1" in
  'start')
	if test -x /usr/lib/lpshut -a -x /usr/lib/lpsched; then
		/usr/lib/lpshut > /dev/null 2>&1
		rm -f /var/spool/lp/SCHEDLOCK /var/spool/lp/FIFO
		/usr/lib/lpsched
	fi
	;;

  'stop')
	if test -x /usr/lib/lpshut; then
		/usr/lib/lpshut > /dev/null 2>&1
	fi
	;;

  *)
	echo "usage: $0 {start|stop}"
	;;
esac
