#! /sbin/sh
#Tag 0x00000f00

# LV control
# "$Revision: 1.6 $"

case $1 in
'start')
	# If an lvtab is present, run lvinit;
	# this must be done before any mounts since any non-root
	# filesystem may be on a logical volume.

	set `/sbin/who -r`
	if [ $9 = "S" ]
	then
		if [ -f /etc/lvtab ] ; then
			if /sbin/chkconfig verbose
			then
				echo "Starting LV:"
			fi
			/sbin/lvinit
		fi
	fi
	;;

'stop')
	;;

*)
	echo "usage: /etc/init.d/lv {start|stop}"
	;;
esac
