#!/sbin/sh
#
# Start X Display Manager
#
# $Revision: 1.2 $
#

IS_ON=/etc/chkconfig
XSGI=/usr/bin/X11/Xsgi
XDM=/usr/bin/X11/xdm

case "$1" in
  'start')
	if test -x $XDM; then
		if $IS_ON windowsystem && test -x $XSGI || $IS_ON xdm; then
			exec $XDM
		fi
	fi
        ;;

  'stop')
	/etc/killall -TERM xdm
        ;;

  *)
        echo "usage: /etc/init.d/xdm {start|stop}"
        ;;
esac

