#!smake
#
# Makefile for LIBCONFIGMON
#
#ident "$Header: "

DEPTH		= .

CFILES      = dbaccess.c configmon_api.c sysconfig.c configmon_lib.c \
		      swconfig.c hwconfig.c 

include $(ROOT)/usr/include/make/libleafdefs
include $(LIBLEAFRULES)
