'\"macro stdmacro
.TH pthread_mutexattr_init 3P
.SH NAME
pthread_mutexattr_init,
pthread_mutexattr_destroy \- initialize/destroy
a mutex attribute object
.Op c p a
.SH C SYNOPSIS
.nf
.ft 3
#include <pthread.h>
.sp .8v
int pthread_mutexattr_init(pthread_mutexattr_t \(**attr);
int pthread_mutexattr_destroy(pthread_mutexattr_t \(**attr);
.ft 1
.SH DESCRIPTION
The function
.IR pthread_mutexattr_init ()
initializes the mutex attribute object referenced by
.I attr
to the default attribute values.
The default sharing value is
.BR PTHREAD_PROCESS_PRIVATE .
The default priority protocol is
.BR PTHREAD_PRIO_NONE .
The default mutex type is
.BR PTHREAD_MUTEX_DEFAULT .
.PP
Once a mutex attribute object is used to initialize one or more mutexes,
any function that affects the attribute object will not affect the
previously initialized mutexes.
.IR pthread_mutexattr_destroy ()
uninitializes the mutex attribute structure referenced by
.IR attr .
.SH DIAGNOSTICS
These functions return zero.
.SH "SEE ALSO"
pthread_mutex_lock(3P),
pthread_mutexattr_setprioceiling(3P),
pthread_mutexattr_setpshared(3P),
pthread_mutexattr_setprotocol(3P),
pthread_mutexattr_settype(3P).
