'\"macro stdmacro
.\"
.\" ----------------
.TH pthread_cancel 3P
.\"
.\" ----------------
.SH NAME
pthread_cancel \- request cancellation of a thread
.\"
.\" ----------------
.Op c p a
.SH C SYNOPSIS
.nf
.ft 3
#include <pthread.h>
.sp .8v
int pthread_cancel(pthread_t thread);
.ft 1
.fi
.Op
.\"
.\" ----------------
.SH DESCRIPTION
The
.IR pthread_cancel ()
function requests that the thread identified by
.I thread
be cancelled.
Cancellation state [see
.IR pthread_setcancelstate ()]
and type [see
.IR pthread_setcanceltype ()]
determine whether
the request is acted upon immediately or at some time in the future;
.IR pthread_cancel ()
does not wait, it merely issues the request.
When
.I thread
does act on the request, it will terminate as if it had called
.IR pthread_exit ()
with a return status of
.BR PTHREAD_CANCELED .
.\"
.\" ----------------
.SH DIAGNOSTICS
On success
.IR pthread_cancel ()
returns zero; otherwise an error number is returned:
.\"
.TP 15
.B [ESRCH]
The
.I thread
parameter does not identify a thread.
.\"
.\" ----------------
.SH "SEE ALSO"
pthread_setcancelstate(3P), pthread_setcanceltype(3P), pthread_exit(3P).
