'\"macro stdmacro
.\"
.\" ----------------
.TH pthread_self 3P
.\"
.\" ----------------
.SH NAME
pthread_self \- identify a thread
.\"
.\" ----------------
.Op c p a
.SH C SYNOPSIS
.nf
.ft 3
#include <pthread.h>
.sp.8v
pthread_t pthread_self(void);
.ft 1
.fi
.Op
.\"
.\" ----------------
.SH DESCRIPTION
The
.IR pthread_self ()
function identifies the calling thread.
This is the same identifier that the creating thread obtains from
.IR pthread_create ().
.\"
.\" ----------------
.SH DIAGNOSTICS
.IR pthread_self ()
returns a value that can be used to identify it.
.\"
.\" ----------------
.SH "SEE ALSO"
pthread_create(3P).
