'\"macro stdmacro
.\"
.\" ----------------
.TH pthread_equal 3P
.\"
.\" ----------------
.SH NAME
pthread_equal \- compare thread identifiers
.\"
.\" ----------------
.Op c p a
.SH C SYNOPSIS
.nf
.ft 3
#include <pthread.h>
.sp.8v
int pthread_equal(pthread_t thread1, pthread_t thread2);
.ft 1
.fi
.Op
.\"
.\" ----------------
.SH DESCRIPTION
The
.IR pthread_equal ()
function compares the thread identifiers
.I thread1
and
.IR thread2 .
.\"
.\" ----------------
.SH DIAGNOSTICS
If the threads
.I thread1
and
.I thread2
identify the same thread then
.IR pthread_equal ()
returns
.BR TRUE ;
otherwise it returns
.BR FALSE .
.\"
.\" ----------------
.SH "SEE ALSO"
pthread_create(3P).
