'\"macro stdmacro
.TH pthread_rwlock_unlock 3P
.SH NAME
pthread_rwlock_unlock \- unlock a read-write lock object
.Op c p a
.SH C SYNOPSIS
.nf
.ft 3
#include <pthread.h>
.HP
.ft 3
int pthread_rwlock_unlock(pthread_rwlock_t \(**rwlock);
.ft 1
.Op
.SH DESCRIPTION
Read-write locks allow a thread to exclusively lock some shared
data while updating that data, or allow any number of threads
to have simultaneous read-only access to the data.
The
.IR pthread_rwlock_unlock ()
function releases a read or write lock held on the read-write 
lock object referenced by
.IR rwlock .
If this function is called to release a read lock and there are
other read locks currently held on the lock object, the lock object
remains in the read locked state.
If this function is called to release the last read or write lock 
for this lock object, the lock is released.
When released, if there are both readers and writers of the same
priority waiting for the read-write lock, writers will be scheduled
before readers.
.SH "DIAGNOSTICS"
This function returns zero.
.SH "SEE ALSO"
pthread_rwlock_init(3P),
pthread_rwlock_rdlock(3P),
pthread_rwlock_wrlock(3P),
pthread_rwlockattr_init(3P),
pthread_rwlockattr_setpshared(3P).
