'\"macro stdmacro
.\"
.\" ----------------
.TH pthread_kill 3P
.\"
.\" ----------------
.SH NAME
pthread_kill \- deliver a signal to a thread
.\"
.\" ----------------
.Op c p a
.SH C SYNOPSIS
.nf
.ft 3
#include <signal.h>
.sp .8v
int pthread_kill(pthread_t thread, int sig);
.ft 1
.fi
.Op
.\"
.\" ----------------
.SH DESCRIPTION
The
.IR pthread_kill ()
function is used to request that a signal be sent to the specified
.IR thread .
.PP
If
.I sig
is zero, error checking is performed, but no signal is actually sent.
.\"
.\" ----------------
.SH DIAGNOSTICS
On success,
.IR pthread_kill ()
returns zero; otherwise, an error number is returned:
.\"
.TP 15
.B [ESRCH]
The 
.I thread
parameter does not identify a thread.
.TP
.B [EINVAL]
The value specified by
.I sig
is either an invalid or unsupported signal number.
.\"
.\" ----------------
.SH "SEE ALSO"
sigaction(2), pthread_sigmask(3P), signal(5).
