'\"macro stdmacro
.TH TASKDESTROY 3P  LOCAL
.SH NAME
taskdestroy \- destroy a task
.Op c p a
.SH C SYNOPSIS
.B #include <sys/types.h>
.br
.B #include <task.h>
.P
.br
.B "int taskdestroy (tid_t tid);"
.br
.Op
.Op f
.SH FORTRAN SYNOPSIS
.B integer*4 function taskdestroy (tid)
.br
.B integer*4 tid
.Op
.SH DESCRIPTION
.I Taskdestroy
causes the named task to be destroyed.
Any task within a process can destroy any other task in that process.
.PP
.I Taskdestroy
will fail and no task will be destroyed if the following is true:
.TP 10
.SM
\%[EINVAL]
The
.I tid
specified is not a valid task id for the calling process.
.SH "SEE ALSO"
sproc(2), taskblock(3P), taskctl(3P), taskcreate(3P).
.SH DIAGNOSTICS
Upon successful completion,
.I taskdestroy
returns 0.
Otherwise, a value of \-1 is
returned to the calling task, and
.I errno\^
is set to indicate the error.
'\".so /pubs/tools/origin.sgi
