'\"macro stdmacro
.TH TASKCTL 3P  LOCAL
.SH NAME
taskctl \- operations on a task
.Op c p a
.SH C SYNOPSIS
.B #include <sys/types.h>
.br
.B #include <task.h>
.P
.br
.B "int taskctl (tid_t tid, unsigned option);"
.Op
.Op f
.SH FORTRAN SYNOPSIS
.B integer*4 function taskctl (tid, option)
.br
.B integer*4 tid
.br
.B integer*4 option
.Op
.SH DESCRIPTION
.I taskctl
provides both information about tasks and the ability to control certain
attributes of a task.
.I option
specifies one of the following:
.TP 1i
.SM
.B TSK_ISBLOCKED
returns 1 if the specified task is currently blocked. Since other processes 
could have subsequently unblocked the task, the result should be considered a
snapshot only.
.PP
.I taskctl
will fail if one or more of the following are true:
.TP 15
.SM
\%[EINVAL]
.I option
does not refer to a valid option.
.TP 15
.SM
\%[EINVAL]
.I tid
does not refer to a valid task.
.SH "SEE ALSO"
prctl(2), taskcreate(3P), taskdestroy(3P).
.SH DIAGNOSTICS
Upon successful completion,
.I taskctl
returns a
.I option
specific value.
Otherwise, a value of \-1 is
returned to the calling task, and
.I errno\^
is set to indicate the error.
