'\"macro stdmacro
.TH USCPSEMA 3P
.SH NAME
uscpsema \- conditionally acquires a semaphore
.Op c p a
.SH C SYNOPSIS
.B #include <ulocks.h>
.PP
.B "int uscpsema (usema_t \(**sema);"
.Op
.Op f
.SH FORTRAN SYNOPSIS
.B #include <ulocks.h>
.PP
.B integer*4 function uscpsema (sema)
.br
.B TYPE sema
.br
.in +1i
where
.B TYPE
is
.B "integer*4"
in 32 bit mode, and is
.B "integer*8"
in 64 bit mode.
.in -1i
.Op
.SH DESCRIPTION
.I uscpsema\^
attempts to acquire the semaphore specified by
.I sema.\^
If the semaphore is not available (its count is less than zero), 
.I uscpsema
returns immediately with an indication that the semaphore is not available.
.SH SEE ALSO
usinitsema(3P), usnewsema(3P), uspsema(3P), ustestsema(3P), usvsema(3P).
.SH DIAGNOSTICS
.I uscpsema 
returns a 0 if the semaphore is not acquired and 1 if the semaphore is acquired.
.I uscpsema
can only return an error (\-1) if the internal semaphore data structure
is corrupted.
