'\"macro stdmacro
.TH USTESTSEMA 3P
.SH NAME
ustestsema \- return the value of a semaphore 
.Op c p a
.SH C SYNOPSIS
.B #include <ulocks.h>
.PP
.B "int ustestsema (usema_t \(**sema);"
.Op
.Op f
.SH FORTRAN SYNOPSIS
.B integer*4 function ustestsema (sema)
.br
.B TYPE sema
.br
.in +1i
where
.B TYPE
is
.B "integer*4"
in 32 bit mode, and is
.B "integer*8"
in 64 bit mode.
.in -1i
.Op
.SH DESCRIPTION
.I ustestsema\^
returns the current value of the semaphore specified by
.I sema.\^
This should be viewed as a snapshot only, useful for debugging.
.SH SEE ALSO
usinitsema(3P), usnewsema(3P), uspsema(3P), uscpsema(3P), usvsema(3P).
.SH DIAGNOSTICS
The current count of the semaphore is returned.
