.SH "SUNOS 5 NOTES"
The SunOS 5 (Solaris 2) port was written by Torsten Kasch,
<torsten@techfak.uni-bielefeld.de>.  Support for multi-cpu,
calculation of CPU% and memory stats provided by
Robert Boucher <boucher@sofkin.ca>, Marc Cohen <marc@aai.com>, 
Charles Hedrick <hedrick@geneva.rutgers.edu>, 
William L. Jones <jones@chpc>, and Casper Dik <casper@fwi.uva.nl>.
