CFLAGS= -g -DSN0 -DFORCE_ERRORS -64 -I.. -I../ml/SN -I../sys/SN 

TARGETS= errufr erruff erruf1 errufr errf errio2 errio erriow \
	errio3 erruflpg cached perftest cache_miss

ALL: $(TARGETS)

clobber:
	rm -f $(TARGETS)



