#!/bin/ksh
#	First, figure out which disk the root is on.  We don't
#	want to screw it up.
#

root=`/etc/devnm /`
root=${root%"s? /"}
rawlist=
for i in `./disks`
do
	if [ "$i" != "$root" ]
	then
		rawlist="$rawlist $i"
	fi
done

#
#	Now start up the raw disk bashers.
#

for i in $rawlist
do
	./diskio -n5 -r10000 -s0x200000 -b -p${i}s7 > /dev/null &
done

#
#	Now start something to hammer on the root disk as well
#

./diskio -n5 -r10000 -s0x40000 -p${root}s1 > /dev/null &

#
#	OK.
#
echo "diskstress started"
