/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * HISTORY
 * $Log: rep_errs.h,v $
 * Revision 65.2  1999/02/04 19:19:39  mek
 * Provide C style include file for IRIX kernel integration.
 *
 * Revision 65.1  1997/10/20 19:20:27  jdoak
 * *** empty log message ***
 *
 * Revision 1.1.12.1  1996/10/02  17:47:05  damon
 * 	Newest DFS from Transarc
 * 	[1996/10/01  18:37:34  damon]
 *
 * Revision 1.1.7.1  1994/06/09  14:07:58  annie
 * 	fixed copyright in src/file
 * 	[1994/06/09  13:22:54  annie]
 * 
 * Revision 1.1.5.3  1993/01/21  19:36:08  zeliff
 * 	Embedding copyright notices
 * 	[1993/01/19  19:49:50  zeliff]
 * 
 * Revision 1.1.5.2  1992/08/31  19:45:56  jaffe
 * 	Replace missing RCS id
 * 	[1992/08/31  14:30:14  jaffe]
 * 
 * Revision 1.1.3.2  1992/07/07  21:56:48  mason
 * 	Transarc delta: mason-ot4388-fix-error-tables 1.1
 * 	  Selected comments:
 * 	    The first entry of an error table MUST be empty.  We use this dummy slot
 * 	    as a convenient place to stick an RCSID.  Others are free to do as they wish.
 * 	    Add dummy entry in slot 0 (zero is NOT an error)
 * 	[1992/07/07  21:30:38  mason]
 * 
 * Revision 1.1  1992/01/19  19:42:01  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */

/*
 * Copyright (C) 1990 Transarc Corporation
 * Licensed Materials - Property of Transarc
 * All Rights Reserved.
 *
 * $Header: /proj/irix6.5.7m/isms/irix/kern/fs/dfs/file/fsint/RCS/rep_errs.h,v 65.2 1999/02/04 19:19:39 mek Exp $
 */

/*
 * rep_errs.h:
 * This file is automatically generated; please do not edit it.
 */
#define REP_ERR_RCSID                            (648998912L)
#define REP_ERR_INVAL_PARAM                      (648998913L)
#define REP_ERR_SHORTVVLOG                       (648998914L)
#define REP_ERR_NOTREPLICA                       (648998915L)
#define REP_ERR_NOVOLUME                         (648998916L)
#define REP_ERR_TOOEARLY                         (648998917L)
#define REP_ERR_NOWAYJOSE                        (648998918L)
#define REP_ERR_UNKNOWNREPLICA                   (648998919L)
#define REP_ERR_NOSTORAGE                        (648998920L)
#define REP_ERR_DESTROY                          (648998921L)
#define REP_ERR_BADCELLID                        (648998922L)
#define REP_ERR_EOF                              (648998923L)
#define REP_ERR_DRAFT                            (648998924L)
#define REP_ERR_BUSY                             (648998925L)
#define REP_ERR_PREVSETFAILED                    (648998926L)
#define REP_ERR_RESETFAILED                      (648998927L)
#define initialize_rep_error_table()
#define ERROR_TABLE_BASE_rep (648998912L)

/* for compatibility with older versions... */
#define init_rep_err_tbl initialize_rep_error_table
#define rep_err_base ERROR_TABLE_BASE_rep
