/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1993, 1994 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * HISTORY
 * $Log: scx_errs.h,v $
 * Revision 65.2  1999/02/04 19:19:40  mek
 * Provide C style include file for IRIX kernel integration.
 *
 * Revision 65.1  1997/10/20 19:20:28  jdoak
 * *** empty log message ***
 *
 * Revision 1.1.19.1  1996/10/02  17:47:09  damon
 * 	Newest DFS from Transarc
 * 	[1996/10/01  18:37:37  damon]
 *
 * Revision 1.1.14.2  1994/06/09  14:08:02  annie
 * 	fixed copyright in src/file
 * 	[1994/06/09  13:22:57  annie]
 * 
 * Revision 1.1.14.1  1994/02/04  20:18:50  devsrc
 * 	Merged from 1.0.3a to 1.1
 * 	[1994/02/04  15:13:07  devsrc]
 * 
 * Revision 1.1.12.1  1993/12/07  17:24:23  jaffe
 * 	New File from Transarc 1.0.3a
 * 	[1993/12/02  21:04:06  jaffe]
 * 
 * $EndLog$
 */

/*
 * Copyright (C) 1993 Transarc Corporation
 * Licensed Materials - Property of Transarc
 * All Rights Reserved.
 *
 * $Header: /proj/irix6.5.7m/isms/irix/kern/fs/dfs/file/fsint/RCS/scx_errs.h,v 65.2 1999/02/04 19:19:40 mek Exp $
 */

/*
 * scx_errs.h:
 * This file is automatically generated; please do not edit it.
 */
#define REP_ERR_RCSID                            (655257600L)
#define TKN_ERR_NEW_IF                           (655257601L)
#define TKN_ERR_NEW_NEEDS_RESET                  (655257602L)
#define TKN_ERR_SPARE1                           (655257603L)
#define TKN_ERR_SPARE2                           (655257604L)
#define TKN_ERR_SPARE3                           (655257605L)
#define TKN_ERR_SPARE4                           (655257606L)
#define TKN_ERR_SPARE5                           (655257607L)
#define TKN_ERR_SPARE6                           (655257608L)
#define TKN_ERR_SPARE7                           (655257609L)
#define TKN_ERR_SPARE8                           (655257610L)
#define TKN_ERR_SPARE9                           (655257611L)
#define TKN_ERR_SPARE10                          (655257612L)
#define TKN_ERR_SPARE11                          (655257613L)
#define TKN_ERR_SPARE12                          (655257614L)
#define TKN_ERR_SPARE13                          (655257615L)
#define TKN_ERR_SPARE14                          (655257616L)
#define TKN_ERR_SPARE15                          (655257617L)
#define TKN_ERR_SPARE16                          (655257618L)
#define TKN_ERR_SPARE17                          (655257619L)
#define TKN_ERR_SPARE18                          (655257620L)
#define TKN_ERR_SPARE19                          (655257621L)
#define TKN_ERR_SPARE20                          (655257622L)
#define TKN_ERR_SPARE21                          (655257623L)
#define TKN_ERR_SPARE22                          (655257624L)
#define TKN_ERR_SPARE23                          (655257625L)
#define TKN_ERR_SPARE24                          (655257626L)
#define TKN_ERR_SPARE25                          (655257627L)
#define TKN_ERR_SPARE26                          (655257628L)
#define TKN_ERR_SPARE27                          (655257629L)
#define TKN_ERR_SPARE28                          (655257630L)
#define TKN_ERR_SPARE29                          (655257631L)
#define TKN_ERR_SPARE30                          (655257632L)
#define TKN_ERR_SPARE31                          (655257633L)
#define TKN_ERR_SPARE32                          (655257634L)
#define TKN_ERR_SPARE33                          (655257635L)
#define TKN_ERR_SPARE34                          (655257636L)
#define TKN_ERR_SPARE35                          (655257637L)
#define TKN_ERR_SPARE36                          (655257638L)
#define TKN_ERR_SPARE37                          (655257639L)
#define TKN_ERR_SPARE38                          (655257640L)
#define TKN_ERR_SPARE39                          (655257641L)
#define TKN_ERR_SPARE40                          (655257642L)
#define TKN_ERR_NEW_SET_BASE                     (655257643L)
#define initialize_scx_error_table()
#define ERROR_TABLE_BASE_scx (655257600L)

/* for compatibility with older versions... */
#define init_scx_err_tbl initialize_scx_error_table
#define scx_err_base ERROR_TABLE_BASE_scx
