DIAGDEPTH= ../../..
include ${DIAGDEPTH}/Makedefs

LINCLUDES = -D_MODERN_C -D_SVR4_SOURCE -Dbug_cc1 -DRADIGO


#LLCOPTS= 315 -DSINGLEWIDE -DDMAC17

CFILES= RadCspaceTest.c RadStatusTest.c \
	RadUtils.c RadRamTest.c RadOscillator.c RadDMATest.c

ASFILES= 

include ${DIAGDEPTH}/Makerules
