#!/bin/sh
#Tag 0x00010D13
#
# Copyright 1995, Silicon Graphics, Inc.
# ALL RIGHTS RESERVED
# 
# UNPUBLISHED -- Rights reserved under the copyright laws of the United
# States.   Use of a copyright notice is precautionary only and does not
# imply publication or disclosure.
# 
# U.S. GOVERNMENT RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in FAR 52.227.19(c)(2) or subparagraph (c)(1)(ii) of the Rights
# in Technical Data and Computer Software clause at DFARS 252.227-7013 and/or
# in similar or successor clauses in the FAR, or the DOD or NASA FAR
# Supplement.  Contractor/manufacturer is Silicon Graphics, Inc.,
# 2011 N. Shoreline Blvd. Mountain View, CA 94039-7311.
# 
# THE CONTENT OF THIS WORK CONTAINS CONFIDENTIAL AND PROPRIETARY
# INFORMATION OF SILICON GRAPHICS, INC. ANY DUPLICATION, MODIFICATION,
# DISTRIBUTION, OR DISCLOSURE IN ANY FORM, IN WHOLE, OR IN PART, IS STRICTLY
# PROHIBITED WITHOUT THE PRIOR EXPRESS WRITTEN PERMISSION OF SILICON
# GRAPHICS, INC.
#
# pmview-based app launcher for pmlaunch
#
# $Id: _pmview_frontend,v 1.21 1997/11/28 03:21:50 markgw Exp $

. /var/pcp/config/pmlaunch/pmlaunch.common

cmd=$1
shift

_pmlaunch_work $cmd

for context in "h" "a"
do
    _listSources $context | while read source
    do
	_trace PCP_STDERR "$PCP_STDERR"
	_trace launch "$LAUNCH $target $flag_debug $flag_namespace $flag_timeport -x $launch_version -$context $source $@"
	$LAUNCH $target $flag_debug $flag_namespace $flag_timeport -x $launch_version -$context $source $@ &
    done
done
