/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * HISTORY
 * $Log: hs_errs.h,v $
 * Revision 65.2  1999/02/04 19:19:41  mek
 * Provide C style include file for IRIX kernel integration.
 *
 * Revision 65.1  1997/10/20 19:19:21  jdoak
 * *** empty log message ***
 *
 * Revision 1.1.12.1  1996/10/02  17:51:50  damon
 * 	Newest DFS from Transarc
 * 	[1996/10/01  18:40:33  damon]
 *
 * Revision 1.1.7.1  1994/06/09  14:10:58  annie
 * 	fixed copyright in src/file
 * 	[1994/06/09  13:24:59  annie]
 * 
 * Revision 1.1.5.3  1993/01/19  16:04:33  cjd
 * 	embedded copyright notice
 * 	[1993/01/19  14:14:35  cjd]
 * 
 * Revision 1.1.5.2  1992/08/31  20:05:48  jaffe
 * 	Replace missing RCS ids
 * 	[1992/08/31  16:25:49  jaffe]
 * 
 * Revision 1.1.3.2  1992/05/20  19:56:07  mason
 * 	Transarc delta: cfe-ot2605-tsr-i-f-changes 1.5
 * 	  Files modified:
 * 	    cm: cm_scache.h
 * 	    config: common_data.acf, common_data.idl, common_def.h
 * 	    fshost: fshs_errs.et
 * 	    fsint: afs4int.acf, afs4int.idl, tkn4int.acf, tkn4int.idl
 * 	    host: hs_errs.et; px: px_repops.c; rep: rep_main.c, repser.h
 * 	    userInt/fts: volc_tokens.c; xvolume: volume.h
 * 	  Selected comments:
 * 	    This delta should encompass the interface changes associated with token
 * 	    state recovery (over server crashes, network partitions, fileset moves,
 * 	    and other things).
 * 	    This delta now captures the interface changes for real.  It includes RPC interface
 * 	    changes, new error codes, and new status bits.  It also includes incomplete changes
 * 	    to fts to support the new interface.
 * 	    A new error code to tell TKM about host-still-up-but-revocation-failed.
 * 	    More TSR interface fallout, mostly to the new model.
 * 	    Fix a merge error.
 * 	    Fixing more merge and syntax errors
 * 	Transarc delta: comer-ot2672-tsr-fshost-px 1.4
 * 	  Files modified:
 * 	    cm: cm_express.c; config: common_def.h
 * 	    fshost: fshs.h, fshs_host.c, fshs_host.h, fshs_hostops.c
 * 	    fshost: fshs_subr.c; host: hs_errs.et
 * 	    px: px.h, px_init.c, px_intops.c, px_remove.c, px_repops.c
 * 	    pxd: pxd.c
 * 	    tkc: tkc.c, tkc.h, tkc_cache.c, tkc_locks.c, tkc_tokens.c
 * 	    tkset: tkset.c, tkset.h; volreg: volreg.c; xaggr: ag_init.c
 * 	  Selected comments:
 * 	    File server, fshost, and tkset changes to support changes
 * 	    for improved token-state recovery.  Specific changes are
 * 	    documented in "File Exporter Token State Recovery".
 * 	    Added HS_ERR_OBSOLETE error message to be returned by the
 * 	    obsolete-for-1.0.1 AFS_RenewAllTokens().
 * 	    Fixed compile errors.
 * 	    Changed TKC code to use new parameter for tkn_ReturnToken
 * 	    CFE: fix typos in a couple of files
 * 	[1992/05/20  11:38:12  mason]
 * 
 * Revision 1.1  1992/01/19  19:42:02  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */

/*
 * hs_errs.h:
 * This file is automatically generated; please do not edit it.
 */
#define HS_RCSID                                 (585773056L)
#define HS_ERR_BADTOKEN                          (585773057L)
#define HS_ERR_HOSTDOWN                          (585773058L)
#define HS_ERR_PARTIAL                           (585773059L)
#define HS_ERR_NOENTRY                           (585773060L)
#define HS_ERR_REVFAIL                           (585773061L)
#define HS_ERR_JUSTKIDDING                       (585773062L)
#define HS_ERR_TRYAGAIN                          (585773063L)
#define HS_ERR_OBSOLETE                          (585773064L)
#define initialize_hst_error_table()
#define ERROR_TABLE_BASE_hst (585773056L)

/* for compatibility with older versions... */
#define init_hst_err_tbl initialize_hst_error_table
#define hst_err_base ERROR_TABLE_BASE_hst
