#!/sbin/sh
#**************************************************************************
#*                                                                        *
#*               Copyright (C) 1994,1997, Silicon Graphics, Inc.          *
#*                                                                        *
#*  These coded instructions, statements, and computer programs  contain  *
#*  unpublished  proprietary  information of Silicon Graphics, Inc., and  *
#*  are protected by Federal copyright law.  They  may  not be disclosed  *
#*  to  third  parties  or copied or duplicated in any form, in whole or  *
#*  in part, without the prior written consent of Silicon Graphics, Inc.  *
#*                                                                        *
#**************************************************************************
 
#
# Execution Script for tests
#

for t in *
do
	if test -d $t
	then
		cd $t
		./00runme
		cd ..
	fi
done
