.TH KSTEAL 1 "Annex box (ktools) Commands" 	
.SH NAME
ksteal - steal an Annex box connection from another user.
.SH SYNOPSIS
.BR ksteal\  [\  -grab\  ]\ [\  -f\  ] 
.B machine

.SH DESCRIPTION
.I ksteal
will will steal the console port of the indicated system if it is not locked (see
.BR kcons(1) ).

.PP
If the idle time is less than two hours, the 
.B -f
option must be used to steal the connection.


.SH OPTIONS
.TP
.B -f
Forcefully steal the connection.  Use when the idle time is less than two hours.

.PP
.TP
.B -grab
Invoke 
.BR kgrab(1) " instead of "  kcons(1)
when starting the new connection.


.SH FILES
.I /usr/annex/portsfile
\- to determine the annex boxes to contact, hardware configuration
and notes of the systems.


.SH "SEE ALSO"
kwho(1),
kfree(1),
klist(1),
kcons(1),
kgrab(1),
annex-intro(1)

.SH NOTES
.PP
.B kcons, kgrab, ksteal, 
and 
.B kreset
invoke 
.B kwho
to determine the status of the system before proceeding with the
desired action.

.SH AUTHOR
Chan Wilson.

.SH BUGS
.B kwho
attempts to contact all of the annex boxes listed in 
.I /usr/annex/portsfile.
If it cannot contact an Annex box (either due to network problems or a dead Annex), 
it will wait for an inordinate amount of time before continuing.  This is due to
the large timeout on the 
.I connect
system call.
