#!smake
#
# Makefile for /usr/lib/librpcsvc.a, the RPC servers' interface library.
#
# ident  "$Revision: 1.1 $
#

DEPTH=.

HFILES= rex.h rexioctl.h
CFILES= bootparam_xdr.c etherxdr.c klm_prot.c mountxdr.c nlm_prot.c \
	rex_xdr.c rstatxdr.c rusersxdr.c rwallxdr.c sm_inter.c \
	sprayxdr.c util.c yppasswdxdr.c rquotaxdr.c

include $(ROOT)/usr/include/make/libleafdefs
include $(LIBLEAFRULES)
