#!smake
#ident  "$Revision: 1.1 $"

DEPTH = .

CFILES  = sscHTMLPreProcessor.c sscHTMLProcessor.c swc_main.c \
	  rgAPI.c sssSession.c 
LCINCS=-I.

include $(ROOT)/usr/include/make/libleafdefs
include $(LIBLEAFRULES)
