#!/bin/sh

# This shell script does whatever needs to be done to make toolroot
# binaries run on build machines.  (Since they may be running anything
# from IRIX 6.2 to 6.5, backwards compatibility is not a given).

# TOOLROOTSAFE is defined (in commondefs) to point to this script.


# libtoolroot.so allows executables which were linked against the
# current ROOT to be run on earlier versions of IRIX.

eval ${TOOLROOTSAFE_O32:-_RLD_LIST=DEFAULT:${TOOLROOT}/usr/lib/libtoolroot.so} \
 ${TOOLROOTSAFE_N32:-_RLDN32_LIST=DEFAULT:${TOOLROOT}/usr/lib32/libtoolroot.so}\
 '"$@"'

