# Makefile libsc/fs
# 
# $Revision: 1.2 $

SCDEPTH=..
include ${SCDEPTH}/libscdefs

#
# Set up to build endian dependent objects
OBJECTDIR=$(TARGETDIR)
LIBPATH=$(LIBNAME)

CFILES= xfs.c xfs_bit.c xfs_dir.c xfs_dir2.c xfs_inode.c

include $(LIBSCRULES)
