TARGET = radiosity

OBJS = rad_main.o patchman.o elemman.o taskman.o modelman.o smallobj.o\
         display.o visible.o rad_tools.o room_model.o 
HHS = model.H parallel.H patch.H radiosity.H task.H
HS = model.h parallel.h patch.h radiosity.h task.h

GLIBDIR = ./glibdumb
GLIB    = glib.a
# look me up in man sigfpe
LIBFPE = -lfpe

MACROS = ../../macros/c.m4.sgi
M4 = m4 -s -Ulen -Uindex
CCOPTS = -float $(CFLAGS)
LDFLAGS = -lm 
CFLAGS = $(CINCLUDE) -O2 -cckr -64
CINCLUDE = -I$(GLIBDIR) -I./glibps 

LOADLIBES =  $(GLIBDIR)/$(GLIB) glibps/glibps.a

CC = cc

x = *

$(TARGET): $(OBJS) 
	cd glibdumb; make
	cd glibps; make
	$(CC) $(CFLAGS)  $(OBJS)  -o $(TARGET) $(LOADLIBES) $(LDFLAGS)

clobber:
	cd glibdumb; make clobber
	cd glibps; make clobber
	rm -f *.[hco] *~ $(TARGET)

clean:
	rm -f *.[hco] *~
run:
	$(TARGET)


.SUFFIXES:
.SUFFIXES:	.o .c .C .h .H

.H.h:
	$(M4) ${MACROS} $*.H > $*.h

.C.c:
	$(M4) $(MACROS) $*.C > $*.c

.c.o:	
	cc -c $(CFLAGS) $*.c

.C.o:	
	m4 -Ulen -Uindex $(MACROS) $*.C > $*.c
	cc -c $(CFLAGS) $*.c

$(HS): $(HHS)

radiosity.h: patch.h model.h parallel.h task.h
rad_main.c: rad_main.C $(HS)
patchman.c: patchman.C $(HS)
elemman.c: elemman.C $(HS)
taskman.c: taskman.C $(HS)
modelman.c: modelman.C $(HS)
smallobj.c: smallobj.C $(HS)
display.c: display.C $(HS)
visible.c: visible.C $(HS)
rad_tools.c: rad_tools.C $(HS)
room_model.c: room_model.C $(HS)

clean:
	$(RM) $(CS) $(ASMS) $(SS) $(OBJS) $(HS)
