#define DEFAULT_FILE		"lock_stress.testfile"
#define DOT					"."
#define DEFAULT_FILE_SIZE	16*1024
#define DEFAULT_PROCESSES	20
#define DEFAULT_ACCESS		RANDOM
#define DEFAULT_PAUSE		1000
#define DEFAULT_RECSIZE		512
#define DEFAULT_REPEAT		-1
#define DEFAULT_VERBOSE		0
#define DEFAULT_MONTIME		2
#define DEFAULT_LOCKTIMEO	10
#define DEFAULT_SIGNUM		SIGTERM
#define DEFAULT_KILLTIME	1

#define BUFLEN				1024
#define OPEN_FLAGS			O_RDWR
#define CREATE_FLAGS		(OPEN_FLAGS | O_CREAT | O_TRUNC)
#define OPEN_MODE \
	(S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP | S_IROTH | S_IWOTH)
#define CREATE_MODE			OPEN_MODE
#define ERROREXIT			-1
