.TH LOCK_STRESS 1 "" "Testing"
.SH NAME
lock_stress \- stress test file and record locking functionality
.br
lock_monitor \- monitor the locks held in the test file during stress testing
.SH SYNOPSIS
.B lock_stress
[-t file] [parameters]
.br
.B lock_monitor
[-t file] [-vs] [parameters]
.SH DESCRIPTION
.I lock_stress
is an application designed to stress test the file and record locking
functionality of a UNIX file system.  The parameters of the stress testing
are specified by the options described below.
.P
If any one of the processes encounters an unexpected error, it will exit.
The parent process will be notified and all of the remaining processes will
be signalled to exit.
.P
.I lock_monitor
monitors the locks on the test file.
.SH OPTIONS
\fIlock_stress\fP and \fIlock_monitor\fP accept the following options.
.TP 8
\fB-t\fP \fIfile\fP
This option turns on lock acquisition and release tracing.  The argument
\fIfile\fP specifies the base file nambe to be used for the trace output.
This name is appended with the process ID for the process producing the
trace.
.TP 8
.B -v
This causes \fIlock_stress\fP and \fIlock_monitor\fP to be verbose about
the testing.  Multiple \fB-v\fP options may be used to get higher levels
of detail in the output.
.TP 8
.B -s
This causes locking statistics to be reported by the lock stress processes
upon exiting.  Note that statistics will not be reported by processes
which exit upon receipt of a signal which is not caught.  The only signal
which is caught by default is SIGINT.
.TP 8
.B -k
This causes \fIlock_stress\fP to periodically signal randomly selected
stress processes.  One of two signals is sent to the process:  SIGINT
and a configured signal.  By default, the configured signal is SIGTERM.
The idea here is for one signal to be a signal which caught by the child
process and one to be a signal which is not caught.  A new child process
is started in place of the signalled one.  This keeps the number of
processes constant.
.P
The stress testing parameters are provided to \fIlock_stress\fP and
\fIlock_monitor\fP as a comma-separated list of parameter specifications.
The parameters are as follows.
.TP 8
\fBfile\fP=\fIpath\fP
set the test file name to \fIpath\fP.  The default test file name is
"lock_stress.testfile".
.TP 8
\fBdir\fP=\fIpath\fP
set the working directory for the test run to \fIpath\fP.  The default
working directory is ".".
.TP 8
\fBprocesses\fP=\fIprocs\fP
set the number of stress processes to \fIprocs\fP.  The default number of
processes is 20.
.TP 8
\fBfilesize\fP=\fIsize\fP
set the test file size to \fIsize\fP.  The size is specified in bytes.
The default file size is 16K bytes.
.TP 8
\fBaccess\fP=\fImethod\fP
set the test file access method to \fImethod\fP, where \fImethod\fP may be
\fBrandom\fP or \fBsequential\fP.  The default setting for the access method
is \fBrandom\fP.
.TP 8
\fBpausetime\fP=\fImicrosecs\fP
set the pause time between locking/unlocking operations to \fImicrosecs\fP.
The default setting is 1000.
.TP 8
\fBrecsize\fP=\fIrange\fP
set the record (locking region) size to \fIrange\fP, where the \fIrange\fP
specifies a range of sizes and may either be \fIsize\fP or \fIsize1-size2\fP.
Specifying a single record size will cause all locked regions to be of the
same size.  The default setting is a single size of 512 bytes.
.TP 8
\fBrepeat\fP=\fIcount\fP
set the repeat count to \fIcount\fP.  This controls how many locking operations
are performed by each process.  Setting the repeat count to -1 causes the
processes to execute until receiving a signal.  Sending SIGINT to the parent
process will cause all of the processes to exit.  The default setting is for
infinite execution.
.TP 8
\fBmontime\fP=\fIseconds\fP
tells \fIlock_monitor\fP to monitor the locks in the test file every
\fIseconds\fP seconds.  The default is monitoring every second.
.TP 8
\fBsignal\fP=\fIsignum\fP
set the uncaught signal to be delivered to processes to \fIsignum\fP.  This is
used only with the \fB-k\fP option.  The default signal is SIGTERM.
.TP 8
\fBkilltime\fP=\fIseconds\fP
set the time between signals to stress processes to \fIseconds\fP seconds.
This is used only with the \fB-k\fP option.  The default is 1 second.
