/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: acf_lex_yy.c,v $
 * Revision 1.1  1993/08/31 06:48:01  jwag
 * Initial revision
 *
 * Revision 1.1.2.3  1993/01/03  21:37:32  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/03  14:31:53  bbelch]
 *
 * Revision 1.1.2.2  1992/12/23  18:42:18  zeliff
 * 	Embedding copyright notice
 * 	[1992/12/23  00:58:51  zeliff]
 * 
 * Revision 1.1  1992/01/19  03:00:31  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
**
**  Copyright (c) 1989 by
**      Hewlett-Packard Company, Palo Alto, Ca. &
**      Digital Equipment Corporation, Maynard, Mass.
**
**
**  NAME:
**
**      acf.y
**
**  FACILITY:
**
**      Interface Definition Language (IDL) Compiler
**
**  ABSTRACT:
**
**      Main module for ACF lexical analyzer.  This module is necessary in
**      order to assure that acf.h is included into lex-generated code before
**      anything else (see acf.h for a description of why this is necessary).
**      lex puts some of its generated definitions BEFORE any user-included
**      code, and therefore the same thing can not be accom- plished by merely
**      putting "#include acf.h" in the lex source.
**
*/

#include <acf.h>                /* Renames globals */
#include <acf_lex_yy_i.c>       /* Generated by lex */
