/**************************************************************************
 *									  *
 * 		 Copyright (C) 1995-1996 Silicon Graphics, Inc.		  *
 *									  *
 *  These coded instructions, statements, and computer programs  contain  *
 *  unpublished  proprietary  information of Silicon Graphics, Inc., and  *
 *  are protected by Federal copyright law.  They  may  not be disclosed  *
 *  to  third  parties  or copied or duplicated in any form, in whole or  *
 *  in part, without the prior written consent of Silicon Graphics, Inc.  *
 *									  *
 **************************************************************************/
#ident  "$Id: dcfile.idl,v 1.7 1997/11/10 23:41:45 ethan Exp $"

#include "ksys/cell/subsysid.h"

/*
 * operations from server to client
 */
subsystem	"dcfile"	DCFILE_SUBSYSID

import <ksys/vshm.h>
import <ksys/cell/tkm.h>
import <ksys/cell/service.h>
import <ksys/cell/handle.h>
import <ksys/cell.h>

/*
 * call to client to return token
 */
synchronous void
recall(
	in	pointerto	obj_handle_t	obj,
	in	valueof		tk_set_t	to_be_recalled,
	in	valueof		tk_disp_t	dofrev,
	out	pointerto	int		error)

/*
 * call to client to set new flag value
 */
synchronous void
setflags(
	in	valueof		int		newflags,
	in	pointerto	obj_handle_t	obj,
	out	pointerto	int		error)

/*
 * call to client to retarget the server
 */
asynchronous
retarget(
	in	pointerto	obj_handle_t	target_handle,
	in	pointerto	obj_handle_t	old_handle,
	in	valueof 	<void *>	rtsync,
	in	valueof		<void *>	error)
