#
#       @(#)tests.init	1.3 97/01/03 Connectathon testsuite
#
#MNTOPTIONS="rw,hard,intr"
#MNTOPTIONS="rw,hard,intr,vers=3,proto=tcp"
MNTOPTIONS="rw,hard,intr,vers=3,proto=udp"
#MNTOPTIONS="rw,hard,intr,vers=2,proto=tcp"
#MNTOPTIONS="rw,hard,intr,vers=2,proto=udp"
MNTPOINT="/mnt"

# Use this mount command if using:
#	SVR3
#MOUNTCMD='./domount -f NFS,$MNTOPTIONS $SERVER\:$SERVPATH $MNTPOINT'

# Use this mount command if using:
#	SVR4
#	Solaris 2.x
MOUNTCMD='./domount -F nfs -o $MNTOPTIONS $SERVER\:$SERVPATH $MNTPOINT'

# Use this mount command if using:
#	BSD
#	SunOS 4.X
#	(DEC) OSF/1
#	HPUX
#MOUNTCMD='./domount -o $MNTOPTIONS $SERVER\:$SERVPATH $MNTPOINT'

# Use this mount command if using:
#	DG/UX
#MOUNTCMD='./domount -t nfs -o $MNTOPTIONS $SERVER\:$SERVPATH $MNTPOINT'

UMOUNTCMD='./domount -u $MNTPOINT'

# Use the next two lines if using:
#	SVR3
#	SVR4
#	Solaris 2.x
#	(DEC) OSF1
#	HPUX
DASHN=
BLC=\\c

# Use the next two lines if using:
#	BSD
#	SunOS 4.X
#DASHN=-n
#BLC=

# Use this path for:
#	Solaris 2.x
#PATH=/opt/SUNWspro/bin:/usr/ccs/bin:/sbin:/bin:/usr/bin:/usr/ucb:/etc:.

# Use this path for:
#	Solaris 2.x with GCC
#PATH=/opt/gnu/bin:/usr/ccs/bin:/sbin:/bin:/usr/bin:/usr/ucb:/etc:.

# Use this path for:
#	HPUX
#PATH=/bin:/usr/bin:/etc:/usr/etc:/usr/local/bin:/usr/contrib/bin:.

# Use this path for:
#	BSD
#	SunOS 4.X
#PATH=/bin:/usr/bin:/usr/ucb:/etc:/usr/etc:.

# Use this path for:
#	(DEC) OSF/1
#	SVR4
#PATH=/bin:/usr/bin:/usr/ucb:/usr/ccs/bin:/sbin:/usr/sbin:.

# Use this path for:
#	DG/UX
#PATH=/bin:/usr/bin:/usr/ucb:/etc:/usr/etc:.

SERVER=""
SERVPATH="/server"
TEST="-a"
TESTARG="-t"

# -----------------------------------------------
# Defines for various variables used in scripts and makefiles.
#
# Do not remove the following three lines.  They may be overridden by
# other configuration parameters lower in this file, but these three
# variables must be defined.
CC=cc
CFLAGS=
LIBS=
LOCKTESTS=tlock

# Use with SVR3 systems.
# Add -TR2 to CFLAGS for use on Amdahl UTS systems.
#CFLAGS=-DSVR3
#LIBS=`echo -lrpc -lsocket`

# Use with BSD systems.
#CFLAGS=-Duse_directs

# Use with SVR4 systems.
#CFLAGS=-DSVR4
#LIBS=`echo -lsocket -lnsl`

# Use with SunOS 4.X systems
#CC=/usr/5bin/cc
#CFLAGS=-DSUNOS4X

# Use with Solaris 2.x systems
#CC=/opt/SUNWspro/bin/cc
# Use this with GCC
#CC=/opt/gnu/bin/gcc
#CFLAGS=`echo -DSVR4 -DMMAP -DSOLARIS2X -DSTDARG`
# Use this with pre-2.2 systems
#LIBS=`echo -lsocket -ltcpip -lstraddr -lnsl`
# Use with 2.2 and later systems
#LIBS=`echo -lsocket -lnsl`
# Use with 2.6 and later systems
#LOCKTESTS=`echo tlock tlock32lfs tlock64`

# Use with (DEC) OSF/1 systems
#CFLAGS=`echo -O -DOSF1 -DMMAP -DSTDARG`
# use the following instead of the above if using gcc
#CFLAGS=`echo -O -DOSF1 -DMMAP -DSTDARG -fwritable-strings`
#MOUNT=/sbin/mount
#UMOUNT=/sbin/umount

# Use with HPUX systems
#CFLAGS=-DHPUX
#CC=/bin/cc
#RM=/bin/rm
#MAKE=/bin/make

# Use with IRIX systems.
CFLAGS=`echo -DSVR4 -DIRIX -DMMAP -w`
PATH=/bin:/usr/bin:/usr/bsd:/etc:/usr/etc:.
# for IRIX 32 bit systems (e.g. INDY, O2, Challenge S)
LOCKTESTS=`echo tlock`
#LOCKTESTS=`echo tlock tlock32lfs`
# for IRIX 64 bit systems (e.g. Challenge L, XL, O200, O2000)
#LOCKTESTS=`echo tlock64`

# Use with DG/UX systems.
#CFLAGS=-DSVR4
#LIBS=`echo -lsocket -lnsl`

# -----------------------------------------------
