/*
 * cbar_defs 
 *
 * Cosmo2 gio 1 chip hardware definitions
 *
 * Copyright 1995, Silicon Graphics, Inc.
 * ALL RIGHTS RESERVED
 *
 * UNPUBLISHED -- Rights reserved under the copyright laws of the United
 * States.   Use of a copyright notice is precautionary only and does not
 * imply publication or disclosure.
 *
 * U.S. GOVERNMENT RESTRICTED RIGHTS LEGEND:
 * Use, duplication or disclosure by the Government is subject to restrictions
 * as set forth in FAR 52.227.19(c)(2) or subparagraph (c)(1)(ii) of the Rights
 * in Technical Data and Computer Software clause at DFARS 252.227-7013 and/or
 * in similar or successor clauses in the FAR, or the DOD or NASA FAR
 * Supplement.  Contractor/manufacturer is Silicon Graphics, Inc.,
 * 2011 N. Shoreline Blvd. Mountain View, CA 94039-7311.
 * THE CONTENT OF THIS WORK CONTAINS CONFIDENTIAL AND PROPRIETARY
 * INFORMATION OF SILICON GRAPHICS, INC. ANY DUPLICATION, MODIFICATION,
 * DISTRIBUTION, OR DISCLOSURE IN ANY FORM, IN WHOLE, OR IN PART, IS STRICTLY
 * PROHIBITED WITHOUT THE PRIOR EXPRESS WRITTEN PERMISSION OF SILICON
 * GRAPHICS, INC.
 */

#include "cosmo2_defs.h"

extern void mcu_WRITE(__uint32_t, UBYTE );
extern void mcu_WRITE_WORD(__uint32_t, UWORD );

UWORD VI_HOR_START_SQ_NTSC_DEFAULT  ;
UWORD VI_HOR_START_SQ_PAL_DEFAULT   ;

UWORD VI_HOR_LEN_SQ_NTSC_DEFAULT   ;
UWORD VI_HOR_LEN_SQ_PAL_DEFAULT    ;

UWORD VI_HOR_START_CCIR_NTSC_DEFAULT ;
UWORD VI_HOR_START_CCIR_PAL_DEFAULT ;
UWORD VI_HOR_LEN_CCIR_DEFAULT ;

UWORD VI_VERT_NTSC_ODD_START_DELAY ;
UWORD VI_VERT_NTSC_EVEN_START_DELAY ;

UWORD VI_VERT_START_NTSC_DEFAULT ;

UWORD VI_VERT_NTSC_ODD_FIELD_DELAY ;
UWORD VI_VERT_NTSC_EVEN_FIELD_DELAY ;
UWORD VI_FIELD_DELAY_NTSC_DEFAULT ;

UWORD VI_VERT_LEN_NTSC_DEFAULT ;


UWORD VI_VERT_PAL_ODD_START_DELAY ;
UWORD VI_VERT_PAL_EVEN_START_DELAY ;
UWORD VI_VERT_START_PAL_DEFAULT ;

UWORD VI_VERT_PAL_ODD_FIELD_DELAY;
UWORD VI_VERT_PAL_EVEN_FIELD_DELAY ;
UWORD VI_FIELD_DELAY_PAL_DEFAULT  ;

UWORD VI_VERT_LEN_PAL_DEFAULT ;


UWORD VO_ODD_VERT_START_NTSC_DEFAULT ;
UWORD VO_EVEN_VERT_START_NTSC_DEFAULT;

UWORD VO_VERT_START_NTSC_DEFAULT ;

UWORD VO_ODD_VERT_LEN_NTSC_DEFAULT ;
UWORD VO_EVEN_VERT_LEN_NTSC_DEFAULT ;

UWORD VO_ODD_VERT_START_PAL_DEFAULT ;
UWORD VO_EVEN_VERT_START_PAL_DEFAULT ;
UWORD VO_VERT_START_PAL_DEFAULT ;

UWORD VO_ODD_VERT_LEN_PAL_DEFAULT ;
UWORD VO_EVEN_VERT_LEN_PAL_DEFAULT ;

UWORD VC_HOR_SYNC_START_CCIR_NTSC_DEFAULT ;
UWORD VC_HOR_SYNC_START_CCIR_PAL_DEFAULT ;
UWORD VC_HOR_LEN_CCIR_DEFAULT ;

UWORD VC_HOR_SYNC_START_NTSC_DEFAULT ;
UWORD VC_HOR_SYNC_START_PAL_DEFAULT ;
UWORD VC_HOR_LEN_SQ_PAL_DEFAULT ;
UWORD VC_HOR_LEN_SQ_NTSC_DEFAULT ;

UWORD VC_ODD_START_NTSC_DEFAULT ;
UWORD VC_EVEN_START_NTSC_DEFAULT ;

UWORD VC_FIELD_LENGTH_NTSC_DEFAULT ;

UWORD VC_ODD_START_PAL_DEFAULT ;
UWORD VC_EVEN_START_PAL_DEFAULT ;
UWORD VC_FIELD_LENGTH_PAL_DEFAULT ;


cosmo2_cbar_chan_setup ( UBYTE pal, UBYTE ccir)
{
msg_printf(VRB, " cbar_chan \n");

VI_HOR_START_SQ_PAL_DEFAULT=176;

VI_HOR_LEN_SQ_NTSC_DEFAULT=640;
VI_HOR_LEN_SQ_PAL_DEFAULT=768;

VI_HOR_START_CCIR_NTSC_DEFAULT=138;
VI_HOR_START_CCIR_PAL_DEFAULT=144;
VI_HOR_LEN_CCIR_DEFAULT=720;

VI_VERT_NTSC_ODD_START_DELAY=13;
VI_VERT_NTSC_EVEN_START_DELAY=12;

VI_VERT_NTSC_ODD_START_DELAY=13-3;
VI_VERT_NTSC_EVEN_START_DELAY=12-3;
VI_VERT_START_NTSC_DEFAULT=(VI_VERT_NTSC_EVEN_START_DELAY<<4 |VI_VERT_NTSC_ODD_START_DELAY);
VI_VERT_NTSC_ODD_FIELD_DELAY=3;
VI_VERT_NTSC_EVEN_FIELD_DELAY=2;
VI_FIELD_DELAY_NTSC_DEFAULT=(VI_VERT_NTSC_EVEN_FIELD_DELAY<<4|VI_VERT_NTSC_ODD_FIELD_DELAY);
VI_VERT_LEN_NTSC_DEFAULT=243;


VI_VERT_PAL_ODD_START_DELAY=15;
VI_VERT_PAL_EVEN_START_DELAY=15;
VI_VERT_START_PAL_DEFAULT=(VI_VERT_PAL_EVEN_START_DELAY<<4 |VI_VERT_PAL_ODD_START_DELAY);
VI_VERT_PAL_ODD_FIELD_DELAY=2;
VI_VERT_PAL_EVEN_FIELD_DELAY=2;
VI_FIELD_DELAY_PAL_DEFAULT=(VI_VERT_PAL_EVEN_FIELD_DELAY<<4|VI_VERT_PAL_ODD_FIELD_DELAY);
VI_VERT_LEN_PAL_DEFAULT=288;


VO_ODD_VERT_START_NTSC_DEFAULT=7;
VO_EVEN_VERT_START_NTSC_DEFAULT=7;

VO_ODD_VERT_START_NTSC_DEFAULT=10;
VO_EVEN_VERT_START_NTSC_DEFAULT=10;


VO_VERT_START_NTSC_DEFAULT=(VO_EVEN_VERT_START_NTSC_DEFAULT<<4|VO_ODD_VERT_START_NTSC_DEFAULT);
VO_ODD_VERT_LEN_NTSC_DEFAULT=256;
VO_EVEN_VERT_LEN_NTSC_DEFAULT=256;

VO_ODD_VERT_START_PAL_DEFAULT=10;
VO_EVEN_VERT_START_PAL_DEFAULT=9;
VO_VERT_START_PAL_DEFAULT=(VO_EVEN_VERT_START_PAL_DEFAULT<<4|VO_ODD_VERT_START_PAL_DEFAULT);
VO_ODD_VERT_LEN_PAL_DEFAULT=306;
VO_EVEN_VERT_LEN_PAL_DEFAULT=305;


VC_HOR_SYNC_START_CCIR_NTSC_DEFAULT=138+1-2;
VC_HOR_SYNC_START_CCIR_PAL_DEFAULT=144+1-2;
VC_HOR_LEN_CCIR_DEFAULT=720;

VC_HOR_SYNC_START_NTSC_DEFAULT=140+1-2;
VC_HOR_SYNC_START_PAL_DEFAULT=176+1-2;
VC_HOR_LEN_SQ_PAL_DEFAULT=768;
VC_HOR_LEN_SQ_NTSC_DEFAULT=640;

VC_ODD_START_NTSC_DEFAULT=20;
VC_EVEN_START_NTSC_DEFAULT=19;

VC_FIELD_LENGTH_NTSC_DEFAULT=243;

VC_ODD_START_PAL_DEFAULT=24;
VC_EVEN_START_PAL_DEFAULT=25;
VC_FIELD_LENGTH_PAL_DEFAULT=288;


if (pal) {
	if (ccir) {
	mcu_WRITE_WORD(CBAR_BASE+VC1_HOR_SYNC_START, VC_HOR_SYNC_START_CCIR_PAL_DEFAULT);
	mcu_WRITE_WORD(CBAR_BASE+VC1_HOR_SYNC_LEN, VC_HOR_LEN_CCIR_DEFAULT);
	mcu_WRITE_WORD(CBAR_BASE+VC1_HOR_DATA_LEN, VC_HOR_LEN_CCIR_DEFAULT);
	}
	else {
	mcu_WRITE_WORD(CBAR_BASE+VC1_HOR_SYNC_START, VC_HOR_SYNC_START_PAL_DEFAULT);
	mcu_WRITE_WORD(CBAR_BASE+VC1_HOR_SYNC_LEN, VC_HOR_LEN_SQ_PAL_DEFAULT);
	mcu_WRITE_WORD(CBAR_BASE+VC1_HOR_DATA_LEN, VC_HOR_LEN_SQ_PAL_DEFAULT);
	}

mcu_WRITE_WORD(CBAR_BASE+VC1_ODD_SYNC_START, VC_ODD_START_PAL_DEFAULT);
mcu_WRITE_WORD(CBAR_BASE+VC1_ODD_DATA_START, VC_ODD_START_PAL_DEFAULT);

mcu_WRITE_WORD(CBAR_BASE+VC1_EVEN_SYNC_START, VC_EVEN_START_PAL_DEFAULT);
mcu_WRITE_WORD(CBAR_BASE+VC1_EVEN_DATA_START, VC_EVEN_START_PAL_DEFAULT);

mcu_WRITE_WORD(CBAR_BASE+VC1_ODD_SYNC_LEN, VC_FIELD_LENGTH_PAL_DEFAULT);
mcu_WRITE_WORD(CBAR_BASE+VC1_EVEN_SYNC_LEN, VC_FIELD_LENGTH_PAL_DEFAULT);
mcu_WRITE_WORD(CBAR_BASE+VC1_VERT_DATA_LEN, VC_FIELD_LENGTH_PAL_DEFAULT);
}

else {
  if (ccir) {
	mcu_WRITE_WORD(CBAR_BASE+VC1_HOR_SYNC_START, VC_HOR_SYNC_START_CCIR_NTSC_DEFAULT);
	mcu_WRITE_WORD(CBAR_BASE+VC1_HOR_SYNC_LEN, VC_HOR_LEN_CCIR_DEFAULT);
	mcu_WRITE_WORD(CBAR_BASE+VC1_HOR_DATA_LEN, VC_HOR_LEN_CCIR_DEFAULT);
	}else{
	mcu_WRITE_WORD(CBAR_BASE+VC1_HOR_SYNC_START,VC_HOR_SYNC_START_NTSC_DEFAULT);
	mcu_WRITE_WORD(CBAR_BASE+VC1_HOR_SYNC_LEN,VC_HOR_LEN_SQ_NTSC_DEFAULT);
	mcu_WRITE_WORD(CBAR_BASE+VC1_HOR_DATA_LEN,VC_HOR_LEN_SQ_NTSC_DEFAULT);
	}

mcu_WRITE_WORD(CBAR_BASE+VC1_ODD_SYNC_START,VC_ODD_START_NTSC_DEFAULT);
mcu_WRITE_WORD(CBAR_BASE+VC1_ODD_DATA_START,VC_ODD_START_NTSC_DEFAULT);

mcu_WRITE_WORD(CBAR_BASE+VC1_EVEN_SYNC_START,VC_EVEN_START_NTSC_DEFAULT);
mcu_WRITE_WORD(CBAR_BASE+VC1_EVEN_DATA_START,VC_EVEN_START_NTSC_DEFAULT);

mcu_WRITE_WORD(CBAR_BASE+VC1_ODD_SYNC_LEN,VC_FIELD_LENGTH_NTSC_DEFAULT);
mcu_WRITE_WORD(CBAR_BASE+VC1_EVEN_SYNC_LEN,VC_FIELD_LENGTH_NTSC_DEFAULT);
mcu_WRITE_WORD(CBAR_BASE+VC1_VERT_DATA_LEN,VC_FIELD_LENGTH_NTSC_DEFAULT);
}

#if 0
mcu_WRITE_WORD(CBAR_BASE+VC2_HOR_SYNC_START,VC1_HOR_SYNC_START);
mcu_WRITE_WORD(CBAR_BASE+VC2_HOR_SYNC_LEN,VC1_HOR_SYNC_LEN);
mcu_WRITE_WORD(CBAR_BASE+VC2_ODD_SYNC_START,VC1_ODD_SYNC_START);
mcu_WRITE_WORD(CBAR_BASE+VC2_ODD_SYNC_LEN,VC1_ODD_SYNC_LEN);
mcu_WRITE_WORD(CBAR_BASE+VC2_EVEN_SYNC_START,VC1_EVEN_SYNC_START);
mcu_WRITE_WORD(CBAR_BASE+VC2_EVEN_SYNC_LEN,VC1_EVEN_SYNC_LEN);
mcu_WRITE_WORD(CBAR_BASE+VC2_ODD_DATA_START,VC1_ODD_DATA_START);
mcu_WRITE_WORD(CBAR_BASE+VC2_EVEN_DATA_START,VC1_EVEN_DATA_START);
mcu_WRITE_WORD(CBAR_BASE+VC2_HOR_DATA_LEN,VC1_HOR_DATA_LEN);
mcu_WRITE_WORD(CBAR_BASE+VC2_VERT_DATA_LEN,VC1_VERT_DATA_LEN);
#endif

	return 0;
}


cosmo2_cbar_vivo_setup( UBYTE pal, UBYTE ccir)
{

	msg_printf(VRB, " cbar_vivo \n");
	VI_HOR_START_SQ_NTSC_DEFAULT=140;
	VI_HOR_START_SQ_PAL_DEFAULT=176;

	VI_HOR_LEN_SQ_NTSC_DEFAULT=640;
	VI_HOR_LEN_SQ_PAL_DEFAULT=768;

VI_HOR_START_CCIR_NTSC_DEFAULT=138;
VI_HOR_START_CCIR_PAL_DEFAULT=144;
VI_HOR_LEN_CCIR_DEFAULT=720;

VI_VERT_NTSC_ODD_START_DELAY=13;
VI_VERT_NTSC_EVEN_START_DELAY=12;

VI_VERT_NTSC_ODD_START_DELAY=13-3;
VI_VERT_NTSC_EVEN_START_DELAY=12-3;
VI_VERT_START_NTSC_DEFAULT=(VI_VERT_NTSC_EVEN_START_DELAY<<4 |VI_VERT_NTSC_ODD_START_DELAY);
VI_VERT_NTSC_ODD_FIELD_DELAY=3;
VI_VERT_NTSC_EVEN_FIELD_DELAY=2;
VI_FIELD_DELAY_NTSC_DEFAULT=(VI_VERT_NTSC_EVEN_FIELD_DELAY<<4|VI_VERT_NTSC_ODD_FIELD_DELAY);
VI_VERT_LEN_NTSC_DEFAULT=243;


VI_VERT_PAL_ODD_START_DELAY=15;
VI_VERT_PAL_EVEN_START_DELAY=15;
VI_VERT_START_PAL_DEFAULT=(VI_VERT_PAL_EVEN_START_DELAY<<4 |VI_VERT_PAL_ODD_START_DELAY);
VI_VERT_PAL_ODD_FIELD_DELAY=2;
VI_VERT_PAL_EVEN_FIELD_DELAY=2;
VI_FIELD_DELAY_PAL_DEFAULT=(VI_VERT_PAL_EVEN_FIELD_DELAY<<4|VI_VERT_PAL_ODD_FIELD_DELAY);
VI_VERT_LEN_PAL_DEFAULT=288;

	if (pal) {
	  if (ccir) {
		mcu_WRITE_WORD(CBAR_BASE+VI_HOR_START, VI_HOR_START_CCIR_PAL_DEFAULT);
		mcu_WRITE_WORD(CBAR_BASE+VI_HOR_LEN, VI_HOR_LEN_CCIR_DEFAULT);
		}
		else {
		mcu_WRITE_WORD(CBAR_BASE+VI_HOR_START, VI_HOR_START_SQ_PAL_DEFAULT);
		mcu_WRITE_WORD(CBAR_BASE+VI_HOR_LEN, VI_HOR_LEN_SQ_PAL_DEFAULT);
		}
	mcu_WRITE(CBAR_BASE+VI_VERT_START, (UBYTE) VI_VERT_START_PAL_DEFAULT);
	mcu_WRITE_WORD(CBAR_BASE+VI_VERT_LEN, VI_VERT_LEN_PAL_DEFAULT);
	mcu_WRITE(CBAR_BASE+VI_FIELD_DELAY, (UBYTE) VI_FIELD_DELAY_PAL_DEFAULT);
	}

	else {
	  if (ccir) {
		mcu_WRITE_WORD(CBAR_BASE+VI_HOR_START, VI_HOR_START_CCIR_NTSC_DEFAULT);
		mcu_WRITE_WORD(CBAR_BASE+VI_HOR_LEN, VI_HOR_LEN_CCIR_DEFAULT);
		}
		else {
		mcu_WRITE_WORD(CBAR_BASE+VI_HOR_START, VI_HOR_START_SQ_NTSC_DEFAULT);
		mcu_WRITE_WORD(CBAR_BASE+VI_HOR_LEN, VI_HOR_LEN_SQ_NTSC_DEFAULT);
		}
	mcu_WRITE(CBAR_BASE+VI_VERT_START, (UBYTE) VI_VERT_START_NTSC_DEFAULT);
	mcu_WRITE_WORD(CBAR_BASE+VI_VERT_LEN, VI_VERT_LEN_NTSC_DEFAULT);
	mcu_WRITE(CBAR_BASE+VI_FIELD_DELAY, (UBYTE) VI_FIELD_DELAY_NTSC_DEFAULT);
	}

 	VO_ODD_VERT_START_NTSC_DEFAULT=10 ;
	VO_EVEN_VERT_START_NTSC_DEFAULT=10 ;
	
VO_VERT_START_NTSC_DEFAULT =
    (VO_EVEN_VERT_START_NTSC_DEFAULT<<4|VO_ODD_VERT_START_NTSC_DEFAULT) ;
	VO_ODD_VERT_LEN_NTSC_DEFAULT=256 ;
	VO_EVEN_VERT_LEN_NTSC_DEFAULT=256 ;

	VO_ODD_VERT_START_PAL_DEFAULT=10 ;
	VO_EVEN_VERT_START_PAL_DEFAULT=9 ;

VO_VERT_START_PAL_DEFAULT =
	(VO_EVEN_VERT_START_PAL_DEFAULT<<4|VO_ODD_VERT_START_PAL_DEFAULT) ;

	VO_ODD_VERT_LEN_PAL_DEFAULT=306 ;
	VO_EVEN_VERT_LEN_PAL_DEFAULT=305 ;

	mcu_WRITE(CBAR_BASE+CBAR_VO_SRC, DATA_SRC_VI|SYNC_SRC_VI);
	mcu_WRITE(CBAR_BASE+CBAR_GALA_SRC, DATA_SRC_VI|SYNC_SRC_VI);
	mcu_WRITE(CBAR_BASE+CBAR_GALB_SRC, DATA_SRC_VI|SYNC_SRC_VI);
	mcu_WRITE(CBAR_BASE+CBAR_GALC_SRC, DATA_SRC_VI|SYNC_SRC_VI);


	if (pal) {
		mcu_WRITE(CBAR_BASE+VO_VERT_START,(UBYTE)VO_VERT_START_PAL_DEFAULT);
		mcu_WRITE_WORD(CBAR_BASE+VO_ODD_VERT_LEN,VO_ODD_VERT_LEN_PAL_DEFAULT);
		mcu_WRITE_WORD(CBAR_BASE+VO_EVEN_VERT_LEN,VO_EVEN_VERT_LEN_PAL_DEFAULT);
		}else{
		mcu_WRITE(CBAR_BASE+VO_VERT_START,(UBYTE)VO_VERT_START_NTSC_DEFAULT);
		mcu_WRITE_WORD(CBAR_BASE+VO_ODD_VERT_LEN,VO_ODD_VERT_LEN_NTSC_DEFAULT);
	   mcu_WRITE_WORD(CBAR_BASE+VO_EVEN_VERT_LEN,VO_EVEN_VERT_LEN_NTSC_DEFAULT);
		}

	VC_HOR_SYNC_START_CCIR_NTSC_DEFAULT = 138;
	VC_HOR_SYNC_START_CCIR_PAL_DEFAULT = 144;
	VC_HOR_LEN_CCIR_DEFAULT = 720;

	VC_HOR_SYNC_START_NTSC_DEFAULT = 140;
	VC_HOR_SYNC_START_PAL_DEFAULT = 176;
	VC_HOR_LEN_SQ_PAL_DEFAULT=768 ;
	VC_HOR_LEN_SQ_NTSC_DEFAULT=640 ;

	VC_EVEN_START_NTSC_DEFAULT=20;
	VC_ODD_START_NTSC_DEFAULT=19 ;
	VC_FIELD_LENGTH_NTSC_DEFAULT=243;

	VC_EVEN_START_PAL_DEFAULT=24 ;
	VC_ODD_START_PAL_DEFAULT=25 ;
	VC_FIELD_LENGTH_PAL_DEFAULT=288 ;

	mcu_WRITE(CBAR_BASE+CBAR_VC1_SRC, DATA_SRC_VI|SYNC_SRC_VI);

	if (pal) {
		if (ccir) {
		mcu_WRITE_WORD(CBAR_BASE+VC1_HOR_SYNC_START, VC_HOR_SYNC_START_PAL_DEFAULT);
		mcu_WRITE_WORD(CBAR_BASE+VC1_HOR_SYNC_LEN, VC_HOR_LEN_CCIR_DEFAULT);
		mcu_WRITE_WORD(CBAR_BASE+VC1_HOR_DATA_LEN, VC_HOR_LEN_CCIR_DEFAULT);
		}else{
		mcu_WRITE_WORD(CBAR_BASE+VC1_HOR_SYNC_START, VC_HOR_SYNC_START_PAL_DEFAULT);
		mcu_WRITE_WORD(CBAR_BASE+VC1_HOR_SYNC_LEN, VC_HOR_LEN_SQ_PAL_DEFAULT);
		mcu_WRITE_WORD(CBAR_BASE+VC1_HOR_DATA_LEN, VC_HOR_LEN_SQ_PAL_DEFAULT);
		}

	mcu_WRITE_WORD(CBAR_BASE+VC1_ODD_SYNC_START, VC_ODD_START_PAL_DEFAULT );
	mcu_WRITE_WORD(CBAR_BASE+VC1_ODD_DATA_START, VC_ODD_START_PAL_DEFAULT );

	mcu_WRITE_WORD(CBAR_BASE+ VC1_EVEN_SYNC_START, VC_EVEN_START_PAL_DEFAULT);
	mcu_WRITE_WORD(CBAR_BASE+ VC1_EVEN_DATA_START, VC_EVEN_START_PAL_DEFAULT);

	mcu_WRITE_WORD(CBAR_BASE+ VC1_ODD_SYNC_LEN, VC_FIELD_LENGTH_PAL_DEFAULT );
	mcu_WRITE_WORD(CBAR_BASE+ VC1_EVEN_SYNC_LEN, VC_FIELD_LENGTH_PAL_DEFAULT );
	mcu_WRITE_WORD(CBAR_BASE+ VC1_VERT_DATA_LEN, VC_FIELD_LENGTH_PAL_DEFAULT );
   }else {
		if (ccir) {
		mcu_WRITE_WORD(CBAR_BASE+VC1_HOR_SYNC_START, VC_HOR_SYNC_START_NTSC_DEFAULT);
		mcu_WRITE_WORD(CBAR_BASE+VC1_HOR_SYNC_LEN, VC_HOR_LEN_CCIR_DEFAULT);
		mcu_WRITE_WORD(CBAR_BASE+VC1_HOR_DATA_LEN, VC_HOR_LEN_CCIR_DEFAULT);
		}else{
		mcu_WRITE_WORD(CBAR_BASE+VC1_HOR_SYNC_START, VC_HOR_SYNC_START_NTSC_DEFAULT);
		mcu_WRITE_WORD(CBAR_BASE+VC1_HOR_SYNC_LEN, VC_HOR_LEN_SQ_NTSC_DEFAULT);
		mcu_WRITE_WORD(CBAR_BASE+VC1_HOR_DATA_LEN, VC_HOR_LEN_SQ_NTSC_DEFAULT);
		}

	mcu_WRITE_WORD(CBAR_BASE+VC1_ODD_SYNC_START, VC_ODD_START_NTSC_DEFAULT );
	mcu_WRITE_WORD(CBAR_BASE+VC1_ODD_DATA_START, VC_ODD_START_NTSC_DEFAULT );

	mcu_WRITE_WORD(CBAR_BASE+ VC1_EVEN_SYNC_START, VC_EVEN_START_NTSC_DEFAULT);
	mcu_WRITE_WORD(CBAR_BASE+ VC1_EVEN_DATA_START, VC_EVEN_START_NTSC_DEFAULT);

	mcu_WRITE_WORD(CBAR_BASE+ VC1_ODD_SYNC_LEN, VC_FIELD_LENGTH_NTSC_DEFAULT );
	mcu_WRITE_WORD(CBAR_BASE+ VC1_EVEN_SYNC_LEN, VC_FIELD_LENGTH_NTSC_DEFAULT );
	mcu_WRITE_WORD(CBAR_BASE+ VC1_VERT_DATA_LEN, VC_FIELD_LENGTH_NTSC_DEFAULT );
   }

	mcu_WRITE(CBAR_BASE+CBAR_VC1_SRC, SYNC_SRC_GALD|DATA_SRC_GALD);
	mcu_WRITE(CBAR_BASE+CBAR_GALC_SRC, SYNC_SRC_VC1|DATA_SRC_VC1);

	return 0;
}


cosmo2_const_cbar_setup()
{
	cosmo2_cbar_vivo_setup (0, 0);
	cosmo2_cbar_chan_setup (0, 0);
	
	mcu_WRITE(CBAR_BASE+CBAR_VO_SRC, SYNC_SRC_VC1|DATA_SRC_VC1);
	mcu_WRITE(CBAR_BASE+CBAR_VC1_SRC, SYNC_SRC_VI);

	return 0;
}
