
/*
 *
 * Cosmo2 gio 1 chip hardware definitions
 *
 * Copyright 1995, Silicon Graphics, Inc.
 * ALL RIGHTS RESERVED
 *
 * UNPUBLISHED -- Rights reserved under the copyright laws of the United
 * States.   Use of a copyright notice is precautionary only and does not
 * imply publication or disclosure.
 *
 * U.S. GOVERNMENT RESTRICTED RIGHTS LEGEND:
 * Use, duplication or disclosure by the Government is subject to restrictions
 * as set forth in FAR 52.227.19(c)(2) or subparagraph (c)(1)(ii) of the Rights
 * in Technical Data and Computer Software clause at DFARS 252.227-7013 and/or
 * in similar or successor clauses in the FAR, or the DOD or NASA FAR
 * Supplement.  Contractor/manufacturer is Silicon Graphics, Inc.,
 * 2011 N. Shoreline Blvd. Mountain View, CA 94039-7311.
 *
 * THE CONTENT OF THIS WORK CONTAINS CONFIDENTIAL AND PROPRIETARY
 * INFORMATION OF SILICON GRAPHICS, INC. ANY DUPLICATION, MODIFICATION,
 * DISTRIBUTION, OR DISCLOSURE IN ANY FORM, IN WHOLE, OR IN PART, IS STRICTLY
 * PROHIBITED WITHOUT THE PRIOR EXPRESS WRITTEN PERMISSION OF SILICON
 * GRAPHICS, INC.
 */


#include "cosmo2_defs.h"
#include "cosmo2_mcu_def.h"
#define _8bit_mask 0xff




name_tbl_t z050_1_t[] =  {
"Z50_GO2", 			Z50_GO + VIDCH1_050_BASE, 		1, _8bit_mask,
"Z50_HARDWARE2", 		Z50_HARDWARE + VIDCH1_050_BASE, 	1, _8bit_mask,
"Z50_MODE2", 			Z50_MODE + VIDCH1_050_BASE, 		1, _8bit_mask,
"Z50_OPTIIONS2", 		Z50_OPTIIONS + VIDCH1_050_BASE, 	1, _8bit_mask,
"Z50_MBCV2", 			Z50_MBCV + VIDCH1_050_BASE, 		1, _8bit_mask,
"Z50_MARKERS_EN2", 		Z50_MARKERS_EN + VIDCH1_050_BASE, 	1, _8bit_mask,
"Z50_INT_REQ_02", 		Z50_INT_REQ_0 + VIDCH1_050_BASE, 	1, _8bit_mask,
"Z50_INT_REQ_12", 		Z50_INT_REQ_1 + VIDCH1_050_BASE, 	1, _8bit_mask,
"Z50_TCV_NET2", 		Z50_TCV_NET_H + VIDCH1_050_BASE, 	4, _8bit_mask,
"Z50_TCV_NET_H2", 		Z50_TCV_NET_H + VIDCH1_050_BASE, 	1, _8bit_mask,
"Z50_TCV_NET_MH2", 		Z50_TCV_NET_MH + VIDCH1_050_BASE, 	1, _8bit_mask,
"Z50_TCV_NET_ML2", 		Z50_TCV_NET_ML + VIDCH1_050_BASE, 	1, _8bit_mask,
"Z50_TCV_NET_L2", 		Z50_TCV_NET_L + VIDCH1_050_BASE, 	1, _8bit_mask,
"Z50_TCV_DATA2", 		Z50_TCV_DATA_H + VIDCH1_050_BASE, 	4, _8bit_mask,
"Z50_TCV_DATA_H2", 		Z50_TCV_DATA_H + VIDCH1_050_BASE, 	1, _8bit_mask,
"Z50_TCV_DATA_MH2", 		Z50_TCV_DATA_MH + VIDCH1_050_BASE, 	1, _8bit_mask,
"Z50_TCV_DATA_ML2", 		Z50_TCV_DATA_ML + VIDCH1_050_BASE, 	1, _8bit_mask,
"Z50_TCV_DATA_L2", 		Z50_TCV_DATA_L + VIDCH1_050_BASE, 	1, _8bit_mask,
"Z50_SF2", 			Z50_SF_H + VIDCH1_050_BASE, 		2, _8bit_mask,
"Z50_SF_H2", 			Z50_SF_H + VIDCH1_050_BASE, 		1, _8bit_mask,
"Z50_SF_L2", 			Z50_SF_L + VIDCH1_050_BASE, 		1, _8bit_mask,
"Z50_AF2", 			Z50_AF_H + VIDCH1_050_BASE, 		3, _8bit_mask,
"Z50_AF_H2", 			Z50_AF_H + VIDCH1_050_BASE, 		1, _8bit_mask,
"Z50_AF_M2", 			Z50_AF_M + VIDCH1_050_BASE, 		1, _8bit_mask,
"Z50_AF_L2", 			Z50_AF_L + VIDCH1_050_BASE, 		1, _8bit_mask,
"Z50_ACV2", 			Z50_ACV_H + VIDCH1_050_BASE, 		4, _8bit_mask,
"Z50_ACV_H2", 			Z50_ACV_H + VIDCH1_050_BASE, 		1, _8bit_mask,
"Z50_ACV_MH2", 			Z50_ACV_MH + VIDCH1_050_BASE, 		1, _8bit_mask,
"Z50_ACV_ML2", 			Z50_ACV_ML + VIDCH1_050_BASE, 		1, _8bit_mask,
"Z50_ACV_L2", 			Z50_ACV_L + VIDCH1_050_BASE, 		1, _8bit_mask,
"Z50_ACT2", 			Z50_ACT_H + VIDCH1_050_BASE, 		4, _8bit_mask,
"Z50_ACT_H2", 			Z50_ACT_H + VIDCH1_050_BASE, 		1, _8bit_mask,
"Z50_ACT_MH2", 			Z50_ACT_MH + VIDCH1_050_BASE, 		1, _8bit_mask,
"Z50_ACT_ML2", 			Z50_ACT_ML + VIDCH1_050_BASE, 		1, _8bit_mask,
"Z50_ACT_L2", 			Z50_ACT_L + VIDCH1_050_BASE, 		1, _8bit_mask,
"Z50_ACV_TRUN2", 		Z50_ACV_TRUN_H + VIDCH1_050_BASE, 	4, _8bit_mask,
"Z50_ACV_TRUN_H2", 		Z50_ACV_TRUN_H + VIDCH1_050_BASE, 	1, _8bit_mask,
"Z50_ACV_TRUN_MH2", 		Z50_ACV_TRUN_MH + VIDCH1_050_BASE, 	1, _8bit_mask,
"Z50_ACV_TRUN_ML2", 		Z50_ACV_TRUN_ML + VIDCH1_050_BASE, 	1, _8bit_mask,
"Z50_ACV_TRUN_L2", 		Z50_ACV_TRUN_L + VIDCH1_050_BASE, 	1, _8bit_mask,
#if 0 
"Z50_STATUS_02", 		Z50_STATUS_0 + VIDCH1_050_BASE, 	1, _8bit_mask,
"Z50_STATUS_12", 		Z50_STATUS_1 + VIDCH1_050_BASE, 	1, _8bit_mask,
"Z50_COMPRESSED_DATA2", Z50_COMPRESSED_DATA + VIDCH1_050_BASE,	1, _8bit_mask,
#endif
"", 				0,				 	0, _8bit_mask,
};



name_tbl_t z050_2_t[] =  {
"Z50_GO2", 			Z50_GO + VIDCH2_050_BASE, 		1, _8bit_mask,
"Z50_HARDWARE2", 		Z50_HARDWARE + VIDCH2_050_BASE, 	1, _8bit_mask,
"Z50_MODE2", 			Z50_MODE + VIDCH2_050_BASE, 		1, _8bit_mask,
"Z50_OPTIIONS2", 		Z50_OPTIIONS + VIDCH2_050_BASE, 	1, _8bit_mask,
"Z50_MBCV2", 			Z50_MBCV + VIDCH2_050_BASE, 		1, _8bit_mask,
"Z50_MARKERS_EN2", 		Z50_MARKERS_EN + VIDCH2_050_BASE, 	1, _8bit_mask,
"Z50_INT_REQ_02", 		Z50_INT_REQ_0 + VIDCH2_050_BASE, 	1, _8bit_mask,
"Z50_INT_REQ_12", 		Z50_INT_REQ_1 + VIDCH2_050_BASE, 	1, _8bit_mask,
"Z50_TCV_NET2", 		Z50_TCV_NET_H + VIDCH2_050_BASE, 	4, _8bit_mask,
"Z50_TCV_NET_H2", 		Z50_TCV_NET_H + VIDCH2_050_BASE, 	1, _8bit_mask,
"Z50_TCV_NET_MH2", 		Z50_TCV_NET_MH + VIDCH2_050_BASE, 	1, _8bit_mask,
"Z50_TCV_NET_ML2", 		Z50_TCV_NET_ML + VIDCH2_050_BASE, 	1, _8bit_mask,
"Z50_TCV_NET_L2", 		Z50_TCV_NET_L + VIDCH2_050_BASE, 	1, _8bit_mask,
"Z50_TCV_DATA2", 		Z50_TCV_DATA_H + VIDCH2_050_BASE, 	4, _8bit_mask,
"Z50_TCV_DATA_H2", 		Z50_TCV_DATA_H + VIDCH2_050_BASE, 	1, _8bit_mask,
"Z50_TCV_DATA_MH2", 		Z50_TCV_DATA_MH + VIDCH2_050_BASE, 	1, _8bit_mask,
"Z50_TCV_DATA_ML2", 		Z50_TCV_DATA_ML + VIDCH2_050_BASE, 	1, _8bit_mask,
"Z50_TCV_DATA_L2", 		Z50_TCV_DATA_L + VIDCH2_050_BASE, 	1, _8bit_mask,
"Z50_SF2", 			Z50_SF_H + VIDCH2_050_BASE, 		2, _8bit_mask,
"Z50_SF_H2", 			Z50_SF_H + VIDCH2_050_BASE, 		1, _8bit_mask,
"Z50_SF_L2", 			Z50_SF_L + VIDCH2_050_BASE, 		1, _8bit_mask,
"Z50_AF2", 			Z50_AF_H + VIDCH2_050_BASE, 		3, _8bit_mask,
"Z50_AF_H2", 			Z50_AF_H + VIDCH2_050_BASE, 		1, _8bit_mask,
"Z50_AF_M2", 			Z50_AF_M + VIDCH2_050_BASE, 		1, _8bit_mask,
"Z50_AF_L2", 			Z50_AF_L + VIDCH2_050_BASE, 		1, _8bit_mask,
"Z50_ACV2", 			Z50_ACV_H + VIDCH2_050_BASE, 		4, _8bit_mask,
"Z50_ACV_H2", 			Z50_ACV_H + VIDCH2_050_BASE, 		1, _8bit_mask,
"Z50_ACV_MH2", 			Z50_ACV_MH + VIDCH2_050_BASE, 		1, _8bit_mask,
"Z50_ACV_ML2", 			Z50_ACV_ML + VIDCH2_050_BASE, 		1, _8bit_mask,
"Z50_ACV_L2", 			Z50_ACV_L + VIDCH2_050_BASE, 		1, _8bit_mask,
"Z50_ACT2", 			Z50_ACT_H + VIDCH2_050_BASE, 		4, _8bit_mask,
"Z50_ACT_H2", 			Z50_ACT_H + VIDCH2_050_BASE, 		1, _8bit_mask,
"Z50_ACT_MH2", 			Z50_ACT_MH + VIDCH2_050_BASE, 		1, _8bit_mask,
"Z50_ACT_ML2", 			Z50_ACT_ML + VIDCH2_050_BASE, 		1, _8bit_mask,
"Z50_ACT_L2", 			Z50_ACT_L + VIDCH2_050_BASE, 		1, _8bit_mask,
"Z50_ACV_TRUN2", 		Z50_ACV_TRUN_H + VIDCH2_050_BASE, 	4, _8bit_mask,
"Z50_ACV_TRUN_H2", 		Z50_ACV_TRUN_H + VIDCH2_050_BASE, 	1, _8bit_mask,
"Z50_ACV_TRUN_MH2", 		Z50_ACV_TRUN_MH + VIDCH2_050_BASE, 	1, _8bit_mask,
"Z50_ACV_TRUN_ML2", 		Z50_ACV_TRUN_ML + VIDCH2_050_BASE, 	1, _8bit_mask,
"Z50_ACV_TRUN_L2", 		Z50_ACV_TRUN_L + VIDCH2_050_BASE, 	1, _8bit_mask,
#if 0 
"Z50_STATUS_02", 		Z50_STATUS_0 + VIDCH2_050_BASE, 	1, _8bit_mask,
"Z50_STATUS_12", 		Z50_STATUS_1 + VIDCH2_050_BASE, 	1, _8bit_mask,
"Z50_COMPRESSED_DATA2",	Z50_COMPRESSED_DATA + VIDCH2_050_BASE,	1, _8bit_mask,
#endif
"", 				0,				 	0, _8bit_mask,
};

name_tbl_t fbc_1_t[] = {
"FBC_ID_REG1", 			FBC_ID_REG + VIDCH1_FBC_BASE, 		1, 	ID_CODE_MASK,
"FBC_INT_EN1", 			FBC_INT_EN + VIDCH1_FBC_BASE, 		1, 	
			IRQ_050|LOCAL_DONE_IRQ |
			VIDEO_DONE_IRQ         |
			UPC_DONE_IRQ           |
			FIFO_02_EMPTY_IRQ      |
			FIFO_13_EMPTY_IRQ,
"FBC_INT_STAT1", 		FBC_INT_STAT + VIDCH1_FBC_BASE, 	1, 	0x0,
"FBC_STATUS1", 			FBC_STATUS + VIDCH1_FBC_BASE, 		1, 	0x0,
"FBC_FLOW1", 			FBC_FLOW + VIDCH1_FBC_BASE, 		1, 
		DATA_FLOW_MODE_MASK | FB_WR_EN | FIELD_SELECT | VIDEO_CONSTANT_EN,
"FBC_MAIN1", 			FBC_MAIN + VIDCH1_FBC_BASE, 		1, 	
		GP1 | GP2 | VIDEO_EN | VIDEO_PAD_EN | UC_PAD_EN | C_PAD_EN,

"FBC_H_ACTIVE_START1", 	FBC_H_ACTIVE_START + VIDCH1_FBC_BASE, 	1, 	_5bit_mask,
"FBC_H_ACTIVE_START1", 	FBC_H_ACTIVE_START + VIDCH1_FBC_BASE+1,	1, 	_8bit_mask,
"FBC_H_ACTIVEG_END1", 	FBC_H_ACTIVEG_END + VIDCH1_FBC_BASE, 	1, 	_5bit_mask,
"FBC_H_ACTIVEG_END1", 	FBC_H_ACTIVEG_END + VIDCH1_FBC_BASE+1, 	1, 	_8bit_mask,
"FBC_H_PADDING_END1", 	FBC_H_PADDING_END + VIDCH1_FBC_BASE, 	1, 	_5bit_mask,
"FBC_H_PADDING_END1", 	FBC_H_PADDING_END + VIDCH1_FBC_BASE+1, 	1, 	_8bit_mask,
"FBC_H_BLANKING_END1", 	FBC_H_BLANKING_END + VIDCH1_FBC_BASE, 	1, 	_5bit_mask,
"FBC_H_BLANKING_END1", 	FBC_H_BLANKING_END + VIDCH1_FBC_BASE+1,	1, 	_8bit_mask,
"FBC_V_ACTIVE_START1",	FBC_V_ACTIVE_START + VIDCH1_FBC_BASE, 	1, 	_5bit_mask,
"FBC_V_ACTIVE_START1",	FBC_V_ACTIVE_START + VIDCH1_FBC_BASE+1,	1, 	_8bit_mask,
"FBC_V_ACTIVEG_END1", 	FBC_V_ACTIVEG_END + VIDCH1_FBC_BASE, 	1, 	_5bit_mask,
"FBC_V_ACTIVEG_END1", 	FBC_V_ACTIVEG_END + VIDCH1_FBC_BASE+1, 	1, 	_8bit_mask,
"FBC_V_PADDING_END1", 	FBC_V_PADDING_END + VIDCH1_FBC_BASE, 	1, 	_5bit_mask,
"FBC_V_PADDING_END1", 	FBC_V_PADDING_END + VIDCH1_FBC_BASE+1, 	1, 	_8bit_mask,
"FBC_V_BLANKING_END1", 	FBC_V_BLANKING_END + VIDCH1_FBC_BASE, 	1, 	_5bit_mask,
"FBC_V_BLANKING_END1", 	FBC_V_BLANKING_END + VIDCH1_FBC_BASE+1,	1, 	_8bit_mask,
"FBC_Y_PAD1", 			FBC_Y_PAD + VIDCH1_FBC_BASE, 		1, 	_8bit_mask,
"FBC_U_PAD1", 			FBC_U_PAD + VIDCH1_FBC_BASE, 		1, 	_8bit_mask,
"FBC_V_PAD1", 			FBC_V_PAD + VIDCH1_FBC_BASE, 		1, 	_8bit_mask,
"FBC_VERT_CLIP_END1", 		FBC_VERT_CLIP_END + VIDCH1_FBC_BASE, 	1, 	_8bit_mask,
"", 0, 0, _8bit_mask,
}; 

name_tbl_t fbc_2_t[] = {
"FBC_ID_REG2", 			FBC_ID_REG + VIDCH2_FBC_BASE, 		1, 	ID_CODE_MASK,
"FBC_INT_EN2", 			FBC_INT_EN + VIDCH2_FBC_BASE, 		1, 	
	IRQ_050|LOCAL_DONE_IRQ|VIDEO_DONE_IRQ|UPC_DONE_IRQ |FIFO_02_EMPTY_IRQ,
"FBC_INT_STAT2", 		FBC_INT_STAT + VIDCH2_FBC_BASE, 	1, 	FBC_INT_STAT,
"FBC_STATUS2", 			FBC_STATUS + VIDCH2_FBC_BASE, 		1, 	
	VIDEO_BLANK_MASK | EVEN_FIELD_MASK,
"FBC_FLOW2", 			FBC_FLOW + VIDCH2_FBC_BASE, 		1, 	
	DATA_FLOW_MODE_MASK | FB_WR_EN | FIELD_SELECT | VIDEO_CONSTANT_EN,
"FBC_MAIN2", 			FBC_MAIN + VIDCH2_FBC_BASE, 		1, 	
	GP1 | GP2 | VIDEO_EN | GO | VIDEO_PAD_EN | UC_PAD_EN | C_PAD_EN,

"FBC_H_ACTIVE_START2",  FBC_H_ACTIVE_START + VIDCH2_FBC_BASE,   1,  _5bit_mask,
"FBC_H_ACTIVE_START2",  FBC_H_ACTIVE_START + VIDCH2_FBC_BASE+1, 1,  _8bit_mask,
"FBC_H_ACTIVEG_END2",   FBC_H_ACTIVEG_END + VIDCH2_FBC_BASE,    1,  _5bit_mask,
"FBC_H_ACTIVEG_END2",   FBC_H_ACTIVEG_END + VIDCH2_FBC_BASE+1,  1,  _8bit_mask,
"FBC_H_PADDING_END2",   FBC_H_PADDING_END + VIDCH2_FBC_BASE,    1,  _5bit_mask,
"FBC_H_PADDING_END2",   FBC_H_PADDING_END + VIDCH2_FBC_BASE+1,  1,  _8bit_mask,
"FBC_H_BLANKING_END2",  FBC_H_BLANKING_END + VIDCH2_FBC_BASE,   1,  _5bit_mask,
"FBC_H_BLANKING_END2",  FBC_H_BLANKING_END + VIDCH2_FBC_BASE+1, 1,  _8bit_mask,
"FBC_V_ACTIVE_START2",  FBC_V_ACTIVE_START + VIDCH2_FBC_BASE,   1,  _5bit_mask,
"FBC_V_ACTIVE_START2",  FBC_V_ACTIVE_START + VIDCH2_FBC_BASE+1, 1,  _8bit_mask,
"FBC_V_ACTIVEG_END2",   FBC_V_ACTIVEG_END + VIDCH2_FBC_BASE,    1,  _5bit_mask,
"FBC_V_ACTIVEG_END2",   FBC_V_ACTIVEG_END + VIDCH2_FBC_BASE+1,  1,  _8bit_mask,
"FBC_V_PADDING_END2",   FBC_V_PADDING_END + VIDCH2_FBC_BASE,    1,  _5bit_mask,
"FBC_V_PADDING_END2",   FBC_V_PADDING_END + VIDCH2_FBC_BASE+1,  1,  _8bit_mask,
"FBC_V_BLANKING_END2",  FBC_V_BLANKING_END + VIDCH2_FBC_BASE,   1,  _5bit_mask,
"FBC_V_BLANKING_END2",  FBC_V_BLANKING_END + VIDCH2_FBC_BASE+1, 1,  _8bit_mask,
"FBC_Y_PAD2",           FBC_Y_PAD + VIDCH2_FBC_BASE,        1,  _8bit_mask,
"FBC_U_PAD2",           FBC_U_PAD + VIDCH2_FBC_BASE,        1,  _8bit_mask,
"FBC_V_PAD2",           FBC_V_PAD + VIDCH2_FBC_BASE,        1,  _8bit_mask,
"FBC_VERT_CLIP_END2",   FBC_VERT_CLIP_END + VIDCH2_FBC_BASE,    1,  _8bit_mask,
"",0, 0, _8bit_mask,
};


name_tbl_t upc_1_t[] = {
"UPC_FLOW_CONTROL1", 		UPC_FLOW_CONTROL + VIDCH1_UPC_BASE, 		1, 	0x77, 
"UPC_GENESIS_ACCESS1", 		UPC_GENESIS_ACCESS + VIDCH1_UPC_BASE, 		1, 	0x3,
"UPC_PIXEL_PER_LINE_REG1", 	UPC_PIXEL_PER_LINE_REG + VIDCH1_UPC_BASE, 	1, 	0x1f,
"UPC_PIXEL_PER_LINE_REG1", 	UPC_PIXEL_PER_LINE_REG + 1 + VIDCH1_UPC_BASE, 	1, 	0xff,
"UPC_GENESIS_OUT_HRES1", 	UPC_GENESIS_OUT_HRES +  VIDCH1_UPC_BASE, 	1, 	0x7,
"UPC_GENESIS_OUT_HRES1", 	UPC_GENESIS_OUT_HRES + 1 + VIDCH1_UPC_BASE, 	1, 	0xff,
"UPC_GENESIS_OUT_VRES1", 	UPC_GENESIS_OUT_VRES +  VIDCH1_UPC_BASE, 	1, 	0x1f,
"UPC_GENESIS_OUT_HRES1", 	UPC_GENESIS_OUT_HRES + 1 + VIDCH1_UPC_BASE, 	1, 	0xff,
"", 0, 0, _8bit_mask,
};


name_tbl_t upc_2_t[] = {
"UPC_FLOW_CONTROL2", 		UPC_FLOW_CONTROL + VIDCH2_UPC_BASE,			1, 0x77,
"UPC_GENESIS_ACCESS2", 		UPC_GENESIS_ACCESS + VIDCH2_UPC_BASE, 		1, 	0x3,
"UPC_PIXEL_PER_LINE_REG2", 	UPC_PIXEL_PER_LINE_REG + VIDCH2_UPC_BASE,	1, 	0x1f,
"UPC_PIXEL_PER_LINE_REG2", 	UPC_PIXEL_PER_LINE_REG + 1 + VIDCH2_UPC_BASE, 	1, 	0xff,
"UPC_GENESIS_OUT_HRES2", 	UPC_GENESIS_OUT_HRES +  VIDCH2_UPC_BASE, 	1, 	0x7,
"UPC_GENESIS_OUT_HRES2", 	UPC_GENESIS_OUT_HRES + 1 + VIDCH2_UPC_BASE, 	1, 	0xff,
"UPC_GENESIS_OUT_VRES2", 	UPC_GENESIS_OUT_VRES +  VIDCH2_UPC_BASE, 	1, 	0x1f,
"UPC_GENESIS_OUT_VRES2", 	UPC_GENESIS_OUT_VRES + 1 + VIDCH2_UPC_BASE, 	1, 	0xff,
"", 0, 0,  _8bit_mask,
};

name_tbl_t cpc_1_t[] = {
"CPC_JPEG_VERT_RESH", 	CPC_JPEG_VERT_RES + VIDCH1_CPC_BASE, 	1, 	0xff,
"CPC_JPEG_VERT_RESL", 	CPC_JPEG_VERT_RES + VIDCH1_CPC_BASE + 1,1, 	0xff,
"CPC_JPEG_HOR_RESH", 	CPC_JPEG_HOR_RES + VIDCH1_CPC_BASE, 	1, 	0xff, 
"CPC_JPEG_HOR_RESL", 	CPC_JPEG_HOR_RES + VIDCH1_CPC_BASE+1, 	1, 	0xff, 

#if 0
"CPC_STRIP_COUNT", , 0xff,
#endif

"CPC_CTL_STATUS1", CPC_CTL_STATUS + VIDCH1_CPC_BASE, 1, 0x47,
"", 0, 0,
};

name_tbl_t cpc_2_t[] = {
"CPC_JPEG_VERT_RESH", 	CPC_JPEG_VERT_RES + VIDCH2_CPC_BASE, 	1, 	0xff,
"CPC_JPEG_VERT_RESL", 	CPC_JPEG_VERT_RES + VIDCH2_CPC_BASE + 1,1,  	0xff,
"CPC_JPEG_HOR_RESH", 	CPC_JPEG_HOR_RES + VIDCH2_CPC_BASE, 	1,  	0xff,
"CPC_JPEG_HOR_RESL", 	CPC_JPEG_HOR_RES + VIDCH2_CPC_BASE + 1, 1,  	0xff,
"CPC_CTL_STATUS2", 	CPC_CTL_STATUS + VIDCH2_CPC_BASE, 	1,  	0x47,
"",0, 0,  _8bit_mask,
};

name_tbl_t z016_1_t[] = {
"Z16_GO_STOP_REG1", 	Z16_GO_STOP_REG + VIDCH1_016_BASE, 	1,  	_8bit_mask,
"Z16_MODE_REG1", 	Z16_MODE_REG + VIDCH1_016_BASE, 	1,  	_8bit_mask,
"Z16_ADDR_PTR_REG1", 	Z16_ADDR_PTR_REG + VIDCH1_016_BASE, 	1,  	_8bit_mask,
"Z16_INDIR_DATA_REG1", 	Z16_INDIR_DATA_REG + VIDCH1_016_BASE, 	1,  	_8bit_mask,
"",			0,					0,  	_8bit_mask,
};

name_tbl_t z016_2_t[] = {
"Z16_GO_STOP_REG2", 		Z16_GO_STOP_REG + VIDCH2_016_BASE, 	1,  _8bit_mask,
"Z16_MODE_REG2", 		Z16_MODE_REG + VIDCH2_016_BASE, 	1,  _8bit_mask,
"Z16_ADDR_PTR_REG2", 		Z16_ADDR_PTR_REG + VIDCH2_016_BASE, 	1,  _8bit_mask,
"Z16_INDIR_DATA_REG2", 		Z16_INDIR_DATA_REG + VIDCH2_016_BASE, 	1,  _8bit_mask,
"",0, 0,  _8bit_mask,
};

name_tbl_t cbar_t[] = {
#if 0
"CBAR_SOFTRESET", 		CBAR_SOFTRESET + CBAR_BASE, 			1,  0x1,
#endif
"CBAR_VO_SRC", 			CBAR_VO_SRC + CBAR_BASE, 				1,  0x3f,
"CBAR_VC1_SRC", 		CBAR_VC1_SRC + CBAR_BASE, 				1,  0x3f,
"CBAR_VC2_SRC", 		CBAR_VC2_SRC + CBAR_BASE, 				1,  0x3f,
"CBAR_GALA_SRC", 		CBAR_GALA_SRC + CBAR_BASE, 				1,  0x3f,
"CBAR_GALB_SRC", 		CBAR_GALB_SRC + CBAR_BASE, 				1,  0x3f,
"CBAR_GALC_SRC", 		CBAR_GALC_SRC + CBAR_BASE, 				1,  0x3f,
"CBAR_GALA_RND_MOD", 	CBAR_GALA_RND_MOD + CBAR_BASE, 			1,  0x7,
"CBAR_GALB_RND_MOD", 	CBAR_GALB_RND_MOD + CBAR_BASE, 			1,  0x7,
"CBAR_GALD_RND_MOD", 	CBAR_GALD_RND_MOD + CBAR_BASE, 			1,  0x7,

"VI_HOR_START", 		VI_HOR_START + CBAR_BASE, 				1,  0x3,
"VI_HOR_START", 		VI_HOR_START + CBAR_BASE + 1, 			1,  _8bit_mask,

"VI_HOR_LEN", 			VI_HOR_LEN + CBAR_BASE, 				1,  0x3,
"VI_HOR_LEN", 			VI_HOR_LEN + CBAR_BASE + 1, 			1,  _8bit_mask,

"VI_VERT_START", 		VI_VERT_START + CBAR_BASE, 				1,  _8bit_mask,

"VI_VERT_LEN", 			VI_VERT_LEN + CBAR_BASE, 				1,  0x1,
"VI_VERT_LEN", 			VI_VERT_LEN + CBAR_BASE+1, 				1,  _8bit_mask,

"VI_FIELD_DELAY", 		VI_FIELD_DELAY + CBAR_BASE, 			1,  _8bit_mask,
"VO_VERT_START", 		VO_VERT_START + CBAR_BASE, 				1,  _8bit_mask,

"VO_ODD_VERT_LEN", 		VO_ODD_VERT_LEN + CBAR_BASE, 			1, 	0x1,
"VO_ODD_VERT_LEN", 		VO_ODD_VERT_LEN + CBAR_BASE + 1, 		1, 	_8bit_mask,

"VO_EVEN_VERT_LEN", 		VO_EVEN_VERT_LEN + CBAR_BASE, 		1,  0x1,
"VO_EVEN_VERT_LEN", 		VO_EVEN_VERT_LEN + CBAR_BASE + 1, 	1,  _8bit_mask,

"VC1_HOR_SYNC_START", 		VC1_HOR_SYNC_START + CBAR_BASE, 	1,  0x3,
"VC1_HOR_SYNC_START", 		VC1_HOR_SYNC_START + CBAR_BASE + 1, 1,  _8bit_mask,

"VC1_HOR_SYNC_LEN", 		VC1_HOR_SYNC_LEN + CBAR_BASE, 		1,  0x3,
"VC1_HOR_SYNC_LEN", 		VC1_HOR_SYNC_LEN + CBAR_BASE + 1, 	1,  _8bit_mask,

"VC1_ODD_SYNC_START", 		VC1_ODD_SYNC_START + CBAR_BASE, 	1,  0x3,
"VC1_ODD_SYNC_START", 		VC1_ODD_SYNC_START + CBAR_BASE + 1, 1,  _8bit_mask,

"VC1_ODD_SYNC_LEN", 		VC1_ODD_SYNC_LEN + CBAR_BASE, 		1,  0x3,
"VC1_ODD_SYNC_LEN", 		VC1_ODD_SYNC_LEN + CBAR_BASE + 1, 	1,  _8bit_mask,

"VC1_EVEN_SYNC_START", 		VC1_EVEN_SYNC_START + CBAR_BASE, 	1,  0x3,
"VC1_EVEN_SYNC_START", 		VC1_EVEN_SYNC_START + CBAR_BASE + 1,1,  _8bit_mask,

"VC1_EVEN_SYNC_LEN", 		VC1_EVEN_SYNC_LEN + CBAR_BASE, 		1,  0x3,
"VC1_EVEN_SYNC_LEN", 		VC1_EVEN_SYNC_LEN + CBAR_BASE + 1, 	1,  _8bit_mask,

"VC1_ODD_DATA_START", 		VC1_ODD_DATA_START + CBAR_BASE, 	1,  0x3,
"VC1_ODD_DATA_START", 		VC1_ODD_DATA_START + CBAR_BASE + 1, 1,  _8bit_mask,

"VC1_EVEN_DATA_START", 		VC1_EVEN_DATA_START + CBAR_BASE, 	1,  0x3,
"VC1_EVEN_DATA_START", 		VC1_EVEN_DATA_START + CBAR_BASE + 1,1,  _8bit_mask,

"VC1_HOR_DATA_LEN", 		VC1_HOR_DATA_LEN + CBAR_BASE, 		1,  0x3,
"VC1_HOR_DATA_LEN", 		VC1_HOR_DATA_LEN + CBAR_BASE + 1, 	1,  _8bit_mask,

"VC1_VERT_DATA_LEN", 		VC1_VERT_DATA_LEN + CBAR_BASE, 		1,  0x3,
"VC1_VERT_DATA_LEN", 		VC1_VERT_DATA_LEN + CBAR_BASE + 1, 	1,  _8bit_mask,

"VC2_HOR_SYNC_START", 		VC2_HOR_SYNC_START + CBAR_BASE, 	1,  0x3,
"VC2_HOR_SYNC_START", 		VC2_HOR_SYNC_START + CBAR_BASE + 1, 1,  _8bit_mask,

"VC2_HOR_SYNC_LEN", 		VC2_HOR_SYNC_LEN + CBAR_BASE, 		1,  0x3,
"VC2_HOR_SYNC_LEN", 		VC2_HOR_SYNC_LEN + CBAR_BASE + 1, 	1,  _8bit_mask,

"VC2_ODD_SYNC_START", 		VC2_ODD_SYNC_START + CBAR_BASE, 	1,  0x3,
"VC2_ODD_SYNC_START", 		VC2_ODD_SYNC_START + CBAR_BASE + 1,	1,  _8bit_mask,

"VC2_ODD_SYNC_LEN", 		VC2_ODD_SYNC_LEN + CBAR_BASE, 		1,  0x3,
"VC2_ODD_SYNC_LEN", 		VC2_ODD_SYNC_LEN + CBAR_BASE + 1, 	1,  _8bit_mask,

"VC2_EVEN_SYNC_START", 		VC2_EVEN_SYNC_START + CBAR_BASE, 	1,  0x3,
"VC2_EVEN_SYNC_START", 		VC2_EVEN_SYNC_START + CBAR_BASE + 1,1,  _8bit_mask,

"VC2_EVEN_SYNC_LEN", 		VC2_EVEN_SYNC_LEN + CBAR_BASE, 		1,  0x3,
"VC2_EVEN_SYNC_LEN", 		VC2_EVEN_SYNC_LEN + CBAR_BASE + 1, 	1,  _8bit_mask,

"VC2_ODD_DATA_START", 		VC2_ODD_DATA_START + CBAR_BASE, 	1,  0x3,
"VC2_ODD_DATA_START", 		VC2_ODD_DATA_START + CBAR_BASE + 1, 1,  _8bit_mask,

"VC2_EVEN_DATA_START", 		VC2_EVEN_DATA_START + CBAR_BASE, 	1,  0x3,
"VC2_EVEN_DATA_START", 		VC2_EVEN_DATA_START + CBAR_BASE + 1,1,  _8bit_mask,

"VC2_HOR_DATA_LEN", 		VC2_HOR_DATA_LEN + CBAR_BASE, 		1,  0x3,
"VC2_HOR_DATA_LEN", 		VC2_HOR_DATA_LEN + CBAR_BASE + 1, 	1,  _8bit_mask,

"VC2_VERT_DATA_LEN", 		VC2_VERT_DATA_LEN + CBAR_BASE, 		1,  0x3,
"VC2_VERT_DATA_LEN", 		VC2_VERT_DATA_LEN + CBAR_BASE + 1, 	1,  _8bit_mask,
"", 0, 0,  _8bit_mask,
};


name_tbl_t scaler_1_t[] = {
"GEN_Y_VERT_SRC_L", GEN_Y_VERT_SRC_L + VIDCH1_GENESIS_BASE,		1, _8bit_mask, 
"GEN_Y_VERT_SRC_H", GEN_Y_VERT_SRC_H + VIDCH1_GENESIS_BASE,		1, _4bit_mask, 
"GEN_Y_HOR_SRC_L", 	GEN_Y_HOR_SRC_L + VIDCH1_GENESIS_BASE, 		1, _8bit_mask, 
"GEN_Y_HOR_SRC_H", 	GEN_Y_HOR_SRC_H + VIDCH1_GENESIS_BASE, 		1, _4bit_mask, 
"GEN_Y_VERT_TARG_L",GEN_Y_VERT_TARG_L + VIDCH1_GENESIS_BASE,	1, _8bit_mask, 
"GEN_Y_VERT_TARG_H",GEN_Y_VERT_TARG_H + VIDCH1_GENESIS_BASE, 	1, _4bit_mask, 
"GEN_Y_HOR_TARG_L",	GEN_Y_HOR_TARG_L + VIDCH1_GENESIS_BASE,		1, _8bit_mask, 
"GEN_Y_HOR_TARG_H",	GEN_Y_HOR_TARG_H + VIDCH1_GENESIS_BASE, 	1, _4bit_mask, 
"GEN_UV_VERT_SRC_L",GEN_UV_VERT_SRC_L + VIDCH1_GENESIS_BASE, 	1, _8bit_mask, 
"GEN_UV_VERT_SRC_H",GEN_UV_VERT_SRC_H + VIDCH1_GENESIS_BASE, 		1, _4bit_mask, 
"GEN_UV_HOR_SRC_L",	GEN_UV_HOR_SRC_L + VIDCH1_GENESIS_BASE, 		1, _8bit_mask, 
"GEN_UV_HOR_SRC_H",	GEN_UV_HOR_SRC_H + VIDCH1_GENESIS_BASE, 		1, _4bit_mask, 
"GEN_UV_VERT_TARG_L", 		GEN_UV_VERT_TARG_L + VIDCH1_GENESIS_BASE, 		1, _8bit_mask, 
"GEN_UV_VERT_TARG_H", 		GEN_UV_VERT_TARG_H + VIDCH1_GENESIS_BASE, 		1, _4bit_mask, 
"GEN_UV_HOR_TARG_L", 		GEN_UV_HOR_TARG_L + VIDCH1_GENESIS_BASE, 		1, _8bit_mask, 
"GEN_UV_HOR_TARG_H", 		GEN_UV_HOR_TARG_H + VIDCH1_GENESIS_BASE, 		1, _4bit_mask, 
"GEN_VBLANK_ODD", 		GEN_VBLANK_ODD + VIDCH1_GENESIS_BASE, 				1, _8bit_mask, 
"GEN_VBLANK_EVEN", 		GEN_VBLANK_EVEN + VIDCH1_GENESIS_BASE, 				1, _8bit_mask, 
"", 0, 0,  _8bit_mask,
};



name_tbl_t scaler_2_t[] = {
"GEN_Y_VERT_SRC_L", 		GEN_Y_VERT_SRC_L + VIDCH2_GENESIS_BASE, 		1, _8bit_mask, 
"GEN_Y_VERT_SRC_H", 		GEN_Y_VERT_SRC_H + VIDCH2_GENESIS_BASE, 		1, _4bit_mask, 
"GEN_Y_HOR_SRC_L", 		GEN_Y_HOR_SRC_L + VIDCH2_GENESIS_BASE, 				1, _8bit_mask, 
"GEN_Y_HOR_SRC_H", 		GEN_Y_HOR_SRC_H + VIDCH2_GENESIS_BASE, 				1, _4bit_mask, 
"GEN_Y_VERT_TARG_L", 		GEN_Y_VERT_TARG_L + VIDCH2_GENESIS_BASE, 		1, _8bit_mask, 
"GEN_Y_VERT_TARG_H", 		GEN_Y_VERT_TARG_H + VIDCH2_GENESIS_BASE, 		1, _4bit_mask, 
"GEN_Y_HOR_TARG_L", 		GEN_Y_HOR_TARG_L + VIDCH2_GENESIS_BASE, 		1, _8bit_mask, 
"GEN_Y_HOR_TARG_H", 		GEN_Y_HOR_TARG_H + VIDCH2_GENESIS_BASE, 		1, _4bit_mask, 
"GEN_UV_VERT_SRC_L", 		GEN_UV_VERT_SRC_L + VIDCH2_GENESIS_BASE, 		1, _8bit_mask, 
"GEN_UV_VERT_SRC_H", 		GEN_UV_VERT_SRC_H + VIDCH2_GENESIS_BASE, 		1, _4bit_mask, 
"GEN_UV_HOR_SRC_L", 		GEN_UV_HOR_SRC_L + VIDCH2_GENESIS_BASE, 		1, _8bit_mask, 
"GEN_UV_HOR_SRC_H", 		GEN_UV_HOR_SRC_H + VIDCH2_GENESIS_BASE, 		1, _4bit_mask, 
"GEN_UV_VERT_TARG_L", 		GEN_UV_VERT_TARG_L + VIDCH2_GENESIS_BASE, 		1, _8bit_mask, 
"GEN_UV_VERT_TARG_H", 		GEN_UV_VERT_TARG_H + VIDCH2_GENESIS_BASE, 		1, _4bit_mask, 
"GEN_UV_HOR_TARG_L", 		GEN_UV_HOR_TARG_L + VIDCH2_GENESIS_BASE, 		1, _8bit_mask, 
"GEN_UV_HOR_TARG_H", 		GEN_UV_HOR_TARG_H + VIDCH2_GENESIS_BASE, 		1, _4bit_mask, 
"GEN_VBLANK_ODD", 		GEN_VBLANK_ODD + VIDCH2_GENESIS_BASE, 			1, _8bit_mask, 
"GEN_VBLANK_EVEN", 		GEN_VBLANK_EVEN + VIDCH2_GENESIS_BASE, 			1, _8bit_mask, 
"", 0, 0,  _8bit_mask,
};

name_tbl_t misc_t[] = {
"PORT0BASE", 0xFFFA4c, 2, 0xffff, 
"PORT0OPTS", 0xFFFA4e, 2, 0xffff,
"PORT1BASE", 0xFFFA50, 2, 0xffff,
"PORT1OPTS", 0xFFFA52, 2, 0xffff,
"PORT2BASE", 0xFFFA54, 2, 0xffff,
"PORT2OPTS", 0xFFFA56, 2, 0xffff,
"PORT3BASE", 0xFFFA58, 2, 0xffff,
"PORT3OPTS", 0xFFFA5a, 2, 0xffff,
"PORT4BASE", 0xFFFA5c, 2, 0xffff,
"PORT4OPTS", 0xFFFA5e, 2, 0xffff,
"PORT5BASE", 0xFFFA60, 2, 0xffff,
"PORT5OPTS", 0xFFFA62, 2, 0xffff,
"PORT6BASE", 0xFFFA64, 2, 0xffff,
"PORT6OPTS", 0xFFFA66, 2, 0xffff,
"PORT7BASE", 0xFFFA68, 2, 0xffff,
"PORT7OPTS", 0xFFFA6A, 2, 0xffff,
"PORT8BASE", 0xFFFA6c, 2, 0xffff,
"PORT8OPTS", 0xFFFA6e, 2, 0xffff,
"PORT9BASE", 0xFFFA70, 2, 0xffff,
"PORT9OPTS", 0xFFFA72, 2, 0xffff,
"PORT10BASE", 0xFFFA74, 2, 0xffff,
"PORT10OPTS", 0xFFFA76, 2, 0xffff,
"IIC_DATA", IIC_DATA, 1, 0xff,
"IIC_S1", IIC_S1, 1, 0xff,
"QSM", QSM, 1, 0xff,
"PORTQS", PORTQS, 2, 0xffff,
"PORTPQSPAR", PORTPQSPAR, 1, 0xff,
"DDRQS", DDRQS, 1, 0xff,
"SCCCR1", SCCCR1, 2, 0xffff,
"PORTF0", 0xfffa19, 1, 0xff,
"PORTF1", 0xfffa1b, 1, 0xff,
"PWMC", 0xfff925, 1, 0xff,
};
