.\"macro stdmacro
.TH BOOTPARAMS 4
.SH NAME
bootparams \- boot parameter data base
.SH SYNOPSIS
.B /etc/bootparams
.SH DESCRIPTION
.LP
The
.I bootparams
file contains the list of client entries that diskless clients use for booting.
For each diskless client the entry should contain the following information:
.LP
.nf
	name of client
	a list of keys, names of servers, and pathnames.
.fi
.LP
The first item of each entry is the name of the diskless client. The
subsequent item is a list of keys, names of servers, and pathnames.
.LP
Items are separated by
.SM TAB
or
.SM SPACE
characters. 
Any text after the # character is ignored.
.SH EXAMPLE
.LP
Here is an example of the
.I /etc/bootparams
file:
.sp
.ft 3
.nf
# Entries for "irisclient"
irisclient	root=myserver:/nfs/root/irisclient \e
		share=myserver:/nfs/share/iris \e
		swap=myserver:/nfs/swap/irisclient
.\"sunclient	root=myserver:/nfs/root/sunclient \e
.\"		swap=myserver:/nfs/swap/sunclient \e
.\"		dump=myserver:/nfs/dump/sunclient
.fi
.SH FILES
/etc/bootparams
.PD
.SH "SEE ALSO"
bootparamd(1M)
