'\"macro stdmacro
.if n .pH g4.cftime @(#)cftime	31.2 of 1/16/87
.nr X
.if \nX=0 .ds x} CFTIME 4 "" "\&"
.if \nX=1 .ds x} CFTIME 4 ""
.if \nX=2 .ds x} CFTIME 4 "" "\&"
.if \nX=3 .ds x} CFTIME "" "" "\&"
.nr X
.if \nX=0 .ds x} \*(x} "" "" "\&"
.if \nX=1 .ds x} \*(x} "" ""
.if \nX=2 .ds x} \*(x} "" "" "\&"
.if \nX=3 .ds x} \*(x} "" "" "\&"
.TH \*(x}
.SH NAME
cftime \- language specific strings
.SH DESCRIPTION
The programmer can create one printable file per language.
These files must be kept in
a special directory /lib/cftime. If this directory does not exist,
the programmer should create it.  The contents of these files are:
.TP 10n
\(bu abbreviated month names ( in order )
.TP
\(bu month names ( in order )
.TP
\(bu abbreviated weekday names ( in order )
.TP
\(bu weekday names ( in order )
.TP
\(bu default strings that specify formats for local time (\f3%x\fP) and 
local date (\f3%X\fP).
.TP
\(bu default format for cftime, if the argument for cftime is zero or null.
.TP
\(bu AM (ante meridian) string
.TP
\(bu PM (post meridian) string
.PP
Each string is on a line by itself. All white space is significant.
The order of the strings in the above list
is the same order in which the strings appear in the file shown below.
.SH EXAMPLE
/lib/cftime/usa_english
.TP 10n
.PD 0
Jan
.TP
Feb
.TP
 ...
.TP
January
.TP
February
.TP
 ...
.TP
Sun
.TP
Mon
.TP
 ...
.TP
Sunday
.TP
Monday
.TP
 ...
.TP
%H:%M:%S
.TP
%m/%d/%y
.TP
%a %b %d %T %Z %Y
.TP
AM
.TP
PM
.PD
.SH FILES
/lib/cftime \- directory that contains the language specific printable files
(create it if it does not exist)
.SH "SEE ALSO"
ctime(3C)
.Ee
'\".so /pubs/tools/origin.att1
