'\"! tbl | mmdoc
'\"macro stdmacro
.if n .pH g4.cpio @(#)cpio	30.2 of 12/25/85
.nr X
.if \nX=0 .ds x} CPIO 4 "" "\&"
.if \nX=1 .ds x} CPIO 4 ""
.if \nX=2 .ds x} CPIO 4 "" "\&"
.if \nX=3 .ds x} CPIO "" "" "\&"
.TH \*(x}
.SH NAME
cpio \- format of cpio archive
.SH DESCRIPTION
.PP
The
.I header\^
structure, when the
.B \-c
option of
.IR cpio (1)
is not used, is:
.PP
.RS
.TS
l l l.
struct {
	short	h_magic,
		h_dev;
	ushort	h_ino,
		h_mode,
		h_uid,
		h_gid;
	short	h_nlink,
		h_rdev,
		h_mtime[2],
		h_namesize,
		h_filesize[2];
	char	h_name[h_namesize rounded to word];
} Hdr;
.TE
.RE
.PP
When the
.B \-c
option is used, the
.I header\^
information is described by:
.PP
.in +.25i
.nf
sscanf(Chdr,"%6lo%6lo%6llo%6lo%6lo%6lo%6lo%6lo%11lo%6o%11llo%s",
.in +.25i
&Hdr.h_magic, &Hdr.h_dev, &Hdr.h_ino, &Hdr.h_mode,
&Hdr.h_uid, &Hdr.h_gid, &Hdr.h_nlink, &Hdr.h_rdev,
&Hdr.g_mtime, &Hdr.h_namesize,&Hdr.h_filesize,Hdr.h_name);
.in -.5i
Other archive formats (e.g \fBustar\fP) use other sscanf strings.
.fi
The
contents
of each file are recorded in an element
of the array of varying length structures,
.IR archive ,
together with other items describing the file.
Every instance of 
.I h_magic\^
contains the constant 070707 (octal).
The items
.I h_dev\^
through 
.I h_mtime\^
have meanings explained in
.IR  stat (2).
The length of the null-terminated path name
.IR h_name ,
including the null byte,
is given by
.IR h_namesize .
.PP
The last record
of the
.I archive\^
always contains the name \s-1TRAILER!!!\s0.
Special files, directories, and the trailer are recorded
with 
.I
h_filesize
equal to zero.
.SH "SEE ALSO"
cpio(1), find(1),
stat(2)
.\"	@(#)cpio.4	6.2 of 10/20/83
.Ee
'\".so /pubs/tools/origin.att
