'\"macro stdmacro
.TH CSHRC 4
.SH NAME
cshrc \- system-wide csh initialization command file
.SH DESCRIPTION
The file
.B /etc/cshrc
contains a list of commands to be invoked whenever a user
logs into the system with \f2csh\f1(1)
as their login shell.
These commands are executed before those in the
.B .cshrc
and
.B .login
files in the home directory of the user.
.SH FILES
/etc/cshrc
.SH SEE ALSO
csh(1).
