.TH dbg 4
.SH NAME
dbg, debug \- the debug filesystem
.SH DESCRIPTION
The debug filesystem, historically mounted under \f2/debug\fP,
provides an interface to running processes.
.P
This interface has been made obsolete by the new
.IR proc (4)
interface which is mounted under \f2/proc\fP.
.I proc
provides more functionality, is easier to use, and
is the recommended interface for accessing a running processes.
.SH "SEE ALSO"
mntproc(1M),
proc(4).
