'\"macro stdmacro
.if n .pH g4.loginlog @(#)loginlog	40.10 of 1/3/91
.\" Copyright 1991 UNIX System Laboratories, Inc.
.\" Copyright 1989, 1990 AT&T
.nr X
.if \nX=0 .ds x} loginlog 4 "" "\&"
.if \nX=1 .ds x} loginlog 4 ""
.if \nX=2 .ds x} loginlog 4 "" "\&"
.if \nX=3 .ds x} loginlog "" "" "\&"
.TH \*(x}
.SH NAME
\f4loginlog\f1 \- log of failed login attempts
.SH DESCRIPTION
After five unsuccessful login attempts,
all the attempts are logged in the file
\f4/var/adm/loginlog\fP.
This file contains one record for each failed attempt.
Each record contains the login name,
tty specification,
and
time.
.PP
This is an
.SM ASCII
file.
Each field within each entry
is separated from the next by a colon.
Each entry is separated from the next by a new-line.
.PP
By default, \f4loginlog\f1 does not exist, so no logging is done.
To enable logging, the log file must be created with
read and write permission for owner only.
Owner must be \f4root\f1 and group must be \f4sys\f1.
.SH FILES
\f4/var/adm/loginlog\fP
.SH "SEE ALSO"
\f4login\fP(1), \f4passwd\fP(1)
.Ee
