'\"macro stdmacro
.TH MOTD 4
.SH NAME
motd \- message of the day
.SH DESCRIPTION
The file
.B /etc/motd
contains information intended to be displayed on the terminal
at login time.
For \f2sh\f1(1) users, this function is performed by the script
\f3/etc/profile\f1.
For \f2csh\f1(1) users, the \f3/etc/cshrc\f1 displays the contents
of the message of the day file.
.SH FILES
/etc/motd
.SH "SEE ALSO"
csh(1), login(1), sh(1), cshrc(4), profile(4).
