'\"macro stdmacro
.TH NETRC 4
.SH NAME
netrc \- ftp auto-login initialization file
.SH DESCRIPTION
The file
.B .netrc
is an ASCII file containing login and initialization information
used by the \f2ftp\f1(1C) auto-login process.
This file resides in the home directory of the user.
See the \f2ftp\f1(1C) man page for further information.
.SH FILES
$HOME/.netrc
.SH SEE ALSO
ftp(1C).
