'\"macro stdmacro
.if n .pH g4.NOSTICKYTMP @(#)NOSTICKYTMP	31.8 of 3/4/87
.nr X
.if \nX=0 .ds x} NOSTICKYTMP 4 ""  "\&"
.if \nX=1 .ds x} NOSTICKYTMP 4 ""
.if \nX=2 .ds x} NOSTICKYTMP 4 "" "\&"
.if \nX=3 .ds x} NOSTICKYTMP "" "" "\&"
.TH \*(x}
.SH NAME
nostickytmp, nocleantmp \- control temporary files
.SH DESCRIPTION
The configuration flag
.I nostickytmp
selects the permissions of the temporary directories.
If
.I nostickytmp
is
.IR off ,
.IR /tmp
and 
.IR /usr/tmp ,
will be changed to sticky directories at boot time.
If it is 
.IR on ,
the mode of the temporary directories won't be changed.
.PP
If the configuration flag
.I nocleantmp
is 
.IR off ,
.IR /tmp
will be cleaned up at boot time.
If it is on, none of the files in
.IR /tmp
will be removed.
.PP
The value of the flags
can be set to
.I on
or
.I off
using
.IR chkconfig (1M).
.SH FILES
/etc/config/nostickytmp
.br
/etc/config/nocleantmp
.SH SEE ALSO
chmod(1), chkconfig(1M)
