'\"macro stdmacro
.if n .pH man4.rmtab @(#)rmtab	30.3 of 2/1/86
.TH RMTAB 4
.SH NAME
rmtab \- remotely mounted file system table
.SH DESCRIPTION
.IX  "rmtab file"  ""  "\fLrmtab\fP \(em remote mounted file system table"
.I Rmtab
resides in the directory
.I /etc
and contains a record of all clients
that have done remote mounts of file systems from this machine.
Whenever a remote
.I mount
is done, an entry is made in the
.I rmtab
file of the machine serving up that file system.
.I Umount
removes entries of a remotely mounted file system.
.I "Umount \-a"
broadcasts to all servers, and informs them that they should remove
all entries from
.I rmtab
created by the sender of the broadcast message
(this is done automatically during system startup).
The table is a series of lines of the form:
.IP
 hostname:directory
.PP
This table is used only to preserve information between crashes,
and is read only by
.IR mountd (1M)
when it starts up.
.I Mountd
keeps an in-core table,
which it uses to handle requests from programs like
.IR showmount (1)
and
.IR shutdown (1M).
.SH FILES
/etc/rmtab
.SH "SEE ALSO"
showmount(1), mountd(1M), mount(1M), umount(1M), shutdown(1M)
.SH BUGS
Although the
.I rmtab
table is close to the truth,
it is not always 100% accurate.
