'\"macro stdmacro
.if n .pH man4.rpc @(#)rpc	30.3 of 2/1/86
.TH RPC 4
.SH NAME
rpc \- RPC program number data base
.SH SYNOPSIS
.B /etc/rpc
.SH DESCRIPTION
.IX  "rpc program number file"  ""  "\fLrpc\fP \(em rpc name data base"
The
.I rpc
file contains user readable names that
can be used in place of Sun RPC program numbers.
Each line has the following information:
.RS
.HP 10
name of server for the RPC program
.br
.ns
.HP 10
RPC program number
.br
.ns
.HP 10
aliases
.RE
.LP
Items are separated by any number of blanks and/or
tab characters.
A ``#'' indicates the beginning of a comment; characters up to the end of
the line are not interpreted by routines which search the file.
.LP
Here is an excerpt of the \f2/etc/rpc\fP file on IRIX:
.nf
.ta \w'sgi_toolkitbusXX'u +1.0i +1.0i +1.0i
#
#       rpc   1.10   87/04/10
#
portmapper	100000  portmap sunrpc
rstatd	100001  rstat rup perfmeter
rusersd	100002  rusers
nfs	100003  nfsprog
ypserv	100004  ypprog
mountd	100005  mount showmount
ypbind	100007
walld	100008  rwall shutdown
sgi_toolkitbus	391001
sgi_fam	391002
.fi
.DT
.SH FILES
/etc/rpc
.SH "SEE ALSO"
getrpcent(3N)
'\".SH ORIGIN
'\"Sun Microsystems
