.TH sys_id 4
.SH NAME
sys_id \- system identification (hostname) file
.SH DESCRIPTION
The file
.I /etc/sys_id
contains the name by which the system is known on communications
networks such as the Internet and UUCP.
The name can be up to 64 alphanumeric characters long
and can include periods and hyphens.
Periods are not part of the name but serve to separate components
of a domain-style name.
For example:
.Ex
iris.widgets.com
.Ee
During system startup this file is read by the script
.I /etc/rc2.d/S20sysetup
and the contents are passed as a parameter to
\f2hostname\f1(1) to initialize the system name.
Once this has been done, this name is returned by the
commands \f2hostname\f1(1) and \f2uname\f1(1) and by the system calls
\f2gethostname\f1(2) and \f2uname\f1(2).
.IR uname (1)
returns only the first eight characters up to the first period.
.SH FILES
/etc/sys_id
.SH SEE ALSO
hostname(1),
uname(1),
gethostname(2),
uname(2),
hostname(5).
