.TH ttytype 4
.SH NAME
ttytype \- data base of terminal types by port
.SH DESCRIPTION
.I ttytype
is a database containing, for each tty port on the system,
the kind of terminal that is attached to it.
There is one line per port,
containing the terminal kind (as a name described in \f2terminfo\f1(4)),
a space, and the name of the tty, minus \f2/dev/\f1.
.PP
This information is read by
.IR tset (1)
to initialize the TERM environment variable at login time.
.SH EXAMPLE
.IP
.nf
iris-ansi	console
vt100	ttyd1
?h19		ttyd2
?h19		ttyd3
?v50am	ttyd4
?v50am	ttyd5
?v50am	ttyd6
?v50am	ttyd7
?v50am	ttyd8
?v50am	ttyd9
?v50am	ttyd10
?v50am	ttyd11
?v50am	ttyd12
.fi
.SH FILES
/etc/ttytype
.SH "SEE ALSO"
tset(1),
terminfo(4).
