.TH ypservers 4
.SH NAME
ypservers \- NIS bindings file
.SH SYNOPSIS
.nf
/var/yp/binding/*/ypservers
.fi
.SH DESCRIPTION
The file \fB/var/yp/binding/DOMAINNAME/ypservers\fP contains a static
list of available NIS servers for the domain DOMAINNAME.  If this file
exists, then only the servers listed in it are eligible to act as NIS
servers for this client.

The file contains a whitespace separated list of host names or IP addresses.
If a name is given then an entry for this host must exist in the local
hosts file \fB/etc/hosts\fP.  An example file would be:

.in +.5i
.nf
128.1.2.1
bigserver
192.0.1.1
150.166.2.3
.fi
.in -.5i

This file lists four hosts which can act as name servers for this system.
NIS bind requests will be sent to each and the first respondant will be
chosen and used until it fails to respond, and which time the client will
rebind.  The current server for a host may be determined using the command
\fBypwhich(1)\fP.
.SH FILES
/var/yp/binding/*/ypservers
.SH SEE ALSO
nsd(1M), nis(7P), ypwhich(1)
.br
\f2IRIX Admin: Networking and Mail\f1
.br
\f2IRIX Admin: NFS and NIS\f1
