#ident  "ide/godzilla/h_x_b/Makefile:  $Revision: 1.2 $"
#
# h_x_b (heart_xbow_bridge) diag makefile

DIAGDEPTH= ../..
include ${DIAGDEPTH}/Makedefs

ASFILES=
CFILES=	hxb_sav_rst.c 	\
	hxb_util.c	\
	hxb_chkout.c 	\
	hxb_status.c

include ${DIAGDEPTH}/Makerules
LINCLUDES = -I../include
