#	Makefile for bstream - the tape streaming filter

include $(ROOT)/usr/include/make/commondefs

TARGETS=bstream

default: $(TARGETS)

include $(COMMONRULES)

install: default
	$(INSTALL) -F /usr/sbin $(TARGETS)
