'\"macro stdmacro
.TH SYSINFO 1
.SH NAME
sysinfo \- print system identification
.SH SYNOPSIS
.B sysinfo [-s][-v][-vv]
.SH DESCRIPTION
.I sysinfo
with no options
prints the unique identifier of the system.  This
identifier is guaranteed to be unique within the Silicon Graphics
product family.
With the
.B -s
option a shorter (32 bit) identifier is printed.
This identifier is not guaranteed to be unique but in practice is.
This number is the same that is available from within a program via the
.IR sysid 
function. On multiple module systems this will return a 32 bit version
of the lowest numbered module's identifier. Because this interface does
not take into account multiple module systems its use is discouraged.
With the
.B -v
option,
.I sysinfo
will print the unique identifier followed by the module number
for each module in the system.
The
.B -vv
option will print the unique identifier, the system serial number and the
module number for each module on all platforms except IP20. On IP20 it will
only print the unique identifier and the module number.
.SH SEE ALSO
sysid(3C)
.SH BUGS
The system identifier on different Silicon Graphics products is associated
with different physical pieces of hardware.
Therefore, the identifier may unexpectedly change when the hardware is
modified.
