.TH TOPOLOGY 1
.SH NAME
\f3topology\f1 \- machine topology information
.SH SYNOPSIS
.nf
topology 
.fi

.SH DESCRIPTION
Machine topology information is extracted from the hardware
graph.

.SH EXAMPLE

When executed on a 16 processor Origin2000 named olympic, 
the topology command yields:
.PP
.nf.
Machine olympic has 16 cpu's, 8 memory nodes, and 4 routers.

The cpus are:
cpu   0 is /hw/module/1/slot/n1/node/cpu/a
cpu   1 is /hw/module/1/slot/n1/node/cpu/b
cpu   2 is /hw/module/1/slot/n2/node/cpu/a
cpu   3 is /hw/module/1/slot/n2/node/cpu/b
cpu   4 is /hw/module/1/slot/n3/node/cpu/a
cpu   5 is /hw/module/1/slot/n3/node/cpu/b
cpu   6 is /hw/module/1/slot/n4/node/cpu/a
cpu   7 is /hw/module/1/slot/n4/node/cpu/b
cpu   8 is /hw/module/2/slot/n1/node/cpu/a
cpu   9 is /hw/module/2/slot/n1/node/cpu/b
cpu  10 is /hw/module/2/slot/n2/node/cpu/a
cpu  11 is /hw/module/2/slot/n2/node/cpu/b
cpu  12 is /hw/module/2/slot/n3/node/cpu/a
cpu  13 is /hw/module/2/slot/n3/node/cpu/b
cpu  14 is /hw/module/2/slot/n4/node/cpu/a
cpu  15 is /hw/module/2/slot/n4/node/cpu/b

The nodes are:
/hw/module/1/slot/n1/node
/hw/module/1/slot/n2/node
/hw/module/1/slot/n3/node
/hw/module/1/slot/n4/node
/hw/module/2/slot/n1/node
/hw/module/2/slot/n2/node
/hw/module/2/slot/n3/node
/hw/module/2/slot/n4/node

The routers are:
/hw/module/1/slot/r1/router
/hw/module/1/slot/r2/router
/hw/module/2/slot/r1/router
/hw/module/2/slot/r2/router

The topology is defined by:
/hw/module/1/slot/n1/node/link -> /hw/module/1/slot/r1/router
/hw/module/1/slot/n2/node/link -> /hw/module/1/slot/r1/router
/hw/module/1/slot/n3/node/link -> /hw/module/1/slot/r2/router
/hw/module/1/slot/n4/node/link -> /hw/module/1/slot/r2/router
/hw/module/2/slot/n1/node/link -> /hw/module/2/slot/r1/router
/hw/module/2/slot/n2/node/link -> /hw/module/2/slot/r1/router
/hw/module/2/slot/n3/node/link -> /hw/module/2/slot/r2/router
/hw/module/2/slot/n4/node/link -> /hw/module/2/slot/r2/router

/hw/module/1/slot/r1/router/1 -> /hw/module/2/slot/r1/router
/hw/module/1/slot/r1/router/4 -> /hw/module/1/slot/n2/node
/hw/module/1/slot/r1/router/5 -> /hw/module/1/slot/n1/node
/hw/module/1/slot/r1/router/6 -> /hw/module/1/slot/r2/router
/hw/module/1/slot/r2/router/1 -> /hw/module/2/slot/r2/router
/hw/module/1/slot/r2/router/4 -> /hw/module/1/slot/n4/node
/hw/module/1/slot/r2/router/5 -> /hw/module/1/slot/n3/node
/hw/module/1/slot/r2/router/6 -> /hw/module/1/slot/r1/router
/hw/module/2/slot/r1/router/1 -> /hw/module/1/slot/r1/router
/hw/module/2/slot/r1/router/4 -> /hw/module/2/slot/n2/node
/hw/module/2/slot/r1/router/5 -> /hw/module/2/slot/n1/node
/hw/module/2/slot/r1/router/6 -> /hw/module/2/slot/r2/router
/hw/module/2/slot/r2/router/1 -> /hw/module/1/slot/r2/router
/hw/module/2/slot/r2/router/4 -> /hw/module/2/slot/n4/node
/hw/module/2/slot/r2/router/5 -> /hw/module/2/slot/n3/node
/hw/module/2/slot/r2/router/6 -> /hw/module/2/slot/r1/router

.fi
.SH SEE ALSO

\f3hinv\f1(1), \f3hwgraph\f1(4)

