.nr X
.if \nX=0 .ds x} clone 7 "Networking Support Utilities" "\&"
.TH \*(x}
.SH NAME
clone \- open any minor device on a STREAMS driver
.SH "DESCRIPTION"
.P
\f2clone\fP is a STREAMS software driver that finds and opens an
unused minor device on another STREAMS driver.
The minor device passed to \f2clone\fP during the open is interpreted as the major device number of
another STREAMS driver for which an unused minor device is to be
obtained.
Each such open results in a separate \f2stream\fP to a previously
unused minor device.
.P
The \f2clone\fP driver consists solely of an open function.
This open function performs all of the necessary work so that subsequent system calls
(including \f2close\fP(2)) require no further involvement of \f2clone\fP.
.P
\f2clone\fP generates an ENXIO error, without opening the device, if the minor device number provided does not correspond to a valid major device, or if the driver indicated is not a STREAMS driver.
.SH "CAVEATS"
Multiple opens of the same minor device cannot be done through the \f2clone\fP interface.
Executing \f2stat\fP(2) on the filesystem node for a cloned device yields a
different result from executing \f2fstat\fP(2) using a file descriptor obtained
from opening the node.
.SH "SEE ALSO"
.\"\f2\s-1STREAMS\s0 Programmer's Guide\fP.
log(7).
