'\"macro stdmacro
.if n .pH g7.par @(#)par	30.2 of 12/25/85
.nr X
.if \nX=0 .ds x} PAR 7 "" "\&"
.if \nX=1 .ds x} PAR 7 ""
.if \nX=2 .ds x} PAR 7 "" "\&"
.if \nX=3 .ds x} PAR "" "" "\&"
.TH \*(x}
.SH NAME
\f4par\f1 \- process activity reporting device
.SH DESCRIPTION
The special file
\f4/dev/par\fP
is used by the programs \f4par\fP(1) and \f4padc\fP(1)
to gather process activity information from the kernel.
The only operations supported by this device are \f4open\fP(2),
\f4ioctl\fP(2) and \f4close\fP(2).
The format of the information provided by this device through its
\f4ioctl\fP(2) commands is not intended for use by any
programs or facilities other than 
\f4par\fP(1) and \f4padc\fP(1)
and is subject to change.
.PP
The file \f4/dev/par\fP
is a pseudo-device
with no associated hardware.
.SH FILES
\f4/dev/par\fP
.SH "SEE ALSO"
\f4par\fP(1),
\f4padc\fP(1).
.Ee
'\".so /pubs/tools/origin.sgi
