'\"macro stdmacro
.TH ZERO 7
.SH NAME
zero \- source of zeroes
.SH DESCRIPTION
A zero special file is a source of zeroed unnamed memory.
.LP
Reads from a zero special file always return a buffer full of zeroes.  The
file is of infinite length.
.LP
Writes to a zero special file are always successful,
but the data written is ignored.
.LP
Mapping a zero special file creates a zero-initialized unnamed memory
object of a length equal to the length of the mapping and rounded up to the
nearest page size as returned by \f2getpagesize\fP\^(2).
Multiple processes can share such a zero special file object
provided a common ancestor mapped the object MAP_SHARED.
.SH FILES
/dev/zero
.SH SEE ALSO
fork(2), mmap(2)
'\".so /pubs/tools/origin.bsd
