#!/bin/sh

set -x

XFSPATH=/xfsstress

. $XFSPATH/SETUP

while /usr/bin/true
do

echo "umount $FS"
umount $FS

rval=$?
if [ $rval != 0 -a $rval != 2 ]
then
	umount -k $FS

	if [ $? != 0 ]
	then
		banner "umount #1 failed"
		ps -edaf
		exit 3
	fi
fi

date

echo xfs_logprint -t -b -i -o $RDSK
xfs_logprint -t -b -i -o $RDSK > $XFSPATH/logprint.out 2>&1

echo "mount $DSK $FS"
mount $DSK $FS

rval=$?
if [ $rval != 0 ]
then
	banner "mount #1 failed"
	exit 3
fi

echo "umount $FS"
umount $FS

rval=$?
if [ $rval != 0 -a $rval != 2 ]
then
	umount -k $FS

	rval=$?
	if [ $rval != 0 -a $rval != 2 ]
	then
		banner "umount #2 failed"
		ps -edaf
		exit 3
	fi
fi

date

xfs_check $RDSK

if [ $? != 0 ]
then
	banner "File System Corrupted"
	exit 3
else
	banner File; banner System; banner OK
	echo "mount $DSK $FS"
	mount $DSK $FS

	rval=$?
	if [ $rval != 0 ]
	then
		banner "mount #2 failed"
		exit 3
	fi

	rm -rf $DIR
	mkdir -p $DIR
	$XFSPATH/runall-errstress.sh $DIR
fi

done
