#!smake
#
# Makefile for libcmd.
#
#ident	"$Revision: 1.3 $"

DEPTH=.
CFILES=magic.c sum.c deflt.c getterm.c systbl.c sttyname.c tp_ops.c

include $(ROOT)/usr/include/make/libleafdefs
include $(LIBLEAFRULES)
