/*
 * iconv_comp.c.h
 *
 * DO NOT EDIT THIS FILE
 * This is generated using
 *	ansifunc
 * from sourcefile
 *	/hosts/colossus/d1/kuwahara/anex/workareas/kudzu/eoe/cmd/iconv_comp/iconv_comp.c
 *
 */

#ifndef ANSIF_EXCLUDE
#define ANSIF_EXCLUDE 1
#define ANSIF_EXCLUDE_SET 1
#endif

/* #include "iconv.h" */
/* #include "iconv_cnv.h" */
/* #include "iconv_int.h" */
/* #include "in_proc.h" */
/* #include "iconv_comp.h" */
/* #include "iconv_comp.c.h" */

/* line: 107 */
int alex_con_octal(
    char 		* s,		/* the string */
    register int	  l,		/* the length */
    long		* val		/* the address to put the value */
) ;

/* line: 281 */
void icc_fixstr( void )
;

/* line: 345 */
void	icc_fixident()
;

/* line: 373 */
void	lexerror()
;

/* line: 392 */
void yyerror(
    const char * s
) ;

/* line: 403 */
int yywrap()
;

/* line: 423 */
int	icc_compar_string(
    ICC_OBJ_TYP	    * p_o_a,
    ICC_OBJ_TYP	    * p_o_b
) ;

/* line: 463 */
int	icc_compar_meth(
    ICC_OBJ_TYP	    * p_o_a,
    ICC_OBJ_TYP	    * p_o_b
) ;

/* line: 488 */
int	icc_compar_clone(
    ICC_OBJ_TYP	    * p_o_a,
    ICC_OBJ_TYP	    * p_o_b
) ;

/* line: 513 */
int	icc_compar_join(
    ICC_OBJ_TYP	    * p_o_a,
    ICC_OBJ_TYP	    * p_o_b
) ;

/* line: 538 */
int	icc_compar_libspec(
    ICC_OBJ_TYP	    * p_o_a,
    ICC_OBJ_TYP	    * p_o_b
) ;

/* line: 561 */
int	icc_compar_libmeth(
    ICC_OBJ_TYP	    * p_o_a,
    ICC_OBJ_TYP	    * p_o_b
) ;

/* line: 598 */
int	icc_compar_spec(
    ICC_OBJ_TYP	    * p_o_a,
    ICC_OBJ_TYP	    * p_o_b
) ;

/* line: 622 */
int icc_compargeneric(
    ICC_OBJ_TYP	    * p_o_a,
    ICC_OBJ_TYP	    * p_o_b
) ;

/* line: 644 */
int icc_compar_1_generic(
    ICC_OBJ_TYP	    * p_o_a,
    ICC_OBJ_TYP	    * p_o_b
) ;

/* line: 668 */
void * icc_findelem(
    ICC_OBJ_HEAD    * p_oh,
    ICC_OBJ_TYP	    * p_o
) ;

/* line: 696 */
void	icc_insert(
    ICC_OBJ_HEAD    * p_oh,
    ICC_OBJ_TYP	    * p_o
) ;

/* line: 723 */
ICC_OBJ_TYP	* icc_findgeneric(
    ICC_OBJ_HEAD    * p_oh,
    void	    * data1,
    void	    * data2
) ;

/* line: 747 */
ICC_OBJ_TYP	* icc_insertgeneric(
    ICC_OBJ_HEAD    * p_oh,
    void	    * data1,
    void	    * data2
) ;

/* line: 775 */
ICC_OBJ_TYP	* icc_insertalloc(
    ICC_OBJ_HEAD    * p_oh,
    ICC_OBJ_TYP	    * p_sobj
) ;

/* line: 804 */
void	* icc_stringof(
    ICC_OBJ_TYP	    * p_obj
) ;

/* line: 825 */
void	* icc_stringof1(
    ICC_OBJ_TYP	    * p_obj
) ;

/* line: 848 */
void	printtable(
    ICC_SPECTAB	    * p_tab
) ;

/* line: 873 */
void	printlspec(
    ICC_STDLIBSPEC	* p_ls
) ;

/* line: 915 */
void	printmeth(
    ICC_METHODS		* p_mth
) ;

/* line: 937 */
void	printspec( ICC_SPEC * p_sp )
;

/* line: 976 */
void	icc_init()
;

/* line: 1033 */
ICC_OBJ_TYP * icc_getstr(
    char	* str
) ;

/* line: 1062 */
ICC_SPEC * icc_getspec(
    ICC_HEAD		* p_hd,
    ICC_OBJ_TYP		* p_o_a,
    ICC_OBJ_TYP		* p_o_b
) ;

/* line: 1090 */
ICC_OBJ_TYP	* icc_getmkgeneric(
    ICC_OBJ_HEAD    * p_oh,
    void	    * data1,
    void	    * data2
) ;

/* line: 1118 */
void	* icc_getmk(
    ICC_OBJ_HEAD    * p_oh,
    ICC_OBJ_TYP	    * p_sobj
) ;

/* line: 1147 */
ICC_SPEC * icc_newspec(
    ICC_HEAD		* p_hd,
    ICC_OBJ_TYP		* p_o_a,
    ICC_OBJ_TYP		* p_o_b
) ;

/* line: 1179 */
void	mkentry(
    char	* from_enc,
    char	* to_enc,
    char	* alg_dso,
    char	* alg_sym,
    char	* ctl_dso,
    char	* ctl_sym,
    ICC_TBLST	* tablelist
) ;

/* line: 1322 */
void	mkclone(
    int		  to_from,
    char	* enc,
    char	* alg_dso,
    char	* alg_sym,
    char	* ctl_dso,
    char	* ctl_sym,
    char	* enc_new,
    char	* alg_dso_new,
    char	* alg_sym_new,
    char	* ctl_dso_new,
    char	* ctl_sym_new
) ;

/* line: 1428 */
void	mkjoin(
    char	* enc,
    char	* alg_dso,
    char	* alg_sym,
    char	* ctl_dso,
    char	* ctl_sym,
    char	* enc_2,
    char	* alg_dso_2,
    char	* alg_sym_2,
    char	* ctl_dso_2,
    char	* ctl_sym_2,
    char	* alg_dso_new,
    char	* alg_sym_new,
    char	* ctl_dso_new,
    char	* ctl_sym_new
) ;

/* line: 1533 */
void	* mktablelist(
    ICC_TBLST   * head,
    ICC_OBJ_TYP * table
) ;

/* line: 1584 */
void	* mktable(
    char	* tbl_dso,
    char	* tbl_sym,
    int		  file
) ;

/* line: 1628 */
void	mkstdlib(
    char	* from_enc,
    char	* to_enc,
    char        * mbwc_dso,
    char        * mbwc_sym,
    ICC_TBLST   * tblst_mbwc,
    ICC_TBLST   * tblst_wcmb
) ;

/* line: 1773 */
void * mklocale_alias(
    char	* locale_name,
    char	* value
) ;

/* line: 1799 */
void * mklocale_codeset(
    char	* locale_name,
    char	* value
) ;

/* line: 1823 */
int	icc_read_input( int argc, char ** argv, char ** pname )
;

/* line: 1891 */
int	icc_cmpstr(
    ICC_OBJ_TYP		** pp_a,
    ICC_OBJ_TYP		** pp_b
) ;

/* line: 1939 */
int	icc_compar(
    const ICC_SPEC	** p_a,
    const ICC_SPEC	** p_b
) ;

/* line: 1964 */
int	icc_compar_ls(
    const ICC_STDLIBSPEC	** p_a,
    const ICC_STDLIBSPEC	** p_b
) ;

/* line: 1996 */
int	icc_nulfnc(
    char	    * ptr,
    int		    * prel,
    void	    * data,
    int		      size,
    int		      align
) ;

/* line: 2023 */
int	icc_cpyfnc(
    char	    * ptr,
    int		    * prel,
    void	    * data,
    int		      size,
    int		      align
) ;

/* line: 2050 */
int	icc_iconv_r_spec_size(
    int		    n
) ;

/* line: 2070 */
int	icc_iconv_r_libspec_size(
    int		    n
) ;

/* line: 2091 */
ICONV_S_RELPTR	icc_setused(
    ICC_OBJ_HEAD    * p_oh,
    ICC_OBJ_TYP	    * p_obj
) ;

/* line: 2127 */
void	icc_dump_data(
    ICC_HEAD	    * p_hd,
    char	    * data,
    int		    * prel,
    ICC_CPYFNC	      fnc,
    ICC_SPEC	   ** pp_top,
    ICC_STDLIBSPEC ** pp_ls_top,
    int		      nstr,
    ICC_OBJ_TYP    ** pp_str,
    ICONV_S_SPEC    * a_sp,
    ICONV_S_LSPEC   * a_ls_sp
) ;

/* line: 2524 */
int	icc_cmpclone(
    ICC_HEAD	    * p_hd,
    ICC_CLONEOBJ    * p_clone,
    ICC_SPEC	    * p_spec
) ;

/* line: 2550 */
long	icc_specsize(
    long	ntable
) ;

/* line: 2570 */
int	icc_mkclone(
    ICC_HEAD	    * p_hd,
    ICC_CLONEOBJ    * p_clone,
    ICC_SPEC	    * p_spec
) ;

/* line: 2616 */
int icc_do_clones(
    ICC_HEAD	    * p_hd
) ;

/* line: 2646 */
int	icc_cmpjoin1(
    ICC_HEAD	    * p_hd,
    ICC_JOINOBJ     * p_join,
    ICC_SPEC	    * p_spec
) ;

/* line: 2669 */
int	icc_cmpjoin2(
    ICC_HEAD	    * p_hd,
    ICC_JOINOBJ     * p_join,
    ICC_SPEC	    * p_spec1,
    ICC_SPEC	    * p_spec2
) ;

/* line: 2691 */
int	icc_mkjoin(
    ICC_HEAD	    * p_hd,
    ICC_JOINOBJ     * p_join,
    ICC_SPEC	    * p_spec1,
    ICC_SPEC	    * p_spec2
) ;

/* line: 2742 */
int	icc_do_joins(
    ICC_HEAD	    * p_hd
) ;

/* line: 2779 */
void	icc_procstr(
    ICC_HEAD	    * p_hd,
    ICC_OBJ_TYP	  *** ppp_str,
    int		      nstr
) ;

/* line: 2836 */
int	icc_markused(
    ICC_OBJ_HEAD    * p_oh,
    ICC_OBJ_TYP	    * p_obj,
    int		      use
) ;

/* line: 2865 */
int	icc_strobjcmp_data1(
    ICC_OBJ_TYP		** pp_a,
    ICC_OBJ_TYP		** pp_b
) ;

/* line: 2929 */
void	icc_markstring(
    ICC_OBJ_TYP	    * p_obj,
    int               sel
) ;

/* line: 2958 */
void	fix_objs(
    ICC_OBJ_HEAD	* p_oh,
    icc_qsort_compar	  func,
    void		( * mark_func )( ICC_OBJ_TYP * p_obj, int sel ),
    int                   sel
) ;

/* line: 3001 */
void	icc_prepare_resource(
    ICC_RES_VALUES	* p_vvals
) ;

/* line: 3050 */
void	icc_write_resource(
    ICC_RES_VALUES	* p_vvals,
    char		* ptr,
    int			* prel,
    ICC_CPYFNC	          fnc
) ;

/* line: 3136 */
void	process( char * filename )
;

/* line: 3365 */
int	icc_cnv_int(
    int		      * p_dst,
    ICC_RES_VALUE     * p_src
) ;

/* line: 3376 */
int	icc_cnv_longlong(
    long long         * p_dst,
    ICC_RES_VALUE     * p_src
) ;

/* line: 3387 */
int	icc_cnv_short(
    short	      * p_dst,
    ICC_RES_VALUE     * p_src
) ;

/* line: 3398 */
int	icc_cnv_byte(
    char	      * p_dst,
    ICC_RES_VALUE     * p_src
) ;

/* line: 3409 */
int	icc_cnv_string(
    ICC_RELPTR	      * p_dst,
    ICC_RES_VALUE     * p_src
) ;

/* line: 3423 */
int	icc_cnv_reference(
    ICONV_REFER       * p_dst,
    ICC_RES_VALUE     * p_src
) ;

/* line: 3496 */
void * mkresource(
    char		* param_name,
    ICC_RES_VALUES	* p_vvals
) ;

/* line: 3560 */
void	* mkvalues(
    ICC_RES_VALUES   * p_vvals,
    ICC_RES_VALUE    * p_vval
) ;

/* line: 3602 */
void	* mkvalue_str(
    ICC_TYPEDEF	    * p_td,
    char	    * ident,
    char	    * value
) ;

/* line: 3651 */
void	* mkvalue_int(
    ICC_TYPEDEF	    * p_td,
    char	    * ident,
    char	    * value
) ;

/* line: 3716 */
void	* mkvalue_table(
    ICC_TYPEDEF	    * p_td,
    char	    * ident,
    ICC_OBJ_TYP	    * table
) ;

/* line: 3788 */
ICC_TYPEDEF * icc_find_type_spec(
    char	* name
) ;

/* line: 3813 */
void	* mkchktyp(
    char	    * typename
) ;

/* line: 3894 */
void	main( int argc, char ** argv )
;

/* used to process #exclude requests */
#ifdef ANSIF_EXCLUDE_SET
#undef ANSIF_EXCLUDE_SET
#undef ANSIF_EXCLUDE
#endif

