#!/bin/csh -xf

echo "================		BANYAN IRIX HEADERS		===================="

cd /d2/banyan
source banyan.setup
rehash
#
# Check irix/kern, irix/include
#
echo "Checking $WORKAREA/irix/kern"
cd $WORKAREA/irix/kern

if ($PURGE) then
	echo "Checking and purging files..."
	p_check -s -v | p_purge -u -v -y -i 
#else
#	echo "No files will be purged since -nopurge was specified"
#	p_check -s -v
endif

if ($UPDATE) then
	echo "Updating files..."
	p_tupdate -v
#else
#	p_tupdate -n
endif

echo "Checking $WORKAREA/irix/include"
cd $WORKAREA/irix/include

if ($PURGE) then
	echo "Checking and purging files..."
	p_check -v -s | p_purge -u -v -y -i 
#else
#	echo "No files will be purged since -nopurge was specified"
#	p_check -v -s
endif

if ($UPDATE) then
	echo "Updating files..."
	p_tupdate -v
#else
#	p_tupdate -n
endif

cd $WORKAREA/irix/kern
make headers & 
cd $WORKAREA/irix/include
make headers & 
wait 

echo "================		DONE MAKING BANYAN IRIX HEADERS		===================="
