#!/bin/csh
# creates the ip22 mfg ide files
#
cd $WORKAREA/stand/arcs/ide/IP22/graphics/EXPRESS
make clobber
make mfgstuff
cd $WORKAREA/stand/arcs/ide/IP22/mem
rm $WORKAREA/stand/arcs/ide/$PRODUCT.O/memtest2.o
rm $WORKAREA/stand/arcs/ide/$PRODUCT.O/checker.o
rm $WORKAREA/stand/arcs/ide/$PRODUCT.O/tb_test.o
make mfgstuff
cd $WORKAREA/stand/arcs/ide
make mfgstuff
cd $WORKAREA/stand/arcs/ide/$PRODUCT.O
size -B *.ide
size -B *.ide | awk '{print $2 + $3}'
#$(IP22_X)TEXTSTART= 88400000 = 138412032 d
#$(IP22_X)LOADADDR = A8400000 = 138412032 d
#$(IP22_X)DATASTART= A8560000 = 139853824 d
#$(IP22_X)TOPCHECK = A8740000 = 141819904 d
# Text : loadaddr + text_size < datastart
# BSS calc for 6.2 is different from 5.3, 6.2 uses loadaddr, 5.3=>datastart
# BSS :  loadaddr + data_size + bss_size < topcheck
echo "Text < 1441792 (txt check)"
echo "(data + bss) < 3407872 (bss check)"
