#!smake -r
# Makefile for making a book

TITLE = CrayMsg_PG
FULL_TITLE = "Cray(R) Message System Programmer's Guide"
VERSION = 007-3548-002, 4/97

include  ${ROOT}/usr/include/make/commonbookdefs

BOOKSHELF = /usr/share/Insight/library/SGI_bookshelves/SGI_Developer
BOOK_ICON = sgi_developer
DTD = CRAYDOCBK

BOOK_FILES = 2121_6.5.sgm

GIF = a11000.gif a11591.gif

include  ${COMMONBOOKRULES}
include  ${COMMONPREPRULES}
