/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 */
/*
 * HISTORY
 * $Log: ubik_data.h,v $
 * Revision 65.2  1999/02/04 19:19:42  mek
 * Provide C style include file for IRIX kernel integration.
 *
 * Revision 65.1  1997/10/20 19:19:40  jdoak
 * *** empty log message ***
 *
 * Revision 1.1.54.1  1996/10/02  17:56:03  damon
 * 	Newest DFS from Transarc
 * 	[1996/10/01  18:42:54  damon]
 *
 * $EndLog$
 */

/* Generated by IDL compiler version OSF DCE T1.2.0-09 */
#ifndef ubik_data_v0_0_included
#define ubik_data_v0_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
#ifndef common_data_v0_0_included
#include <dcedfs/common_data.h>
#endif
typedef struct BDesc {
unsigned32 host;
signed16 portal;
signed32 session;
} BDesc;
typedef struct net_version {
signed32 epoch;
signed32 counter;
} net_version;
typedef struct net_tid {
signed32 epoch;
signed32 counter;
} net_tid;
typedef struct ubik_debug {
signed32 now;
signed32 lastYesTime;
unsigned32 lastYesHost;
signed32 lastYesState;
signed32 lastYesClaim;
unsigned32 lowestHost;
signed32 lowestTime;
unsigned32 syncHost;
signed32 syncTime;
struct net_version syncVersion;
struct net_tid syncTid;
signed32 amSyncSite;
signed32 syncSiteUntil;
signed32 nServers;
signed32 lockedPages;
signed32 writeLockedPages;
struct net_version localVersion;
signed32 activeWrite;
signed32 tidCounter;
signed32 anyReadLocks;
signed32 anyWriteLocks;
signed32 recoveryState;
signed32 currentTrans;
signed32 writeTrans;
signed32 epochTime;
} ubik_debug;
typedef struct ubik_debug_v2 {
signed32 providerVers;
unsigned32 myAddr;
uuid_t myRealm;
uuid_t myPrinc;
uuid_t lastYesRealm;
uuid_t lastYesPrinc;
} ubik_debug_v2;
typedef struct ubik_sdebug {
unsigned32 addr;
signed32 lastVoteTime;
signed32 lastBeaconSent;
signed32 lastVote;
struct net_version remoteVersion;
signed32 currentDB;
signed32 beaconSinceDown;
signed32 up;
} ubik_sdebug;
typedef struct ubik_sdebug_v2 {
signed32 providerVers;
uuid_t realm;
uuid_t principal;
} ubik_sdebug_v2;
#define BULK_ERROR (1)
typedef idl_byte bulkdata[1024];
#define UBULK_MAXLENGTH (1024)
#define UBULK_BEGIN (0)
#define UBULK_LOCK (1)
#define UBULK_TRUNC (2)
#define UBULK_WRITE (3)
typedef struct ubik_bulk_update {
signed32 op;
signed32 arg1;
signed32 arg2;
signed32 arg3;
signed32 arg4;
signed32 length;
idl_byte data[1024];
} ubik_bulk_update;

#ifdef __cplusplus
    }

#endif
#endif
