/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 */
/*
 * HISTORY
 * $Log: afsvl_proc.h,v $
 * Revision 65.2  1999/02/04 19:19:38  mek
 * Provide C style include file for IRIX kernel integration.
 *
 * Revision 65.1  1997/10/20 19:20:06  jdoak
 * *** empty log message ***
 *
 * Revision 1.1.41.1  1996/10/02  17:45:49  damon
 * 	Newest DFS from Transarc
 * 	[1996/10/01  18:36:56  damon]
 *
 * Revision 1.1.36.2  1994/06/09  14:06:50  annie
 * 	fixed copyright in src/file
 * 	[1994/06/09  13:22:07  annie]
 * 
 * Revision 1.1.36.1  1994/02/04  20:17:51  devsrc
 * 	Merged from 1.0.3a to 1.1
 * 	[1994/02/04  15:12:38  devsrc]
 * 
 * Revision 1.1.34.1  1993/12/07  17:23:29  jaffe
 * 	1.0.3a update from Transarc
 * 	[1993/12/03  15:15:39  jaffe]
 * 
 * Revision 1.1.2.5  1993/01/21  19:33:41  zeliff
 * 	Embedding copyright notices
 * 	[1993/01/19  19:47:13  zeliff]
 * 
 * Revision 1.1.2.4  1992/11/24  17:01:29  bolinger
 * 	Change include file install directory from .../afs to .../dcedfs.
 * 	[1992/11/22  17:56:27  bolinger]
 * 
 * Revision 1.1.2.3  1992/09/15  13:12:19  jaffe
 * 	Transarc delta: vijay-ot4824-multiple-ubik-servers-fail-to-startup 1.3
 * 	  Selected comments:
 * 
 * 	    Problems were detected when multiple ubik servers were started up in a cell.
 * 	    This delta attempts to fix these bugs that prevent multiple ubik servers
 * 	    from running in a cell. Problems fixed are
 * 	    1. a hang in sec_id_parse_name was eliminated by removing unnecessary
 * 	    global locks (pthread_lock_global_np)
 * 	    2. ubik_Call routine cleaned up to handle all error cases. flserver RPC
 * 	    interface had to be changed to return the communication status as a
 * 	    return value instead of as a parameter.
 * 	    3. An error code was not returned if an invalid group is passed to ubik_
 * 	    ServerInit.
 * 	    Any other bugs noticed will be added to this delta. Not ready for release yet,
 * 	    upgrading before further changes are added.
 * 	    comm status as a return value instead of as a parameter
 * 	    After the upgrade, made changes to CM, PX, REP and fixed some typos in
 * 	    flserver and ubik. The changes are mainly to follow the new VL_ RPC
 * 	    signature.
 * 	    cleaned up bad merge.
 * 	[1992/09/14  19:35:31  jaffe]
 * 
 * Revision 1.1.2.2  1992/08/31  19:33:01  jaffe
 * 	Transarc delta: cfe-ot4029-portable-rpc-data-types 1.2
 * 	  Selected comments:
 * 	    If ``long'' could possibly mean ``64 bits'' any time soon, we need to keep
 * 	    our RPC interfaces from breaking.
 * 	    see above
 * 	    More of the same.  Forgot a couple of .idl files, and needed to change
 * 	    a couple of procedure signatures to match.
 * 	[1992/08/30  02:18:27  jaffe]
 * 
 * Revision 1.1  1992/01/19  02:48:39  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */

/* Generated by IDL compiler version OSF DCE T1.2.0-09 */
#ifndef VL__v4_0_included
#define VL__v4_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif
#include <dce/rpc.h>

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
#ifndef afsvl_data_v0_0_included
#include <dcedfs/afsvl_data.h>
#endif
extern error_status_t VL_GetEntryByID(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ /* Type must appear in user header or IDL */ afs_hyper_t *Volid,
    /* [in] */ unsigned32 voltype,
    /* [out] */ vldbentry *entry
#endif
);
extern error_status_t VL_GetEntryByName(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ volumeName volName,
    /* [out] */ vldbentry *entry
#endif
);
extern error_status_t VL_Probe(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h
#endif
);
extern error_status_t VL_GetCellInfo(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [out] */ vlconf_cell *MyCell
#endif
);
extern error_status_t VL_GetNextServersByID(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ /* Type must appear in user header or IDL */ afs_hyper_t *Volid,
    /* [in] */ unsigned32 voltype,
    /* [in] */ unsigned32 startHere,
    /* [out] */ unsigned32 *nextStartP,
    /* [out] */ vldbentry *entry,
    /* [out] */ unsigned32 *flagsP
#endif
);
extern error_status_t VL_GetNextServersByName(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ volumeName volName,
    /* [in] */ unsigned32 startHere,
    /* [out] */ unsigned32 *nextStartP,
    /* [out] */ vldbentry *entry,
    /* [out] */ unsigned32 *flagsP
#endif
);
extern error_status_t VL_GetSiteInfo(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ afsNetAddr *OldAddr,
    /* [out] */ siteDesc *FullSiteInfo
#endif
);
extern error_status_t VL_GetCEntryByID(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ /* Type must appear in user header or IDL */ afs_hyper_t *Volid,
    /* [in] */ unsigned32 voltype,
    /* [out] */ compactvldbentry *entry
#endif
);
extern error_status_t VL_GetCEntryByName(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ volumeName volName,
    /* [out] */ compactvldbentry *entry
#endif
);
extern error_status_t VL_GetCNextServersByID(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ /* Type must appear in user header or IDL */ afs_hyper_t *Volid,
    /* [in] */ unsigned32 voltype,
    /* [in] */ unsigned32 startHere,
    /* [out] */ unsigned32 *nextStartP,
    /* [out] */ compactvldbentry *entry,
    /* [out] */ unsigned32 *flagsP
#endif
);
extern error_status_t VL_GetCNextServersByName(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ volumeName volName,
    /* [in] */ unsigned32 startHere,
    /* [out] */ unsigned32 *nextStartP,
    /* [out] */ compactvldbentry *entry,
    /* [out] */ unsigned32 *flagsP
#endif
);
extern error_status_t VL_ExpandSiteCookie(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ unsigned32 Cookie,
    /* [out] */ siteDesc *FullSiteInfo
#endif
);
extern error_status_t VL_GetServerInterfaces(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in, out] */ dfs_interfaceList *serverInterfacesP
#endif
);
typedef struct VL__v4_0_epv_t {
error_status_t (*VL_GetEntryByID)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ /* Type must appear in user header or IDL */ afs_hyper_t *Volid,
    /* [in] */ unsigned32 voltype,
    /* [out] */ vldbentry *entry
#endif
);
error_status_t (*VL_GetEntryByName)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ volumeName volName,
    /* [out] */ vldbentry *entry
#endif
);
error_status_t (*VL_Probe)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h
#endif
);
error_status_t (*VL_GetCellInfo)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [out] */ vlconf_cell *MyCell
#endif
);
error_status_t (*VL_GetNextServersByID)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ /* Type must appear in user header or IDL */ afs_hyper_t *Volid,
    /* [in] */ unsigned32 voltype,
    /* [in] */ unsigned32 startHere,
    /* [out] */ unsigned32 *nextStartP,
    /* [out] */ vldbentry *entry,
    /* [out] */ unsigned32 *flagsP
#endif
);
error_status_t (*VL_GetNextServersByName)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ volumeName volName,
    /* [in] */ unsigned32 startHere,
    /* [out] */ unsigned32 *nextStartP,
    /* [out] */ vldbentry *entry,
    /* [out] */ unsigned32 *flagsP
#endif
);
error_status_t (*VL_GetSiteInfo)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ afsNetAddr *OldAddr,
    /* [out] */ siteDesc *FullSiteInfo
#endif
);
error_status_t (*VL_GetCEntryByID)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ /* Type must appear in user header or IDL */ afs_hyper_t *Volid,
    /* [in] */ unsigned32 voltype,
    /* [out] */ compactvldbentry *entry
#endif
);
error_status_t (*VL_GetCEntryByName)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ volumeName volName,
    /* [out] */ compactvldbentry *entry
#endif
);
error_status_t (*VL_GetCNextServersByID)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ /* Type must appear in user header or IDL */ afs_hyper_t *Volid,
    /* [in] */ unsigned32 voltype,
    /* [in] */ unsigned32 startHere,
    /* [out] */ unsigned32 *nextStartP,
    /* [out] */ compactvldbentry *entry,
    /* [out] */ unsigned32 *flagsP
#endif
);
error_status_t (*VL_GetCNextServersByName)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ volumeName volName,
    /* [in] */ unsigned32 startHere,
    /* [out] */ unsigned32 *nextStartP,
    /* [out] */ compactvldbentry *entry,
    /* [out] */ unsigned32 *flagsP
#endif
);
error_status_t (*VL_ExpandSiteCookie)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ unsigned32 Cookie,
    /* [out] */ siteDesc *FullSiteInfo
#endif
);
error_status_t (*VL_GetServerInterfaces)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in, out] */ dfs_interfaceList *serverInterfacesP
#endif
);
} VL__v4_0_epv_t;
extern rpc_if_handle_t VL__v4_0_c_ifspec;
extern rpc_if_handle_t VL__v4_0_s_ifspec;

#ifdef __cplusplus
    }

#else
#endif
#endif
