
//////////////////////////////////////////////////////////////
//
// Header file for BulletinBoardUI
//
//    This file is generated by RapidApp 1.2
//
//    This class implements the user interface portion of a class
//    Normally it is not used directly.
//    Instead the subclass, BulletinBoard is instantiated
//
//    To extend or alter the behavior of this class, you should
//    modify the BulletinBoard files
//
//    Restrict changes to those sections between
//    the "//--- Start/End editable code block" markers
//
//    This will allow RapidApp to integrate changes more easily
//
//    This class is a ViewKit user interface "component".
//    For more information on how components are used, see the
//    "ViewKit Programmers' Manual", and the RapidApp
//    User's Guide.
//
//////////////////////////////////////////////////////////////
#ifndef BULLETINBOARDUI_H
#define BULLETINBOARDUI_H
#include <Vk/VkComponent.h>


//---- Start editable code block: headers and declarations


//---- End editable code block: headers and declarations


// Externally defined classes referenced by this class:

class VkTickMarks;
class VkVuMeter;


class BulletinBoardUI : public VkComponent
{ 

  public:

    BulletinBoardUI ( const char *, Widget );
    BulletinBoardUI ( const char * );
    ~BulletinBoardUI();
    void create ( Widget );
    const char *  className();

    //---- Start editable code block: BulletinBoard public


    //---- End editable code block: BulletinBoard public


  protected:


    // Classes created by this class

    class VkVuMeter *_meterMP;
    class VkVuMeter *_meterFP;
    class VkVuMeter *_meterCMS;
    class VkVuMeter *_meterCMF;
    class VkVuMeter *_meterCMT;
    class VkVuMeter *_meterUMS;
    class VkVuMeter *_meterUMF;
    class VkVuMeter *_meterUMT;
    class VkVuMeter *_meterAMS;
    class VkVuMeter *_meterAMF;
    class VkVuMeter *_meterAMT;
    class VkVuMeter *_meterCI;
    class VkTickMarks *_tickmarks;

    // Widgets created by this class

    Widget  _bulletinBoard;
    Widget  _lAMF;
    Widget  _lAMS;
    Widget  _lAMT;
    Widget  _lCI;
    Widget  _lCMF;
    Widget  _lCMS;
    Widget  _lCMT;
    Widget  _lChange;
    Widget  _lFP;
    Widget  _lMP;
    Widget  _lNode;
    Widget  _lUMF;
    Widget  _lUMS;
    Widget  _lUMT;
    Widget  _label;
    Widget  _label1;
    Widget  _label10;
    Widget  _label11;
    Widget  _label12;
    Widget  _label2;
    Widget  _label3;
    Widget  _label4;
    Widget  _label5;
    Widget  _label6;
    Widget  _label7;
    Widget  _label8;
    Widget  _label9;
    Widget  _scrolledList;
    Widget  _scrolledWindow;
    Widget  _valAMF;
    Widget  _valAMS;
    Widget  _valAMT;
    Widget  _valCI;
    Widget  _valCMF;
    Widget  _valCMS;
    Widget  _valCMT;
    Widget  _valFP;
    Widget  _valMP;
    Widget  _valMT;
    Widget  _valUMF;
    Widget  _valUMS;
    Widget  _valUMT;


    // These virtual functions are called from the private callbacks (below)
    // Intended to be overriden in derived classes to define actions

    virtual void nodeSelect ( Widget, XtPointer );

    //---- Start editable code block: BulletinBoard protected


    //---- End editable code block: BulletinBoard protected


  private: 

    // Array of default resources

    static String      _defaultBulletinBoardUIResources[];


    // Callbacks to interface with Motif

    static void nodeSelectCallback ( Widget, XtPointer, XtPointer );

    //---- Start editable code block: BulletinBoard private


    //---- End editable code block: BulletinBoard private
};
//---- Start editable code block: End of generated code


//---- End editable code block: End of generated code

#endif

