/**************************************************************************
 *									  *
 * 		 Copyright (C) 1995-1996 Silicon Graphics, Inc.		  *
 *									  *
 *  These coded instructions, statements, and computer programs  contain  *
 *  unpublished  proprietary  information of Silicon Graphics, Inc., and  *
 *  are protected by Federal copyright law.  They  may  not be disclosed  *
 *  to  third  parties  or copied or duplicated in any form, in whole or  *
 *  in part, without the prior written consent of Silicon Graphics, Inc.  *
 *									  *
 **************************************************************************/

#include "ksys/cell/subsysid.h"

subsystem	"dsproc"	DSPROC_SUBSYSID

import <sys/proc.h>
import <ksys/vproc.h>
import <ksys/cell/tkm.h>
import <ksys/cell/service.h>
import <ksys/cell.h>
import <sys/hwperftypes.h>
import <pproc_private.h>
import <ksys/vpag.h>
import <fs/cfs/cfs.h>
import <sys/cred.h>
import <sys/time.h>

import <ksys/vfile.h>
import "os/file/cell/dfile_private.h"

synchronous int
get_reference(
	in	valueof		cell_t		sender,
	in	valueof		pid_t		pid,
	out	pointerto	obj_handle_t	handle,
	out	pointerto	short		state)

synchronous void
get_proc(
	in	valueof		objid_t		objid,
	out	pointerto	<proc_t *>	pp)

synchronous void
get_attr(
	in	valueof		objid_t		objid,
	in	valueof		int		flags,
	out	pointerto	vp_get_attr_t	attr)

synchronous void
parent_notify(
	in	valueof		objid_t		objid,
	in	valueof		pid_t		pid,
	in	valueof		int		wcode,
	in	valueof		int		wdata,
	in	pointerto	<struct timeval>	utime,
	in	pointerto	<struct timeval>	stime,
	in	valueof		pid_t		pgid,
	in	valueof		sequence_num_t	pgseq,
	in	valueof		short		xstat,
	out	pointerto	int		ignore)

synchronous void
reap(
	in	valueof		objid_t		objid,
	in	valueof		cell_t		sender,
	in	valueof		tk_set_t	retset,
	in	valueof		tk_disp_t	why,
	in	valueof		int		flags,
	out	pointerto	<struct rusage>	rusage,
	out	bufferof	<struct cpu_mon>	hw_events,
	out	pointerto	int		rtflags)

synchronous void
return(
	in	valueof		objid_t		objid,
	in	valueof		cell_t		sender,
	in	valueof		tk_set_t	to_return,
	in	valueof		tk_set_t	to_refuse,
	in	valueof		tk_set_t	unknown,
	in	valueof		tk_disp_t	why)

synchronous void
return_unknown(
	in	valueof		objid_t		objid,
	in	valueof		cell_t		sender,
	in	valueof		tk_set_t	unknown,
	in	valueof		tk_disp_t	why)

synchronous void
reparent(
	in	valueof		objid_t		objid,
	in	valueof		int		to_detach)

synchronous int
sendsig(
	in	valueof		objid_t		objid,
	in	valueof		int		sig,
	in	valueof		int		flags,
	in	valueof		pid_t		sid,
	in	valueof		credid_t	credid,
	in	bufferof	<struct k_siginfo> info)

synchronous int
setpgid(
	in	valueof		objid_t		objid,
	in	valueof		pid_t		pgid,
	in	valueof		pid_t		callers_pid,
	in	valueof		pid_t		callers_sid)

synchronous void
pgrp_linkage(
	in	valueof		objid_t		objid,
	in	valueof		pid_t		parent_pgid,
	in	valueof		pid_t		parent_sid)

synchronous int
ctty_access(
	in	valueof		objid_t		objid,
	in	valueof		<enum jobcontrol> access)

synchronous int
ctty_clear(
	in	valueof		objid_t		objid)

synchronous void
ctty_hangup(
	in	valueof		objid_t		objid)

synchronous void
getvpagg(
	in	pointerto	obj_handle_t		handle,
	out	pointerto	<struct vpagg_s *>	vpagp)

synchronous void
setvpagg(
	in	pointerto	obj_handle_t	handle,
	in	pointerto	vpagg_t 	vpag)

synchronous void
getprnode(
	in	valueof		objid_t		objid,
        in      valueof         int             flag,
        in      pointerto       cfs_handle_t    vfshandle,
        out     pointerto       cfs_handle_t    vnhandle)

synchronous int
procblk(
	in	valueof		objid_t		objid,
	in	valueof		int		action,
	in	valueof		int		count,
	in	valueof		credid_t	crid,
	in	valueof		int		isself)

synchronous int
prctl(
	in	valueof		objid_t		objid,
	in	valueof		int		option,
	in	valueof		<sysarg_t>	arg,
	in	valueof		int		isself,
	in	valueof		credid_t	crid,
	in	valueof		<pid_t>		callers_pid,
	inout	pointerto	<union rval>	rvp)

synchronous int
set_unblkonexecpid(
	in	valueof		objid_t		objid,
	in	valueof		<pid_t>		unblkpid)

synchronous void
unblkpid(
	in	valueof		objid_t		objid)

synchronous void
getrlimit(
	in	valueof		objid_t		objid,
	in	valueof		int		which,
	out	pointerto	<struct rlimit>	lim)

asynchronous
client_retargetted(
	in	valueof		cell_t		client,
	in	valueof		<void *>	retarget_id)

callback int
fdt_dup(
	in	valueof		objid_t		objid,
	in	pointerto	vfile_export_t	vfe,
	out	pointerto	int		newfd)

synchronous void
setinfo_runq(
	in	valueof		objid_t		objid,
	in	valueof		int		rqtype,
	in	valueof		int		arg,
	out	pointerto	__int64_t	rval)

asynchronous
poll_wakeup(
	in	valueof		objid_t		objid,
	in	valueof		ushort_t	id,
	in	valueof		ushort_t	rotor)

synchronous int
getcomm(
	in	valueof		objid_t		objid,
	in	valueof		credid_t	crid,
	out	bufferof	char		buf)

synchronous void
get_xattr(
	in	valueof		objid_t		objid,
	in	valueof		int		flags,
	out	pointerto	vp_get_xattr_t	xattr)
