/**************************************************************************
 *									  *
 * 		 Copyright (C) 1995-1996 Silicon Graphics, Inc.		  *
 *									  *
 *  These coded instructions, statements, and computer programs  contain  *
 *  unpublished  proprietary  information of Silicon Graphics, Inc., and  *
 *  are protected by Federal copyright law.  They  may  not be disclosed  *
 *  to  third  parties  or copied or duplicated in any form, in whole or  *
 *  in part, without the prior written consent of Silicon Graphics, Inc.  *
 *									  *
 **************************************************************************/

#include "ksys/cell/subsysid.h"

/*
 * operations from client to server
 */
subsystem	"dssession"	DSSESSION_SUBSYSID

import <ksys/cell/tkm.h>
import <ksys/cell/service.h>
import <ksys/cell.h>
import <ksys/vsession.h>
import <sys/vnode.h>
import <fs/cfs/dv.h>

synchronous void
obtain(
	out	pointerto	int		errno,
	in	valueof		cell_t		sender,
	in	valueof		pid_t		pgid,
	in	valueof		tk_set_t	to_be_obtained,
	in	valueof		tk_set_t	to_be_returned,
	in	valueof		tk_disp_t	dofret,
	out	pointerto	tk_set_t	already_obtained,
	out	pointerto	tk_set_t	granted,
	out	pointerto	tk_set_t	refused,
	inout	pointerto	objid_t 	objid,
	out	pointerto	cell_t		relocated_to)

/*
 * call from client to server returning tokens
 */
synchronous void
return(
	in	valueof		cell_t		sender,
	in	valueof		objid_t 	objid,
	in	valueof		tk_set_t	to_be_returned,
	in	valueof		tk_set_t	unknown,
	in	valueof		tk_disp_t	why)

/*
 * Calls from client cell to server:
 */           

/* join not required */

synchronous void
leave(
	in	valueof		cell_t		client,
	in	valueof		objid_t		objid,
	in	valueof		pid_t		sid)

synchronous void
ctty_alloc(
	in	valueof		objid_t		objid,
	in	valueof		pid_t		sid,
	in	pointerto	cfs_handle_t	ctty_handlep,
	out	pointerto	int		error)

synchronous void
ctty_dealloc(
	in	valueof		objid_t		objid,
	in	valueof		pid_t		sid,
	in	valueof		int		ishangup)

/* ctty_hold not required */

synchronous void
ctty_getvnode(
	in	valueof		objid_t		objid,
	in	valueof		pid_t		sid,
	out	pointerto	cfs_handle_t	ctty_handlep,
	out	pointerto	int		error)

/* ctty_rele not required */

/* ctty_wait not required */

synchronous void
ctty_devnum(
	in	valueof		objid_t		objid,
	in	valueof		pid_t		sid,
	out	pointerto	dev_t		devnump)
