/*
 * Copyright (c) Hewlett-Packard Company 1995
 * Unpublished work. All Rights Reserved.
 *
 * HISTORY
 * $Log: ufs_trace.h,v $
 * Revision 65.2  1999/02/04 19:19:45  mek
 * Provide C style include file for IRIX kernel integration.
 *
 * Revision 65.1  1997/10/20 19:20:28  jdoak
 * *** empty log message ***
 *
 * Revision /main/brezak_transarc/1  1995/06/01  22:10 UTC  brezak
 * 	machdep makefile for RIOS
 *
 * Revision /main/brezak_transarc/1  1995/05/24  22:33 UTC  brezak
 * 	Messages for icl traces
 * 	[1995/05/24  14:49 UTC  brezak  /main/brezak_mothra10/1]
 *
 * $EndLog$
 */

/*
 * ufs_trace.h:
 * This file is automatically generated; please do not edit it.
 */
#define UFS_TRACE_NULL                           (704008192L)
#define UFS_TRACE_END_ERROR                      (704008193L)
#define UFS_TRACE_ENTER_AGHOLD                   (704008194L)
#define UFS_TRACE_ENTER_AGRELE                   (704008195L)
#define UFS_TRACE_ENTER_AGLOCK                   (704008196L)
#define UFS_TRACE_ENTER_AGUNLOCK                 (704008197L)
#define UFS_TRACE_ENTER_AGSTAT                   (704008198L)
#define UFS_TRACE_ENTER_AGCREATE                 (704008199L)
#define UFS_TRACE_ENTER_AGINFO                   (704008200L)
#define UFS_TRACE_ENTER_AGDETACH                 (704008201L)
#define UFS_TRACE_ENTER_AGATTACH                 (704008202L)
#define UFS_TRACE_ENTER_AGATTACH_LOOKUP          (704008203L)
#define UFS_TRACE_AGSYNC                         (704008204L)
#define UFS_TRACE_ENTER_VOLHOLD                  (704008205L)
#define UFS_TRACE_ENTER_VOLRELE                  (704008206L)
#define UFS_TRACE_ENTER_VOLLOCK                  (704008207L)
#define UFS_TRACE_ENTER_VOLUNLOCK                (704008208L)
#define UFS_TRACE_ENTER_VOLOPEN                  (704008209L)
#define UFS_TRACE_VOLOPEN_CONCUR                 (704008210L)
#define UFS_TRACE_ENTER_VOLSEEK                  (704008211L)
#define UFS_TRACE_ENTER_VOLTELL                  (704008212L)
#define UFS_TRACE_ENTER_VOLSCAN                  (704008213L)
#define UFS_TRACE_ENTER_VOLCLOSE                 (704008214L)
#define UFS_TRACE_VOLDEPLETE                     (704008215L)
#define UFS_TRACE_VOLDESTROY                     (704008216L)
#define UFS_TRACE_ENTER_VOLATTACH                (704008217L)
#define UFS_TRACE_ENTER_VOLDETACH                (704008218L)
#define UFS_TRACE_ENTER_VOLGETSTATUS             (704008219L)
#define UFS_TRACE_ENTER_VOLSETSTATUS             (704008220L)
#define UFS_TRACE_ENTER_VOLCREATE                (704008221L)
#define UFS_TRACE_ENTER_VOLREAD                  (704008222L)
#define UFS_TRACE_ENTER_VOLWRITE                 (704008223L)
#define UFS_TRACE_ENTER_VOLREADHOLE              (704008224L)
#define UFS_TRACE_ENTER_VOLTRUNCATE              (704008225L)
#define UFS_TRACE_ENTER_VOLDELETE                (704008226L)
#define UFS_TRACE_ENTER_VOLGETATTR               (704008227L)
#define UFS_TRACE_ENTER_VOLSETATTR               (704008228L)
#define UFS_TRACE_ENTER_VOLGETACL                (704008229L)
#define UFS_TRACE_ENTER_VOLSETACL                (704008230L)
#define UFS_TRACE_VOLCLONE                       (704008231L)
#define UFS_TRACE_VOLRECLONE                     (704008232L)
#define UFS_TRACE_VOLUNCLONE                     (704008233L)
#define UFS_TRACE_ENTER_VOLVGET                  (704008234L)
#define UFS_TRACE_ENTER_VOLROOT                  (704008235L)
#define UFS_TRACE_VOLISROOT                      (704008236L)
#define UFS_TRACE_VOLGETVV                       (704008237L)
#define UFS_TRACE_ENTER_VOLSETDYSTAT             (704008238L)
#define UFS_TRACE_VOLSETNEWVID                   (704008239L)
#define UFS_TRACE_VOLCOPYACL                     (704008240L)
#define UFS_TRACE_ENTER_VOLFREEDYSTAT            (704008241L)
#define UFS_TRACE_VOLCONCURR                     (704008242L)
#define UFS_TRACE_VOLSWAPIDS                     (704008243L)
#define UFS_TRACE_VOLSYNC                        (704008244L)
#define UFS_TRACE_VOLPUSHSTATUS                  (704008245L)
#define UFS_TRACE_VOLREADDIR                     (704008246L)
#define UFS_TRACE_VOLAPPENDDIR                   (704008247L)
#define UFS_TRACE_VOLGETZLC                      (704008248L)
#define UFS_TRACE_ENTER_VOLGETNEXTHOLES          (704008249L)
#define UFS_TRACE_VOLBULKSETSTATUS               (704008250L)
#define UFS_TRACE_END_AGLOCK                     (704008251L)
#define UFS_TRACE_END_AGUNLOCK                   (704008252L)
#define UFS_TRACE_END_AGSTAT                     (704008253L)
#define UFS_TRACE_END_AGCREATE                   (704008254L)
#define UFS_TRACE_END_VOLINFO_BADIX              (704008255L)
#define UFS_TRACE_END_VOLINFO_BADVOL             (704008256L)
#define UFS_TRACE_END_VOLINFO                    (704008257L)
#define UFS_TRACE_END_AGDETACH                   (704008258L)
#define UFS_TRACE_END_AGATTACH_COPYIN            (704008259L)
#define UFS_TRACE_END_AGATTACH_LNAME             (704008260L)
#define UFS_TRACE_END_AGATTACH_MTYPE             (704008261L)
#define UFS_TRACE_END_AGATTACH_INVAL             (704008262L)
#define UFS_TRACE_END_AGATTACH                   (704008263L)
#define UFS_TRACE_END_VOLHOLD                    (704008264L)
#define UFS_TRACE_END_VOLRELE                    (704008265L)
#define UFS_TRACE_END_VOLLOCK                    (704008266L)
#define UFS_TRACE_END_VOLUNLOCK                  (704008267L)
#define UFS_TRACE_END_VOLOPEN                    (704008268L)
#define UFS_TRACE_END_VOLSEEK                    (704008269L)
#define UFS_TRACE_END_VOLTELL                    (704008270L)
#define UFS_TRACE_END_VOLSCAN_SEEK               (704008271L)
#define UFS_TRACE_END_VOLSCAN                    (704008272L)
#define UFS_TRACE_END_VOLCLOSE                   (704008273L)
#define UFS_TRACE_END_VOLATTACH_TA               (704008274L)
#define UFS_TRACE_END_VOLATTACH                  (704008275L)
#define UFS_TRACE_END_VOLDETACH                  (704008276L)
#define UFS_TRACE_END_VOLGETSTATUS_UFSSTAT       (704008277L)
#define UFS_TRACE_END_VOLGETSTATUS               (704008278L)
#define UFS_TRACE_END_VOLSETSTATUS               (704008279L)
#define UFS_TRACE_END_VOLCREATE_DEL              (704008280L)
#define UFS_TRACE_END_VOLCREATE_SCAN             (704008281L)
#define UFS_TRACE_END_VOLCREATE                  (704008282L)
#define UFS_TRACE_END_VOLREAD_VGET               (704008283L)
#define UFS_TRACE_END_VOLREAD                    (704008284L)
#define UFS_TRACE_END_VOLWRITE_VGET              (704008285L)
#define UFS_TRACE_END_VOLWRITE                   (704008286L)
#define UFS_TRACE_END_VOLREADHOLE                (704008287L)
#define UFS_TRACE_END_VOLTRUNC_VGET              (704008288L)
#define UFS_TRACE_END_VOLTRUNC                   (704008289L)
#define UFS_TRACE_END_VOLDELETE                  (704008290L)
#define UFS_TRACE_END_VOLGETATTR_VGET            (704008291L)
#define UFS_TRACE_END_VOLGETATTR                 (704008292L)
#define UFS_TRACE_END_VOLSETATTR_VGET            (704008293L)
#define UFS_TRACE_END_VOLSETATTR                 (704008294L)
#define UFS_TRACE_END_VOLGETACL_VGET             (704008295L)
#define UFS_TRACE_END_VOLGETACL                  (704008296L)
#define UFS_TRACE_END_VOLSETACL_VGET             (704008297L)
#define UFS_TRACE_END_VOLSETACL                  (704008298L)
#define UFS_TRACE_END_VOLVGET                    (704008299L)
#define UFS_TRACE_END_VOLROOT_ROOT               (704008300L)
#define UFS_TRACE_END_VOLROOT                    (704008301L)
#define UFS_TRACE_END_VOLSETDYSTAT               (704008302L)
#define UFS_TRACE_END_VOLFREEDYSTAT              (704008303L)
#define UFS_TRACE_END_VOLREADDIR_VGET            (704008304L)
#define UFS_TRACE_END_VOLREADDIR                 (704008305L)
#define UFS_TRACE_END_VOLAPPENDDIR_VGET          (704008306L)
#define UFS_TRACE_END_VOLAPPENDDIR               (704008307L)
#define UFS_TRACE_END_VOLGETNEXTHOLES_VGET       (704008308L)
#define UFS_TRACE_END_VOLGETNEXTHOLES            (704008309L)
#define initialize_zuf_error_table()
#define ERROR_TABLE_BASE_zuf (704008192L)

/* for compatibility with older versions... */
#define init_zuf_err_tbl initialize_zuf_error_table
#define zuf_err_base ERROR_TABLE_BASE_zuf
