'\"macro stdmacro
.if n .pH g2.sgi_sesmgr @(#)sgi_sesmgr	30.11 of 11/29/95
.TH sgi_sesmgr 2
.SH NAME
sgi_sesmgr \- SGI Session Manager
.Op c p a
.SH C SYNOPSIS
.B #include <sys/sesmgr.h>
.PP
.B #include <sys/t6api_private.h>
.PP
.B "int sgi_sesmgr(struct syssesmgra *uap, ... /\(** arg \(**/);"
.SH DESCRIPTION
.I sgi_sesmgr\^
is an internal SGI function.
See manual pages satmp_done(2),
satmp_init(2),
satmp_get_attr_reply(2),
satmp_get_lrtok_reply(2), 
satmp(7),
t6ext_attr(3N),
t6new_attr(3N),
t6mls_socket(3N),
t6get_endpt_mask(3N),
t6set_endpt_mask(3N),
t6get_endpt_default(3N),
t6set_endpt_default(3N)
t6last_attr(3N),
t6peek_attr(3N),
t6recvfrom(3N),
t6sendto(3N),
t6rhdb_put_host(3N),
t6rhdb_get_host(3N),
t6rhdb_flush(3N),
t6rhdb_stat(3N) and
libt6(3N)
for user level APIs information.
.SH SOURCE
Trusted Systems Interoperability Group
.SH NOTES
