#ident "cmd/head/Makefile: $Revision: 1.5 $"

include	$(ROOT)/usr/include/make/commondefs

TARGETS=head

default: $(TARGETS)

include $(COMMONRULES)

install: default
	$(INSTALL) -F /usr/bsd $(TARGETS)
