DIAGDEPTH= ../..
include ${DIAGDEPTH}/Makedefs

HFILES= tlb.h
CFILES= mem.c mod.c nocache.c pid.c purge.c translate.c \
	valid.c utlb_miss.c tlbtest.c

ASFILES= tfptlb.s

include ${DIAGDEPTH}/Makerules
