.if n .pH ddi.rm/d2/gen/print @(#)print	43.9 of 11/25/92
.\" Copyright 1992, 1991 UNIX System Laboratories, Inc.
.TH print D2
.IX "\f4print\fP(D2)"
.SH "NAME"
\f4print\fP \- display a driver message on the system console
.SH "SYNOPSIS"
.nf
.na
.ft 4
#include <sys/types.h>
#include <sys/errno.h>
#include <sys/ddi.h>
.sp 0.4
int \f2prefix\fPprint(dev_t \f2dev\fP, char *\f2str\fP);
.ft 1
.ad
.fi
.SS Arguments
.RS 0
.IP \f2dev\fP 10n
Device number.
.IP \f2str\fP 10n
Pointer to a NULL-terminated character string describing the problem.
.RE
.SH "DESCRIPTION"
The
\f4print\fP routine is called indirectly by the kernel for the block device
when the kernel has detected an exceptional condition
(such as out of space) in the device.
The driver should print the message on the console along with
any driver-specific information.
.SS "Return Values"
Ignored
.SH USAGE
This entry point is optional,
and is valid for block device drivers only.
.P
To display the message on the console,
the driver should use the \f4cmn_err\fP(D3) function.
.IX "\f4cmn_err\fP(D3)"
.P
The driver should not try to interpret the text string passed to it.
.SS "Synchronization Constraints"
The \f4print\fP routine should not call any functions that sleep.
.SH REFERENCES
.na
\f4cmn_err\fP(D3)
.ad
