.if n .pH ddi.rm/d2/gen/unload @(#)unload	43.17 of 11/25/92
.\" Copyright 1992 UNIX System Laboratories, Inc.
.TH unload D2
.SH NAME
\f4unload\fP \- unload a loadable kernel module
.IX "\f4unload\fP(D2)"
.SH SYNOPSIS
.nf
.na
.ft 4
.sp 0.4
int \f2prefix\fPunload(void);
.ft 1
.ad
.fi
.SH DESCRIPTION
The module \f4unload\fP routine
handles any cleanup a loadable kernel module must perform
before it can be dynamically unloaded from a running system.
.SS "Return Values"
The \f4unload\fP routine should return 0 for success,
or the appropriate error number.
.SH USAGE
This entry point is optional.
.P
The \f4unload\fP routine can perform activities such as:
.RS 0
.IP
deallocate memory acquired for private data
.IP
cancel any outstanding \f4itimeout\fP(D3) or \f4bufcall\fP(D3) requests
made by the module
.RE
.SS "Synchronization Constraints"
The \f4unload\fP routine should not sleep,
and should not call any functions that sleep.
