#!/bin/csh
set totmemsize=`hinv -t memory | nawk '{print $4}'`
set fracsize=`expr $totmemsize \* 3 / 10`
echo Starting splock test on ${fracsize} megs of memory | tee -a /usr/tmp/ostests.log
echo "OS SPLOCK Log file" > /usr/tmp/os-splock.log
date >> /usr/tmp/os-splock.log
/usr/diags/os/bin/splocks -m ${fracsize} -l 1000 >>& /usr/tmp/os-splock.log &
