#ifndef WIN_H
#define WIN_H

#ident "$Header: /proj/irix6.5.7m/isms/eoe/cmd/xfs/dump/restore/RCS/win.h,v 1.2 1995/07/20 22:59:46 cbullis Exp $"

/* win.[ch] - windows into a very large file
 */

/* initialize the window abstraction
 */
void win_init( intgen_t fd,
	       off64_t rngoff,		/* offset into file of windowing */
	       size_t winsz,		/* window size */
	       size_t wincntmax );	/* max number of windows to manage */

/* supply a pointer to the portion of the file identified by off.
 */
void win_map( off64_t off,		/* file offset relative to rngoff */
	      void **pp );		/* returns pointer by reference */

/* invalidate the pointer previously supplied. SIDE-EFFECT: zeros
 * by reference the caller's pointer.
 */
void win_unmap( off64_t off,		/* must match win_map param */
	        void **pp );		/* ptr generated by win_map: ZEROED */

#endif /* WIN_H */
