#
# /etc/cshrc - Default settings for all csh users
#
# This is 'sourced' before $HOME/.cshrc, which in turn preceeds $HOME/.login
# when a csh user logs in or invokes /bin/su with the `-' option.

# Tell the shell where to look for mail.
if ($?MAIL == 0) setenv MAIL /usr/mail/$USER
set mail=$MAIL

if (! $?ENVONLY) then

	# Print the message of the day.
	cat -s /etc/motd

	# Check for mail.
	if ( -e /bin/mail ) then
	    if ( { /bin/mail -e } ) then
		echo 'You have mail.'
	    endif
	endif
endif

setenv MSGVERB text:action
setenv NOMSGLABEL 1
setenv NOMSGSEVERITY 1
