/* Layout file created by tedit */

#ifndef TUDONTAUTOINCLUDE
#include "tuLabelMenuItem.h"
#include "tuMenu.h"
#include "tuSeparator.h"
#include "tuMenuBar.h"
#endif /* TUDONTAUTOINCLUDE */

#ifdef TUREGISTERGADGETS
#undef TUREGISTERGADGETS
#endif /* TUREGISTERGADGETS */
#define TUREGISTERGADGETS { \
    tuLabelMenuItem::registerForPickling(); \
    tuMenu::registerForPickling(); \
    tuSeparator::registerForPickling(); \
    tuMenuBar::registerForPickling(); \
}

static char* layoutstr =
"(MenuBar "
 "(rows 1) "
 "(cols 6) "
 "(defaultAlignment 0) "
 "(resources "
  "((horizontalOffset 5) "
   "(fixedHeight True))) "
 "(child "
  "(LabelMenuItem "
   "(subMenu "
    "(Menu "
     "(rows 5) "
     "(cols 1) "
     "(defaultAlignment 3) "
     "(ownParent True) "
     "(title File) "
     "(resources "
      "((topInset 4) "
       "(bottomInset 4) "
       "(leftInset 4) "
       "(rightInset 4) "
       "(horizontalOffset 2))) "
     "(child "
      "(LabelMenuItem  "
       "(resources "
        "((callback File_open) "
         "(accelerator Alt\\ o) "
         "(labelString Open...))))) "
     "(constraint R0C0A3) "
     "(child "
      "(LabelMenuItem "
       "(subMenu "
        "(Menu "
         "(rows 2) "
         "(cols 1) "
         "(defaultAlignment 3) "
         "(ownParent True) "
         "(resources "
          "((topInset 4) "
           "(bottomInset 4) "
           "(leftInset 4) "
           "(rightInset 4) "
           "(horizontalOffset 2))) "
         "(child "
          "(LabelMenuItem  "
           "(resources "
            "((callback Save_data) "
             "(accelerator Alt\\ !Shift\\ s) "
             "(labelString Save))))) "
         "(constraint R0C0A3) "
         "(child "
          "(LabelMenuItem  "
           "(resources "
            "((callback Save_dataas) "
             "(accelerator \\\"Alt-S\\\"\\ Shift\\ Alt\\ s) "
             "(labelString Save\\ As...))))) "
         "(constraint R1C0A3))) "
       "(resources "
        "((callback ) "
         "(labelString Save\\ Networks))))) "
     "(constraint R1C0A3) "
     "(child "
      "(LabelMenuItem "
       "(subMenu "
        "(Menu "
         "(rows 2) "
         "(cols 1) "
         "(defaultAlignment 3) "
         "(ownParent True) "
         "(resources "
          "((topInset 4) "
           "(bottomInset 4) "
           "(leftInset 4) "
           "(rightInset 4) "
           "(horizontalOffset 2))) "
         "(child "
          "(LabelMenuItem  "
           "(resources "
            "((callback Save_ui) "
             "(accelerator Control\\ !Shift\\ s) "
             "(labelString Save))))) "
         "(constraint R0C0A3) "
         "(child "
          "(LabelMenuItem  "
           "(resources "
            "((callback Save_uias) "
             "(accelerator \\\"Ctrl-S\\\"\\ Shift\\ Control\\ s) "
             "(labelString Save\\ As...))))) "
         "(constraint R1C0A3))) "
       "(resources "
        "((callback File_save) "
         "(labelString Save\\ Controls))))) "
     "(constraint R2C0A3) "
     "(child "
      "(Separator "
       "(orientation horizontal))) "
     "(constraint R3C0A3) "
     "(child "
      "(LabelMenuItem  "
       "(resources "
        "((callback File_quit) "
         "(accelerator Alt\\ q) "
         "(labelString Quit))))) "
     "(constraint R4C0A3))) "
   "(resources "
    "((labelString File))))) "
 "(constraint R0C0A0) "
 "(child "
  "(LabelMenuItem "
   "(subMenu "
    "(Menu "
     "(rows 5) "
     "(cols 1) "
     "(defaultAlignment 3) "
     "(ownParent True) "
     "(title Controls) "
     "(resources "
      "((topInset 4) "
       "(bottomInset 4) "
       "(leftInset 4) "
       "(rightInset 4) "
       "(horizontalOffset 2))) "
     "(child "
      "(LabelMenuItem  "
       "(resources "
        "((callback Gadget_snoop) "
         "(labelString Snoop...))))) "
     "(constraint R0C0A3) "
     "(child "
      "(LabelMenuItem  "
       "(resources "
        "((callback Gadget_map) "
         "(labelString Map...))))) "
     "(constraint R1C0A3) "
     "(child "
      "(LabelMenuItem  "
       "(resources "
        "((callback Gadget_netnode) "
         "(labelString NetNode...))))) "
     "(constraint R2C0A3) "
     "(child "
      "(LabelMenuItem  "
       "(resources "
        "((callback Gadget_traffic) "
         "(labelString Traffic...))))) "
     "(constraint R3C0A3) "
     "(child "
      "(LabelMenuItem  "
       "(resources "
        "((callback Gadget_hide) "
         "(labelString Hide...))))) "
     "(constraint R4C0A3))) "
   "(resources "
    "((labelString Controls))))) "
 "(constraint R0C1A0) "
 "(child "
  "(LabelMenuItem "
   "(subMenu "
    "(Menu "
     "(instanceName Menu_Actions) "
     "(rows 8) "
     "(cols 1) "
     "(defaultAlignment 3) "
     "(ownParent True) "
     "(title Actions) "
     "(resources "
      "((topInset 4) "
       "(bottomInset 4) "
       "(leftInset 4) "
       "(rightInset 4) "
       "(horizontalOffset 2))) "
     "(child "
      "(LabelMenuItem  "
       "(resources "
        "((callback Action_info) "
         "(accelerator Alt\\ i) "
         "(labelString Information))))) "
     "(constraint R0C0A3) "
     "(child "
      "(LabelMenuItem "
       "(instanceName Action_find)  "
       "(resources "
        "((callback Action_find) "
         "(accelerator Alt\\ f) "
         "(labelString Find...))))) "
     "(constraint R1C0A3) "
     "(child "
      "(LabelMenuItem "
       "(instanceName Action_ping)  "
       "(resources "
        "((callback Action_ping) "
         "(accelerator Alt\\ p) "
         "(labelString Ping...))))) "
     "(constraint R2C0A3) "
     "(child "
      "(LabelMenuItem "
       "(instanceName Action_trace)  "
       "(resources "
        "((callback Action_trace) "
         "(accelerator Alt\\ t) "
         "(labelString Trace\\ Route...))))) "
     "(constraint R3C0A3) "
     "(child "
      "(Separator "
       "(orientation horizontal))) "
     "(constraint R4C0A3) "
     "(child "
      "(LabelMenuItem  "
       "(resources "
        "((callback Action_home) "
         "(accelerator Home) "
         "(labelString Home))))) "
     "(constraint R5C0A3) "
     "(child "
      "(LabelMenuItem "
       "(instanceName Action_delete)  "
       "(resources "
        "((callback Action_delete) "
         "(accelerator Alt\\ d) "
         "(labelString Delete...))))) "
     "(constraint R6C0A3) "
     "(child "
      "(LabelMenuItem  "
       "(resources "
        "((callback Action_deleteAll) "
         "(accelerator Alt\\ a) "
         "(labelString Delete\\ All))))) "
     "(constraint R7C0A3))) "
   "(resources "
    "((labelString Actions))))) "
 "(constraint R0C2A0) "
 "(child "
  "(LabelMenuItem "
   "(subMenu "
    "(Menu "
     "(rows 5) "
     "(cols 1) "
     "(defaultAlignment 3) "
     "(ownParent True) "
     "(title Tools) "
     "(resources "
      "((topInset 4) "
       "(bottomInset 4) "
       "(leftInset 4) "
       "(rightInset 4) "
       "(horizontalOffset 2))) "
     "(child "
      "(LabelMenuItem  "
       "(resources "
        "((callback Tool_analyzer) "
         "(labelString Analyzer))))) "
     "(constraint R0C0A3) "
     "(child "
      "(LabelMenuItem  "
       "(resources "
        "((callback Tool_browser) "
         "(labelString Browser))))) "
     "(constraint R1C0A3) "
     "(child "
      "(LabelMenuItem  "
       "(resources "
        "((callback Tool_netgraph) "
         "(labelString NetGraph))))) "
     "(constraint R2C0A3) "
     "(child "
      "(LabelMenuItem  "
       "(resources "
        "((callback Tool_netlook) "
         "(labelString NetLook))))) "
     "(constraint R3C0A3) "
     "(child "
      "(LabelMenuItem  "
       "(resources "
        "((callback Tool_nettop) "
         "(labelString NetTop))))) "
     "(constraint R4C0A3))) "
   "(resources "
    "((labelString Tools))))) "
 "(constraint R0C3A0) "
 "(child "
  "(LabelMenuItem "
   "(subMenu "
    "(Menu "
     "(rows 6) "
     "(cols 1) "
     "(defaultAlignment 3) "
     "(ownParent True) "
     "(title Help) "
     "(resources "
      "((topInset 4) "
       "(bottomInset 4) "
       "(leftInset 4) "
       "(rightInset 4) "
       "(horizontalOffset 2))) "
     "(child "
      "(LabelMenuItem  "
       "(resources "
        "((callback Help_general) "
         "(accelerator Alt\\ h) "
         "(labelString Introduction))))) "
     "(constraint R0C0A3) "
     "(child "
      "(LabelMenuItem  "
       "(resources "
        "((callback Help_main) "
         "(labelString Main\\ Window))))) "
     "(constraint R1C0A3) "
     "(child "
      "(LabelMenuItem "
       "(subMenu "
        "(Menu "
         "(rows 2) "
         "(cols 1) "
         "(defaultAlignment 3) "
         "(ownParent True) "
         "(resources "
          "((topInset 4) "
           "(bottomInset 4) "
           "(leftInset 4) "
           "(rightInset 4) "
           "(horizontalOffset 2))) "
         "(child "
          "(LabelMenuItem  "
           "(resources "
            "((callback Help_data) "
             "(labelString Network\\ Data\\ Files))))) "
         "(constraint R0C0A3) "
         "(child "
          "(LabelMenuItem  "
           "(resources "
            "((callback Help_ui) "
             "(labelString Controls\\ Files))))) "
         "(constraint R1C0A3))) "
       "(resources "
        "((labelString File))))) "
     "(constraint R2C0A3) "
     "(child "
      "(LabelMenuItem "
       "(subMenu "
        "(Menu "
         "(rows 5) "
         "(cols 1) "
         "(defaultAlignment 3) "
         "(ownParent True) "
         "(resources "
          "((topInset 4) "
           "(bottomInset 4) "
           "(leftInset 4) "
           "(rightInset 4) "
           "(horizontalOffset 2))) "
         "(child "
          "(LabelMenuItem  "
           "(resources "
            "((callback Help_snoop) "
             "(labelString Snoop))))) "
         "(constraint R0C0A3) "
         "(child "
          "(LabelMenuItem  "
           "(resources "
            "((callback Help_map) "
             "(labelString Map))))) "
         "(constraint R1C0A3) "
         "(child "
          "(LabelMenuItem  "
           "(resources "
            "((callback Help_netnode) "
             "(labelString NetNode))))) "
         "(constraint R2C0A3) "
         "(child "
          "(LabelMenuItem  "
           "(resources "
            "((callback Help_traffic) "
             "(labelString Traffic))))) "
         "(constraint R3C0A3) "
         "(child "
          "(LabelMenuItem  "
           "(resources "
            "((callback Help_hide) "
             "(labelString Hide))))) "
         "(constraint R4C0A3))) "
       "(resources "
        "((labelString Controls))))) "
     "(constraint R3C0A3) "
     "(child "
      "(LabelMenuItem "
       "(subMenu "
        "(Menu "
         "(rows 7) "
         "(cols 1) "
         "(defaultAlignment 3) "
         "(ownParent True) "
         "(resources "
          "((topInset 4) "
           "(bottomInset 4) "
           "(leftInset 4) "
           "(rightInset 4) "
           "(horizontalOffset 2))) "
         "(child "
          "(LabelMenuItem  "
           "(resources "
            "((callback Help_info) "
             "(labelString Information))))) "
         "(constraint R0C0A3) "
         "(child "
          "(LabelMenuItem  "
           "(resources "
            "((callback Help_find) "
             "(labelString Find))))) "
         "(constraint R1C0A3) "
         "(child "
          "(LabelMenuItem  "
           "(resources "
            "((callback Help_ping) "
             "(labelString Ping))))) "
         "(constraint R2C0A3) "
         "(child "
          "(LabelMenuItem  "
           "(resources "
            "((callback Help_trace) "
             "(labelString Trace\\ Route))))) "
         "(constraint R3C0A3) "
         "(child "
          "(LabelMenuItem  "
           "(resources "
            "((callback Help_home) "
             "(labelString Home))))) "
         "(constraint R4C0A3) "
         "(child "
          "(LabelMenuItem  "
           "(resources "
            "((callback Help_delete) "
             "(labelString Delete))))) "
         "(constraint R5C0A3) "
         "(child "
          "(LabelMenuItem  "
           "(resources "
            "((callback Help_new) "
             "(labelString Delete\\ All))))) "
         "(constraint R6C0A3))) "
       "(resources "
        "((labelString Actions))))) "
     "(constraint R4C0A3) "
     "(child "
      "(LabelMenuItem  "
       "(resources "
        "((callback Help_tools) "
         "(labelString Tools))))) "
     "(constraint R5C0A3))) "
   "(resources "
    "((labelString Help))))) "
 "(constraint R0C5A0))";
