/* Layout file created by tedit */

#ifndef TUDONTAUTOINCLUDE
#include "tuCheckBox.h"
#include "tuLabel.h"
#include "tuRadioButton.h"
#include "tuRowColumn.h"
#include "tuSeparator.h"
#include "tuGap.h"
#include "tuLabelButton.h"
#endif /* TUDONTAUTOINCLUDE */

#ifdef TUREGISTERGADGETS
#undef TUREGISTERGADGETS
#endif /* TUREGISTERGADGETS */
#define TUREGISTERGADGETS { \
    tuCheckBox::registerForPickling(); \
    tuLabel::registerForPickling(); \
    tuRadioButton::registerForPickling(); \
    tuRowColumn::registerForPickling(); \
    tuSeparator::registerForPickling(); \
    tuGap::registerForPickling(); \
    tuLabelButton::registerForPickling(); \
}

static char* layoutstr =
"(RowColumn "
 "(rows 11) "
 "(cols 1) "
 "(growdir vertical) "
 "(defaultAlignment 0) "
 "(resources "
  "((topInset 8) "
   "(bottomInset 8) "
   "(leftInset 8) "
   "(rightInset 8) "
   "(horizontalOffset 8) "
   "(verticalOffset 8))) "
 "(child "
  "(CheckBox "
   "(instanceName Network_ignore) "
   "(resources "
    "((callback Network_ignore) "
     "(labelString Ignore\\ new\\ networks))))) "
 "(constraint R0C0A0) "
 "(child "
  "(CheckBox "
   "(instanceName Network_show) "
   "(resources "
    "((callback Network_show) "
     "(labelString Show\\ all\\ networks))))) "
 "(constraint R1C0A0) "
 "(child "
  "(Label "
   "(resources "
    "((labelString Label\\ networks:))))) "
 "(constraint R2C0A0) "
 "(child "
  "(RowColumn "
   "(rows 2) "
   "(cols 1) "
   "(defaultAlignment 0) "
   "(resources "
    "((leftInset 25) "
     "(rightInset 10) "
     "(horizontalOffset 10) "
     "(verticalOffset 5))) "
   "(child "
    "(RadioButton "
     "(instanceName Network_name) "
     "(resources "
      "((multichoice Network_label) "
       "(labelString by\\ name))))) "
   "(constraint R0C0A0) "
   "(child "
    "(RadioButton "
     "(instanceName Network_number) "
     "(resources "
      "((multichoice Network_label) "
       "(labelString by\\ IP\\ network\\ number))))) "
   "(constraint R1C0A0))) "
 "(constraint R3C0A0) "
 "(child "
  "(Separator "
   "(orientation horizontal))) "
 "(constraint R4C0A0) "
 "(child "
  "(CheckBox "
   "(instanceName Node_ignore) "
   "(resources "
    "((callback Node_ignore) "
     "(labelString Ignore\\ new\\ nodes))))) "
 "(constraint R5C0A0) "
 "(child "
  "(CheckBox "
   "(instanceName Node_show) "
   "(resources "
    "((callback Node_show) "
     "(labelString Show\\ all\\ nodes))))) "
 "(constraint R6C0A0) "
 "(child "
  "(Label "
   "(resources "
    "((labelString Label\\ nodes:))))) "
 "(constraint R7C0A0) "
 "(child "
  "(RowColumn "
   "(rows 6) "
   "(cols 1) "
   "(growdir vertical) "
   "(defaultAlignment 0) "
   "(resources "
    "((leftInset 25) "
     "(rightInset 10) "
     "(horizontalOffset 10) "
     "(verticalOffset 5))) "
   "(child "
    "(RadioButton "
     "(instanceName Node_full) "
     "(resources "
      "((multichoice Node_label) "
       "(labelString by\\ full\\ domain\\ name))))) "
   "(constraint R0C0A0) "
   "(child "
    "(RadioButton "
     "(instanceName Node_local) "
     "(resources "
      "((multichoice Node_label) "
       "(labelString by\\ local\\ host\\ name))))) "
   "(constraint R1C0A0) "
   "(child "
    "(RadioButton "
     "(instanceName Node_ip) "
     "(resources "
      "((multichoice Node_label) "
       "(labelString by\\ Internet\\ address))))) "
   "(constraint R2C0A0) "
   "(child "
    "(RadioButton "
     "(instanceName Node_dec) "
     "(resources "
      "((multichoice Node_label) "
       "(labelString by\\ DECnet\\ address))))) "
   "(constraint R3C0A0) "
   "(child "
    "(RadioButton "
     "(instanceName Node_vendor) "
     "(resources "
      "((multichoice Node_label) "
       "(labelString by\\ vendor\\ code))))) "
   "(constraint R4C0A0) "
   "(child "
    "(RadioButton "
     "(instanceName Node_physical) "
     "(resources "
      "((multichoice Node_label) "
       "(labelString by\\ physical\\ address))))) "
   "(constraint R5C0A0))) "
 "(constraint R8C0A0) "
 "(child "
  "(Separator "
   "(orientation horizontal))) "
 "(constraint R9C0A0) "
 "(child "
  "(RowColumn "
   "(rows 1) "
   "(cols 3) "
   "(defaultAlignment 0) "
   "(resources "
    "((horizontalOffset 8))) "
   "(child "
    "(Gap "
     "(orientation horizontal) "
     "(resources "
      "((minWidth 50))))) "
   "(constraint R0C0A0) "
   "(child "
    "(LabelButton "
     "(resources "
      "((callback NetNode_close) "
       "(accelerator Alt\\ c) "
       "(labelString Close))))) "
   "(constraint R0C1A0) "
   "(child "
    "(LabelButton "
     "(resources "
      "((callback NetNode_help) "
       "(accelerator Alt\\ h) "
       "(labelString Help))))) "
   "(constraint R0C2A0))) "
 "(constraint R10C0A0))";
