/* Layout file created by tedit */

#ifndef TUDONTAUTOINCLUDE
#include "tuLabel.h"
#include "tuTextField.h"
#include "tuFrame.h"
#include "tuLabelButton.h"
#include "tuRowColumn.h"
#include "tuGap.h"
#include "tuCheckBox.h"
#include "tuScrollView.h"
#endif /* TUDONTAUTOINCLUDE */

#ifdef TUREGISTERGADGETS
#undef TUREGISTERGADGETS
#endif /* TUREGISTERGADGETS */
#define TUREGISTERGADGETS { \
    tuLabel::registerForPickling(); \
    tuTextField::registerForPickling(); \
    tuFrame::registerForPickling(); \
    tuLabelButton::registerForPickling(); \
    tuRowColumn::registerForPickling(); \
    tuGap::registerForPickling(); \
    tuCheckBox::registerForPickling(); \
    tuScrollView::registerForPickling(); \
}

static char* layoutstr =
"(RowColumn "
 "(rows 3) "
 "(cols 1) "
 "(growdir vertical) "
 "(defaultAlignment 0) "
 "(resources "
  "((topInset 8) "
   "(bottomInset 8) "
   "(leftInset 8) "
   "(rightInset 8) "
   "(horizontalOffset 8) "
   "(verticalOffset 8))) "
 "(child "
  "(RowColumn "
   "(rows 1) "
   "(cols 3) "
   "(defaultAlignment 0) "
   "(resources "
    "((horizontalOffset 8) "
     "(fixedHeight True))) "
   "(child "
    "(Label "
     "(resources "
      "((labelString Filter:) "
       "(font -*-helvetica-bold-r-normal--14-100*))))) "
   "(constraint R0C0A4) "
   "(child "
    "(Frame "
     "(resources "
      "((frame Innie))) "
     "(child "
      "(TextField "
       "(instanceName Snoop_filtertext) "
       "(text ) "
       "(resources "
        "((terminatorCallBack Snoop_dofiltertext) "
         "(keepAllTextVisible False))))))) "
   "(constraint R0C1A4) "
   "(child "
    "(LabelButton "
     "(resources "
      "((callback Snoop_archiver) "
       "(labelString NetFilters))))) "
   "(constraint R0C2A4))) "
 "(constraint R0C0A0) "
 "(child "
  "(RowColumn "
   "(rows 2) "
   "(cols 1) "
   "(growdir vertical) "
   "(defaultAlignment 0) "
   "(resources "
    "((verticalOffset 2))) "
   "(child "
    "(RowColumn "
     "(rows 1) "
     "(cols 4) "
     "(defaultAlignment 1) "
     "(resources "
      "((fixedHeight True))) "
     "(child "
      "(Label "
       "(resources "
        "((labelString Snoop) "
         "(font -*-helvetica-bold-r-normal--14-*-*-*-p-82-iso8859-1))))) "
     "(constraint R0C0A1) "
     "(child "
      "(Gap "
       "(orientation horizontal))) "
     "(constraint R0C1A1) "
     "(child "
      "(Label "
       "(resources "
        "((labelString Data\\ Station) "
         "(font -*-helvetica-bold-r-normal--14-*-*-*-p-82-iso8859-1))))) "
     "(constraint R0C2A0) "
     "(child "
      "(Gap "
       "(orientation horizontal))) "
     "(constraint R0C3A1))) "
   "(constraint R0C0A0) "
   "(child "
    "(Frame "
     "(child "
      "(ScrollView "
       "(horizBar False) "
       "(vertBar True) "
       "(child "
        "(RowColumn "
         "(instanceName Snoop_container) "
         "(rows 1) "
         "(cols 2) "
         "(growdir vertical) "
         "(defaultAlignment 4) "
         "(resources "
          "((leftInset 8) "
           "(rightInset 8) "
           "(horizontalOffset 8) "
           "(verticalOffset 8))) "
         "(child "
          "(CheckBox "
           "(resources "
            "((labelString ))) "
           "(enabled False))) "
         "(constraint R0C0A4) "
         "(child "
          "(Frame "
           "(instanceName Snoop_entryfield) "
           "(resources "
            "((frame Innie))) "
           "(child "
            "(TextField "
             "(text ) "
             "(resources "
              "((terminatorCallBack Snoop_edit) "
               "(keepAllTextVisible False))))))) "
         "(constraint R0C1A4))))))) "
   "(constraint R1C0A0))) "
 "(constraint R1C0A0) "
 "(child "
  "(RowColumn "
   "(rows 1) "
   "(cols 3) "
   "(defaultAlignment 0) "
   "(resources "
    "((horizontalOffset 8) "
     "(fixedHeight True))) "
   "(child "
    "(Gap "
     "(orientation horizontal) "
     "(resources "
      "((minWidth 200))))) "
   "(constraint R0C0A0) "
   "(child "
    "(LabelButton "
     "(resources "
      "((callback Snoop_close) "
       "(accelerator Alt\\ c) "
       "(labelString Close))))) "
   "(constraint R0C1A0) "
   "(child "
    "(LabelButton "
     "(resources "
      "((callback Snoop_help) "
       "(accelerator Alt\\ h) "
       "(labelString Help))))) "
   "(constraint R0C2A0))) "
 "(constraint R2C0A0))";
