/* Layout file created by tedit */

#ifndef TUDONTAUTOINCLUDE
#include "tuLabel.h"
#include "tuRadioButton.h"
#include "tuRowColumn.h"
#include "tuDial.h"
#include "tuFrame.h"
#include "tuTextField.h"
#include "tuGap.h"
#include "tuCheckBox.h"
#include "tuSeparator.h"
#include "tuLabelButton.h"
#endif /* TUDONTAUTOINCLUDE */

#ifdef TUREGISTERGADGETS
#undef TUREGISTERGADGETS
#endif /* TUREGISTERGADGETS */
#define TUREGISTERGADGETS { \
    tuLabel::registerForPickling(); \
    tuRadioButton::registerForPickling(); \
    tuRowColumn::registerForPickling(); \
    tuDial::registerForPickling(); \
    tuFrame::registerForPickling(); \
    tuTextField::registerForPickling(); \
    tuGap::registerForPickling(); \
    tuCheckBox::registerForPickling(); \
    tuSeparator::registerForPickling(); \
    tuLabelButton::registerForPickling(); \
}

static char* layoutstr =
"(RowColumn "
 "(rows 8) "
 "(cols 1) "
 "(growdir vertical) "
 "(defaultAlignment 0) "
 "(resources "
  "((topInset 8) "
   "(bottomInset 8) "
   "(leftInset 8) "
   "(rightInset 8) "
   "(horizontalOffset 8) "
   "(verticalOffset 8))) "
 "(child "
  "(RowColumn "
   "(rows 2) "
   "(cols 1) "
   "(defaultAlignment 0) "
   "(resources "
    "((verticalOffset 3))) "
   "(child "
    "(Label "
     "(resources "
      "((labelString For\\ traffic:))))) "
   "(constraint R0C0A0) "
   "(child "
    "(RowColumn "
     "(rows 2) "
     "(cols 1) "
     "(defaultAlignment 0) "
     "(resources "
      "((leftInset 25) "
       "(horizontalOffset 10) "
       "(verticalOffset 5))) "
     "(child "
      "(RadioButton "
       "(instanceName Traffic_endpoint) "
       "(resources "
        "((multichoice Traffic_mode) "
         "(labelString show\\ the\\ source\\ and\\ destination))))) "
     "(constraint R0C0A0) "
     "(child "
      "(RadioButton "
       "(instanceName Traffic_hop) "
       "(resources "
        "((multichoice Traffic_mode) "
         "(labelString show\\ the\\ local\\ hop))))) "
     "(constraint R1C0A0))) "
   "(constraint R1C0A0))) "
 "(constraint R0C0A0) "
 "(child "
  "(RowColumn "
   "(rows 2) "
   "(cols 1) "
   "(defaultAlignment 0) "
   "(resources "
    "((verticalOffset 3))) "
   "(child "
    "(Label "
     "(resources "
      "((labelString Base\\ scale\\ of\\ traffic:))))) "
   "(constraint R0C0A0) "
   "(child "
    "(RowColumn "
     "(rows 2) "
     "(cols 1) "
     "(growdir vertical) "
     "(defaultAlignment 0) "
     "(resources "
      "((leftInset 25) "
       "(rightInset 10) "
       "(horizontalOffset 10) "
       "(verticalOffset 3))) "
     "(child "
      "(RadioButton "
       "(instanceName Traffic_packets) "
       "(resources "
        "((multichoice Traffic_basis) "
         "(labelString on\\ number\\ of\\ packets))))) "
     "(constraint R0C0A0) "
     "(child "
      "(RadioButton "
       "(instanceName Traffic_bytes) "
       "(resources "
        "((multichoice Traffic_basis) "
         "(labelString on\\ number\\ of\\ bytes))))) "
     "(constraint R1C0A0))) "
   "(constraint R1C0A0))) "
 "(constraint R1C0A0) "
 "(child "
  "(RowColumn "
   "(rows 2) "
   "(cols 1) "
   "(defaultAlignment 0) "
   "(child "
    "(Label "
     "(resources "
      "((labelString Each\\ color\\ step\\ represents:))))) "
   "(constraint R0C0A0) "
   "(child "
    "(RowColumn "
     "(rows 2) "
     "(cols 2) "
     "(defaultAlignment 0) "
     "(resources "
      "((leftInset 25) "
       "(horizontalOffset 35))) "
     "(child "
      "(Dial "
       "(instanceName Traffic_packetstepdial) "
       "(resources "
        "((callback Traffic_packetstep) "
         "(dragCallBack ) "
         "(lowerBound 1) "
         "(position 1) "
         "(startAngle -135) "
         "(angleRange -265) "
         "(numticks 10) "
         "(quantize True) "
         "(font -*-helvetica-medium-r-normal--12-*-*-*-p-*-iso8859-1))))) "
     "(constraint R0C0A5) "
     "(child "
      "(Dial "
       "(instanceName Traffic_bytestepdial) "
       "(resources "
        "((callback Traffic_bytestep) "
         "(lowerBound 1) "
         "(upperBound 8192) "
         "(position 1) "
         "(startAngle -135) "
         "(angleRange -265) "
         "(numticks 9) "
         "(font -*-helvetica-medium-r-normal--8-*-*-*-p-*-iso8859-1))))) "
     "(constraint R0C1A5) "
     "(child "
      "(Label "
       "(instanceName Traffic_packetsteplabel) "
       "(resources "
        "((labelString Packets))))) "
     "(constraint R1C0A1) "
     "(child "
      "(Label "
       "(instanceName Traffic_bytesteplabel) "
       "(resources "
        "((labelString Bytes))))) "
     "(constraint R1C1A1))) "
   "(constraint R1C0A0))) "
 "(constraint R2C0A0) "
 "(child "
  "(RowColumn "
   "(rows 2) "
   "(cols 1) "
   "(defaultAlignment 0) "
   "(child "
    "(Label "
     "(resources "
      "((labelString Traffic\\ volume\\ colormap\\ indicies:))))) "
   "(constraint R0C0A0) "
   "(child "
    "(RowColumn "
     "(rows 4) "
     "(cols 1) "
     "(defaultAlignment 0) "
     "(resources "
      "((leftInset 25) "
       "(rightInset 8) "
       "(horizontalOffset 8) "
       "(verticalOffset 3))) "
     "(child "
      "(Frame "
       "(instanceName Traffic_tile_parent))) "
     "(constraint R1C0A4) "
     "(child "
      "(RowColumn "
       "(rows 2) "
       "(cols 3) "
       "(defaultAlignment 0) "
       "(child "
        "(Frame "
         "(resources "
          "((frame Innie))) "
         "(child "
          "(TextField "
           "(instanceName Traffic_mincolor) "
           "(text ) "
           "(resources "
            "((terminatorCallBack Traffic_mincolor) "
             "(keepAllTextVisible False))))))) "
       "(constraint R0C0A0) "
       "(child "
        "(Gap "
         "(orientation horizontal) "
         "(resources "
          "((minWidth 110))))) "
       "(constraint R0C1A1) "
       "(child "
        "(Frame "
         "(resources "
          "((frame Innie))) "
         "(child "
          "(TextField "
           "(instanceName Traffic_maxcolor) "
           "(text ) "
           "(resources "
            "((terminatorCallBack Traffic_maxcolor) "
             "(keepAllTextVisible False))))))) "
       "(constraint R0C2A0) "
       "(child "
        "(Label "
         "(instanceName Traffic_mincolorlabel) "
         "(resources "
          "((labelString <\\ 1))))) "
       "(constraint R1C0A1) "
       "(child "
        "(Label "
         "(instanceName Traffic_unitcolorlabel) "
         "(resources "
          "((labelString packets\\ /\\ second))))) "
       "(constraint R1C1A1) "
       "(child "
        "(Label "
         "(instanceName Traffic_maxcolorlabel) "
         "(resources "
          "((labelString >=\\ 8))))) "
       "(constraint R1C2A1))) "
     "(constraint R2C0A0))) "
   "(constraint R1C0A0))) "
 "(constraint R3C0A0) "
 "(child "
  "(RowColumn "
   "(rows 2) "
   "(cols 1) "
   "(defaultAlignment 0) "
   "(resources "
    "((verticalOffset 3))) "
   "(child "
    "(CheckBox "
     "(instanceName Traffic_rescale) "
     "(resources "
      "((callback Traffic_rescale) "
       "(labelString Recalculate\\ color\\ of\\ traffic\\ lines))))) "
   "(constraint R0C0A0) "
   "(child "
    "(RowColumn "
     "(rows 1) "
     "(cols 4) "
     "(defaultAlignment 0) "
     "(resources "
      "((leftInset 27) "
       "(horizontalOffset 8))) "
     "(child "
      "(Label "
       "(resources "
        "((labelString every))))) "
     "(constraint R0C0A4) "
     "(child "
      "(Frame "
       "(resources "
        "((frame Innie))) "
       "(child "
        "(TextField "
         "(instanceName Traffic_rescalevalue) "
         "(text ) "
         "(resources "
          "((terminatorCallBack Traffic_rescalevalue) "
           "(keepAllTextVisible False))))))) "
     "(constraint R0C1A0) "
     "(child "
      "(Label "
       "(resources "
        "((labelString seconds))))) "
     "(constraint R0C2A4) "
     "(child "
      "(Gap "
       "(orientation horizontal) "
       "(resources "
        "((minWidth 50))))) "
     "(constraint R0C3A4))) "
   "(constraint R1C0A0))) "
 "(constraint R4C0A0) "
 "(child "
  "(RowColumn "
   "(rows 2) "
   "(cols 1) "
   "(defaultAlignment 0) "
   "(resources "
    "((verticalOffset 3))) "
   "(child "
    "(CheckBox "
     "(instanceName Traffic_timeout) "
     "(resources "
      "((callback Traffic_timeout) "
       "(labelString Delete\\ traffic\\ lines))))) "
   "(constraint R0C0A0) "
   "(child "
    "(RowColumn "
     "(rows 1) "
     "(cols 3) "
     "(defaultAlignment 0) "
     "(resources "
      "((leftInset 27) "
       "(horizontalOffset 8))) "
     "(child "
      "(Label "
       "(resources "
        "((labelString after))))) "
     "(constraint R0C0A4) "
     "(child "
      "(Frame "
       "(resources "
        "((frame Innie))) "
       "(child "
        "(TextField "
         "(instanceName Traffic_timeoutvalue) "
         "(text ) "
         "(resources "
          "((terminatorCallBack Traffic_timeoutvalue) "
           "(keepAllTextVisible False))))))) "
     "(constraint R0C1A4) "
     "(child "
      "(Label "
       "(resources "
        "((labelString seconds\\ of\\ no\\ traffic))))) "
     "(constraint R0C2A4))) "
   "(constraint R1C0A0))) "
 "(constraint R5C0A0) "
 "(child "
  "(Separator "
   "(orientation horizontal))) "
 "(constraint R6C0A0) "
 "(child "
  "(RowColumn "
   "(rows 1) "
   "(cols 3) "
   "(defaultAlignment 0) "
   "(resources "
    "((horizontalOffset 8))) "
   "(child "
    "(Gap "
     "(orientation horizontal) "
     "(resources "
      "((minWidth 50))))) "
   "(constraint R0C0A0) "
   "(child "
    "(LabelButton "
     "(resources "
      "((callback Traffic_close) "
       "(accelerator Alt\\ c) "
       "(labelString Close))))) "
   "(constraint R0C1A0) "
   "(child "
    "(LabelButton "
     "(resources "
      "((callback Traffic_help) "
       "(accelerator Alt\\ h) "
       "(labelString Help))))) "
   "(constraint R0C2A0))) "
 "(constraint R7C0A0))";
