/*
 * Copyright 1997, Silicon Graphics, Inc.
 * ALL RIGHTS RESERVED
 * 
 * UNPUBLISHED -- Rights reserved under the copyright laws of the United
 * States.   Use of a copyright notice is precautionary only and does not
 * imply publication or disclosure.
 * 
 * U.S. GOVERNMENT RESTRICTED RIGHTS LEGEND:
 * Use, duplication or disclosure by the Government is subject to restrictions
 * as set forth in FAR 52.227.19(c)(2) or subparagraph (c)(1)(ii) of the Rights
 * in Technical Data and Computer Software clause at DFARS 252.227-7013 and/or
 * in similar or successor clauses in the FAR, or the DOD or NASA FAR
 * Supplement.  Contractor/manufacturer is Silicon Graphics, Inc.,
 * 2011 N. Shoreline Blvd. Mountain View, CA 94039-7311.
 * 
 * THE CONTENT OF THIS WORK CONTAINS CONFIDENTIAL AND PROPRIETARY
 * INFORMATION OF SILICON GRAPHICS, INC. ANY DUPLICATION, MODIFICATION,
 * DISTRIBUTION, OR DISCLOSURE IN ANY FORM, IN WHOLE, OR IN PART, IS STRICTLY
 * PROHIBITED WITHOUT THE PRIOR EXPRESS WRITTEN PERMISSION OF SILICON
 * GRAPHICS, INC.
 */


//////////////////////////////////////////////////////////////
//
// Header file for ArchiveBoundsForm
//
//    This file is generated by RapidApp 1.2
//
//    This class implements the user interface portion of a class
//
//    Restrict changes to those sections between
//    the "//--- Start/End editable code block" markers
//
//    This will allow RapidApp to integrate changes more easily
//
//    This class is a ViewKit user interface "component".
//    For more information on how components are used, see the
//    "ViewKit Programmers' Manual", and the RapidApp
//    User's Guide.
//
//////////////////////////////////////////////////////////////
#ifndef ARCHIVEBOUNDSFORM_H
#define ARCHIVEBOUNDSFORM_H
#include <Vk/VkComponent.h>


//---- Start editable code block: headers and declarations
#include <sys/time.h>

//---- End editable code block: headers and declarations


class ArchiveBoundsForm : public VkComponent
{ 


  public:

    ArchiveBoundsForm ( const char *, Widget );
    ArchiveBoundsForm ( const char * );
    ~ArchiveBoundsForm();
    void create ( Widget );
    const char *  className();

    //---- Start editable code block: ArchiveBoundsForm public

    void showBounds(void);
    void setBounds(int startPercent, int finishPercent);
    void setBounds(struct timeval *s, struct timeval *f);
    void addBounds(struct timeval *s, struct timeval *f, Boolean force = False);
    void getBounds(struct timeval *s, struct timeval *f);
    void getBounds(double *s, double *f);
    void setManual(Boolean manual);
    void showDetail(Boolean ms, Boolean year);
    Boolean isManual(void);
    static const char *const boundsChanged;
    static const char *const cancelActivate;
    void notifyBoundsChanged(struct timeval *s, struct timeval *f);


    //---- End editable code block: ArchiveBoundsForm public



    // Widgets created by this class

    Widget  _archiveBoundsMainForm2;
    Widget  _cancelButton;
    Widget  _helpButton;
    Widget  _finishLabel;
    Widget  _finishScale;
    Widget  _finishText;
    Widget  _manualToggle;
    Widget  _separator;
    Widget  _startLabel;
    Widget  _startScale;
    Widget  _startText;


    // These virtual functions are called from the private callbacks (below)
    // Intended to be overriden in derived classes to define actions

    virtual void cancelActivateCB ( Widget, XtPointer );
    virtual void finishScaleChangedCB ( Widget, XtPointer );
    virtual void finishScaleDragCB ( Widget, XtPointer );
    virtual void finishTextActivateCB ( Widget, XtPointer );
    virtual void finishTextChangedCB ( Widget, XtPointer );
    virtual void manualToggleChangedCB ( Widget, XtPointer );
    virtual void startScaleChangedCB ( Widget, XtPointer );
    virtual void startScaleDragCB ( Widget, XtPointer );
    virtual void startTextActivateCB ( Widget, XtPointer );
    virtual void startTextChangedCB ( Widget, XtPointer );

    //---- Start editable code block: ArchiveBoundsForm protected

    struct timeval _epochTimeval;
    struct timeval _finalTimeval;
    struct timeval _startWindowTimeval;
    struct timeval _finishWindowTimeval;
    char _startTextString[64];
    char _finishTextString[64];
    Boolean _manual;
    Boolean _showMilliseconds;
    Boolean _showYear;
    Boolean _dragStartScale;
    Boolean _dragFinishScale;


    //---- End editable code block: ArchiveBoundsForm protected


  private: 

    // Array of default resources

    static String      _defaultArchiveBoundsFormResources[];


    // Callbacks to interface with Motif

    static void cancelActivateCBCallback ( Widget, XtPointer, XtPointer );
    static void finishScaleChangedCBCallback ( Widget, XtPointer, XtPointer );
    static void finishScaleDragCBCallback ( Widget, XtPointer, XtPointer );
    static void finishTextActivateCBCallback ( Widget, XtPointer, XtPointer );
    static void finishTextChangedCBCallback ( Widget, XtPointer, XtPointer );
    static void manualToggleChangedCBCallback ( Widget, XtPointer, XtPointer );
    static void startScaleChangedCBCallback ( Widget, XtPointer, XtPointer );
    static void startScaleDragCBCallback ( Widget, XtPointer, XtPointer );
    static void startTextActivateCBCallback ( Widget, XtPointer, XtPointer );
    static void startTextChangedCBCallback ( Widget, XtPointer, XtPointer );

    //---- Start editable code block: ArchiveBoundsForm private


    //---- End editable code block: ArchiveBoundsForm private
};
//---- Start editable code block: End of generated code


//---- End editable code block: End of generated code

#endif

