#!/bin/sh

# little script to burn the IP17 eeprom.
# family code is for the SEEQ 2816A, for the unisite programmer

/usr/bsd/rsh root@canuck.asd /usr/local/bin/dataio/nprom -w -U -c0B7023 -a/dev/ttyd2 < $1
