/**************************************************************************
 *									  *
 * 		 Copyright (C) 1995-1996 Silicon Graphics, Inc.		  *
 *									  *
 *  These coded instructions, statements, and computer programs  contain  *
 *  unpublished  proprietary  information of Silicon Graphics, Inc., and  *
 *  are protected by Federal copyright law.  They  may  not be disclosed  *
 *  to  third  parties  or copied or duplicated in any form, in whole or  *
 *  in part, without the prior written consent of Silicon Graphics, Inc.  *
 *									  *
 **************************************************************************/

#include "ksys/cell/subsysid.h"

/*
 * operations from server to client
 */
subsystem	"dcshm"	DCSHM_SUBSYSID

import <ksys/vshm.h>
import <ksys/cell/tkm.h>
import <ksys/cell/service.h>
import <ksys/cell.h>
import <ksys/cell/object.h>
import <ksys/cell/handle.h>

/*
 * call to client to return token
 */
synchronous void
recall(
	out	pointerto 32	int		errno,
	in	valueof		int		vshmid,
	in	valueof		tk_set_t	to_be_recalled,
	in	valueof		tk_disp_t	dofrev)
