/**************************************************************************
 *									  *
 * 		 Copyright (C) 1995-1996 Silicon Graphics, Inc.		  *
 *									  *
 *  These coded instructions, statements, and computer programs  contain  *
 *  unpublished  proprietary  information of Silicon Graphics, Inc., and  *
 *  are protected by Federal copyright law.  They  may  not be disclosed  *
 *  to  third  parties  or copied or duplicated in any form, in whole or  *
 *  in part, without the prior written consent of Silicon Graphics, Inc.  *
 *									  *
 **************************************************************************/

#include "ksys/cell/subsysid.h"

/*
 * operations from client to server
 */
subsystem	"dsshm"	DSSHM_SUBSYSID

import <sys/ipc.h>
import <sys/shm.h>
import <ksys/vshm.h>
import <ksys/cell/tkm.h>
import <ksys/cell/service.h>
import <ksys/cell.h>
import <ksys/cell/object.h>
import <ksys/cell/handle.h>

synchronous void
obtain(
	out	pointerto 32	int		errno,
	in	valueof		cell_t		sender,
	in	valueof		int		vshmid,
	in	valueof		tk_set_t	to_be_obtained,
	in	valueof		tk_set_t	to_be_returned,
	in	valueof		tk_disp_t	dofret,
	out	pointerto 32	tk_set_t	already_obtained,
	out	pointerto 32	tk_set_t	granted,
	out	pointerto 32	tk_set_t	refused,
	inout	pointerto	objid_t 	objid,
	out	pointerto 32	int		key,
	out	pointerto 32	cell_t		relocated_to)

/*
 * call from client to server returning tokens
 */
synchronous void
return(
	in	valueof		cell_t		sender,
	in	valueof		objid_t 	objid,
	in	valueof		tk_set_t	to_be_returned,
	in	valueof		tk_set_t	unknown,
	in	valueof		tk_disp_t	why)

synchronous void
freeid(
	in	valueof		int 		id)

synchronous void
getmo(
	in	valueof		objid_t 	objid,
	out	pointerto	as_mohandle_t	mop)

synchronous void
keycheck(
	out	pointerto 32	int		error,
	in	valueof		objid_t 	objid,
	in      valueof         credid_t	credid,
	in	valueof		int		flag,
	in	valueof		size_t		size)

synchronous void
attach(
	out	pointerto 32	int		error,
	in	valueof		objid_t 	objid,
	in	valueof		int		flag,
	in	pointerto	asid_t		asid,
	in	valueof		pid_t		pid,
	in      valueof         credid_t	credid,
	in	valueof		caddr_t		addr,
	out	pointerto 64	caddr_t		aaddr)

synchronous void
setdtime(
	in	valueof		objid_t 	objid,
	in	valueof		int		dtime,
	in	valueof		pid_t		pid)

synchronous void
rmid(
	out	pointerto 32	int		error,
	in	valueof		objid_t 	objid,
	in      valueof         credid_t	credid,
	in	valueof		int		flag)

synchronous void
ipcset(
	out	pointerto 32	int		error,
	in	valueof		objid_t 	objid,
	in	pointerto	<struct ipc_perm> perm,
	in      valueof         credid_t	credid)

synchronous void
getstat(
	out     pointerto 32    int		error,
	in	valueof		objid_t 	objid,
	in      valueof         credid_t	credid,
	out	pointerto	<struct shmid_ds> shmds,
	out	pointerto 32	cell_t		cell)

synchronous void
getstatus(
	out     pointerto 32    int		error,
	in	valueof		int		id,
	in	valueof		uint64_t	location,
	in      valueof         credid_t	credid,
	out	pointerto	<struct shmstat> stat)

synchronous void
mac_access(
	out	pointerto 32	int		error,
	in	valueof		objid_t 	objid,
	in      valueof         credid_t	credid)

asynchronous
obj_retargetted(
	in	valueof		cell_t		client,
	in	valueof		int		id,
	in	valueof		objid_t 	what,
	in	valueof		<void *>	retarget_sync)
