#include "nib_procs.h"
#include "niblet.h"

int test_array[][PROCS_PER_TEST + 1] = {
	{INVALID, -1},						/* 0 */
	{INVALID, COUNTER, COUNTER, -1},			/* 1 */
	{MPMON, MPMON, -1},					/* 2 */
	{MPINTADD, INVALID, MPINTADD, -1},			/* 3 */
	{MPSLOCK, MPSLOCK, INVALID, -1},			/* 4 */
	{MPINTADD, MPSLOCK, MPINTADD, MPSLOCK, INVALID, -1},	/* 5 */
	{MPSLOCK, MPMON, INVALID, MPSLOCK, MPMON, -1},		/* 6 */
	{MPHLOCK, MPHLOCK, -1},					/* 7 */
	{INVALID, MPMON, MPMON, MPSLOCK, MPSLOCK, 
		MPINTADD, MPINTADD, MPHLOCK, MPHLOCK, -1},	/* 8 */
	{MPINTADD_4, MPINTADD_4, MPINTADD_4,
		MPINTADD_4, INVALID, MPMON, MPSLOCK,
		MPHLOCK, MPHLOCK,
		MPSLOCK, MPMON, -1},				/* 9 */
	{MEMTEST, MEMTEST, MEMTEST, MEMTEST, MEMTEST, -1},	/* a */
	{BIGMEM, BIGMEM, BIGMEM, INVALID, INVALID,
		INVALID, -1},					/* b */
	{PRINTTEST,  PRINTTEST, PRINTTEST, PRINTTEST,
	PRINTTEST,  PRINTTEST, PRINTTEST, PRINTTEST,
	PRINTTEST,  PRINTTEST, PRINTTEST, PRINTTEST,
	PRINTTEST,  PRINTTEST, -1},				/* c */
	{BIGINTADD_4, BIGINTADD_4, BIGINTADD_4, BIGINTADD_4,
		INVALID, BIGROVE, BIGROVE, BIGROVE, BIGHLOCK,
		BIGHLOCK, BIGMEM, BIGMEM, BIGMEM, INVALID, -1},	/* d */
	{MPROVE, MPROVE, MPROVE, MPROVE,
	MPROVE, MPROVE, MPROVE, MPROVE, -1},			/* e */
	{INVALID, INVALID, NIBFAIL, INVALID, NIBFAIL, -1}	/* f */
};

int num_tests = sizeof(test_array) / (sizeof(int) * PROCS_PER_TEST + 1);
int avail_procs = NUM_PROCS;

